import { describe, expect, test } from "bun:test";
import { join } from "node:path";

import { type SidebarEntry, sidebar } from "../src/sidebar.ts";

const docsRoot = join(import.meta.dir, "..");
const repoRoot = join(docsRoot, "..");
const landingPagePath = join(docsRoot, "index.md");

const GROUP_LABELS = ["Guides", "Recipes", "Reference", "Embedding", "Telemetry", "Contributing"] as const;
const RECIPE_IDS = [
  "backdrop",
  "drupal",
  "drupal-cms",
  "joomla",
  "lamp",
  "laravel",
  "lemp",
  "mean",
  "rails",
  "symfony",
  "wordpress",
] as const;
const CONTRIBUTING_SLUGS = ["contributing/ci", "contributing/release", "contributing/decisions"] as const;
const TELEMETRY_SLUGS = ["telemetry/events", "telemetry/retention"] as const;
const ALPHA_INSTALL_SLUG = "alpha-install-and-bug-reports";

const entries: readonly SidebarEntry[] = sidebar;

const isGroup = (entry: SidebarEntry): boolean => entry.items !== undefined;

const findGroup = (label: string): SidebarEntry => {
  const group = entries.find((entry) => entry.label === label && isGroup(entry));
  if (group === undefined) throw new Error(`The sidebar has no "${label}" group.`);
  return group;
};

const collectSlugs = (entry: SidebarEntry): readonly string[] => [
  ...(entry.slug === undefined ? [] : [entry.slug]),
  ...(entry.items ?? []).flatMap(collectSlugs),
];

const collectAutogenerateDirectories = (entry: SidebarEntry): readonly string[] => [
  ...(entry.autogenerate === undefined ? [] : [entry.autogenerate.directory]),
  ...(entry.items ?? []).flatMap(collectAutogenerateDirectories),
];

const slugsOf = (entry: SidebarEntry): readonly string[] =>
  (entry.items ?? []).flatMap((item) => (item.slug === undefined ? [] : [item.slug]));

const autogenerateDirectoriesOf = (entry: SidebarEntry): readonly string[] =>
  (entry.items ?? []).flatMap((item) =>
    item.autogenerate === undefined ? [] : [item.autogenerate.directory],
  );

const contentFileCandidates = (href: string): readonly string[] => {
  const slug = href.replace(/^\.\//, "").replace(/^\/+/, "").replace(/\/+$/, "");
  if (slug.startsWith("recipes/"))
    return [join(repoRoot, "recipes", slug.slice("recipes/".length), "README.mdx")];
  return [join(docsRoot, `${slug}.md`), join(docsRoot, `${slug}.mdx`)];
};

const readLandingPage = async (): Promise<string> => {
  const file = Bun.file(landingPagePath);
  if (!(await file.exists())) throw new Error(`The landing page is missing at ${landingPagePath}.`);
  return file.text();
};

const internalLinksOf = (source: string): readonly string[] => [
  ...new Set([
    ...[...source.matchAll(/]\((\.?\/[^)\s]*)\)/g)].map(([, href]) => href ?? ""),
    ...[...source.matchAll(/^\s*link:\s*(\.?\/\S*)\s*$/gm)].map(([, href]) => href ?? ""),
  ]),
];

const normalizeLink = (href: string): string => (href.startsWith("./") ? href.slice(1) : href);

describe("docs sidebar", () => {
  test("lists every top-level group in reading order", () => {
    // Given: the published sidebar.
    // When: its group labels are collected.
    const labels = entries.filter(isGroup).map((entry) => entry.label);

    // Then: the six documentation groups ship in a stable order.
    expect(labels).toEqual([...GROUP_LABELS]);
  });

  test("links the alpha install page above the groups", () => {
    // Given: the published sidebar.
    // When: its top-level links are collected.
    const topLevelSlugs = entries.flatMap((entry) => (entry.slug === undefined ? [] : [entry.slug]));

    // Then: readers reach the install instructions without opening a group.
    expect(topLevelSlugs).toContain(ALPHA_INSTALL_SLUG);
  });

  test("publishes an explicit user-facing guides list", () => {
    // Given: the Guides group.
    const guides = findGroup("Guides");
    const slugs = collectSlugs(guides);
    const directories = collectAutogenerateDirectories(guides);
    const serialized = JSON.stringify(sidebar);

    // When: its explicit slugs and scoped catalogs are collected.
    // Then: user how-tos stay on the path and leaked internals stay off it.
    expect(guides.collapsed).toBe(true);
    expect(directories).not.toContain("guides");
    expect(directories).toEqual(["guides/services", "guides/tooling", "guides/landofile", "guides/config"]);
    expect(slugs).toContain("guides/tutorial/app-lifecycle");
    expect(slugs).toContain("guides/tutorial/from-lando-3");
    expect(slugs).toContain("guides/node-postgres");
    expect(slugs).toContain("guides/cli/everyday-commands");
    expect(slugs).toContain("guides/cli/cache-refresh");
    expect(slugs).toContain("guides/cli/verbosity-and-debug");
    expect(slugs).toContain("guides/scratch/scratch-from-recipe");
    expect(slugs).toContain("guides/cli/ssh");
    expect(slugs).toContain("guides/setup/provider-selection");
    expect(slugs).toContain("guides/setup/provider-auto-setup");
    expect(slugs).toContain("guides/install/github-releases");
    expect(slugs).toContain("guides/install/posix-installer");
    expect(slugs).toContain("guides/install/wsl");
    expect(slugs).toContain("guides/recipes/lamp-stack-variants");
    expect(slugs).toContain("guides/recipes/authoring-runs-allowlist");
    expect(slugs).toContain("guides/recipes/authoring-fetch-allowlist");
    expect(slugs).toContain("guides/recipes/programmatic-recipe");
    expect(slugs).not.toContain("guides/recipes/remote-sources");
    expect(slugs).toContain("guides/subsystems/proxy-traefik");
    expect(slugs).toContain("guides/subsystems/doctor-walkthrough");
    expect(slugs).not.toContain("guides/recipes/canonical-public-transcript");
    expect(slugs).not.toContain("guides/install/verify-installer-scripts");
    expect(slugs).not.toContain("guides/cli/terminal-ui-polish");
    expect(serialized).not.toContain("guides/authoring");
    expect(serialized).not.toContain("guides/release");
    expect(serialized).not.toContain("guides/library");
    expect(serialized).not.toContain("guides/embedding");
    expect(serialized).not.toContain("guides/schemas");
    expect(serialized).not.toContain("guides/contributing");
    expect(serialized).not.toContain("provider-docker-windows");
    expect(serialized).not.toContain("provider-podman-windows");
    expect(serialized).not.toContain("provider-podman-macos");
    expect(serialized).not.toContain("provider-lando-windows");
    expect(serialized).not.toContain("file-sync-mutagen");
    expect(serialized).not.toContain("compiled-binary-setup-parity");
    expect(serialized).not.toContain("healthcheck-runner");
    expect(serialized).not.toContain("scanner-service");
    expect(serialized).not.toContain("ssh-sidecar");
    expect(serialized).not.toContain("guides/global/");
    expect(serialized).not.toContain("canonical-public-transcript");
    expect(serialized).not.toContain("verify-installer-scripts");
    expect(serialized).not.toContain("terminal-ui-polish");
    expect(serialized).not.toContain("windows-installer");
    expect(serialized).not.toContain("ci-github-actions");
  });

  test("lists exactly the recipes that ship a README", async () => {
    // Given: the Recipes group.
    const recipes = findGroup("Recipes");

    // When: its slugs are collected.
    const slugs = slugsOf(recipes);

    // Then: the shipped recipe READMEs are linked and none are invented.
    expect(slugs).toEqual(RECIPE_IDS.map((id) => `recipes/${id}`));
    expect(slugs).not.toContain("recipes/toolbox");
    for (const id of RECIPE_IDS) {
      expect(await Bun.file(join(repoRoot, "recipes", id, "README.mdx")).exists()).toBe(true);
    }
  });

  test("autogenerates reference and links the PHP base image notes", () => {
    // Given: the Reference group.
    const reference = findGroup("Reference");

    // When: its autogenerated directories and explicit slugs are collected.
    const directories = autogenerateDirectoriesOf(reference);
    const slugs = slugsOf(reference);

    // Then: generated reference pages and the hand-written companion both appear.
    expect(directories).toEqual(["reference"]);
    expect(slugs).toEqual(["php-base-images"]);
  });

  test("links the embedding and telemetry pages", () => {
    // Given: the Embedding and Telemetry groups.
    const embedding = findGroup("Embedding");
    const telemetry = findGroup("Telemetry");

    // When: their slugs are collected.
    // Then: every page in those areas is reachable.
    expect(slugsOf(embedding)).toEqual(["embedding"]);
    expect(slugsOf(telemetry)).toEqual([...TELEMETRY_SLUGS]);
  });

  test("lists exactly the three contributing pages", () => {
    // Given: the Contributing group.
    const contributing = findGroup("Contributing");

    // When: its slugs are collected.
    // Then: CI, release, and decision records are the whole group.
    expect(slugsOf(contributing)).toEqual([...CONTRIBUTING_SLUGS]);
  });

  test("never links planning material", () => {
    // Given: the serialized sidebar.
    const serialized = JSON.stringify(sidebar);

    // When: planning-only paths are searched for.
    // Then: the coverage matrix, prd- path prefixes, and spec/ paths stay out of the reader surface.
    expect(serialized).not.toContain("guides/INDEX");
    expect(serialized).not.toContain("prd-");
    expect(serialized).not.toContain("spec/");
  });
});

describe("docs landing page", () => {
  test("renders as a splash page at the site root", async () => {
    // Given: the landing page source.
    const source = await readLandingPage();

    // When: its frontmatter is inspected.
    const frontmatter = source.split("---")[1] ?? "";

    // Then: it uses the splash template with a hero.
    expect(frontmatter).toContain("template: splash");
    expect(frontmatter).toContain("hero:");
    expect(frontmatter).toContain("tagline:");
  });

  test("points at install, guides, recipes, reference, and embedding", async () => {
    // Given: the landing page source.
    const source = await readLandingPage();

    // When: its internal links are collected and normalized.
    const links = internalLinksOf(source).map(normalizeLink);

    // Then: every documentation area has an entry point.
    expect(links).toContain(`/${ALPHA_INSTALL_SLUG}/`);
    expect(links.some((href) => href.startsWith("/guides/"))).toBe(true);
    expect(links.some((href) => href.startsWith("/recipes/"))).toBe(true);
    expect(links.some((href) => href.startsWith("/reference/"))).toBe(true);
    expect(links).toContain("/embedding/");
  });

  test("only links pages that exist", async () => {
    // Given: the landing page source.
    const source = await readLandingPage();

    // When: each internal link is resolved back to a content file.
    const resolved = await Promise.all(
      internalLinksOf(source).map(async (href) => {
        const normalized = normalizeLink(href);
        const candidates = await Promise.all(
          contentFileCandidates(normalized).map((path) => Bun.file(path).exists()),
        );
        return [href, candidates.includes(true)] as const;
      }),
    );

    // Then: no landing-page link is a 404.
    expect(resolved.filter(([, exists]) => !exists)).toEqual([]);
  });

  test("never cites planning material", async () => {
    // Given: the landing page source.
    const source = await readLandingPage();

    // When: planning-only paths are searched for.
    // Then: readers only see shipped documentation.
    expect(source).not.toContain("spec/");
    expect(source).not.toContain("prd-");
    expect(source).not.toContain("guides/INDEX");
  });
});
