/** A Starlight sidebar entry: an internal link, a manual group, or an autogenerated group. */
export type SidebarEntry = {
  readonly label?: string;
  readonly slug?: string;
  readonly collapsed?: boolean;
  readonly autogenerate?: { readonly directory: string; readonly collapsed?: boolean };
  readonly items?: readonly SidebarEntry[];
};

export const sidebar = [
  { label: "Install the Alpha", slug: "alpha-install-and-bug-reports" },
  {
    label: "Guides",
    collapsed: true,
    items: [{ autogenerate: { directory: "guides", collapsed: true } }],
  },
  {
    label: "Recipes",
    items: [
      { label: "Drupal", slug: "recipes/drupal" },
      { label: "Drupal CMS", slug: "recipes/drupal-cms" },
      { label: "LAMP", slug: "recipes/lamp" },
      { label: "LEMP", slug: "recipes/lemp" },
      { label: "WordPress", slug: "recipes/wordpress" },
    ],
  },
  {
    label: "Reference",
    collapsed: true,
    items: [
      { autogenerate: { directory: "reference", collapsed: true } },
      { label: "PHP base images", slug: "php-base-images" },
    ],
  },
  {
    label: "Embedding",
    items: [{ label: "Embed @lando/core", slug: "embedding" }],
  },
  {
    label: "Telemetry",
    items: [
      { label: "Events", slug: "telemetry/events" },
      { label: "Retention", slug: "telemetry/retention" },
    ],
  },
  {
    label: "Contributing",
    items: [
      { label: "CI", slug: "contributing/ci" },
      { label: "Release", slug: "contributing/release" },
      { label: "Decisions", slug: "contributing/decisions" },
    ],
  },
] as const satisfies readonly SidebarEntry[];
