import { afterEach, beforeEach, describe, expect, test } from "bun:test";
import { createHash } from "node:crypto";
import { mkdir, mkdtemp, readFile, realpath, rm, stat, symlink, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { isAbsolute, join } from "node:path";

import { Effect } from "effect";

import { type LandofileShape, ServiceName } from "@lando/sdk/schema";

import { getLandofileIncludeSources, getLocalIncludePaths } from "../src/include-provenance.ts";
import { resolveLandofileIncludes as resolveLandofileIncludesPackage } from "../src/includes.ts";
import type {
  GitIncludeCloner,
  NpmIncludeExtractor,
  NpmIncludeFetcher,
  NpmIncludeRecipeSource,
  ResolveIncludesError,
} from "../src/includes.ts";
import { loadLandofileLayers } from "../src/service.ts";
import { makeTestLandofilePorts, makeTestLandofileStateStore } from "./support.ts";

const resolveLandofileIncludes = (options: Parameters<typeof resolveLandofileIncludesPackage>[0]) =>
  resolveLandofileIncludesPackage({ ...options, stateStore: makeTestLandofileStateStore() });

const resolveEffect = (
  landofile: LandofileShape,
  appRoot: string,
  cacheRoot: string,
  userIncludesDir = cacheRoot,
) =>
  resolveLandofileIncludes({
    landofile,
    appRoot,
    cacheRoot,
    ports: makeTestLandofilePorts(cacheRoot, userIncludesDir),
  });

const runResolve = (
  landofile: LandofileShape,
  appRoot: string,
  cacheRoot: string,
  userIncludesDir = cacheRoot,
) => Effect.runPromise(resolveEffect(landofile, appRoot, cacheRoot, userIncludesDir));

const serviceType = (landofile: LandofileShape, name: string) =>
  landofile.services?.[ServiceName.make(name)]?.type;

const includeErrorKind = (error: ResolveIncludesError): string => {
  if (error._tag !== "LandofileIncludeError") throw new Error(`expected include error, got ${error._tag}`);
  return error.kind;
};

const exists = (path: string) =>
  stat(path).then(
    () => true,
    () => false,
  );

const lockfile = (source: string, resolved: string, checksum: string) =>
  [
    "# DO NOT EDIT - generated by Lando.",
    "includes:",
    `  - source: ${source}`,
    `    resolved: ${resolved}`,
    `    checksum: ${checksum}`,
    "",
  ].join("\n");

describe("resolveLandofileIncludes", () => {
  let appRoot: string;
  let cacheRoot: string;
  let userIncludesDir: string;
  let previousCacheRoot: string | undefined;

  beforeEach(async () => {
    appRoot = await mkdtemp(join(tmpdir(), "lando-includes-app-"));
    cacheRoot = await mkdtemp(join(tmpdir(), "lando-includes-cache-"));
    userIncludesDir = await mkdtemp(join(tmpdir(), "lando-user-includes-"));
    previousCacheRoot = process.env.LANDO_USER_CACHE_ROOT;
    process.env.LANDO_USER_CACHE_ROOT = cacheRoot;
  });

  afterEach(async () => {
    process.env.LANDO_USER_CACHE_ROOT = previousCacheRoot;
    await rm(appRoot, { recursive: true, force: true });
    await rm(cacheRoot, { recursive: true, force: true });
    await rm(userIncludesDir, { recursive: true, force: true });
  });

  test("merges a local relative include and does not write a lockfile", async () => {
    await writeFile(join(appRoot, "fragment.yml"), "services:\n  api:\n    type: node\n", "utf8");

    const result = await runResolve(
      {
        name: "demo",
        includes: ["./fragment.yml"],
        services: { [ServiceName.make("api")]: { primary: true } },
      },
      appRoot,
      cacheRoot,
    );

    expect(result).toEqual({
      name: "demo",
      services: { [ServiceName.make("api")]: { type: "node", primary: true } },
    });
    expect(await exists(join(appRoot, ".lando.lock.yml"))).toBe(false);
  });

  test("merges explicitly selected nested user profiles before project overrides", async () => {
    // Given: a user profile with declaring-directory and root-relative nested profiles.
    await mkdir(join(userIncludesDir, "corp"), { recursive: true });
    await mkdir(join(userIncludesDir, "shared"), { recursive: true });
    await writeFile(
      join(userIncludesDir, "corp", "base.yml"),
      "services:\n  api:\n    type: node\n    env_file:\n      - ./app.env\n",
      "utf8",
    );
    await writeFile(
      join(userIncludesDir, "shared", "cache.yaml"),
      "services:\n  cache:\n    type: redis\n",
      "utf8",
    );
    await writeFile(
      join(userIncludesDir, "corp", "php.yml"),
      [
        "includes:",
        "  - ./base.yml",
        "  - user:shared/cache.yaml",
        "services:",
        "  api:",
        "    build:",
        "      context: ./docker",
        "",
      ].join("\n"),
      "utf8",
    );

    // When: the app explicitly opts into the user profile and overrides its service.
    const result = await runResolve(
      {
        includes: ["user:corp/php.yml"],
        services: { [ServiceName.make("api")]: { type: "php" } },
      },
      appRoot,
      cacheRoot,
      userIncludesDir,
    );

    // Then: nesting and precedence match ordinary includes, while authored paths stay app-relative.
    expect(result.services?.[ServiceName.make("api")]).toMatchObject({
      type: "php",
      envFile: ["./app.env"],
      build: { context: "./docker" },
    });
    expect(serviceType(result, "cache")).toBe("redis");
    expect(getLandofileIncludeSources(result)).toEqual([
      {
        id: "user:corp/base.yml",
        sha256: createHash("sha256")
          .update(await readFile(join(userIncludesDir, "corp", "base.yml"), "utf8"))
          .digest("hex"),
      },
      {
        id: "user:corp/php.yml",
        sha256: createHash("sha256")
          .update(await readFile(join(userIncludesDir, "corp", "php.yml"), "utf8"))
          .digest("hex"),
      },
      {
        id: "user:shared/cache.yaml",
        sha256: createHash("sha256")
          .update(await readFile(join(userIncludesDir, "shared", "cache.yaml"), "utf8"))
          .digest("hex"),
      },
    ]);
  });

  test("does not load user profiles without explicit app opt-in", async () => {
    // Given: a valid profile exists in the user includes directory.
    await writeFile(join(userIncludesDir, "implicit.yml"), "services:\n  hidden:\n    type: redis\n", "utf8");

    // When: the app declares no includes.
    const result = await runResolve({ name: "demo" }, appRoot, cacheRoot, userIncludesDir);

    // Then: the profile has no effect.
    expect(result.services).toBeUndefined();
  });

  test("preserves user include provenance through layered Landofile loading", async () => {
    // Given: the canonical layer explicitly selects a user profile.
    await writeFile(join(appRoot, ".lando.yml"), "name: layered-user\nincludes:\n  - user:corp.yml\n");
    await writeFile(join(userIncludesDir, "corp.yml"), "services:\n  api:\n    type: node\n");

    // When: the complete layered loader resolves the app.
    const landofile = await Effect.runPromise(
      loadLandofileLayers(appRoot, join(appRoot, ".lando.yml"), {
        ports: makeTestLandofilePorts(cacheRoot, userIncludesDir),
        stateStore: makeTestLandofileStateStore(),
        templates: { modules: [] },
      }),
    );

    // Then: public provenance remains logical after the layer merge.
    expect(getLandofileIncludeSources(landofile)).toEqual([
      {
        id: "user:corp.yml",
        sha256: createHash("sha256").update("services:\n  api:\n    type: node\n").digest("hex"),
      },
    ]);
  });

  test.each([
    { source: "user:", kind: "subpath-invalid" },
    { source: "user:../escape.yml", kind: "outside-root" },
    { source: "user:/absolute.yml", kind: "subpath-invalid" },
    { source: "user:C:\\absolute.yml", kind: "subpath-invalid" },
    { source: "user:\\\\server\\share.yml", kind: "subpath-invalid" },
    { source: "user:profile.json", kind: "subpath-invalid" },
  ])("rejects invalid user include source $source", async ({ source, kind }) => {
    // Given/When: an app selects a malformed or escaping user source.
    const error = await Effect.runPromise(
      Effect.flip(resolveEffect({ includes: [source] }, appRoot, cacheRoot, userIncludesDir)),
    );

    // Then: resolution fails with a machine-readable include error.
    expect(error._tag).toBe("LandofileIncludeError");
    expect(includeErrorKind(error)).toBe(kind);
  });

  test("rejects a user profile symlink that resolves outside the user includes root", async () => {
    // Given: a user include symlink targets a readable profile outside the configured root.
    const outsideRoot = await mkdtemp(join(tmpdir(), "lando-user-include-outside-"));
    await writeFile(join(outsideRoot, "escape.yml"), "services:\n  leak:\n    type: node\n", "utf8");
    await symlink(join(outsideRoot, "escape.yml"), join(userIncludesDir, "escape.yml"));
    try {
      // When: the app explicitly selects the symlink.
      const error = await Effect.runPromise(
        Effect.flip(resolveEffect({ includes: ["user:escape.yml"] }, appRoot, cacheRoot, userIncludesDir)),
      );

      // Then: realpath containment rejects it.
      expect(error._tag).toBe("LandofileIncludeError");
      expect(includeErrorKind(error)).toBe("outside-root");
    } finally {
      await rm(outsideRoot, { recursive: true, force: true });
    }
  });

  test("rejects remote includes declared by a user profile", async () => {
    // Given: a user profile attempts to introduce a remote source.
    await writeFile(
      join(userIncludesDir, "remote.yml"),
      "includes:\n  - github:acme/profile/fragment.yml\n",
      "utf8",
    );

    // When: the app selects that profile.
    const error = await Effect.runPromise(
      Effect.flip(resolveEffect({ includes: ["user:remote.yml"] }, appRoot, cacheRoot, userIncludesDir)),
    );

    // Then: resolution fails before any acquisition port is called.
    expect(error._tag).toBe("LandofileIncludeError");
    expect(includeErrorKind(error)).toBe("source-unresolved");
  });

  test("rejects file-access expressions declared by a user profile", async () => {
    // Given: a user profile tries to read an adjacent host file through load().
    await writeFile(join(userIncludesDir, "corp.pem"), "private material", "utf8");
    await writeFile(
      join(userIncludesDir, "file-access.yml"),
      [
        "services:",
        "  api:",
        "    type: node",
        "    security:",
        "      ca:",
        "        - \"{{ load('./corp.pem') }}\"",
        "",
      ].join("\n"),
      "utf8",
    );

    // When: the app selects that profile.
    const error = await Effect.runPromise(
      Effect.flip(resolveEffect({ includes: ["user:file-access.yml"] }, appRoot, cacheRoot, userIncludesDir)),
    );

    // Then: the file-access expression is rejected rather than evaluated.
    expect(error._tag).toBe("LandofileParseError");
  });

  test("creates a git include lock entry with commit SHA and fragment checksum", async () => {
    const cloner: GitIncludeCloner = {
      clone: async ({ stagingDir }) => {
        await mkdir(stagingDir, { recursive: true });
        await writeFile(
          join(stagingDir, "postgres.yml"),
          "services:\n  database:\n    type: postgres\n",
          "utf8",
        );
        return { commitSha: "abc123" };
      },
    };

    const result = await Effect.runPromise(
      resolveLandofileIncludes({
        landofile: {
          name: "demo",
          includes: [{ source: "github:acme/fragments@main", path: "postgres.yml" }],
        },
        appRoot,
        cacheRoot,
        ports: makeTestLandofilePorts(cacheRoot),
        deps: { gitCloner: cloner },
      }),
    );

    const written = await readFile(join(appRoot, ".lando.lock.yml"), "utf8");
    expect(serviceType(result, "database")).toBe("postgres");
    expect(written).toContain("source: github:acme/fragments");
    expect(written).toContain("resolved: abc123");
    expect(written).toMatch(/checksum: [0-9a-f]{64}/);
  });

  test("uses a matching git lock without rewriting the lockfile", async () => {
    const fragment = "services:\n  database:\n    type: postgres\n";
    const checksum = new Bun.CryptoHasher("sha256").update(fragment).digest("hex");
    const path = join(appRoot, ".lando.lock.yml");
    const locked = lockfile("github:acme/fragments/postgres.yml", "abc123", checksum);
    await writeFile(path, locked, "utf8");
    const cloner: GitIncludeCloner = {
      clone: async ({ stagingDir }) => {
        await mkdir(stagingDir, { recursive: true });
        await writeFile(join(stagingDir, "postgres.yml"), fragment, "utf8");
        return { commitSha: "abc123" };
      },
    };

    const result = await Effect.runPromise(
      resolveLandofileIncludes({
        landofile: { includes: [{ source: "github:acme/fragments", path: "postgres.yml" }] },
        appRoot,
        cacheRoot,
        ports: makeTestLandofilePorts(cacheRoot),
        deps: { gitCloner: cloner },
      }),
    );

    expect(serviceType(result, "database")).toBe("postgres");
    expect(await readFile(path, "utf8")).toBe(locked);
  });

  test("fails closed with LandofileLockMismatchError when a git lock checksum drifts", async () => {
    await writeFile(
      join(appRoot, ".lando.lock.yml"),
      lockfile("github:acme/fragments/postgres.yml", "abc123", "0".repeat(64)),
      "utf8",
    );
    const cloner: GitIncludeCloner = {
      clone: async ({ stagingDir }) => {
        await mkdir(stagingDir, { recursive: true });
        await writeFile(
          join(stagingDir, "postgres.yml"),
          "services:\n  database:\n    type: postgres\n",
          "utf8",
        );
        return { commitSha: "abc123" };
      },
    };

    const error = await Effect.runPromise(
      Effect.flip(
        resolveLandofileIncludes({
          landofile: { includes: [{ source: "github:acme/fragments", path: "postgres.yml" }] },
          appRoot,
          cacheRoot,
          ports: makeTestLandofilePorts(cacheRoot),
          deps: { gitCloner: cloner },
        }),
      ),
    );

    expect(error._tag).toBe("LandofileLockMismatchError");
    expect(error.remediation).toContain("app:includes:update");
  });

  test("records distinct lock entries for two fragments from one git repo", async () => {
    const cloner: GitIncludeCloner = {
      clone: async ({ stagingDir }) => {
        await mkdir(stagingDir, { recursive: true });
        await writeFile(join(stagingDir, "db.yml"), "services:\n  db:\n    type: postgres\n", "utf8");
        await writeFile(join(stagingDir, "cache.yml"), "services:\n  cache:\n    type: redis\n", "utf8");
        return { commitSha: "abc123" };
      },
    };
    const landofile: LandofileShape = {
      includes: [
        { source: "github:acme/fragments", path: "db.yml" },
        { source: "github:acme/fragments", path: "cache.yml" },
      ],
    };

    const result = await Effect.runPromise(
      resolveLandofileIncludes({
        landofile,
        appRoot,
        cacheRoot,
        ports: makeTestLandofilePorts(cacheRoot),
        deps: { gitCloner: cloner },
      }),
    );
    expect(serviceType(result, "db")).toBe("postgres");
    expect(serviceType(result, "cache")).toBe("redis");

    const written = await readFile(join(appRoot, ".lando.lock.yml"), "utf8");
    expect(written).toContain("source: github:acme/fragments/db.yml");
    expect(written).toContain("source: github:acme/fragments/cache.yml");

    const second = await Effect.runPromise(
      resolveLandofileIncludes({
        landofile,
        appRoot,
        cacheRoot,
        ports: makeTestLandofilePorts(cacheRoot),
        deps: { gitCloner: cloner },
      }),
    );
    expect(serviceType(second, "db")).toBe("postgres");
    expect(await readFile(join(appRoot, ".lando.lock.yml"), "utf8")).toBe(written);
  });

  test("creates an npm include lock entry with resolved version and checksum", async () => {
    const npmRecipeSource: NpmIncludeRecipeSource = {
      resolve: async () => ({
        packageName: "@acme/fragments",
        version: "1.2.3",
        dist: { tarball: "https://registry.example/pkg.tgz" },
      }),
    };
    const fetcher: NpmIncludeFetcher = { fetch: async () => new Uint8Array([1, 2, 3]) };
    const extractor: NpmIncludeExtractor = {
      extract: async (_bytes, destDir) => {
        await mkdir(join(destDir, "package", "fragments"), { recursive: true });
        await writeFile(
          join(destDir, "package", "fragments", "web.yml"),
          "services:\n  web:\n    type: node\n",
          "utf8",
        );
      },
    };

    const result = await Effect.runPromise(
      resolveLandofileIncludes({
        landofile: { includes: [{ source: "npm:@acme/fragments/fragments/web.yml@latest" }] },
        appRoot,
        cacheRoot,
        ports: makeTestLandofilePorts(cacheRoot),
        deps: { npmRecipeSource, npmFetcher: fetcher, npmExtractor: extractor },
      }),
    );

    const written = await readFile(join(appRoot, ".lando.lock.yml"), "utf8");
    expect(serviceType(result, "web")).toBe("node");
    expect(written).toContain("source: npm:@acme/fragments/fragments/web.yml");
    expect(written).toContain("resolved: 1.2.3");
  });

  test("resolves nested fragment includes before merging the parent fragment", async () => {
    await writeFile(join(appRoot, "base.yml"), "services:\n  api:\n    type: node\n", "utf8");
    await writeFile(
      join(appRoot, "parent.yml"),
      "includes:\n  - ./base.yml\nservices:\n  api:\n    primary: true\n",
      "utf8",
    );

    const result = await runResolve({ includes: ["./parent.yml"] }, appRoot, cacheRoot);

    expect(result).toEqual({
      services: { [ServiceName.make("api")]: { type: "node", primary: true } },
    });
  });

  test("rejects include cycles", async () => {
    await writeFile(join(appRoot, "a.yml"), "includes:\n  - ./b.yml\n", "utf8");
    await writeFile(join(appRoot, "b.yml"), "includes:\n  - ./a.yml\n", "utf8");

    const error = await Effect.runPromise(
      Effect.flip(resolveEffect({ includes: ["./a.yml"] }, appRoot, cacheRoot)),
    );

    expect(error._tag).toBe("LandofileIncludeError");
    expect(includeErrorKind(error)).toBe("cycle");
  });

  test("rejects include recursion past max depth", async () => {
    for (let i = 0; i < 10; i += 1) {
      await writeFile(
        join(appRoot, `${i}.yml`),
        i === 9 ? "services:\n  web:\n    type: node\n" : `includes:\n  - ./${i + 1}.yml\n`,
        "utf8",
      );
    }

    const error = await Effect.runPromise(
      Effect.flip(
        resolveLandofileIncludes({
          landofile: { includes: ["./0.yml"] },
          appRoot,
          cacheRoot,
          ports: makeTestLandofilePorts(cacheRoot),
          maxDepth: 3,
        }),
      ),
    );

    expect(error._tag).toBe("LandofileIncludeError");
    expect(includeErrorKind(error)).toBe("max-depth");
  });

  test("rejects local includes outside the app root", async () => {
    const outside = join(await mkdtemp(join(tmpdir(), "lando-outside-")), "fragment.yml");
    await writeFile(outside, "services:\n  web:\n    type: node\n", "utf8");

    const error = await Effect.runPromise(
      Effect.flip(resolveEffect({ includes: [outside] }, appRoot, cacheRoot)),
    );

    expect(error._tag).toBe("LandofileIncludeError");
    expect(includeErrorKind(error)).toBe("outside-root");
  });

  test("rejects a git fragment path that escapes the cloned repo via a symlink", async () => {
    const secretDir = await mkdtemp(join(tmpdir(), "lando-includes-secret-"));
    await writeFile(join(secretDir, "secret.yml"), "services:\n  leak:\n    type: node\n", "utf8");
    const cloner: GitIncludeCloner = {
      clone: async ({ stagingDir }) => {
        await mkdir(stagingDir, { recursive: true });
        await symlink(join(secretDir, "secret.yml"), join(stagingDir, "postgres.yml"));
        return { commitSha: "abc123" };
      },
    };

    try {
      const error = await Effect.runPromise(
        Effect.flip(
          resolveLandofileIncludes({
            landofile: { includes: [{ source: "github:acme/fragments", path: "postgres.yml" }] },
            appRoot,
            cacheRoot,
            ports: makeTestLandofilePorts(cacheRoot),
            deps: { gitCloner: cloner },
          }),
        ),
      );

      expect(error._tag).toBe("LandofileIncludeError");
      expect(includeErrorKind(error)).toBe("outside-root");
      expect(await exists(join(appRoot, ".lando.lock.yml"))).toBe(false);
    } finally {
      await rm(secretDir, { recursive: true, force: true });
    }
  });

  test("rejects fragments that declare a forbidden top-level name", async () => {
    await writeFile(
      join(appRoot, "named.yml"),
      "name: forbidden\nservices:\n  web:\n    type: node\n",
      "utf8",
    );

    const error = await Effect.runPromise(
      Effect.flip(resolveEffect({ includes: ["./named.yml"] }, appRoot, cacheRoot)),
    );

    expect(error._tag).toBe("LandofileIncludeError");
    expect(includeErrorKind(error)).toBe("forbidden-field");
  });

  test("records absolute local include paths for nested fragments", async () => {
    // Given a fragment that itself includes another fragment. Nested include specs resolve
    // against the app root, not the including fragment's directory, so both live at the root.
    const innerPath = join(appRoot, "inner.yml");
    await writeFile(join(appRoot, "outer.yml"), "includes:\n  - ./inner.yml\n", "utf8");
    await writeFile(innerPath, "services:\n  cache:\n    type: redis\n", "utf8");

    // When
    const resolved = await runResolve({ includes: ["./outer.yml"] }, appRoot, cacheRoot);
    const localIncludePaths = getLocalIncludePaths(resolved);

    // Then every remembered path stays an absolute filesystem path, because the app-plan cache
    // invalidator realpaths and root-checks them; an authored relative spec would resolve wrong.
    expect(localIncludePaths.every(isAbsolute)).toBe(true);
    expect(await Promise.all(localIncludePaths.map((path) => realpath(path)))).toContain(
      await realpath(innerPath),
    );
  });
});
