import { createHash } from "node:crypto";
import { isAbsolute, join } from "node:path";

import { type Context, Effect, Layer } from "effect";

import { GlobalAppError, GlobalDistConflictError, GlobalLandofilePathConflictError } from "@lando/sdk/errors";
import { AbsolutePath, type MountInput, type ServiceConfig } from "@lando/sdk/schema";
import { ConfigService, FileSystem, GlobalAppService } from "@lando/sdk/services";

export { GlobalAppService } from "@lando/sdk/services";

export const GLOBAL_APP_ID = "global";

const distMarker = "# DO NOT EDIT — regenerated by Lando.";
const distOverrideHint = "# Put global app overrides in .lando.yml (merged after this file).";
const distHashPrefix = "# lando-global-dist-sha256: ";
const userLandofileContent = [
  "# User overrides for the global Lando app.",
  "# Generated services live in .lando.dist.yml (merged before this file).",
  "",
].join("\n");

const globalAppError = (operation: string, message: string, cause: unknown): GlobalAppError =>
  new GlobalAppError({ message, operation, cause });

const sha256 = (content: string): string => createHash("sha256").update(content).digest("hex");

const sortedEntries = <T>(record: Readonly<Record<string, T>>): ReadonlyArray<readonly [string, T]> =>
  Object.entries(record).sort(([left], [right]) => left.localeCompare(right));

const isPlainRecord = (value: unknown): value is Record<string, unknown> =>
  typeof value === "object" && value !== null && !Array.isArray(value);

const escapeDoubleQuotedScalar = (value: string): string =>
  value
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\n/g, "\\n")
    .replace(/\r/g, "\\r")
    .replace(/\t/g, "\\t");

const formatScalar = (value: string | number | boolean | null): string => {
  if (value === null) return "null";
  if (typeof value === "number" || typeof value === "boolean") return String(value);
  if (
    value === "" ||
    /^\s|\s$/.test(value) ||
    /[#[\]\{\}\n\r\t]/.test(value) ||
    /^[A-Za-z_][A-Za-z0-9_-]*:(?:\s|$)/.test(value) ||
    (value.startsWith("'") && value.endsWith("'")) ||
    (value.startsWith('"') && value.endsWith('"')) ||
    value === "null" ||
    value === "true" ||
    value === "false" ||
    /^-?\d+(?:\.\d+)?$/.test(value)
  ) {
    if (!/[\n\r\t]/.test(value) && !value.includes("'")) return `'${value}'`;
    return `"${escapeDoubleQuotedScalar(value)}"`;
  }
  return value;
};

const emitArray = (items: ReadonlyArray<unknown>, indent: number): ReadonlyArray<string> => {
  const prefix = " ".repeat(indent);
  if (items.length === 0) return [`${prefix}[]`];

  return items.flatMap((item) => {
    if (isPlainRecord(item)) {
      const entries = sortedEntries(item);
      if (entries.length === 0) return [`${prefix}- {}`];
      const firstEntry = entries[0];
      if (firstEntry === undefined) return [`${prefix}- {}`];
      const [firstKey, firstValue] = firstEntry;
      const rest = entries.slice(1);
      const lines = emitValue(firstKey, firstValue, indent, "- ");
      return [...lines, ...rest.flatMap(([key, value]) => emitValue(key, value, indent + 2))];
    }

    if (Array.isArray(item)) return [`${prefix}- ${JSON.stringify(item)}`];
    return [`${prefix}- ${formatScalar(item as string | number | boolean | null)}`];
  });
};

const emitValue = (key: string, value: unknown, indent: number, marker = ""): ReadonlyArray<string> => {
  const prefix = `${" ".repeat(indent)}${marker}${key}:`;
  if (Array.isArray(value)) {
    if (value.length === 0) return [`${prefix} []`];
    return [prefix, ...emitArray(value, indent + marker.length + 2)];
  }
  if (isPlainRecord(value)) {
    const entries = sortedEntries(value);
    if (entries.length === 0) return [prefix];
    return [
      prefix,
      ...entries.flatMap(([nestedKey, nestedValue]) =>
        emitValue(nestedKey, nestedValue, indent + marker.length + 2),
      ),
    ];
  }
  return [`${prefix} ${formatScalar(value as string | number | boolean | null)}`];
};

const emitServices = (services: Readonly<Record<string, ServiceConfig>>): ReadonlyArray<string> =>
  sortedEntries(services).flatMap(([serviceId, service]) => emitValue(serviceId, service, 2));

const buildDistBody = (services: Readonly<Record<string, ServiceConfig>>): string =>
  ["name: global", "runtime: 4", "services:", ...emitServices(services), ""].join("\n");

const buildDistContent = (services: Readonly<Record<string, ServiceConfig>>): string => {
  const body = buildDistBody(services);
  return [distMarker, distOverrideHint, `${distHashPrefix}${sha256(body)}`, body].join("\n");
};

// Windows drive-letter prefix ("C:\" or "C:/") whose ":" is a path char, not a mount separator.
const DRIVE_LETTER_PREFIX = /^[A-Za-z]:[\\/]/;

const isBindPathSource = (source: string): boolean =>
  source.startsWith(".") ||
  source.startsWith("/") ||
  source.startsWith("~") ||
  DRIVE_LETTER_PREFIX.test(source);

const stringMountBindSource = (entry: string): string | undefined => {
  const source = DRIVE_LETTER_PREFIX.test(entry)
    ? `${entry.slice(0, 2)}${entry.slice(2).split(":")[0] ?? ""}`
    : entry.split(":")[0];
  if (source === undefined || source.length === 0) return undefined;
  return isBindPathSource(source) ? source : undefined;
};

const mountBindSource = (mount: MountInput): string | undefined => {
  if (typeof mount === "string") return stringMountBindSource(mount);
  return (mount.type ?? "bind") === "bind" && mount.source !== undefined ? mount.source : undefined;
};

const bindMountSources = (services: Readonly<Record<string, ServiceConfig>>): ReadonlyArray<string> =>
  Object.values(services).flatMap((service) =>
    (service.mounts ?? []).flatMap((mount) => {
      const source = mountBindSource(mount);
      return source === undefined ? [] : [source];
    }),
  );

const splitYamlLines = (content: string): ReadonlyArray<string> => content.split(/\r?\n/);

const currentDistBody = (content: string): string => splitYamlLines(content).slice(3).join("\n");

const embeddedDistHash = (content: string): string | undefined =>
  splitYamlLines(content)
    .find((line) => line.startsWith(distHashPrefix))
    ?.slice(distHashPrefix.length)
    .trim();

const makeGlobalAppService = (
  configService: Context.Tag.Service<typeof ConfigService>,
  fileSystem: Context.Tag.Service<typeof FileSystem>,
): Context.Tag.Service<typeof GlobalAppService> => {
  const root = configService.get("userDataRoot").pipe(
    Effect.mapError(
      (cause) =>
        new GlobalAppError({
          message: "Unable to resolve the user data root for the global app.",
          operation: "root",
          cause,
        }),
    ),
    Effect.flatMap((userDataRoot) =>
      userDataRoot === undefined
        ? Effect.fail(
            new GlobalAppError({
              message: "No user data root is configured; cannot locate the global app directory.",
              operation: "root",
              remediation: "Set userDataRoot in the Lando config or LANDO_USER_DATA_ROOT.",
            }),
          )
        : Effect.succeed(AbsolutePath.make(join(userDataRoot, GLOBAL_APP_ID))),
    ),
  );

  const paths = root.pipe(
    Effect.map((globalRoot) => ({
      root: globalRoot,
      distLandofile: AbsolutePath.make(join(globalRoot, ".lando.dist.yml")),
      userLandofile: AbsolutePath.make(join(globalRoot, ".lando.yml")),
    })),
  );

  const ensureRoot = root.pipe(
    Effect.flatMap((path) =>
      fileSystem
        .mkdir(path)
        .pipe(
          Effect.mapError((cause) =>
            globalAppError("ensureRoot", `Unable to create the global app directory at ${path}.`, cause),
          ),
        ),
    ),
  );

  const ensureUserLandofile = Effect.gen(function* () {
    const resolved = yield* paths;
    yield* ensureRoot;
    const existing = yield* fileSystem.lstat(resolved.userLandofile).pipe(
      Effect.map((stats) => ({ _tag: "stat" as const, stats })),
      Effect.catchTag("FileNotFoundError", () => Effect.succeed({ _tag: "missing" as const })),
      Effect.mapError((cause) =>
        globalAppError(
          "ensureUserLandofile",
          `Unable to inspect the global app overlay path at ${resolved.userLandofile}.`,
          cause,
        ),
      ),
    );

    if (existing._tag === "missing") {
      yield* fileSystem
        .writeAtomic(resolved.userLandofile, userLandofileContent)
        .pipe(
          Effect.mapError((cause) =>
            globalAppError(
              "ensureUserLandofile",
              `Unable to create the global app overlay file at ${resolved.userLandofile}.`,
              cause,
            ),
          ),
        );
      return { path: resolved.userLandofile, created: true };
    }

    if (existing.stats.isDirectory) {
      return yield* Effect.fail(
        new GlobalLandofilePathConflictError({
          message: `The global app overlay path is a directory: ${resolved.userLandofile}.`,
          path: resolved.userLandofile,
          expected: "file",
          actual: "directory",
          remediation: `Remove the directory at ${resolved.userLandofile} so Lando can create the global overlay file.`,
        }),
      );
    }

    return { path: resolved.userLandofile, created: false };
  });

  const regenerateDist = (input?: { readonly services?: Record<string, ServiceConfig> }) =>
    Effect.gen(function* () {
      const resolved = yield* paths;
      yield* ensureRoot;
      const services = input?.services ?? {};
      for (const source of bindMountSources(services)) {
        const mountPath = isAbsolute(source) ? source : join(resolved.root, source);
        yield* fileSystem
          .mkdir(mountPath)
          .pipe(
            Effect.mapError((cause) =>
              globalAppError(
                "regenerateDist",
                `Unable to create the global service bind-mount source at ${mountPath}.`,
                cause,
              ),
            ),
          );
      }
      const serviceIds = Object.keys(services).sort((left, right) => left.localeCompare(right));
      const nextContent = buildDistContent(services);
      const exists = yield* fileSystem
        .exists(resolved.distLandofile)
        .pipe(
          Effect.mapError((cause) =>
            globalAppError(
              "regenerateDist",
              `Unable to check the generated global app Landofile at ${resolved.distLandofile}.`,
              cause,
            ),
          ),
        );

      if (!exists) {
        yield* fileSystem
          .writeAtomic(resolved.distLandofile, nextContent)
          .pipe(
            Effect.mapError((cause) =>
              globalAppError(
                "regenerateDist",
                `Unable to write the generated global app Landofile at ${resolved.distLandofile}.`,
                cause,
              ),
            ),
          );
        return { path: resolved.distLandofile, status: "created" as const, serviceIds };
      }

      const currentContent = yield* fileSystem
        .readText(resolved.distLandofile)
        .pipe(
          Effect.mapError((cause) =>
            globalAppError(
              "regenerateDist",
              `Unable to read the generated global app Landofile at ${resolved.distLandofile}.`,
              cause,
            ),
          ),
        );

      if (splitYamlLines(currentContent)[0] !== distMarker) {
        return yield* Effect.fail(
          new GlobalDistConflictError({
            message: `The generated global app Landofile path is not managed by Lando: ${resolved.distLandofile}.`,
            path: resolved.distLandofile,
            reason: "foreign-file",
            remediation: "Move .lando.dist.yml aside or move overrides into .lando.yml, then rerun.",
          }),
        );
      }

      const currentHash = embeddedDistHash(currentContent);
      const actualHash = sha256(currentDistBody(currentContent));
      if (currentHash !== actualHash) {
        return yield* Effect.fail(
          new GlobalDistConflictError({
            message: `The generated global app Landofile was manually edited: ${resolved.distLandofile}.`,
            path: resolved.distLandofile,
            reason: "manual-edit",
            remediation:
              "move changes from .lando.dist.yml into .lando.yml, then restore the generated file and rerun.",
          }),
        );
      }

      if (currentContent === nextContent) {
        return { path: resolved.distLandofile, status: "unchanged" as const, serviceIds };
      }

      yield* fileSystem
        .writeAtomic(resolved.distLandofile, nextContent)
        .pipe(
          Effect.mapError((cause) =>
            globalAppError(
              "regenerateDist",
              `Unable to write the generated global app Landofile at ${resolved.distLandofile}.`,
              cause,
            ),
          ),
        );
      return { path: resolved.distLandofile, status: "updated" as const, serviceIds };
    });

  const ensureRunning = () =>
    Effect.fail(
      globalAppError("ensureRunning", "Global service startup requires the app runtime.", undefined),
    );
  return { id: GLOBAL_APP_ID, root, ensureRoot, paths, ensureUserLandofile, ensureRunning, regenerateDist };
};

export const GlobalAppServiceLive = Layer.effect(
  GlobalAppService,
  Effect.gen(function* () {
    const configService = yield* ConfigService;
    const fileSystem = yield* FileSystem;
    return makeGlobalAppService(configService, fileSystem);
  }),
);
