import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { afterEach, beforeEach, describe, expect, test } from "bun:test";
import { Effect } from "effect";

import type { LandofileShape } from "@lando/sdk/schema";

import { verifyLandofileIncludes } from "../../src/landofile/includes.ts";
import type { GitIncludeCloner } from "../../src/landofile/includes.ts";

const lockfile = (source: string, resolved: string, checksum: string) =>
  [
    "# DO NOT EDIT - generated by Lando.",
    "includes:",
    `  - source: ${source}`,
    `    resolved: ${resolved}`,
    `    checksum: ${checksum}`,
    "",
  ].join("\n");

const sha256 = (content: string): string => new Bun.CryptoHasher("sha256").update(content).digest("hex");

const FRAGMENT = "services:\n  database:\n    type: postgres\n";

const clonerFor = (fragment: string, commitSha: string): GitIncludeCloner => ({
  clone: async ({ stagingDir }) => {
    await mkdir(stagingDir, { recursive: true });
    await writeFile(join(stagingDir, "postgres.yml"), fragment, "utf8");
    return { commitSha };
  },
});

describe("verifyLandofileIncludes", () => {
  let appRoot: string;
  let cacheRoot: string;
  let previousCacheRoot: string | undefined;

  beforeEach(async () => {
    appRoot = await mkdtemp(join(tmpdir(), "lando-includes-verify-app-"));
    cacheRoot = await mkdtemp(join(tmpdir(), "lando-includes-verify-cache-"));
    previousCacheRoot = process.env.LANDO_USER_CACHE_ROOT;
    process.env.LANDO_USER_CACHE_ROOT = cacheRoot;
  });

  afterEach(async () => {
    process.env.LANDO_USER_CACHE_ROOT = previousCacheRoot;
    await rm(appRoot, { recursive: true, force: true });
    await rm(cacheRoot, { recursive: true, force: true });
  });

  const runVerify = (landofile: LandofileShape, gitCloner?: GitIncludeCloner) =>
    Effect.runPromise(
      verifyLandofileIncludes({
        landofile,
        appRoot,
        cacheRoot,
        ...(gitCloner === undefined ? {} : { deps: { gitCloner } }),
      }),
    );

  test("a Landofile with no remote includes verifies ok with no entries", async () => {
    const report = await runVerify({ name: "demo", recipe: "lamp" });
    expect(report.entries).toEqual([]);
    expect(report.mismatches).toEqual([]);
    expect(report.ok).toBe(true);
  });

  test("a fresh matching lock verifies ok", async () => {
    const source = "github:acme/fragments/postgres.yml";
    await writeFile(join(appRoot, ".lando.lock.yml"), lockfile(source, "abc123", sha256(FRAGMENT)), "utf8");

    const report = await runVerify(
      { includes: [{ source: "github:acme/fragments", path: "postgres.yml" }] },
      clonerFor(FRAGMENT, "abc123"),
    );

    expect(report.ok).toBe(true);
    expect(report.mismatches).toEqual([]);
    expect(report.entries).toEqual([
      {
        source,
        status: "ok",
        expected: `abc123:${sha256(FRAGMENT)}`,
        actual: `abc123:${sha256(FRAGMENT)}`,
      },
    ]);
    // Read-only: lockfile content is unchanged.
    expect(await readFile(join(appRoot, ".lando.lock.yml"), "utf8")).toBe(
      lockfile(source, "abc123", sha256(FRAGMENT)),
    );
  });

  test("a checksum/ref drift reports a mismatch in the LandofileLockMismatchError schema", async () => {
    const source = "github:acme/fragments/postgres.yml";
    await writeFile(join(appRoot, ".lando.lock.yml"), lockfile(source, "old123", "a".repeat(64)), "utf8");

    const report = await runVerify(
      { includes: [{ source: "github:acme/fragments", path: "postgres.yml" }] },
      clonerFor(FRAGMENT, "new456"),
    );

    expect(report.ok).toBe(false);
    expect(report.entries).toEqual([
      {
        source,
        status: "mismatch",
        expected: `old123:${"a".repeat(64)}`,
        actual: `new456:${sha256(FRAGMENT)}`,
      },
    ]);
    expect(report.mismatches).toHaveLength(1);
    const mismatch = report.mismatches[0];
    expect(mismatch?._tag).toBe("LandofileLockMismatchError");
    expect(mismatch?.source).toBe(source);
    expect(mismatch?.lockfile).toBe(join(appRoot, ".lando.lock.yml"));
    expect(mismatch?.expected).toBe(`old123:${"a".repeat(64)}`);
    expect(mismatch?.actual).toBe(`new456:${sha256(FRAGMENT)}`);
    expect(mismatch?.remediation).toContain("lando app:includes:update");
    // Read-only: lockfile is NOT rewritten.
    expect(await readFile(join(appRoot, ".lando.lock.yml"), "utf8")).toBe(
      lockfile(source, "old123", "a".repeat(64)),
    );
  });

  test("a remote include with no lock entry reports a missing status", async () => {
    const report = await runVerify(
      { includes: [{ source: "github:acme/fragments", path: "postgres.yml" }] },
      clonerFor(FRAGMENT, "abc123"),
    );

    expect(report.ok).toBe(false);
    expect(report.entries).toEqual([
      {
        source: "github:acme/fragments/postgres.yml",
        status: "missing",
        expected: null,
        actual: `abc123:${sha256(FRAGMENT)}`,
      },
    ]);
    expect(report.mismatches[0]?.expected).toBe("<missing>");
    expect(report.mismatches[0]?.actual).toBe(`abc123:${sha256(FRAGMENT)}`);
    // Read-only: no lockfile is written.
    expect(await Bun.file(join(appRoot, ".lando.lock.yml")).exists()).toBe(false);
  });

  test("an orphan lock entry with no resolved fragment reports a stale status", async () => {
    const source = "github:acme/fragments/postgres.yml";
    await writeFile(join(appRoot, ".lando.lock.yml"), lockfile(source, "abc123", sha256(FRAGMENT)), "utf8");

    const report = await runVerify({ name: "demo", recipe: "lamp" });

    expect(report.ok).toBe(false);
    expect(report.entries).toEqual([
      { source, status: "stale", expected: `abc123:${sha256(FRAGMENT)}`, actual: null },
    ]);
    expect(report.mismatches[0]?.actual).toBe("<missing>");
    // Read-only: orphan lock entry is preserved.
    expect(await readFile(join(appRoot, ".lando.lock.yml"), "utf8")).toBe(
      lockfile(source, "abc123", sha256(FRAGMENT)),
    );
  });
});
