import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { afterEach, beforeEach, describe, expect, test } from "bun:test";
import { Effect } from "effect";

import type { LandofileShape } from "@lando/sdk/schema";

import { updateLandofileIncludes } from "../../src/landofile/includes.ts";
import type { GitIncludeCloner } from "../../src/landofile/includes.ts";

const lockfile = (source: string, resolved: string, checksum: string) =>
  [
    "# DO NOT EDIT - generated by Lando.",
    "includes:",
    `  - source: ${source}`,
    `    resolved: ${resolved}`,
    `    checksum: ${checksum}`,
    "",
  ].join("\n");

const sha256 = (content: string): string => new Bun.CryptoHasher("sha256").update(content).digest("hex");

const exists = (path: string) =>
  Bun.file(path)
    .exists()
    .catch(() => false);

describe("updateLandofileIncludes", () => {
  let appRoot: string;
  let cacheRoot: string;
  let previousCacheRoot: string | undefined;

  beforeEach(async () => {
    appRoot = await mkdtemp(join(tmpdir(), "lando-includes-update-app-"));
    cacheRoot = await mkdtemp(join(tmpdir(), "lando-includes-update-cache-"));
    previousCacheRoot = process.env.LANDO_USER_CACHE_ROOT;
    process.env.LANDO_USER_CACHE_ROOT = cacheRoot;
  });

  afterEach(async () => {
    process.env.LANDO_USER_CACHE_ROOT = previousCacheRoot;
    await rm(appRoot, { recursive: true, force: true });
    await rm(cacheRoot, { recursive: true, force: true });
  });

  const runUpdate = (landofile: LandofileShape, gitCloner?: GitIncludeCloner, check?: boolean) =>
    Effect.runPromise(
      updateLandofileIncludes({
        landofile,
        appRoot,
        cacheRoot,
        ...(gitCloner === undefined ? {} : { deps: { gitCloner } }),
        ...(check === true ? { check: true } : {}),
      }),
    );

  test("refresh rewrites a drifted git lock instead of failing closed", async () => {
    const fragment = "services:\n  database:\n    type: postgres\n";
    const source = "github:acme/fragments/postgres.yml";
    await writeFile(join(appRoot, ".lando.lock.yml"), lockfile(source, "old123", "0".repeat(64)), "utf8");
    const gitCloner: GitIncludeCloner = {
      clone: async ({ stagingDir }) => {
        await mkdir(stagingDir, { recursive: true });
        await writeFile(join(stagingDir, "postgres.yml"), fragment, "utf8");
        return { commitSha: "new456" };
      },
    };

    const report = await runUpdate(
      { includes: [{ source: "github:acme/fragments", path: "postgres.yml" }] },
      gitCloner,
    );

    expect(report.entries).toEqual([
      { source, resolved: "new456", checksum: sha256(fragment), status: "updated" },
    ]);
    expect(report.drift).toBe(true);
    expect(report.wrote).toBe(true);
    expect(report.checkMode).toBe(false);
    const written = await readFile(join(appRoot, ".lando.lock.yml"), "utf8");
    expect(written).toContain("resolved: new456");
    expect(written).toContain(`checksum: ${sha256(fragment)}`);
  });

  test("adds a missing git include lock", async () => {
    const fragment = "services:\n  database:\n    type: postgres\n";
    const gitCloner: GitIncludeCloner = {
      clone: async ({ stagingDir }) => {
        await mkdir(stagingDir, { recursive: true });
        await writeFile(join(stagingDir, "postgres.yml"), fragment, "utf8");
        return { commitSha: "abc123" };
      },
    };

    const report = await runUpdate(
      { includes: [{ source: "github:acme/fragments", path: "postgres.yml" }] },
      gitCloner,
    );

    expect(report.entries).toEqual([
      {
        source: "github:acme/fragments/postgres.yml",
        resolved: "abc123",
        checksum: sha256(fragment),
        status: "added",
      },
    ]);
    expect(report.drift).toBe(true);
    expect(report.wrote).toBe(true);
    expect(await exists(join(appRoot, ".lando.lock.yml"))).toBe(true);
  });

  test("leaves a matching fresh lock unchanged", async () => {
    const fragment = "services:\n  database:\n    type: postgres\n";
    const source = "github:acme/fragments/postgres.yml";
    await writeFile(join(appRoot, ".lando.lock.yml"), lockfile(source, "abc123", sha256(fragment)), "utf8");
    const gitCloner: GitIncludeCloner = {
      clone: async ({ stagingDir }) => {
        await mkdir(stagingDir, { recursive: true });
        await writeFile(join(stagingDir, "postgres.yml"), fragment, "utf8");
        return { commitSha: "abc123" };
      },
    };

    const report = await runUpdate(
      { includes: [{ source: "github:acme/fragments", path: "postgres.yml" }] },
      gitCloner,
    );

    expect(report.entries[0]?.status).toBe("unchanged");
    expect(report.drift).toBe(false);
    expect(report.wrote).toBe(false);
  });

  test("check mode reports drift without rewriting the lockfile", async () => {
    const fragment = "services:\n  database:\n    type: postgres\n";
    const source = "github:acme/fragments/postgres.yml";
    const original = lockfile(source, "old123", "0".repeat(64));
    const path = join(appRoot, ".lando.lock.yml");
    await writeFile(path, original, "utf8");
    const gitCloner: GitIncludeCloner = {
      clone: async ({ stagingDir }) => {
        await mkdir(stagingDir, { recursive: true });
        await writeFile(join(stagingDir, "postgres.yml"), fragment, "utf8");
        return { commitSha: "new456" };
      },
    };

    const report = await runUpdate(
      { includes: [{ source: "github:acme/fragments", path: "postgres.yml" }] },
      gitCloner,
      true,
    );

    expect(report.drift).toBe(true);
    expect(report.wrote).toBe(false);
    expect(report.checkMode).toBe(true);
    expect(await readFile(path, "utf8")).toBe(original);
  });

  test("reports no drift for a Landofile with no remote includes", async () => {
    const report = await runUpdate({ name: "demo", recipe: "lamp" });

    expect(report.entries).toEqual([]);
    expect(report.removed).toEqual([]);
    expect(report.drift).toBe(false);
    expect(report.wrote).toBe(false);
  });
});
