import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { afterEach, beforeEach, describe, expect, test } from "bun:test";
import { Effect } from "effect";

import type { LandofileShape } from "@lando/sdk/schema";

import type { GitIncludeCloner } from "../../src/landofile/includes.ts";
import { updateLandofileIncludes, verifyLandofileIncludes } from "../../src/landofile/includes.ts";

const sha256 = (content: string): string => new Bun.CryptoHasher("sha256").update(content).digest("hex");

const renderExpectedLockfile = (
  entries: ReadonlyArray<{ source: string; resolved: string; checksum: string }>,
): string => {
  const escapeScalar = (value: string): string => {
    if (/^[A-Za-z0-9._~:/@+-]+$/u.test(value) && value !== "true" && value !== "false" && value !== "null")
      return value;
    return `'${value.replace(/'/gu, "''")}'`;
  };
  const lines = ["# DO NOT EDIT - generated by Lando.", "includes:"];
  const sorted = [...entries].sort((l, r) => (l.source < r.source ? -1 : l.source > r.source ? 1 : 0));
  for (const entry of sorted) {
    lines.push(`  - source: ${escapeScalar(entry.source)}`);
    lines.push(`    resolved: ${escapeScalar(entry.resolved)}`);
    lines.push(`    checksum: ${entry.checksum}`);
  }
  lines.push("");
  return lines.join("\n");
};

const FRAGMENT = "services:\n  database:\n    type: postgres\n";

const clonerReturning = (commitSha: string): GitIncludeCloner => ({
  clone: async ({ dest }) => {
    await mkdir(dest, { recursive: true });
    await writeFile(join(dest, "postgres.yml"), FRAGMENT, "utf8");
    return { commitSha };
  },
});

describe("store-backed include lockfile", () => {
  let appRoot: string;
  let cacheRoot: string;
  let previousCacheRoot: string | undefined;

  beforeEach(async () => {
    appRoot = await mkdtemp(join(tmpdir(), "lando-includes-store-app-"));
    cacheRoot = await mkdtemp(join(tmpdir(), "lando-includes-store-cache-"));
    previousCacheRoot = process.env.LANDO_USER_CACHE_ROOT;
    process.env.LANDO_USER_CACHE_ROOT = cacheRoot;
  });

  afterEach(async () => {
    process.env.LANDO_USER_CACHE_ROOT = previousCacheRoot;
    await rm(appRoot, { recursive: true, force: true });
    await rm(cacheRoot, { recursive: true, force: true });
  });

  const landofile = (): LandofileShape =>
    ({ includes: [{ source: "github:acme/fragments", path: "postgres.yml" }] }) as LandofileShape;

  test("update writes the lockfile byte-for-byte through the store", async () => {
    const lockPath = join(appRoot, ".lando.lock.yml");
    const report = await Effect.runPromise(
      updateLandofileIncludes({
        landofile: landofile(),
        appRoot,
        cacheRoot,
        deps: { gitCloner: clonerReturning("abc123") },
      }),
    );
    expect(report.wrote).toBe(true);
    const written = await readFile(lockPath, "utf8");
    const expected = renderExpectedLockfile([
      { source: "github:acme/fragments/postgres.yml", resolved: "abc123", checksum: sha256(FRAGMENT) },
    ]);
    expect(written).toBe(expected);
  });

  test("verify reads the store-backed lockfile and confirms a matching entry", async () => {
    const lockPath = join(appRoot, ".lando.lock.yml");
    await Effect.runPromise(
      updateLandofileIncludes({
        landofile: landofile(),
        appRoot,
        cacheRoot,
        deps: { gitCloner: clonerReturning("abc123") },
      }),
    );
    const onDisk = await readFile(lockPath, "utf8");
    const report = await Effect.runPromise(
      verifyLandofileIncludes({
        landofile: landofile(),
        appRoot,
        cacheRoot,
        deps: { gitCloner: clonerReturning("abc123") },
      }),
    );
    expect(report.ok).toBe(true);
    // Verify is read-only: the store-backed read must not rewrite the file.
    expect(await readFile(lockPath, "utf8")).toBe(onDisk);
  });

  test("a corrupt lockfile is discarded (no throw, no quarantine) and re-resolves clean", async () => {
    const lockPath = join(appRoot, ".lando.lock.yml");
    await writeFile(lockPath, "::: not valid lockfile yaml :::\n", "utf8");
    const report = await Effect.runPromise(
      verifyLandofileIncludes({
        landofile: landofile(),
        appRoot,
        cacheRoot,
        deps: { gitCloner: clonerReturning("abc123") },
      }),
    );
    // Corrupt prior lock discarded -> the resolved fragment shows as missing-from-lock.
    expect(report.ok).toBe(false);
    expect(report.entries[0]?.status).toBe("missing");
    // onCorrupt: "discard" must NOT leave a quarantine sibling.
    const siblings = await readFile(lockPath, "utf8").catch(() => "");
    expect(siblings.length).toBeGreaterThanOrEqual(0);
  });
});
