import { mkdir, mkdtemp, readFile, rm, stat, symlink, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { Effect } from "effect";

import type { LandofileShape } from "@lando/sdk/schema";

import { resolveLandofileIncludes } from "../../src/landofile/includes.ts";
import type {
  GitIncludeCloner,
  NpmIncludeExtractor,
  NpmIncludeFetcher,
  NpmIncludeRegistryClient,
} from "../../src/landofile/includes.ts";

const resolveEffect = (landofile: LandofileShape, appRoot: string, cacheRoot: string) =>
  resolveLandofileIncludes({ landofile, appRoot, cacheRoot });

const runResolve = (landofile: LandofileShape, appRoot: string, cacheRoot: string) =>
  Effect.runPromise(resolveEffect(landofile, appRoot, cacheRoot));

const exists = (path: string) =>
  stat(path).then(
    () => true,
    () => false,
  );

const lockfile = (source: string, resolved: string, checksum: string) =>
  [
    "# DO NOT EDIT - generated by Lando.",
    "includes:",
    `  - source: ${source}`,
    `    resolved: ${resolved}`,
    `    checksum: ${checksum}`,
    "",
  ].join("\n");

describe("resolveLandofileIncludes", () => {
  let appRoot: string;
  let cacheRoot: string;
  let previousCacheRoot: string | undefined;

  beforeEach(async () => {
    appRoot = await mkdtemp(join(tmpdir(), "lando-includes-app-"));
    cacheRoot = await mkdtemp(join(tmpdir(), "lando-includes-cache-"));
    previousCacheRoot = process.env.LANDO_USER_CACHE_ROOT;
    process.env.LANDO_USER_CACHE_ROOT = cacheRoot;
  });

  afterEach(async () => {
    process.env.LANDO_USER_CACHE_ROOT = previousCacheRoot;
    await rm(appRoot, { recursive: true, force: true });
    await rm(cacheRoot, { recursive: true, force: true });
  });

  test("merges a local relative include and does not write a lockfile", async () => {
    await writeFile(join(appRoot, "fragment.yml"), "services:\n  api:\n    type: node\n", "utf8");

    const result = await runResolve(
      { name: "demo", includes: ["./fragment.yml"], services: { api: { primary: true } } },
      appRoot,
      cacheRoot,
    );

    expect(result).toEqual({ name: "demo", services: { api: { type: "node", primary: true } } });
    expect(await exists(join(appRoot, ".lando.lock.yml"))).toBe(false);
  });

  test("creates a git include lock entry with commit SHA and fragment checksum", async () => {
    const cloner: GitIncludeCloner = {
      clone: async ({ stagingDir }) => {
        await mkdir(stagingDir, { recursive: true });
        await writeFile(
          join(stagingDir, "postgres.yml"),
          "services:\n  database:\n    type: postgres\n",
          "utf8",
        );
        return { commitSha: "abc123" };
      },
    };

    const result = await Effect.runPromise(
      resolveLandofileIncludes({
        landofile: {
          name: "demo",
          includes: [{ source: "github:acme/fragments@main", path: "postgres.yml" }],
        },
        appRoot,
        cacheRoot,
        deps: { gitCloner: cloner },
      }),
    );

    const written = await readFile(join(appRoot, ".lando.lock.yml"), "utf8");
    expect(result.services?.database?.type).toBe("postgres");
    expect(written).toContain("source: github:acme/fragments");
    expect(written).toContain("resolved: abc123");
    expect(written).toMatch(/checksum: [0-9a-f]{64}/);
  });

  test("uses a matching git lock without rewriting the lockfile", async () => {
    const fragment = "services:\n  database:\n    type: postgres\n";
    const checksum = new Bun.CryptoHasher("sha256").update(fragment).digest("hex");
    const path = join(appRoot, ".lando.lock.yml");
    const locked = lockfile("github:acme/fragments/postgres.yml", "abc123", checksum);
    await writeFile(path, locked, "utf8");
    const cloner: GitIncludeCloner = {
      clone: async ({ stagingDir }) => {
        await mkdir(stagingDir, { recursive: true });
        await writeFile(join(stagingDir, "postgres.yml"), fragment, "utf8");
        return { commitSha: "abc123" };
      },
    };

    const result = await Effect.runPromise(
      resolveLandofileIncludes({
        landofile: { includes: [{ source: "github:acme/fragments", path: "postgres.yml" }] },
        appRoot,
        cacheRoot,
        deps: { gitCloner: cloner },
      }),
    );

    expect(result.services?.database?.type).toBe("postgres");
    expect(await readFile(path, "utf8")).toBe(locked);
  });

  test("fails closed with LandofileLockMismatchError when a git lock checksum drifts", async () => {
    await writeFile(
      join(appRoot, ".lando.lock.yml"),
      lockfile("github:acme/fragments/postgres.yml", "abc123", "0".repeat(64)),
      "utf8",
    );
    const cloner: GitIncludeCloner = {
      clone: async ({ stagingDir }) => {
        await mkdir(stagingDir, { recursive: true });
        await writeFile(
          join(stagingDir, "postgres.yml"),
          "services:\n  database:\n    type: postgres\n",
          "utf8",
        );
        return { commitSha: "abc123" };
      },
    };

    const error = await Effect.runPromise(
      Effect.flip(
        resolveLandofileIncludes({
          landofile: { includes: [{ source: "github:acme/fragments", path: "postgres.yml" }] },
          appRoot,
          cacheRoot,
          deps: { gitCloner: cloner },
        }),
      ),
    );

    expect(error._tag).toBe("LandofileLockMismatchError");
    expect(error.remediation).toContain("app:includes:update");
  });

  test("records distinct lock entries for two fragments from one git repo", async () => {
    const cloner: GitIncludeCloner = {
      clone: async ({ stagingDir }) => {
        await mkdir(stagingDir, { recursive: true });
        await writeFile(join(stagingDir, "db.yml"), "services:\n  db:\n    type: postgres\n", "utf8");
        await writeFile(join(stagingDir, "cache.yml"), "services:\n  cache:\n    type: redis\n", "utf8");
        return { commitSha: "abc123" };
      },
    };
    const landofile: LandofileShape = {
      includes: [
        { source: "github:acme/fragments", path: "db.yml" },
        { source: "github:acme/fragments", path: "cache.yml" },
      ],
    };

    const result = await Effect.runPromise(
      resolveLandofileIncludes({ landofile, appRoot, cacheRoot, deps: { gitCloner: cloner } }),
    );
    expect(result.services?.db?.type).toBe("postgres");
    expect(result.services?.cache?.type).toBe("redis");

    const written = await readFile(join(appRoot, ".lando.lock.yml"), "utf8");
    expect(written).toContain("source: github:acme/fragments/db.yml");
    expect(written).toContain("source: github:acme/fragments/cache.yml");

    const second = await Effect.runPromise(
      resolveLandofileIncludes({ landofile, appRoot, cacheRoot, deps: { gitCloner: cloner } }),
    );
    expect(second.services?.db?.type).toBe("postgres");
    expect(await readFile(join(appRoot, ".lando.lock.yml"), "utf8")).toBe(written);
  });

  test("creates an npm include lock entry with resolved version and checksum", async () => {
    const registryClient: NpmIncludeRegistryClient = {
      fetchPackument: async () => ({
        versions: { "1.2.3": { dist: { tarball: "https://registry.example/pkg.tgz" } } },
        "dist-tags": { latest: "1.2.3" },
      }),
    };
    const fetcher: NpmIncludeFetcher = { fetch: async () => new Uint8Array([1, 2, 3]) };
    const extractor: NpmIncludeExtractor = {
      extract: async (_bytes, destDir) => {
        await mkdir(join(destDir, "package", "fragments"), { recursive: true });
        await writeFile(
          join(destDir, "package", "fragments", "web.yml"),
          "services:\n  web:\n    type: node\n",
          "utf8",
        );
      },
    };

    const result = await Effect.runPromise(
      resolveLandofileIncludes({
        landofile: { includes: [{ source: "npm:@acme/fragments/fragments/web.yml@latest" }] },
        appRoot,
        cacheRoot,
        deps: { npmRegistryClient: registryClient, npmFetcher: fetcher, npmExtractor: extractor },
      }),
    );

    const written = await readFile(join(appRoot, ".lando.lock.yml"), "utf8");
    expect(result.services?.web?.type).toBe("node");
    expect(written).toContain("source: npm:@acme/fragments/fragments/web.yml");
    expect(written).toContain("resolved: 1.2.3");
  });

  test("resolves nested fragment includes before merging the parent fragment", async () => {
    await writeFile(join(appRoot, "base.yml"), "services:\n  api:\n    type: node\n", "utf8");
    await writeFile(
      join(appRoot, "parent.yml"),
      "includes:\n  - ./base.yml\nservices:\n  api:\n    primary: true\n",
      "utf8",
    );

    const result = await runResolve({ includes: ["./parent.yml"] }, appRoot, cacheRoot);

    expect(result).toEqual({ services: { api: { type: "node", primary: true } } });
  });

  test("rejects include cycles", async () => {
    await writeFile(join(appRoot, "a.yml"), "includes:\n  - ./b.yml\n", "utf8");
    await writeFile(join(appRoot, "b.yml"), "includes:\n  - ./a.yml\n", "utf8");

    const error = await Effect.runPromise(
      Effect.flip(resolveEffect({ includes: ["./a.yml"] }, appRoot, cacheRoot)),
    );

    expect(error._tag).toBe("LandofileIncludeError");
    expect(error.kind).toBe("cycle");
  });

  test("rejects include recursion past max depth", async () => {
    for (let i = 0; i < 10; i += 1) {
      await writeFile(
        join(appRoot, `${i}.yml`),
        i === 9 ? "services:\n  web:\n    type: node\n" : `includes:\n  - ./${i + 1}.yml\n`,
        "utf8",
      );
    }

    const error = await Effect.runPromise(
      Effect.flip(
        resolveLandofileIncludes({ landofile: { includes: ["./0.yml"] }, appRoot, cacheRoot, maxDepth: 3 }),
      ),
    );

    expect(error._tag).toBe("LandofileIncludeError");
    expect(error.kind).toBe("max-depth");
  });

  test("rejects local includes outside the app root", async () => {
    const outside = join(await mkdtemp(join(tmpdir(), "lando-outside-")), "fragment.yml");
    await writeFile(outside, "services:\n  web:\n    type: node\n", "utf8");

    const error = await Effect.runPromise(
      Effect.flip(resolveEffect({ includes: [outside] }, appRoot, cacheRoot)),
    );

    expect(error._tag).toBe("LandofileIncludeError");
    expect(error.kind).toBe("outside-root");
  });

  test("rejects a git fragment path that escapes the cloned repo via a symlink", async () => {
    const secretDir = await mkdtemp(join(tmpdir(), "lando-includes-secret-"));
    await writeFile(join(secretDir, "secret.yml"), "services:\n  leak:\n    type: node\n", "utf8");
    const cloner: GitIncludeCloner = {
      clone: async ({ stagingDir }) => {
        await mkdir(stagingDir, { recursive: true });
        await symlink(join(secretDir, "secret.yml"), join(stagingDir, "postgres.yml"));
        return { commitSha: "abc123" };
      },
    };

    try {
      const error = await Effect.runPromise(
        Effect.flip(
          resolveLandofileIncludes({
            landofile: { includes: [{ source: "github:acme/fragments", path: "postgres.yml" }] },
            appRoot,
            cacheRoot,
            deps: { gitCloner: cloner },
          }),
        ),
      );

      expect(error._tag).toBe("LandofileIncludeError");
      expect(error.kind).toBe("outside-root");
      expect(await exists(join(appRoot, ".lando.lock.yml"))).toBe(false);
    } finally {
      await rm(secretDir, { recursive: true, force: true });
    }
  });

  test("rejects fragments that declare a forbidden top-level name", async () => {
    await writeFile(
      join(appRoot, "named.yml"),
      "name: forbidden\nservices:\n  web:\n    type: node\n",
      "utf8",
    );

    const error = await Effect.runPromise(
      Effect.flip(resolveEffect({ includes: ["./named.yml"] }, appRoot, cacheRoot)),
    );

    expect(error._tag).toBe("LandofileIncludeError");
    expect(error.kind).toBe("forbidden-field");
  });
});
