import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, relative } from "node:path";

import { afterEach, beforeEach, describe, expect, test } from "bun:test";
import { Effect } from "effect";

import type { LandofileShape } from "@lando/sdk/schema";

import { updateLandofileIncludes } from "../../src/landofile/includes.ts";
import type { GitIncludeCloner } from "../../src/landofile/includes.ts";

const lockfile = (source: string, resolved: string, checksum: string) =>
  [
    "# DO NOT EDIT - generated by Lando.",
    "includes:",
    `  - source: ${source}`,
    `    resolved: ${resolved}`,
    `    checksum: ${checksum}`,
    "",
  ].join("\n");

const sha256 = (content: string): string => new Bun.CryptoHasher("sha256").update(content).digest("hex");

const exists = (path: string) =>
  Bun.file(path)
    .exists()
    .catch(() => false);

describe("updateLandofileIncludes", () => {
  let appRoot: string;
  let cacheRoot: string;
  let previousCacheRoot: string | undefined;

  beforeEach(async () => {
    appRoot = await mkdtemp(join(tmpdir(), "lando-includes-update-app-"));
    cacheRoot = await mkdtemp(join(tmpdir(), "lando-includes-update-cache-"));
    previousCacheRoot = process.env.LANDO_USER_CACHE_ROOT;
    process.env.LANDO_USER_CACHE_ROOT = cacheRoot;
  });

  afterEach(async () => {
    process.env.LANDO_USER_CACHE_ROOT = previousCacheRoot;
    await rm(appRoot, { recursive: true, force: true });
    await rm(cacheRoot, { recursive: true, force: true });
  });

  const runUpdate = (landofile: LandofileShape, gitCloner?: GitIncludeCloner, check?: boolean) =>
    Effect.runPromise(
      updateLandofileIncludes({
        landofile,
        appRoot,
        cacheRoot,
        ...(gitCloner === undefined ? {} : { deps: { gitCloner } }),
        ...(check === true ? { check: true } : {}),
      }),
    );

  test("refresh rewrites a drifted git lock instead of failing closed", async () => {
    const fragment = "services:\n  database:\n    type: postgres\n";
    const source = "github:acme/fragments/postgres.yml";
    await writeFile(join(appRoot, ".lando.lock.yml"), lockfile(source, "old123", "0".repeat(64)), "utf8");
    const gitCloner: GitIncludeCloner = {
      clone: async ({ stagingDir }) => {
        await mkdir(stagingDir, { recursive: true });
        await writeFile(join(stagingDir, "postgres.yml"), fragment, "utf8");
        return { commitSha: "new456" };
      },
    };

    const report = await runUpdate(
      { includes: [{ source: "github:acme/fragments", path: "postgres.yml" }] },
      gitCloner,
    );

    expect(report.entries).toEqual([
      { source, resolved: "new456", checksum: sha256(fragment), status: "updated" },
    ]);
    expect(report.drift).toBe(true);
    expect(report.wrote).toBe(true);
    expect(report.checkMode).toBe(false);
    const written = await readFile(join(appRoot, ".lando.lock.yml"), "utf8");
    expect(written).toContain("resolved: new456");
    expect(written).toContain(`checksum: ${sha256(fragment)}`);
  });

  test("adds a missing git include lock", async () => {
    const fragment = "services:\n  database:\n    type: postgres\n";
    const gitCloner: GitIncludeCloner = {
      clone: async ({ stagingDir }) => {
        await mkdir(stagingDir, { recursive: true });
        await writeFile(join(stagingDir, "postgres.yml"), fragment, "utf8");
        return { commitSha: "abc123" };
      },
    };

    const report = await runUpdate(
      { includes: [{ source: "github:acme/fragments", path: "postgres.yml" }] },
      gitCloner,
    );

    expect(report.entries).toEqual([
      {
        source: "github:acme/fragments/postgres.yml",
        resolved: "abc123",
        checksum: sha256(fragment),
        status: "added",
      },
    ]);
    expect(report.drift).toBe(true);
    expect(report.wrote).toBe(true);
    expect(await exists(join(appRoot, ".lando.lock.yml"))).toBe(true);
  });

  test("leaves a matching fresh lock unchanged", async () => {
    const fragment = "services:\n  database:\n    type: postgres\n";
    const source = "github:acme/fragments/postgres.yml";
    await writeFile(join(appRoot, ".lando.lock.yml"), lockfile(source, "abc123", sha256(fragment)), "utf8");
    const gitCloner: GitIncludeCloner = {
      clone: async ({ stagingDir }) => {
        await mkdir(stagingDir, { recursive: true });
        await writeFile(join(stagingDir, "postgres.yml"), fragment, "utf8");
        return { commitSha: "abc123" };
      },
    };

    const report = await runUpdate(
      { includes: [{ source: "github:acme/fragments", path: "postgres.yml" }] },
      gitCloner,
    );

    expect(report.entries[0]?.status).toBe("unchanged");
    expect(report.drift).toBe(false);
    expect(report.wrote).toBe(false);
  });

  test("check mode reports drift without rewriting the lockfile", async () => {
    const fragment = "services:\n  database:\n    type: postgres\n";
    const source = "github:acme/fragments/postgres.yml";
    const original = lockfile(source, "old123", "0".repeat(64));
    const path = join(appRoot, ".lando.lock.yml");
    await writeFile(path, original, "utf8");
    const gitCloner: GitIncludeCloner = {
      clone: async ({ stagingDir }) => {
        await mkdir(stagingDir, { recursive: true });
        await writeFile(join(stagingDir, "postgres.yml"), fragment, "utf8");
        return { commitSha: "new456" };
      },
    };

    const report = await runUpdate(
      { includes: [{ source: "github:acme/fragments", path: "postgres.yml" }] },
      gitCloner,
      true,
    );

    expect(report.drift).toBe(true);
    expect(report.wrote).toBe(false);
    expect(report.checkMode).toBe(true);
    expect(await readFile(path, "utf8")).toBe(original);
  });

  test("reports no drift for a Landofile with no remote includes", async () => {
    const report = await runUpdate({ name: "demo", recipe: "lamp" });

    expect(report.entries).toEqual([]);
    expect(report.removed).toEqual([]);
    expect(report.drift).toBe(false);
    expect(report.wrote).toBe(false);
    expect(report.noNetwork).toBe(false);
    expect(report.requestedSources).toEqual([]);
  });

  const clonerFor = (fragment: string, commitSha: string, calls: string[]): GitIncludeCloner => ({
    clone: async ({ url, stagingDir }) => {
      calls.push(url);
      await mkdir(stagingDir, { recursive: true });
      await writeFile(join(stagingDir, "postgres.yml"), fragment, "utf8");
      return { commitSha };
    },
  });

  const twoIncludeLandofile: LandofileShape = {
    includes: [
      { source: "github:acme/one", path: "postgres.yml" },
      { source: "github:acme/two", path: "postgres.yml" },
    ],
  };

  test("scoped update refreshes only the named source and preserves other lock entries", async () => {
    const fragOne = "services:\n  db1:\n    type: postgres\n";
    const lockPath = join(appRoot, ".lando.lock.yml");
    await writeFile(
      lockPath,
      [
        "# DO NOT EDIT - generated by Lando.",
        "includes:",
        "  - source: github:acme/one/postgres.yml",
        "    resolved: old1",
        `    checksum: ${"0".repeat(64)}`,
        "  - source: github:acme/two/postgres.yml",
        "    resolved: old2",
        `    checksum: ${"0".repeat(64)}`,
        "",
      ].join("\n"),
      "utf8",
    );
    const calls: string[] = [];
    const report = await Effect.runPromise(
      updateLandofileIncludes({
        landofile: twoIncludeLandofile,
        appRoot,
        cacheRoot,
        sources: ["github:acme/one"],
        deps: { gitCloner: clonerFor(fragOne, "new1", calls) },
      }),
    );

    expect(report.requestedSources).toEqual(["github:acme/one"]);
    expect(report.entries.map((entry) => entry.source)).toEqual(["github:acme/one/postgres.yml"]);
    expect(report.entries[0]?.resolved).toBe("new1");
    expect(calls).toEqual(["https://github.com/acme/one.git"]);
    const written = await readFile(lockPath, "utf8");
    expect(written).toContain("source: github:acme/one/postgres.yml");
    expect(written).toContain("resolved: new1");
    expect(written).toContain("source: github:acme/two/postgres.yml");
    expect(written).toContain("resolved: old2");
  });

  test("scoped update with an unknown source fails and lists known sources", async () => {
    const calls: string[] = [];
    const exit = await Effect.runPromiseExit(
      updateLandofileIncludes({
        landofile: twoIncludeLandofile,
        appRoot,
        cacheRoot,
        sources: ["github:acme/nope"],
        deps: { gitCloner: clonerFor("x", "y", calls) },
      }),
    );

    expect(calls).toEqual([]);
    expect(exit._tag).toBe("Failure");
    if (exit._tag === "Failure") {
      const failure = exit.cause;
      const message = JSON.stringify(failure);
      expect(message).toContain("github:acme/nope");
      expect(message).toContain("github:acme/one");
      expect(message).toContain("github:acme/two");
    }
  });

  const seedGitCache = async (commitSha: string, fragment: string): Promise<void> => {
    const dir = join(cacheRoot, "includes", "git", commitSha);
    await mkdir(dir, { recursive: true });
    await writeFile(join(dir, "postgres.yml"), fragment, "utf8");
  };

  test("--no-network resolves from cache without touching the network", async () => {
    const fragment = "services:\n  database:\n    type: postgres\n";
    const source = "github:acme/fragments/postgres.yml";
    await writeFile(join(appRoot, ".lando.lock.yml"), lockfile(source, "abc123", sha256(fragment)), "utf8");
    await seedGitCache("abc123", fragment);
    const calls: string[] = [];
    const throwingCloner: GitIncludeCloner = {
      clone: async ({ url }) => {
        calls.push(url);
        throw new Error("network access is forbidden in --no-network mode");
      },
    };

    const report = await Effect.runPromise(
      updateLandofileIncludes({
        landofile: { includes: [{ source: "github:acme/fragments", path: "postgres.yml" }] },
        appRoot,
        cacheRoot,
        noNetwork: true,
        deps: { gitCloner: throwingCloner },
      }),
    );

    expect(calls).toEqual([]);
    expect(report.noNetwork).toBe(true);
    expect(report.entries[0]?.status).toBe("unchanged");
    expect(report.drift).toBe(false);
    expect(report.wrote).toBe(false);
  });

  test("--no-network with a missing cache artifact fails with remediation and no network", async () => {
    const source = "github:acme/fragments/postgres.yml";
    await writeFile(join(appRoot, ".lando.lock.yml"), lockfile(source, "missing999", "a".repeat(64)), "utf8");
    const calls: string[] = [];
    const throwingCloner: GitIncludeCloner = {
      clone: async ({ url }) => {
        calls.push(url);
        throw new Error("network access is forbidden in --no-network mode");
      },
    };

    const exit = await Effect.runPromiseExit(
      updateLandofileIncludes({
        landofile: { includes: [{ source: "github:acme/fragments", path: "postgres.yml" }] },
        appRoot,
        cacheRoot,
        noNetwork: true,
        deps: { gitCloner: throwingCloner },
      }),
    );

    expect(calls).toEqual([]);
    expect(exit._tag).toBe("Failure");
    if (exit._tag === "Failure") {
      const message = JSON.stringify(exit.cause);
      expect(message).toContain("--no-network");
    }
  });

  test("--no-network rejects lockfile resolved paths that escape the include cache", async () => {
    const source = "github:acme/fragments/postgres.yml";
    const outsideRoot = await mkdtemp(join(tmpdir(), "lando-includes-update-outside-"));
    try {
      const fragment = "services:\n  stolen:\n    type: postgres\n";
      await writeFile(join(outsideRoot, "postgres.yml"), fragment, "utf8");
      const gitCacheRoot = join(cacheRoot, "includes", "git");
      const escapedResolved = relative(gitCacheRoot, outsideRoot);
      await writeFile(
        join(appRoot, ".lando.lock.yml"),
        lockfile(source, escapedResolved, sha256(fragment)),
        "utf8",
      );
      const calls: string[] = [];
      const throwingCloner: GitIncludeCloner = {
        clone: async ({ url }) => {
          calls.push(url);
          throw new Error("network access is forbidden in --no-network mode");
        },
      };

      const exit = await Effect.runPromiseExit(
        updateLandofileIncludes({
          landofile: { includes: [{ source: "github:acme/fragments", path: "postgres.yml" }] },
          appRoot,
          cacheRoot,
          noNetwork: true,
          deps: { gitCloner: throwingCloner },
        }),
      );

      expect(calls).toEqual([]);
      expect(exit._tag).toBe("Failure");
      if (exit._tag === "Failure") {
        const message = JSON.stringify(exit.cause);
        expect(message).toContain("outside the include cache");
      }
    } finally {
      await rm(outsideRoot, { recursive: true, force: true });
    }
  });

  test("--no-network rejects npm lockfile resolved paths that escape the include cache", async () => {
    const source = "npm:@acme/fragments";
    const fragment = "services:\n  stolen:\n    type: postgres\n";
    const outsidePackage = join(cacheRoot, "includes", "outside-npm", "package");
    await mkdir(outsidePackage, { recursive: true });
    await writeFile(join(outsidePackage, "postgres.yml"), fragment, "utf8");
    await writeFile(
      join(appRoot, ".lando.lock.yml"),
      lockfile(source, "../../../outside-npm", sha256(fragment)),
      "utf8",
    );

    const exit = await Effect.runPromiseExit(
      updateLandofileIncludes({
        landofile: { includes: [{ source, path: "postgres.yml" }] },
        appRoot,
        cacheRoot,
        noNetwork: true,
      }),
    );

    expect(exit._tag).toBe("Failure");
    if (exit._tag === "Failure") {
      const message = JSON.stringify(exit.cause);
      expect(message).toContain("outside the include cache");
    }
  });

  test("--no-network composes with --check on a warm cache", async () => {
    const fragment = "services:\n  database:\n    type: postgres\n";
    const source = "github:acme/fragments/postgres.yml";
    const lockPath = join(appRoot, ".lando.lock.yml");
    const original = lockfile(source, "abc123", "0".repeat(64));
    await writeFile(lockPath, original, "utf8");
    await seedGitCache("abc123", fragment);

    const report = await Effect.runPromise(
      updateLandofileIncludes({
        landofile: { includes: [{ source: "github:acme/fragments", path: "postgres.yml" }] },
        appRoot,
        cacheRoot,
        noNetwork: true,
        check: true,
      }),
    );

    expect(report.noNetwork).toBe(true);
    expect(report.checkMode).toBe(true);
    expect(report.drift).toBe(true);
    expect(report.wrote).toBe(false);
    expect(await readFile(lockPath, "utf8")).toBe(original);
  });
});
