/**
 * **GENERATED FILE** — do not edit by hand.
 *
 * Regenerate via `bun run scripts/build-oclif-manifest.ts`.
 *
 * The compiled binary embeds the OCLIF manifest through this static module so
 * command metadata is available without reading `oclif.manifest.json` from
 * disk at runtime.
 */
import type { Interfaces } from "@oclif/core";

export const COMPILED_OCLIF_MANIFEST = {
  commands: {
    "app:cache:refresh": {
      aliases: [],
      args: {},
      description: "Rebuild the app plan, tooling graph, and command index without starting services.",
      flags: {},
      hasDynamicHelp: false,
      hidden: false,
      hiddenAliases: [],
      id: "app:cache:refresh",
      pluginAlias: "@lando/core",
      pluginName: "@lando/core",
      pluginType: "core",
      strict: true,
      enableJsonFlag: false,
      landoSpec: {
        id: "app:cache:refresh",
        summary: "Rebuild the app plan, tooling graph, and command index without starting services.",
        namespace: "app",
        bootstrap: "app",
      },
      bootstrap: "app",
      isESM: true,
      relativePath: ["src", "cli", "oclif", "commands", "app", "cache", "refresh.ts"],
      aliasPermutations: [],
      permutations: [
        "app:cache:refresh",
        "cache:app:refresh",
        "cache:refresh:app",
        "app:refresh:cache",
        "refresh:app:cache",
        "refresh:cache:app",
      ],
    },
    "app:config": {
      aliases: [],
      args: {},
      description: "Read the current app's Landofile.",
      flags: {
        format: {
          description: "Output format.",
          name: "format",
          default: "table",
          hasDynamicHelp: false,
          multiple: false,
          options: ["table", "json"],
          type: "option",
        },
      },
      hasDynamicHelp: false,
      hidden: false,
      hiddenAliases: [],
      id: "app:config",
      pluginAlias: "@lando/core",
      pluginName: "@lando/core",
      pluginType: "core",
      strict: true,
      enableJsonFlag: false,
      landoSpec: {
        id: "app:config",
        summary: "Read the current app's Landofile.",
        namespace: "app",
        topLevelAlias: false,
        bootstrap: "app",
      },
      bootstrap: "app",
      isESM: true,
      relativePath: ["src", "cli", "oclif", "commands", "app", "config", "index.ts"],
      aliasPermutations: [],
      permutations: ["app:config", "config:app"],
    },
    "app:config:lint": {
      aliases: [],
      args: {},
      description: "Validate the current app's Landofile against the canonical schema.",
      flags: {
        format: {
          description: "Output format.",
          name: "format",
          default: "text",
          hasDynamicHelp: false,
          multiple: false,
          options: ["text", "json"],
          type: "option",
        },
      },
      hasDynamicHelp: false,
      hidden: false,
      hiddenAliases: [],
      id: "app:config:lint",
      pluginAlias: "@lando/core",
      pluginName: "@lando/core",
      pluginType: "core",
      strict: true,
      enableJsonFlag: false,
      landoSpec: {
        id: "app:config:lint",
        summary: "Validate the current app's Landofile against the canonical schema.",
        namespace: "app",
        topLevelAlias: false,
        bootstrap: "minimal",
      },
      bootstrap: "minimal",
      isESM: true,
      relativePath: ["src", "cli", "oclif", "commands", "app", "config", "lint.ts"],
      aliasPermutations: [],
      permutations: [
        "app:config:lint",
        "config:app:lint",
        "config:lint:app",
        "app:lint:config",
        "lint:app:config",
        "lint:config:app",
      ],
    },
    "app:config:translate": {
      aliases: [],
      args: {},
      description: "Translate a non-canonical config file into a canonical v4 Landofile.",
      flags: {
        write: {
          description: "Overwrite the input Landofile in place (a .bak backup is kept).",
          name: "write",
          allowNo: false,
          type: "boolean",
        },
        format: {
          description: "Output format.",
          name: "format",
          default: "text",
          hasDynamicHelp: false,
          multiple: false,
          options: ["text", "json"],
          type: "option",
        },
      },
      hasDynamicHelp: false,
      hidden: false,
      hiddenAliases: [],
      id: "app:config:translate",
      pluginAlias: "@lando/core",
      pluginName: "@lando/core",
      pluginType: "core",
      strict: true,
      enableJsonFlag: false,
      landoSpec: {
        id: "app:config:translate",
        summary: "Translate a non-canonical config file into a canonical v4 Landofile.",
        namespace: "app",
        topLevelAlias: false,
        bootstrap: "minimal",
      },
      bootstrap: "minimal",
      isESM: true,
      relativePath: ["src", "cli", "oclif", "commands", "app", "config", "translate.ts"],
      aliasPermutations: [],
      permutations: [
        "app:config:translate",
        "config:app:translate",
        "config:translate:app",
        "app:translate:config",
        "translate:app:config",
        "translate:config:app",
      ],
    },
    "app:destroy": {
      aliases: ["destroy"],
      args: {},
      description: "Destroy the current Lando app (preserves volumes unless --volumes).",
      flags: {
        volumes: {
          description: "Also remove app/service-scoped storage volumes.",
          name: "volumes",
          allowNo: false,
          type: "boolean",
        },
        yes: {
          char: "y",
          description: "Skip the confirmation prompt (no-op until interactive prompts land).",
          name: "yes",
          allowNo: false,
          type: "boolean",
        },
      },
      hasDynamicHelp: false,
      hidden: false,
      hiddenAliases: [],
      id: "app:destroy",
      pluginAlias: "@lando/core",
      pluginName: "@lando/core",
      pluginType: "core",
      strict: true,
      enableJsonFlag: false,
      landoSpec: {
        id: "app:destroy",
        summary: "Destroy the current Lando app (preserves volumes unless --volumes).",
        namespace: "app",
        topLevelAlias: true,
        bootstrap: "app",
      },
      bootstrap: "app",
      isESM: true,
      relativePath: ["src", "cli", "oclif", "commands", "app", "destroy.ts"],
      aliasPermutations: ["destroy"],
      permutations: ["app:destroy", "destroy:app"],
    },
    "app:exec": {
      aliases: ["exec"],
      args: {
        command: {
          description: "Command to run (first positional).",
          name: "command",
        },
      },
      description: "Run a command in a Lando service.",
      flags: {
        service: {
          char: "s",
          description: "Service to run the command in.",
          name: "service",
          hasDynamicHelp: false,
          multiple: false,
          type: "option",
        },
        user: {
          char: "u",
          description: "User to run the command as inside the service.",
          name: "user",
          hasDynamicHelp: false,
          multiple: false,
          type: "option",
        },
        cwd: {
          description: "Working directory inside the service.",
          name: "cwd",
          hasDynamicHelp: false,
          multiple: false,
          type: "option",
        },
      },
      hasDynamicHelp: false,
      hidden: false,
      hiddenAliases: [],
      id: "app:exec",
      pluginAlias: "@lando/core",
      pluginName: "@lando/core",
      pluginType: "core",
      strict: false,
      enableJsonFlag: false,
      landoSpec: {
        id: "app:exec",
        summary: "Run a command in a Lando service.",
        namespace: "app",
        topLevelAlias: true,
        bootstrap: "app",
      },
      bootstrap: "app",
      isESM: true,
      relativePath: ["src", "cli", "oclif", "commands", "app", "exec.ts"],
      aliasPermutations: ["exec"],
      permutations: ["app:exec", "exec:app"],
    },
    "app:includes:update": {
      aliases: [],
      args: {},
      description: "Refresh every includes lockfile entry to its latest source-resolved version.",
      flags: {
        check: {
          description: "Report would-be lockfile drift without writing.",
          name: "check",
          allowNo: false,
          type: "boolean",
        },
        format: {
          description: "Output format.",
          name: "format",
          default: "text",
          hasDynamicHelp: false,
          multiple: false,
          options: ["text", "json"],
          type: "option",
        },
      },
      hasDynamicHelp: false,
      hidden: false,
      hiddenAliases: [],
      id: "app:includes:update",
      pluginAlias: "@lando/core",
      pluginName: "@lando/core",
      pluginType: "core",
      strict: true,
      enableJsonFlag: false,
      landoSpec: {
        id: "app:includes:update",
        summary: "Refresh every includes lockfile entry to its latest source-resolved version.",
        namespace: "app",
        bootstrap: "minimal",
      },
      bootstrap: "minimal",
      isESM: true,
      relativePath: ["src", "cli", "oclif", "commands", "app", "includes", "update.ts"],
      aliasPermutations: [],
      permutations: [
        "app:includes:update",
        "includes:app:update",
        "includes:update:app",
        "app:update:includes",
        "update:app:includes",
        "update:includes:app",
      ],
    },
    "app:includes:verify": {
      aliases: [],
      args: {},
      description: "Verify the includes lockfile matches the resolved tree without updating it.",
      flags: {
        format: {
          description: "Output format.",
          name: "format",
          default: "text",
          hasDynamicHelp: false,
          multiple: false,
          options: ["text", "json"],
          type: "option",
        },
      },
      hasDynamicHelp: false,
      hidden: false,
      hiddenAliases: [],
      id: "app:includes:verify",
      pluginAlias: "@lando/core",
      pluginName: "@lando/core",
      pluginType: "core",
      strict: true,
      enableJsonFlag: false,
      landoSpec: {
        id: "app:includes:verify",
        summary: "Verify the includes lockfile matches the resolved tree without updating it.",
        namespace: "app",
        bootstrap: "minimal",
      },
      bootstrap: "minimal",
      isESM: true,
      relativePath: ["src", "cli", "oclif", "commands", "app", "includes", "verify.ts"],
      aliasPermutations: [],
      permutations: [
        "app:includes:verify",
        "includes:app:verify",
        "includes:verify:app",
        "app:verify:includes",
        "verify:app:includes",
        "verify:includes:app",
      ],
    },
    "app:info": {
      aliases: ["info"],
      args: {},
      description: "Print provider-neutral runtime info for the current app.",
      flags: {},
      hasDynamicHelp: false,
      hidden: false,
      hiddenAliases: [],
      id: "app:info",
      pluginAlias: "@lando/core",
      pluginName: "@lando/core",
      pluginType: "core",
      strict: true,
      enableJsonFlag: false,
      landoSpec: {
        id: "app:info",
        summary: "Print provider-neutral runtime info for the current app.",
        namespace: "app",
        topLevelAlias: true,
        bootstrap: "app",
      },
      bootstrap: "app",
      isESM: true,
      relativePath: ["src", "cli", "oclif", "commands", "app", "info.ts"],
      aliasPermutations: ["info"],
      permutations: ["app:info", "info:app"],
    },
    "app:logs": {
      aliases: ["logs"],
      args: {},
      description: "Stream logs from the current app.",
      flags: {
        service: {
          char: "s",
          description: "Filter logs to a single planned service.",
          name: "service",
          hasDynamicHelp: false,
          multiple: false,
          type: "option",
        },
        follow: {
          char: "f",
          description: "Stream new log lines (deferred to Beta).",
          name: "follow",
          allowNo: false,
          type: "boolean",
        },
        tail: {
          description: "Show last N lines per service.",
          name: "tail",
          hasDynamicHelp: false,
          multiple: false,
          type: "option",
        },
        since: {
          description: "Filter to lines since the given time (deferred to Beta).",
          name: "since",
          hasDynamicHelp: false,
          multiple: false,
          type: "option",
        },
      },
      hasDynamicHelp: false,
      hidden: false,
      hiddenAliases: [],
      id: "app:logs",
      pluginAlias: "@lando/core",
      pluginName: "@lando/core",
      pluginType: "core",
      strict: true,
      enableJsonFlag: false,
      landoSpec: {
        id: "app:logs",
        summary: "Stream logs from the current app.",
        namespace: "app",
        topLevelAlias: true,
        bootstrap: "app",
      },
      bootstrap: "app",
      isESM: true,
      relativePath: ["src", "cli", "oclif", "commands", "app", "logs.ts"],
      aliasPermutations: ["logs"],
      permutations: ["app:logs", "logs:app"],
    },
    "app:rebuild": {
      aliases: ["rebuild"],
      args: {},
      description: "Rebuild artifacts and restart the current app.",
      flags: {},
      hasDynamicHelp: false,
      hidden: false,
      hiddenAliases: [],
      id: "app:rebuild",
      pluginAlias: "@lando/core",
      pluginName: "@lando/core",
      pluginType: "core",
      strict: true,
      enableJsonFlag: false,
      landoSpec: {
        id: "app:rebuild",
        summary: "Rebuild artifacts and restart the current app.",
        namespace: "app",
        topLevelAlias: true,
        bootstrap: "app",
      },
      bootstrap: "app",
      isESM: true,
      relativePath: ["src", "cli", "oclif", "commands", "app", "rebuild.ts"],
      aliasPermutations: ["rebuild"],
      permutations: ["app:rebuild", "rebuild:app"],
    },
    "app:restart": {
      aliases: ["restart"],
      args: {},
      description: "Restart the current app (stop + start).",
      flags: {},
      hasDynamicHelp: false,
      hidden: false,
      hiddenAliases: [],
      id: "app:restart",
      pluginAlias: "@lando/core",
      pluginName: "@lando/core",
      pluginType: "core",
      strict: true,
      enableJsonFlag: false,
      landoSpec: {
        id: "app:restart",
        summary: "Restart the current app (stop + start).",
        namespace: "app",
        topLevelAlias: true,
        bootstrap: "app",
      },
      bootstrap: "app",
      isESM: true,
      relativePath: ["src", "cli", "oclif", "commands", "app", "restart.ts"],
      aliasPermutations: ["restart"],
      permutations: ["app:restart", "restart:app"],
    },
    "app:shell": {
      aliases: ["shell"],
      args: {},
      description: "Open an interactive shell in a Lando service.",
      flags: {
        service: {
          char: "s",
          description: "Service to open a shell in.",
          name: "service",
          hasDynamicHelp: false,
          multiple: false,
          type: "option",
        },
        host: {
          description: "Open a host shell scoped to the current app.",
          name: "host",
          allowNo: false,
          type: "boolean",
        },
      },
      hasDynamicHelp: false,
      hidden: false,
      hiddenAliases: [],
      id: "app:shell",
      pluginAlias: "@lando/core",
      pluginName: "@lando/core",
      pluginType: "core",
      strict: false,
      enableJsonFlag: false,
      landoSpec: {
        id: "app:shell",
        summary: "Open an interactive shell in a Lando service.",
        namespace: "app",
        topLevelAlias: true,
        bootstrap: "app",
      },
      bootstrap: "app",
      isESM: true,
      relativePath: ["src", "cli", "oclif", "commands", "app", "shell.ts"],
      aliasPermutations: ["shell"],
      permutations: ["app:shell", "shell:app"],
    },
    "app:ssh": {
      aliases: ["ssh"],
      args: {
        command: {
          description: "Optional command to run instead of the default shell.",
          name: "command",
        },
      },
      description:
        "Open an interactive shell in a Lando service (alias of `exec --tty --interactive sh -l`).",
      flags: {
        service: {
          char: "s",
          description: "Service to open a shell in.",
          name: "service",
          hasDynamicHelp: false,
          multiple: false,
          type: "option",
        },
        user: {
          char: "u",
          description: "User to run the shell as inside the service.",
          name: "user",
          hasDynamicHelp: false,
          multiple: false,
          type: "option",
        },
        subsystem: {
          description: "(Beta) SSH subsystem to invoke; rejected in Alpha.",
          name: "subsystem",
          hasDynamicHelp: false,
          multiple: false,
          type: "option",
        },
        sidecar: {
          description: "(Beta) Open the shell in a per-app SSH sidecar; rejected in Alpha.",
          name: "sidecar",
          allowNo: false,
          type: "boolean",
        },
      },
      hasDynamicHelp: false,
      hidden: false,
      hiddenAliases: [],
      id: "app:ssh",
      pluginAlias: "@lando/core",
      pluginName: "@lando/core",
      pluginType: "core",
      strict: false,
      enableJsonFlag: false,
      landoSpec: {
        id: "app:ssh",
        summary: "Open an interactive shell in a Lando service (alias of `exec --tty --interactive sh -l`).",
        namespace: "app",
        topLevelAlias: true,
        bootstrap: "app",
      },
      bootstrap: "app",
      isESM: true,
      relativePath: ["src", "cli", "oclif", "commands", "app", "ssh.ts"],
      aliasPermutations: ["ssh"],
      permutations: ["app:ssh", "ssh:app"],
    },
    "app:start": {
      aliases: ["start"],
      args: {},
      description: "Start the current Lando app.",
      flags: {},
      hasDynamicHelp: false,
      hidden: false,
      hiddenAliases: [],
      id: "app:start",
      pluginAlias: "@lando/core",
      pluginName: "@lando/core",
      pluginType: "core",
      strict: true,
      enableJsonFlag: false,
      landoSpec: {
        id: "app:start",
        summary: "Start the current Lando app.",
        namespace: "app",
        topLevelAlias: true,
        bootstrap: "app",
      },
      bootstrap: "app",
      isESM: true,
      relativePath: ["src", "cli", "oclif", "commands", "app", "start.ts"],
      aliasPermutations: ["start"],
      permutations: ["app:start", "start:app"],
    },
    "app:stop": {
      aliases: ["stop"],
      args: {},
      description: "Stop the current Lando app.",
      flags: {},
      hasDynamicHelp: false,
      hidden: false,
      hiddenAliases: [],
      id: "app:stop",
      pluginAlias: "@lando/core",
      pluginName: "@lando/core",
      pluginType: "core",
      strict: true,
      enableJsonFlag: false,
      landoSpec: {
        id: "app:stop",
        summary: "Stop the current Lando app.",
        namespace: "app",
        topLevelAlias: true,
        bootstrap: "app",
      },
      bootstrap: "app",
      isESM: true,
      relativePath: ["src", "cli", "oclif", "commands", "app", "stop.ts"],
      aliasPermutations: ["stop"],
      permutations: ["app:stop", "stop:app"],
    },
    "apps:init": {
      aliases: ["init"],
      args: {},
      description: "Generate a new Lando app.",
      flags: {
        name: {
          description: "App name (slugified for the project id).",
          name: "name",
          hasDynamicHelp: false,
          multiple: false,
          type: "option",
        },
        source: {
          description: "Init source id (cwd, git, tarball, npm, registry, template).",
          name: "source",
          hasDynamicHelp: false,
          multiple: false,
          type: "option",
        },
        url: {
          description: "Remote recipe source URL (for --source=git/tarball).",
          name: "url",
          hasDynamicHelp: false,
          multiple: false,
          type: "option",
        },
        id: {
          description: "Recipe id for --source=registry.",
          name: "id",
          hasDynamicHelp: false,
          multiple: false,
          type: "option",
        },
        "registry-url": {
          description: "Override the recipe registry base URL (for --source=registry).",
          name: "registry-url",
          hasDynamicHelp: false,
          multiple: false,
          type: "option",
        },
        package: {
          description: "npm package spec <name>[@version] (for --source=npm).",
          name: "package",
          hasDynamicHelp: false,
          multiple: false,
          type: "option",
        },
        path: {
          description: "Subdirectory within a remote recipe source.",
          name: "path",
          hasDynamicHelp: false,
          multiple: false,
          type: "option",
        },
        checksum: {
          description: "Expected SHA-256 of a --source=tarball archive (64 hex chars).",
          name: "checksum",
          hasDynamicHelp: false,
          multiple: false,
          type: "option",
        },
        recipe: {
          description: "Recipe to apply.",
          name: "recipe",
          hasDynamicHelp: false,
          multiple: false,
          type: "option",
        },
        destination: {
          description: "Target directory.",
          name: "destination",
          hasDynamicHelp: false,
          multiple: false,
          type: "option",
        },
        full: {
          description: "Use full recipe defaults instead of prompts.",
          name: "full",
          allowNo: false,
          type: "boolean",
        },
        yes: {
          description: "Accept every prompt's default without asking.",
          name: "yes",
          allowNo: false,
          type: "boolean",
        },
        "no-interactive": {
          aliases: ["non-interactive"],
          description:
            "Disable interactive prompting. Missing required answers fail with RecipeMissingAnswerError.",
          name: "no-interactive",
          allowNo: false,
          type: "boolean",
        },
        answer: {
          description: "Recipe answer in key=value form (repeatable).",
          name: "answer",
          hasDynamicHelp: false,
          multiple: true,
          type: "option",
        },
        option: {
          description: "Recipe option in key=value form (repeatable).",
          name: "option",
          hasDynamicHelp: false,
          multiple: true,
          type: "option",
        },
      },
      hasDynamicHelp: false,
      hidden: false,
      hiddenAliases: [],
      id: "apps:init",
      pluginAlias: "@lando/core",
      pluginName: "@lando/core",
      pluginType: "core",
      strict: true,
      enableJsonFlag: false,
      landoSpec: {
        id: "apps:init",
        summary: "Generate a new Lando app.",
        namespace: "apps",
        topLevelAlias: true,
        bootstrap: "commands",
      },
      bootstrap: "commands",
      isESM: true,
      relativePath: ["src", "cli", "oclif", "commands", "apps", "init.ts"],
      aliasPermutations: ["init"],
      permutations: ["apps:init", "init:apps"],
    },
    "apps:list": {
      aliases: ["list"],
      args: {},
      description: "List Lando apps applied across discovered providers on this host.",
      flags: {
        format: {
          description: "Output format.",
          name: "format",
          default: "table",
          hasDynamicHelp: false,
          multiple: false,
          options: ["json", "table"],
          type: "option",
        },
        path: {
          description: "Filter apps whose root contains the given substring.",
          name: "path",
          hasDynamicHelp: false,
          multiple: false,
          type: "option",
        },
      },
      hasDynamicHelp: false,
      hidden: false,
      hiddenAliases: [],
      id: "apps:list",
      pluginAlias: "@lando/core",
      pluginName: "@lando/core",
      pluginType: "core",
      strict: true,
      enableJsonFlag: false,
      landoSpec: {
        id: "apps:list",
        summary: "List Lando apps applied across discovered providers on this host.",
        namespace: "apps",
        topLevelAlias: true,
        bootstrap: "minimal",
      },
      bootstrap: "minimal",
      isESM: true,
      relativePath: ["src", "cli", "oclif", "commands", "apps", "list.ts"],
      aliasPermutations: ["list"],
      permutations: ["apps:list", "list:apps"],
    },
    "apps:poweroff": {
      aliases: ["poweroff"],
      args: {},
      description: "Stop every Lando-managed service across apps.",
      flags: {
        "keep-global": {
          description: "Do not stop the global app.",
          name: "keep-global",
          allowNo: false,
          type: "boolean",
        },
        "keep-scratch": {
          description: "Do not stop scratch apps.",
          name: "keep-scratch",
          allowNo: false,
          type: "boolean",
        },
        yes: {
          char: "y",
          description: "Skip confirmation prompts.",
          name: "yes",
          allowNo: false,
          type: "boolean",
        },
      },
      hasDynamicHelp: false,
      hidden: false,
      hiddenAliases: [],
      id: "apps:poweroff",
      pluginAlias: "@lando/core",
      pluginName: "@lando/core",
      pluginType: "core",
      strict: true,
      enableJsonFlag: false,
      landoSpec: {
        id: "apps:poweroff",
        summary: "Stop every Lando-managed service across apps.",
        namespace: "apps",
        topLevelAlias: true,
        bootstrap: "minimal",
      },
      bootstrap: "minimal",
      isESM: true,
      relativePath: ["src", "cli", "oclif", "commands", "apps", "poweroff.ts"],
      aliasPermutations: ["poweroff"],
      permutations: ["apps:poweroff", "poweroff:apps"],
    },
    "apps:scratch:destroy": {
      aliases: ["scratch:destroy"],
      args: {
        id: {
          description: "Scratch app id.",
          name: "id",
          required: true,
        },
      },
      description: "Destroy a scratch Lando app.",
      flags: {
        "keep-volumes": {
          description: "Keep scratch volumes for inspection.",
          name: "keep-volumes",
          allowNo: false,
          type: "boolean",
        },
      },
      hasDynamicHelp: false,
      hidden: false,
      hiddenAliases: [],
      id: "apps:scratch:destroy",
      pluginAlias: "@lando/core",
      pluginName: "@lando/core",
      pluginType: "core",
      strict: true,
      enableJsonFlag: false,
      landoSpec: {
        id: "apps:scratch:destroy",
        summary: "Destroy a scratch Lando app.",
        namespace: "apps",
        topLevelAlias: "scratch:destroy",
        bootstrap: "scratch",
      },
      bootstrap: "scratch",
      isESM: true,
      relativePath: ["src", "cli", "oclif", "commands", "apps", "scratch", "destroy.ts"],
      aliasPermutations: ["scratch:destroy", "destroy:scratch"],
      permutations: [
        "apps:scratch:destroy",
        "scratch:apps:destroy",
        "scratch:destroy:apps",
        "apps:destroy:scratch",
        "destroy:apps:scratch",
        "destroy:scratch:apps",
      ],
    },
    "apps:scratch:gc": {
      aliases: ["scratch:gc"],
      args: {},
      description: "Inspect scratch Lando app orphans.",
      flags: {
        prune: {
          description: "Reap orphaned scratch resources after reporting them.",
          name: "prune",
          allowNo: false,
          type: "boolean",
        },
      },
      hasDynamicHelp: false,
      hidden: false,
      hiddenAliases: [],
      id: "apps:scratch:gc",
      pluginAlias: "@lando/core",
      pluginName: "@lando/core",
      pluginType: "core",
      strict: true,
      enableJsonFlag: false,
      landoSpec: {
        id: "apps:scratch:gc",
        summary: "Inspect scratch Lando app orphans.",
        namespace: "apps",
        topLevelAlias: "scratch:gc",
        bootstrap: "scratch",
      },
      bootstrap: "scratch",
      isESM: true,
      relativePath: ["src", "cli", "oclif", "commands", "apps", "scratch", "gc.ts"],
      aliasPermutations: ["scratch:gc", "gc:scratch"],
      permutations: [
        "apps:scratch:gc",
        "scratch:apps:gc",
        "scratch:gc:apps",
        "apps:gc:scratch",
        "gc:apps:scratch",
        "gc:scratch:apps",
      ],
    },
    "apps:scratch:info": {
      aliases: ["scratch:info"],
      args: {
        id: {
          description: "Scratch app id.",
          name: "id",
          required: false,
        },
      },
      description: "Show information for a scratch Lando app.",
      flags: {
        format: {
          description: "Output format.",
          name: "format",
          default: "table",
          hasDynamicHelp: false,
          multiple: false,
          options: ["table", "json"],
          type: "option",
        },
      },
      hasDynamicHelp: false,
      hidden: false,
      hiddenAliases: [],
      id: "apps:scratch:info",
      pluginAlias: "@lando/core",
      pluginName: "@lando/core",
      pluginType: "core",
      strict: true,
      enableJsonFlag: false,
      landoSpec: {
        id: "apps:scratch:info",
        summary: "Show information for a scratch Lando app.",
        namespace: "apps",
        topLevelAlias: "scratch:info",
        bootstrap: "scratch",
      },
      bootstrap: "scratch",
      isESM: true,
      relativePath: ["src", "cli", "oclif", "commands", "apps", "scratch", "info.ts"],
      aliasPermutations: ["scratch:info", "info:scratch"],
      permutations: [
        "apps:scratch:info",
        "scratch:apps:info",
        "scratch:info:apps",
        "apps:info:scratch",
        "info:apps:scratch",
        "info:scratch:apps",
      ],
    },
    "apps:scratch:list": {
      aliases: ["scratch:list"],
      args: {},
      description: "List scratch Lando apps.",
      flags: {
        format: {
          description: "Output format.",
          name: "format",
          default: "table",
          hasDynamicHelp: false,
          multiple: false,
          options: ["table", "json"],
          type: "option",
        },
      },
      hasDynamicHelp: false,
      hidden: false,
      hiddenAliases: [],
      id: "apps:scratch:list",
      pluginAlias: "@lando/core",
      pluginName: "@lando/core",
      pluginType: "core",
      strict: true,
      enableJsonFlag: false,
      landoSpec: {
        id: "apps:scratch:list",
        summary: "List scratch Lando apps.",
        namespace: "apps",
        topLevelAlias: "scratch:list",
        bootstrap: "scratch",
      },
      bootstrap: "scratch",
      isESM: true,
      relativePath: ["src", "cli", "oclif", "commands", "apps", "scratch", "list.ts"],
      aliasPermutations: ["scratch:list", "list:scratch"],
      permutations: [
        "apps:scratch:list",
        "scratch:apps:list",
        "scratch:list:apps",
        "apps:list:scratch",
        "list:apps:scratch",
        "list:scratch:apps",
      ],
    },
    "apps:scratch:logs": {
      aliases: ["scratch:logs"],
      args: {
        id: {
          description: "Scratch app id.",
          name: "id",
          required: false,
        },
      },
      description: "Show logs for a scratch Lando app.",
      flags: {},
      hasDynamicHelp: false,
      hidden: false,
      hiddenAliases: [],
      id: "apps:scratch:logs",
      pluginAlias: "@lando/core",
      pluginName: "@lando/core",
      pluginType: "core",
      strict: true,
      enableJsonFlag: false,
      landoSpec: {
        id: "apps:scratch:logs",
        summary: "Show logs for a scratch Lando app.",
        namespace: "apps",
        topLevelAlias: "scratch:logs",
        bootstrap: "scratch",
      },
      bootstrap: "scratch",
      isESM: true,
      relativePath: ["src", "cli", "oclif", "commands", "apps", "scratch", "logs.ts"],
      aliasPermutations: ["scratch:logs", "logs:scratch"],
      permutations: [
        "apps:scratch:logs",
        "scratch:apps:logs",
        "scratch:logs:apps",
        "apps:logs:scratch",
        "logs:apps:scratch",
        "logs:scratch:apps",
      ],
    },
    "apps:scratch:start": {
      aliases: ["scratch:start", "scratch"],
      args: {},
      description: "Start a scratch Lando app.",
      flags: {
        fork: {
          description: "Use the current app as the scratch source.",
          name: "fork",
          allowNo: false,
          type: "boolean",
        },
        from: {
          description: "Recipe reference to materialize as a scratch app.",
          name: "from",
          hasDynamicHelp: false,
          multiple: false,
          type: "option",
        },
        detach: {
          description: "Return after acquiring the scratch app.",
          name: "detach",
          allowNo: false,
          type: "boolean",
        },
        name: {
          description: "Base name for the generated scratch id.",
          name: "name",
          hasDynamicHelp: false,
          multiple: false,
          type: "option",
        },
        answer: {
          description: "Recipe answer in key=value form (repeatable).",
          name: "answer",
          hasDynamicHelp: false,
          multiple: true,
          type: "option",
        },
        option: {
          description: "Alias for --answer in key=value form (repeatable).",
          name: "option",
          hasDynamicHelp: false,
          multiple: true,
          type: "option",
        },
        yes: {
          char: "y",
          description: "Accept every recipe prompt's default without asking.",
          name: "yes",
          allowNo: false,
          type: "boolean",
        },
        "no-interactive": {
          aliases: ["non-interactive"],
          description: "Never prompt; recipe prompts must be satisfied by defaults or --answer.",
          name: "no-interactive",
          allowNo: false,
          type: "boolean",
        },
        isolate: {
          description: "Fork isolation: 'none' shares the source app root, 'full' uses a content copy.",
          name: "isolate",
          hasDynamicHelp: false,
          multiple: false,
          options: ["none", "full"],
          type: "option",
        },
        "mount-cwd": {
          description: "Mount the current working directory into the scratch app's primary service.",
          name: "mount-cwd",
          hasDynamicHelp: false,
          helpValue: "container-path",
          multiple: false,
          type: "option",
        },
        "share-global-storage": {
          description: "Join the shared cross-app network and expose the global app's storage scope.",
          name: "share-global-storage",
          allowNo: false,
          type: "boolean",
        },
      },
      hasDynamicHelp: false,
      hidden: false,
      hiddenAliases: [],
      id: "apps:scratch:start",
      pluginAlias: "@lando/core",
      pluginName: "@lando/core",
      pluginType: "core",
      strict: true,
      enableJsonFlag: false,
      landoSpec: {
        id: "apps:scratch:start",
        summary: "Start a scratch Lando app.",
        namespace: "apps",
        topLevelAlias: ["scratch:start", "scratch"],
        bootstrap: "scratch",
      },
      bootstrap: "scratch",
      isESM: true,
      relativePath: ["src", "cli", "oclif", "commands", "apps", "scratch", "start.ts"],
      aliasPermutations: ["scratch:start", "start:scratch", "scratch"],
      permutations: [
        "apps:scratch:start",
        "scratch:apps:start",
        "scratch:start:apps",
        "apps:start:scratch",
        "start:apps:scratch",
        "start:scratch:apps",
      ],
    },
    "apps:scratch:stop": {
      aliases: ["scratch:stop"],
      args: {
        id: {
          description: "Scratch app id.",
          name: "id",
          required: true,
        },
      },
      description: "Stop a scratch Lando app.",
      flags: {},
      hasDynamicHelp: false,
      hidden: false,
      hiddenAliases: [],
      id: "apps:scratch:stop",
      pluginAlias: "@lando/core",
      pluginName: "@lando/core",
      pluginType: "core",
      strict: true,
      enableJsonFlag: false,
      landoSpec: {
        id: "apps:scratch:stop",
        summary: "Stop a scratch Lando app.",
        namespace: "apps",
        topLevelAlias: "scratch:stop",
        bootstrap: "scratch",
      },
      bootstrap: "scratch",
      isESM: true,
      relativePath: ["src", "cli", "oclif", "commands", "apps", "scratch", "stop.ts"],
      aliasPermutations: ["scratch:stop", "stop:scratch"],
      permutations: [
        "apps:scratch:stop",
        "scratch:apps:stop",
        "scratch:stop:apps",
        "apps:stop:scratch",
        "stop:apps:scratch",
        "stop:scratch:apps",
      ],
    },
    "meta:bun": {
      aliases: ["bun"],
      args: {},
      description: "Proxy to the embedded Bun CLI via BunSelfRunner.",
      flags: {},
      hasDynamicHelp: false,
      hidden: false,
      hiddenAliases: [],
      id: "meta:bun",
      pluginAlias: "@lando/core",
      pluginName: "@lando/core",
      pluginType: "core",
      strict: false,
      enableJsonFlag: false,
      landoSpec: {
        id: "meta:bun",
        summary: "Proxy to the embedded Bun CLI via BunSelfRunner.",
        namespace: "meta",
        topLevelAlias: true,
        bootstrap: "minimal",
      },
      bootstrap: "minimal",
      isESM: true,
      relativePath: ["src", "cli", "oclif", "commands", "meta", "bun.ts"],
      aliasPermutations: ["bun"],
      permutations: ["meta:bun", "bun:meta"],
    },
    "meta:config": {
      aliases: ["config"],
      args: {
        subcommand: {
          description: "Subcommand: view (default), get, set, unset, edit, validate, translate.",
          name: "subcommand",
          required: false,
        },
        key: {
          description: "Dot-path key for get/set/unset.",
          name: "key",
          required: false,
        },
        value: {
          description: "Value for set.",
          name: "value",
          required: false,
        },
      },
      description: "Read or write the global Lando config (view/get; write ops are deferred to Beta).",
      flags: {
        format: {
          description: "Output format.",
          name: "format",
          default: "table",
          hasDynamicHelp: false,
          multiple: false,
          options: ["json", "yaml", "table"],
          type: "option",
        },
        path: {
          description: "Dot-path key selector.",
          name: "path",
          hasDynamicHelp: false,
          multiple: false,
          type: "option",
        },
      },
      hasDynamicHelp: false,
      hidden: false,
      hiddenAliases: [],
      id: "meta:config",
      pluginAlias: "@lando/core",
      pluginName: "@lando/core",
      pluginType: "core",
      strict: false,
      enableJsonFlag: false,
      landoSpec: {
        id: "meta:config",
        summary: "Read or write the global Lando config (view/get; write ops are deferred to Beta).",
        namespace: "meta",
        topLevelAlias: "config",
        bootstrap: "minimal",
      },
      bootstrap: "minimal",
      isESM: true,
      relativePath: ["src", "cli", "oclif", "commands", "meta", "config.ts"],
      aliasPermutations: ["config"],
      permutations: ["meta:config", "config:meta"],
    },
    "meta:doctor": {
      aliases: ["doctor"],
      args: {},
      description: "Run diagnostics for app config, host/provider setup, and plugin-contributed checks.",
      flags: {
        provider: {
          description:
            "Report what would be selected if `--provider=…` were used (e.g. lando, docker, podman).",
          name: "provider",
          hasDynamicHelp: false,
          multiple: false,
          type: "option",
        },
        fix: {
          description: "Re-run the setup step of each degraded subsystem whose recovery is safe to automate.",
          name: "fix",
          allowNo: false,
          type: "boolean",
        },
        app: {
          description: "Also lint the current app's Landofile against the canonical schema.",
          name: "app",
          allowNo: false,
          type: "boolean",
        },
        deprecations: {
          description: "Also report deprecated surfaces used by the current app and loaded plugins.",
          name: "deprecations",
          allowNo: false,
          type: "boolean",
        },
        format: {
          description: "Output format for doctor reports.",
          name: "format",
          default: "text",
          hasDynamicHelp: false,
          multiple: false,
          options: ["text", "json", "yaml"],
          type: "option",
        },
      },
      hasDynamicHelp: false,
      hidden: false,
      hiddenAliases: [],
      id: "meta:doctor",
      pluginAlias: "@lando/core",
      pluginName: "@lando/core",
      pluginType: "core",
      strict: true,
      enableJsonFlag: false,
      landoSpec: {
        id: "meta:doctor",
        summary: "Run diagnostics for app config, host/provider setup, and plugin-contributed checks.",
        namespace: "meta",
        topLevelAlias: true,
        bootstrap: "provider",
      },
      bootstrap: "provider",
      isESM: true,
      relativePath: ["src", "cli", "oclif", "commands", "meta", "doctor.ts"],
      aliasPermutations: ["doctor"],
      permutations: ["meta:doctor", "doctor:meta"],
    },
    "meta:events:follow": {
      aliases: ["events"],
      args: {},
      description: "Follow the lifecycle event trace stream for diagnostics and e2e tests.",
      flags: {},
      hasDynamicHelp: false,
      hidden: false,
      hiddenAliases: [],
      id: "meta:events:follow",
      pluginAlias: "@lando/core",
      pluginName: "@lando/core",
      pluginType: "core",
      strict: true,
      enableJsonFlag: false,
      landoSpec: {
        id: "meta:events:follow",
        summary: "Follow the lifecycle event trace stream for diagnostics and e2e tests.",
        namespace: "meta",
        topLevelAlias: "events",
        bootstrap: "minimal",
      },
      bootstrap: "minimal",
      isESM: true,
      relativePath: ["src", "cli", "oclif", "commands", "meta", "events", "follow.ts"],
      aliasPermutations: ["events"],
      permutations: [
        "meta:events:follow",
        "events:meta:follow",
        "events:follow:meta",
        "meta:follow:events",
        "follow:meta:events",
        "follow:events:meta",
      ],
    },
    "meta:global:config": {
      aliases: ["global:config"],
      args: {},
      description: "Read the host-level global Lando app Landofile stack.",
      flags: {
        format: {
          description: "Output format.",
          name: "format",
          default: "table",
          hasDynamicHelp: false,
          multiple: false,
          options: ["table", "json"],
          type: "option",
        },
      },
      hasDynamicHelp: false,
      hidden: false,
      hiddenAliases: [],
      id: "meta:global:config",
      pluginAlias: "@lando/core",
      pluginName: "@lando/core",
      pluginType: "core",
      strict: true,
      enableJsonFlag: false,
      landoSpec: {
        id: "meta:global:config",
        summary: "Read the host-level global Lando app Landofile stack.",
        namespace: "meta",
        topLevelAlias: "global:config",
        bootstrap: "global",
      },
      bootstrap: "global",
      isESM: true,
      relativePath: ["src", "cli", "oclif", "commands", "meta", "global", "config.ts"],
      aliasPermutations: ["global:config", "config:global"],
      permutations: [
        "meta:global:config",
        "global:meta:config",
        "global:config:meta",
        "meta:config:global",
        "config:meta:global",
        "config:global:meta",
      ],
    },
    "meta:global:destroy": {
      aliases: ["global:destroy"],
      args: {},
      description: "Destroy the host-level global Lando app provider resources.",
      flags: {
        yes: {
          char: "y",
          description: "Confirm destruction of global app provider resources.",
          name: "yes",
          allowNo: false,
          type: "boolean",
        },
        purge: {
          description: "Also remove global service data volumes.",
          name: "purge",
          allowNo: false,
          type: "boolean",
        },
      },
      hasDynamicHelp: false,
      hidden: false,
      hiddenAliases: [],
      id: "meta:global:destroy",
      pluginAlias: "@lando/core",
      pluginName: "@lando/core",
      pluginType: "core",
      strict: true,
      enableJsonFlag: false,
      landoSpec: {
        id: "meta:global:destroy",
        summary: "Destroy the host-level global Lando app provider resources.",
        namespace: "meta",
        topLevelAlias: "global:destroy",
        bootstrap: "global",
      },
      bootstrap: "global",
      isESM: true,
      relativePath: ["src", "cli", "oclif", "commands", "meta", "global", "destroy.ts"],
      aliasPermutations: ["global:destroy", "destroy:global"],
      permutations: [
        "meta:global:destroy",
        "global:meta:destroy",
        "global:destroy:meta",
        "meta:destroy:global",
        "destroy:meta:global",
        "destroy:global:meta",
      ],
    },
    "meta:global:info": {
      aliases: [],
      args: {},
      description: "Global-app `info` (deliverable).",
      flags: {},
      hasDynamicHelp: false,
      hidden: false,
      hiddenAliases: [],
      id: "meta:global:info",
      pluginAlias: "@lando/core",
      pluginName: "@lando/core",
      pluginType: "core",
      strict: true,
      enableJsonFlag: false,
      landoSpec: {
        id: "meta:global:info",
        summary: "Global-app `info` (deliverable).",
        namespace: "meta",
        bootstrap: "minimal",
      },
      bootstrap: "minimal",
      isESM: true,
      relativePath: ["src", "cli", "oclif", "commands", "meta", "global", "info.ts"],
      aliasPermutations: [],
      permutations: [
        "meta:global:info",
        "global:meta:info",
        "global:info:meta",
        "meta:info:global",
        "info:meta:global",
        "info:global:meta",
      ],
    },
    "meta:global:install": {
      aliases: ["global:install"],
      args: {
        plugin: {
          description: "Plugin name for future global-service enablement.",
          name: "plugin",
          required: false,
        },
      },
      description: "Materialize the host-level global Lando app Landofile stack.",
      flags: {},
      hasDynamicHelp: false,
      hidden: false,
      hiddenAliases: [],
      id: "meta:global:install",
      pluginAlias: "@lando/core",
      pluginName: "@lando/core",
      pluginType: "core",
      strict: true,
      enableJsonFlag: false,
      landoSpec: {
        id: "meta:global:install",
        summary: "Materialize the host-level global Lando app Landofile stack.",
        namespace: "meta",
        topLevelAlias: "global:install",
        bootstrap: "global",
      },
      bootstrap: "global",
      isESM: true,
      relativePath: ["src", "cli", "oclif", "commands", "meta", "global", "install.ts"],
      aliasPermutations: ["global:install", "install:global"],
      permutations: [
        "meta:global:install",
        "global:meta:install",
        "global:install:meta",
        "meta:install:global",
        "install:meta:global",
        "install:global:meta",
      ],
    },
    "meta:global:list": {
      aliases: [],
      args: {},
      description: "Global-app `list` (deliverable).",
      flags: {},
      hasDynamicHelp: false,
      hidden: false,
      hiddenAliases: [],
      id: "meta:global:list",
      pluginAlias: "@lando/core",
      pluginName: "@lando/core",
      pluginType: "core",
      strict: true,
      enableJsonFlag: false,
      landoSpec: {
        id: "meta:global:list",
        summary: "Global-app `list` (deliverable).",
        namespace: "meta",
        bootstrap: "minimal",
      },
      bootstrap: "minimal",
      isESM: true,
      relativePath: ["src", "cli", "oclif", "commands", "meta", "global", "list.ts"],
      aliasPermutations: [],
      permutations: [
        "meta:global:list",
        "global:meta:list",
        "global:list:meta",
        "meta:list:global",
        "list:meta:global",
        "list:global:meta",
      ],
    },
    "meta:global:logs": {
      aliases: [],
      args: {},
      description: "Global-app `logs` (deliverable).",
      flags: {},
      hasDynamicHelp: false,
      hidden: false,
      hiddenAliases: [],
      id: "meta:global:logs",
      pluginAlias: "@lando/core",
      pluginName: "@lando/core",
      pluginType: "core",
      strict: true,
      enableJsonFlag: false,
      landoSpec: {
        id: "meta:global:logs",
        summary: "Global-app `logs` (deliverable).",
        namespace: "meta",
        bootstrap: "minimal",
      },
      bootstrap: "minimal",
      isESM: true,
      relativePath: ["src", "cli", "oclif", "commands", "meta", "global", "logs.ts"],
      aliasPermutations: [],
      permutations: [
        "meta:global:logs",
        "global:meta:logs",
        "global:logs:meta",
        "meta:logs:global",
        "logs:meta:global",
        "logs:global:meta",
      ],
    },
    "meta:global:rebuild": {
      aliases: [],
      args: {},
      description: "Global-app `rebuild` (deliverable).",
      flags: {},
      hasDynamicHelp: false,
      hidden: false,
      hiddenAliases: [],
      id: "meta:global:rebuild",
      pluginAlias: "@lando/core",
      pluginName: "@lando/core",
      pluginType: "core",
      strict: true,
      enableJsonFlag: false,
      landoSpec: {
        id: "meta:global:rebuild",
        summary: "Global-app `rebuild` (deliverable).",
        namespace: "meta",
        bootstrap: "minimal",
      },
      bootstrap: "minimal",
      isESM: true,
      relativePath: ["src", "cli", "oclif", "commands", "meta", "global", "rebuild.ts"],
      aliasPermutations: [],
      permutations: [
        "meta:global:rebuild",
        "global:meta:rebuild",
        "global:rebuild:meta",
        "meta:rebuild:global",
        "rebuild:meta:global",
        "rebuild:global:meta",
      ],
    },
    "meta:global:restart": {
      aliases: [],
      args: {},
      description: "Global-app `restart` (deliverable).",
      flags: {},
      hasDynamicHelp: false,
      hidden: false,
      hiddenAliases: [],
      id: "meta:global:restart",
      pluginAlias: "@lando/core",
      pluginName: "@lando/core",
      pluginType: "core",
      strict: true,
      enableJsonFlag: false,
      landoSpec: {
        id: "meta:global:restart",
        summary: "Global-app `restart` (deliverable).",
        namespace: "meta",
        bootstrap: "minimal",
      },
      bootstrap: "minimal",
      isESM: true,
      relativePath: ["src", "cli", "oclif", "commands", "meta", "global", "restart.ts"],
      aliasPermutations: [],
      permutations: [
        "meta:global:restart",
        "global:meta:restart",
        "global:restart:meta",
        "meta:restart:global",
        "restart:meta:global",
        "restart:global:meta",
      ],
    },
    "meta:global:start": {
      aliases: ["global:start"],
      args: {},
      description: "Start the host-level global Lando app.",
      flags: {
        service: {
          char: "s",
          description: "Start and inspect a specific global service (repeatable).",
          name: "service",
          hasDynamicHelp: false,
          multiple: true,
          type: "option",
        },
      },
      hasDynamicHelp: false,
      hidden: false,
      hiddenAliases: [],
      id: "meta:global:start",
      pluginAlias: "@lando/core",
      pluginName: "@lando/core",
      pluginType: "core",
      strict: true,
      enableJsonFlag: false,
      landoSpec: {
        id: "meta:global:start",
        summary: "Start the host-level global Lando app.",
        namespace: "meta",
        topLevelAlias: "global:start",
        bootstrap: "global",
      },
      bootstrap: "global",
      isESM: true,
      relativePath: ["src", "cli", "oclif", "commands", "meta", "global", "start.ts"],
      aliasPermutations: ["global:start", "start:global"],
      permutations: [
        "meta:global:start",
        "global:meta:start",
        "global:start:meta",
        "meta:start:global",
        "start:meta:global",
        "start:global:meta",
      ],
    },
    "meta:global:status": {
      aliases: ["global:status"],
      args: {},
      description: "Show runtime status for the host-level global Lando app.",
      flags: {
        service: {
          char: "s",
          description: "Filter to a specific global service (repeatable).",
          name: "service",
          hasDynamicHelp: false,
          multiple: true,
          type: "option",
        },
        format: {
          description: "Output format.",
          name: "format",
          default: "table",
          hasDynamicHelp: false,
          multiple: false,
          options: ["table", "json"],
          type: "option",
        },
      },
      hasDynamicHelp: false,
      hidden: false,
      hiddenAliases: [],
      id: "meta:global:status",
      pluginAlias: "@lando/core",
      pluginName: "@lando/core",
      pluginType: "core",
      strict: true,
      enableJsonFlag: false,
      landoSpec: {
        id: "meta:global:status",
        summary: "Show runtime status for the host-level global Lando app.",
        namespace: "meta",
        topLevelAlias: "global:status",
        bootstrap: "global",
      },
      bootstrap: "global",
      isESM: true,
      relativePath: ["src", "cli", "oclif", "commands", "meta", "global", "status.ts"],
      aliasPermutations: ["global:status", "status:global"],
      permutations: [
        "meta:global:status",
        "global:meta:status",
        "global:status:meta",
        "meta:status:global",
        "status:meta:global",
        "status:global:meta",
      ],
    },
    "meta:global:stop": {
      aliases: ["global:stop"],
      args: {},
      description: "Stop the host-level global Lando app.",
      flags: {},
      hasDynamicHelp: false,
      hidden: false,
      hiddenAliases: [],
      id: "meta:global:stop",
      pluginAlias: "@lando/core",
      pluginName: "@lando/core",
      pluginType: "core",
      strict: true,
      enableJsonFlag: false,
      landoSpec: {
        id: "meta:global:stop",
        summary: "Stop the host-level global Lando app.",
        namespace: "meta",
        topLevelAlias: "global:stop",
        bootstrap: "global",
      },
      bootstrap: "global",
      isESM: true,
      relativePath: ["src", "cli", "oclif", "commands", "meta", "global", "stop.ts"],
      aliasPermutations: ["global:stop", "stop:global"],
      permutations: [
        "meta:global:stop",
        "global:meta:stop",
        "global:stop:meta",
        "meta:stop:global",
        "stop:meta:global",
        "stop:global:meta",
      ],
    },
    "meta:global:uninstall": {
      aliases: ["global:uninstall"],
      args: {
        plugin: {
          description: "Plugin name for future global-service disablement.",
          name: "plugin",
          required: false,
        },
      },
      description: "Clear generated services from the host-level global Lando app.",
      flags: {
        purge: {
          description:
            "Also remove global service provider resources and data volumes before clearing services.",
          name: "purge",
          allowNo: false,
          type: "boolean",
        },
      },
      hasDynamicHelp: false,
      hidden: false,
      hiddenAliases: [],
      id: "meta:global:uninstall",
      pluginAlias: "@lando/core",
      pluginName: "@lando/core",
      pluginType: "core",
      strict: true,
      enableJsonFlag: false,
      landoSpec: {
        id: "meta:global:uninstall",
        summary: "Clear generated services from the host-level global Lando app.",
        namespace: "meta",
        topLevelAlias: "global:uninstall",
        bootstrap: "global",
      },
      bootstrap: "global",
      isESM: true,
      relativePath: ["src", "cli", "oclif", "commands", "meta", "global", "uninstall.ts"],
      aliasPermutations: ["global:uninstall", "uninstall:global"],
      permutations: [
        "meta:global:uninstall",
        "global:meta:uninstall",
        "global:uninstall:meta",
        "meta:uninstall:global",
        "uninstall:meta:global",
        "uninstall:global:meta",
      ],
    },
    "meta:plugin:add": {
      aliases: ["plugin:add"],
      args: {
        spec: {
          description: "Plugin spec (npm package name with optional @version).",
          name: "spec",
          required: false,
        },
      },
      description: "Install a plugin (npm source) with manifest validation and trust prompt.",
      flags: {
        trust: {
          description:
            "Trust the plugin for this session (required for non-interactive installs; persistent trust is deferred to Beta).",
          name: "trust",
          allowNo: false,
          type: "boolean",
        },
        yes: {
          char: "y",
          description: "Alias of --trust.",
          name: "yes",
          allowNo: false,
          type: "boolean",
        },
        force: {
          description: "Re-install even if already present.",
          name: "force",
          allowNo: false,
          type: "boolean",
        },
      },
      hasDynamicHelp: false,
      hidden: false,
      hiddenAliases: [],
      id: "meta:plugin:add",
      pluginAlias: "@lando/core",
      pluginName: "@lando/core",
      pluginType: "core",
      strict: true,
      enableJsonFlag: false,
      landoSpec: {
        id: "meta:plugin:add",
        summary: "Install a plugin (npm source) with manifest validation and trust prompt.",
        namespace: "meta",
        topLevelAlias: true,
        bootstrap: "minimal",
      },
      bootstrap: "minimal",
      isESM: true,
      relativePath: ["src", "cli", "oclif", "commands", "meta", "plugin", "add.ts"],
      aliasPermutations: ["plugin:add", "add:plugin"],
      permutations: [
        "meta:plugin:add",
        "plugin:meta:add",
        "plugin:add:meta",
        "meta:add:plugin",
        "add:meta:plugin",
        "add:plugin:meta",
      ],
    },
    "meta:plugin:build": {
      aliases: [],
      args: {},
      description: "Build the current plugin source (authoring command).",
      flags: {},
      hasDynamicHelp: false,
      hidden: false,
      hiddenAliases: [],
      id: "meta:plugin:build",
      pluginAlias: "@lando/core",
      pluginName: "@lando/core",
      pluginType: "core",
      strict: true,
      enableJsonFlag: false,
      landoSpec: {
        id: "meta:plugin:build",
        summary: "Build the current plugin source (authoring command).",
        namespace: "meta",
        topLevelAlias: false,
        bootstrap: "minimal",
      },
      bootstrap: "minimal",
      isESM: true,
      relativePath: ["src", "cli", "oclif", "commands", "meta", "plugin", "build.ts"],
      aliasPermutations: [],
      permutations: [
        "meta:plugin:build",
        "plugin:meta:build",
        "plugin:build:meta",
        "meta:build:plugin",
        "build:meta:plugin",
        "build:plugin:meta",
      ],
    },
    "meta:plugin:link": {
      aliases: [],
      args: {
        path: {
          description: "Plugin authoring directory to link (defaults to cwd).",
          name: "path",
          required: false,
        },
      },
      description: "Symlink the current plugin into the user-global plugin store (authoring command).",
      flags: {},
      hasDynamicHelp: false,
      hidden: false,
      hiddenAliases: [],
      id: "meta:plugin:link",
      pluginAlias: "@lando/core",
      pluginName: "@lando/core",
      pluginType: "core",
      strict: true,
      enableJsonFlag: false,
      landoSpec: {
        id: "meta:plugin:link",
        summary: "Symlink the current plugin into the user-global plugin store (authoring command).",
        namespace: "meta",
        topLevelAlias: false,
        bootstrap: "minimal",
      },
      bootstrap: "minimal",
      isESM: true,
      relativePath: ["src", "cli", "oclif", "commands", "meta", "plugin", "link.ts"],
      aliasPermutations: [],
      permutations: [
        "meta:plugin:link",
        "plugin:meta:link",
        "plugin:link:meta",
        "meta:link:plugin",
        "link:meta:plugin",
        "link:plugin:meta",
      ],
    },
    "meta:plugin:login": {
      aliases: ["plugin:login"],
      args: {},
      description: "Authenticate with a private plugin registry.",
      flags: {
        registry: {
          description: "Registry URL.",
          name: "registry",
          required: true,
          hasDynamicHelp: false,
          multiple: false,
          type: "option",
        },
      },
      hasDynamicHelp: false,
      hidden: false,
      hiddenAliases: [],
      id: "meta:plugin:login",
      pluginAlias: "@lando/core",
      pluginName: "@lando/core",
      pluginType: "core",
      strict: true,
      enableJsonFlag: false,
      landoSpec: {
        id: "meta:plugin:login",
        summary: "Authenticate with a plugin source.",
        namespace: "meta",
        topLevelAlias: true,
        bootstrap: "minimal",
      },
      bootstrap: "minimal",
      isESM: true,
      relativePath: ["src", "cli", "oclif", "commands", "meta", "plugin", "login.ts"],
      aliasPermutations: ["plugin:login", "login:plugin"],
      permutations: [
        "meta:plugin:login",
        "plugin:meta:login",
        "plugin:login:meta",
        "meta:login:plugin",
        "login:meta:plugin",
        "login:plugin:meta",
      ],
    },
    "meta:plugin:logout": {
      aliases: ["plugin:logout"],
      args: {},
      description: "Sign out of a private plugin registry.",
      flags: {
        registry: {
          description: "Registry URL.",
          name: "registry",
          hasDynamicHelp: false,
          multiple: false,
          type: "option",
        },
      },
      hasDynamicHelp: false,
      hidden: false,
      hiddenAliases: [],
      id: "meta:plugin:logout",
      pluginAlias: "@lando/core",
      pluginName: "@lando/core",
      pluginType: "core",
      strict: true,
      enableJsonFlag: false,
      landoSpec: {
        id: "meta:plugin:logout",
        summary: "Forget plugin source authentication.",
        namespace: "meta",
        topLevelAlias: true,
        bootstrap: "minimal",
      },
      bootstrap: "minimal",
      isESM: true,
      relativePath: ["src", "cli", "oclif", "commands", "meta", "plugin", "logout.ts"],
      aliasPermutations: ["plugin:logout", "logout:plugin"],
      permutations: [
        "meta:plugin:logout",
        "plugin:meta:logout",
        "plugin:logout:meta",
        "meta:logout:plugin",
        "logout:meta:plugin",
        "logout:plugin:meta",
      ],
    },
    "meta:plugin:new": {
      aliases: [],
      args: {
        name: {
          description: "New plugin package name.",
          name: "name",
          required: false,
        },
        destination: {
          description: "Destination directory.",
          name: "destination",
          required: false,
        },
      },
      description: "Scaffold a new plugin from a built-in template (authoring command).",
      flags: {
        template: {
          description: "Bundled plugin template id.",
          name: "template",
          hasDynamicHelp: false,
          multiple: false,
          options: [
            "service-type",
            "provider",
            "tooling-engine",
            "template-engine",
            "route-filter",
            "config-translator",
            "recipe",
            "bare",
          ],
          type: "option",
        },
        cspace: {
          description: "Contribution namespace used by the scaffold.",
          name: "cspace",
          hasDynamicHelp: false,
          multiple: false,
          type: "option",
        },
        description: {
          description: "Plugin description.",
          name: "description",
          hasDynamicHelp: false,
          multiple: false,
          type: "option",
        },
        answer: {
          description: "Scaffold answer in key=value form (repeatable).",
          name: "answer",
          hasDynamicHelp: false,
          multiple: true,
          type: "option",
        },
        answers: {
          description: "Path to a JSON answers file.",
          name: "answers",
          hasDynamicHelp: false,
          multiple: false,
          type: "option",
        },
        "no-interactive": {
          description: "Never prompt; name, template, cspace, and description must be supplied.",
          name: "no-interactive",
          allowNo: false,
          type: "boolean",
        },
      },
      hasDynamicHelp: false,
      hidden: false,
      hiddenAliases: [],
      id: "meta:plugin:new",
      pluginAlias: "@lando/core",
      pluginName: "@lando/core",
      pluginType: "core",
      strict: true,
      enableJsonFlag: false,
      landoSpec: {
        id: "meta:plugin:new",
        summary: "Scaffold a new plugin from a built-in template (authoring command).",
        namespace: "meta",
        topLevelAlias: false,
        bootstrap: "minimal",
      },
      bootstrap: "minimal",
      isESM: true,
      relativePath: ["src", "cli", "oclif", "commands", "meta", "plugin", "new.ts"],
      aliasPermutations: [],
      permutations: [
        "meta:plugin:new",
        "plugin:meta:new",
        "plugin:new:meta",
        "meta:new:plugin",
        "new:meta:plugin",
        "new:plugin:meta",
      ],
    },
    "meta:plugin:publish": {
      aliases: [],
      args: {},
      description: "Publish the current plugin (authoring command).",
      flags: {},
      hasDynamicHelp: false,
      hidden: false,
      hiddenAliases: [],
      id: "meta:plugin:publish",
      pluginAlias: "@lando/core",
      pluginName: "@lando/core",
      pluginType: "core",
      strict: true,
      enableJsonFlag: false,
      landoSpec: {
        id: "meta:plugin:publish",
        summary: "Publish the current plugin (authoring command).",
        namespace: "meta",
        topLevelAlias: false,
        bootstrap: "minimal",
      },
      bootstrap: "minimal",
      isESM: true,
      relativePath: ["src", "cli", "oclif", "commands", "meta", "plugin", "publish.ts"],
      aliasPermutations: [],
      permutations: [
        "meta:plugin:publish",
        "plugin:meta:publish",
        "plugin:publish:meta",
        "meta:publish:plugin",
        "publish:meta:plugin",
        "publish:plugin:meta",
      ],
    },
    "meta:plugin:remove": {
      aliases: ["plugin:remove"],
      args: {
        name: {
          description: "Plugin name.",
          name: "name",
          required: false,
        },
      },
      description: "Remove an installed Lando plugin.",
      flags: {},
      hasDynamicHelp: false,
      hidden: false,
      hiddenAliases: [],
      id: "meta:plugin:remove",
      pluginAlias: "@lando/core",
      pluginName: "@lando/core",
      pluginType: "core",
      strict: true,
      enableJsonFlag: false,
      landoSpec: {
        id: "meta:plugin:remove",
        summary: "Remove an installed Lando plugin.",
        namespace: "meta",
        topLevelAlias: true,
        bootstrap: "minimal",
      },
      bootstrap: "minimal",
      isESM: true,
      relativePath: ["src", "cli", "oclif", "commands", "meta", "plugin", "remove.ts"],
      aliasPermutations: ["plugin:remove", "remove:plugin"],
      permutations: [
        "meta:plugin:remove",
        "plugin:meta:remove",
        "plugin:remove:meta",
        "meta:remove:plugin",
        "remove:meta:plugin",
        "remove:plugin:meta",
      ],
    },
    "meta:plugin:test": {
      aliases: [],
      args: {},
      description: "Run the current plugin's Bun test suite (authoring command).",
      flags: {},
      hasDynamicHelp: false,
      hidden: false,
      hiddenAliases: [],
      id: "meta:plugin:test",
      pluginAlias: "@lando/core",
      pluginName: "@lando/core",
      pluginType: "core",
      strict: false,
      enableJsonFlag: false,
      landoSpec: {
        id: "meta:plugin:test",
        summary: "Run the current plugin's Bun test suite (authoring command).",
        namespace: "meta",
        topLevelAlias: false,
        bootstrap: "minimal",
      },
      bootstrap: "minimal",
      isESM: true,
      relativePath: ["src", "cli", "oclif", "commands", "meta", "plugin", "test.ts"],
      aliasPermutations: [],
      permutations: [
        "meta:plugin:test",
        "plugin:meta:test",
        "plugin:test:meta",
        "meta:test:plugin",
        "test:meta:plugin",
        "test:plugin:meta",
      ],
    },
    "meta:plugin:trust": {
      aliases: ["plugin:trust"],
      args: {
        action: {
          description: "Plugin name, list, or revoke.",
          name: "action",
          required: true,
        },
        name: {
          description: "Plugin name to revoke.",
          name: "name",
          required: false,
        },
      },
      description: "Manage trusted plugin postinstall entries.",
      flags: {},
      hasDynamicHelp: false,
      hidden: false,
      hiddenAliases: [],
      id: "meta:plugin:trust",
      pluginAlias: "@lando/core",
      pluginName: "@lando/core",
      pluginType: "core",
      strict: true,
      enableJsonFlag: false,
      landoSpec: {
        id: "meta:plugin:trust",
        summary: "Manage trusted plugin postinstall entries.",
        namespace: "meta",
        topLevelAlias: true,
        bootstrap: "minimal",
      },
      bootstrap: "minimal",
      isESM: true,
      relativePath: ["src", "cli", "oclif", "commands", "meta", "plugin", "trust.ts"],
      aliasPermutations: ["plugin:trust", "trust:plugin"],
      permutations: [
        "meta:plugin:trust",
        "plugin:meta:trust",
        "plugin:trust:meta",
        "meta:trust:plugin",
        "trust:meta:plugin",
        "trust:plugin:meta",
      ],
    },
    "meta:plugin:trust-authoring-root": {
      aliases: [],
      args: {
        path: {
          description: "Absolute path to mark as a trusted authoring root.",
          name: "path",
          required: true,
        },
      },
      description: "Authorize an absolute path as a plugin authoring root.",
      flags: {},
      hasDynamicHelp: false,
      hidden: false,
      hiddenAliases: [],
      id: "meta:plugin:trust-authoring-root",
      pluginAlias: "@lando/core",
      pluginName: "@lando/core",
      pluginType: "core",
      strict: true,
      enableJsonFlag: false,
      landoSpec: {
        id: "meta:plugin:trust-authoring-root",
        summary: "Authorize an absolute path as a plugin authoring root.",
        namespace: "meta",
        bootstrap: "minimal",
      },
      bootstrap: "minimal",
      isESM: true,
      relativePath: ["src", "cli", "oclif", "commands", "meta", "plugin", "trust-authoring-root.ts"],
      aliasPermutations: [],
      permutations: [
        "meta:plugin:trust-authoring-root",
        "plugin:meta:trust-authoring-root",
        "plugin:trust-authoring-root:meta",
        "meta:trust-authoring-root:plugin",
        "trust-authoring-root:meta:plugin",
        "trust-authoring-root:plugin:meta",
      ],
    },
    "meta:plugin:unlink": {
      aliases: [],
      args: {
        name: {
          description: "Plugin name.",
          name: "name",
          required: true,
        },
      },
      description: "Remove a previously linked plugin (authoring command).",
      flags: {},
      hasDynamicHelp: false,
      hidden: false,
      hiddenAliases: [],
      id: "meta:plugin:unlink",
      pluginAlias: "@lando/core",
      pluginName: "@lando/core",
      pluginType: "core",
      strict: true,
      enableJsonFlag: false,
      landoSpec: {
        id: "meta:plugin:unlink",
        summary: "Remove a previously linked plugin (authoring command).",
        namespace: "meta",
        topLevelAlias: false,
        bootstrap: "minimal",
      },
      bootstrap: "minimal",
      isESM: true,
      relativePath: ["src", "cli", "oclif", "commands", "meta", "plugin", "unlink.ts"],
      aliasPermutations: [],
      permutations: [
        "meta:plugin:unlink",
        "plugin:meta:unlink",
        "plugin:unlink:meta",
        "meta:unlink:plugin",
        "unlink:meta:plugin",
        "unlink:plugin:meta",
      ],
    },
    "meta:recipes:list": {
      aliases: ["recipes"],
      args: {},
      description: "List canonical recipes shipped with the binary.",
      flags: {},
      hasDynamicHelp: false,
      hidden: false,
      hiddenAliases: [],
      id: "meta:recipes:list",
      pluginAlias: "@lando/core",
      pluginName: "@lando/core",
      pluginType: "core",
      strict: true,
      enableJsonFlag: false,
      landoSpec: {
        id: "meta:recipes:list",
        summary: "List canonical recipes shipped with the binary.",
        namespace: "meta",
        topLevelAlias: "recipes",
        bootstrap: "none",
      },
      bootstrap: "none",
      isESM: true,
      relativePath: ["src", "cli", "oclif", "commands", "meta", "recipes", "list.ts"],
      aliasPermutations: ["recipes"],
      permutations: [
        "meta:recipes:list",
        "recipes:meta:list",
        "recipes:list:meta",
        "meta:list:recipes",
        "list:meta:recipes",
        "list:recipes:meta",
      ],
    },
    "meta:setup": {
      aliases: ["setup"],
      args: {},
      description: "Run provider, CA, proxy, and shell-integration setup.",
      flags: {
        yes: {
          description: "Skip confirmation prompts.",
          name: "yes",
          allowNo: false,
          type: "boolean",
        },
        "no-interactive": {
          description: "Do not prompt; fail or use documented non-interactive setup defaults.",
          name: "no-interactive",
          allowNo: false,
          type: "boolean",
        },
        provider: {
          description:
            "Choose a provider (e.g. lando, docker, podman). Overrides Landofile/env/config selection.",
          name: "provider",
          hasDynamicHelp: false,
          multiple: false,
          type: "option",
        },
        "skip-provider": {
          name: "skip-provider",
          allowNo: false,
          type: "boolean",
        },
        "skip-proxy": {
          name: "skip-proxy",
          allowNo: false,
          type: "boolean",
        },
        "skip-install-ca": {
          name: "skip-install-ca",
          allowNo: false,
          type: "boolean",
        },
        "skip-shell-integration": {
          name: "skip-shell-integration",
          allowNo: false,
          type: "boolean",
        },
        "skip-file-sync": {
          description: "Skip Mutagen binary download; deferred to first accelerated app:start.",
          name: "skip-file-sync",
          allowNo: false,
          type: "boolean",
        },
        "runtime-bundle-url": {
          description: "Override the Lando-managed runtime bundle URL for setup.",
          name: "runtime-bundle-url",
          hasDynamicHelp: false,
          multiple: false,
          type: "option",
        },
        "runtime-bundle-sha256": {
          description: "Pinned SHA-256 paired with --runtime-bundle-url for verifying a local bundle.",
          name: "runtime-bundle-sha256",
          hasDynamicHelp: false,
          multiple: false,
          type: "option",
        },
        "host-proxy": {
          description:
            "Configure the host-proxy DNS mechanism. `auto` (default) selects the per-platform default; `none` opts out for users managing their own DNS.",
          name: "host-proxy",
          default: "auto",
          hasDynamicHelp: false,
          multiple: false,
          options: ["auto", "none"],
          type: "option",
        },
      },
      hasDynamicHelp: false,
      hidden: false,
      hiddenAliases: [],
      id: "meta:setup",
      pluginAlias: "@lando/core",
      pluginName: "@lando/core",
      pluginType: "core",
      strict: true,
      enableJsonFlag: false,
      landoSpec: {
        id: "meta:setup",
        summary: "Run host setup (provider, CA, proxy, shell integration).",
        namespace: "meta",
        topLevelAlias: true,
        bootstrap: "minimal",
      },
      bootstrap: "minimal",
      isESM: true,
      relativePath: ["src", "cli", "oclif", "commands", "meta", "setup.ts"],
      aliasPermutations: ["setup"],
      permutations: ["meta:setup", "setup:meta"],
    },
    "meta:shellenv": {
      aliases: ["shellenv"],
      args: {},
      description: "Print shell-profile snippets to integrate Lando into your PATH.",
      flags: {
        shell: {
          name: "shell",
          default: "posix",
          hasDynamicHelp: false,
          multiple: false,
          options: ["posix", "powershell", "pwsh"],
          type: "option",
        },
      },
      hasDynamicHelp: false,
      hidden: false,
      hiddenAliases: [],
      id: "meta:shellenv",
      pluginAlias: "@lando/core",
      pluginName: "@lando/core",
      pluginType: "core",
      strict: true,
      enableJsonFlag: false,
      landoSpec: {
        id: "meta:shellenv",
        summary: "Print shell-profile snippets to integrate Lando into your PATH.",
        namespace: "meta",
        topLevelAlias: true,
        bootstrap: "none",
      },
      bootstrap: "none",
      isESM: true,
      relativePath: ["src", "cli", "oclif", "commands", "meta", "shellenv.ts"],
      aliasPermutations: ["shellenv"],
      permutations: ["meta:shellenv", "shellenv:meta"],
    },
    "meta:uninstall": {
      aliases: ["uninstall"],
      args: {},
      description: "Remove Lando-owned installed files after confirmation.",
      flags: {
        "dry-run": {
          description: "Print the uninstall plan without changing the system.",
          name: "dry-run",
          allowNo: false,
          type: "boolean",
        },
        yes: {
          char: "y",
          description: "Confirm destructive uninstall execution after reviewing the plan.",
          name: "yes",
          allowNo: false,
          type: "boolean",
        },
        "keep-data": {
          description: "Remove Lando-owned toolchain files while preserving app data and global state.",
          name: "keep-data",
          allowNo: false,
          type: "boolean",
        },
        purge: {
          description: "Remove Lando-owned toolchain files and data roots after confirmation.",
          name: "purge",
          allowNo: false,
          type: "boolean",
        },
      },
      hasDynamicHelp: false,
      hidden: false,
      hiddenAliases: [],
      id: "meta:uninstall",
      pluginAlias: "@lando/core",
      pluginName: "@lando/core",
      pluginType: "core",
      strict: true,
      enableJsonFlag: false,
      landoSpec: {
        id: "meta:uninstall",
        summary: "Remove Lando-owned installed files after confirmation.",
        namespace: "meta",
        topLevelAlias: true,
        bootstrap: "minimal",
      },
      bootstrap: "minimal",
      isESM: true,
      relativePath: ["src", "cli", "oclif", "commands", "meta", "uninstall.ts"],
      aliasPermutations: ["uninstall"],
      permutations: ["meta:uninstall", "uninstall:meta"],
    },
    "meta:update": {
      aliases: ["update"],
      args: {},
      description: "Update Lando core and plugins.",
      flags: {},
      hasDynamicHelp: false,
      hidden: false,
      hiddenAliases: [],
      id: "meta:update",
      pluginAlias: "@lando/core",
      pluginName: "@lando/core",
      pluginType: "core",
      strict: true,
      enableJsonFlag: false,
      landoSpec: {
        id: "meta:update",
        summary: "Update Lando core and plugins.",
        namespace: "meta",
        topLevelAlias: true,
        bootstrap: "plugins",
      },
      bootstrap: "plugins",
      isESM: true,
      relativePath: ["src", "cli", "oclif", "commands", "meta", "update.ts"],
      aliasPermutations: ["update"],
      permutations: ["meta:update", "update:meta"],
    },
    "meta:version": {
      aliases: ["--version", "-v", "version"],
      args: {},
      description: "Show the Lando + Bun + plugin versions.",
      flags: {},
      hasDynamicHelp: false,
      hidden: false,
      hiddenAliases: [],
      id: "meta:version",
      pluginAlias: "@lando/core",
      pluginName: "@lando/core",
      pluginType: "core",
      strict: true,
      enableJsonFlag: false,
      landoSpec: {
        id: "meta:version",
        summary: "Show the Lando + Bun + plugin versions.",
        namespace: "meta",
        topLevelAlias: true,
        bootstrap: "none",
      },
      bootstrap: "none",
      isESM: true,
      relativePath: ["src", "cli", "oclif", "commands", "meta", "version.ts"],
      aliasPermutations: ["--version", "-v", "version"],
      permutations: ["meta:version", "version:meta"],
    },
    "meta:x": {
      aliases: ["x"],
      args: {
        spec: {
          description: "Package spec (e.g. prettier@latest, @astrojs/cli)",
          name: "spec",
          required: true,
        },
      },
      description: "One-shot package execution via BunSelfRunner.x (bunx-equivalent).",
      flags: {},
      hasDynamicHelp: false,
      hidden: false,
      hiddenAliases: [],
      id: "meta:x",
      pluginAlias: "@lando/core",
      pluginName: "@lando/core",
      pluginType: "core",
      strict: false,
      enableJsonFlag: false,
      landoSpec: {
        id: "meta:x",
        summary: "One-shot package execution via BunSelfRunner.x (bunx-equivalent).",
        namespace: "meta",
        topLevelAlias: true,
        bootstrap: "minimal",
      },
      bootstrap: "minimal",
      isESM: true,
      relativePath: ["src", "cli", "oclif", "commands", "meta", "x.ts"],
      aliasPermutations: ["x"],
      permutations: ["meta:x", "x:meta"],
    },
  },
  version: "0.0.0",
} satisfies Interfaces.Manifest;
