import { expect, test } from "bun:test";

import * as engineLayers from "../../src/testing/engine-layers.ts";

const EXPECTED_ENGINE_LAYER_EXPORTS = [
  "AppPlannerLive",
  "BuildOrchestratorLive",
  "CacheServiceLive",
  "CertificateAuthorityResolver",
  "CertificateAuthorityUnavailableLive",
  "ConfigResultSchema",
  "ConfigServiceLive",
  "DataMoverLive",
  "DeprecationServiceLive",
  "EventServiceLive",
  "FileSystemLive",
  "GlobalAppServiceLive",
  "HOST_PROXY_WORKER_PROTOCOL_VERSION",
  "HealthcheckRunnerUnavailableLive",
  "HostMaintenanceRegistry",
  "HostProxyServiceDisabledLive",
  "LandofileServiceLive",
  "PLUGIN_NEW_TEMPLATE_IDS",
  "PluginRegistryLive",
  "ProviderExecToolingEngineLive",
  "ProxyServiceUnavailableLive",
  "RuntimeCwd",
  "ScratchRegistry",
  "ScratchRegistryLive",
  "ScratchResourceScanner",
  "ScratchResourceScannerLive",
  "SecretStoreLive",
  "SshServiceUnavailableLive",
  "StreamFrameSink",
  "TELEMETRY_EVENT_INVENTORY",
  "UpdateLaunchProbeError",
  "UpdateMinimumVersionError",
  "UpdatePermissionError",
  "UrlScannerUnavailableLive",
  "appCommandCachePath",
  "appToolingCompilationCachePath",
  "applySetMutation",
  "applyUnsetMutation",
  "assertLandoVersionConstraint",
  "assertToolingNameClaimable",
  "assertUserAppIdNotReserved",
  "attachEffectiveTooling",
  "buildRunLandoRequest",
  "buildToolingInvocation",
  "buildUninstallPlan",
  "buildWindowsReplacementScript",
  "cliRuntimeOptions",
  "config",
  "decodeAppCommandIndex",
  "decodeIssues",
  "decodePluginCommandIndex",
  "defaultFetchManifestBytes",
  "deriveAppPlanCacheKey",
  "dispatchRunLando",
  "effectiveBootstrapForCommand",
  "ensureGlobalServicesRunning",
  "getAtPath",
  "globalInstall",
  "loadUserLandofile",
  "loadUserLandofileAt",
  "loadUserLandofileFile",
  "logsAppForTarget",
  "makeEngineLandofileServiceLive",
  "makeEnvSecretStoreLive",
  "makePluginRegistryLive",
  "makePluginTrustStore",
  "makeScratchAppServiceLive",
  "makeScratchRegistry",
  "makeShellRunnerLive",
  "managedFileLedger",
  "parseConfigPath",
  "parseConfigValue",
  "parseTypedValue",
  "pluginCommandCachePath",
  "providerImages",
  "publishTaskStart",
  "publishedEndpointUrl",
  "publishedEndpointUrls",
  "readAppPlanSourceFingerprint",
  "readScratchLandofile",
  "recordUpdateOutcomeTelemetry",
  "registerBuiltInContractDeprecations",
  "requiredGlobalServicesForPlan",
  "reservedTopLevelAliasOwner",
  "resolveCliTelemetryState",
  "resolveLandofileIncludes",
  "resolveScratchAcquireIsolation",
  "resolveUpdateManifestUrl",
  "scheduleWindowsReplacement",
  "setAtPath",
  "stripHostProxyRunLando",
  "uninstall",
  "unsetAtPath",
  "update",
  "updateChannelForVersion",
  "updateOutcomeFromError",
  "validateGlobalServiceContributions",
  "validateToolingArguments",
  "writeAppCommandCacheStrict",
  "writeCachedAppPlan",
  "writeCwdAppMapEntry",
  "writePluginCommandCacheStrict",
  "writeWorkerRecord",
] as const;

test("exports the reviewed engine coupling surface", () => {
  // Given the internal engine-coupling module
  // When its runtime exports are enumerated
  const exportedNames = Object.keys(engineLayers).sort();

  // Then only the committed append-only migration surface is exposed
  expect(exportedNames).toEqual([...EXPECTED_ENGINE_LAYER_EXPORTS]);
});
