import * as fs from "node:fs/promises";
import * as path from "node:path";
import { type Context, Effect, Layer } from "effect";

import {
  ShellExecError,
  ShellScriptOutsideRootError,
  ToolingCompileError,
  ToolingExecError,
} from "@lando/sdk/errors";
import type { AppPlan } from "@lando/sdk/schema";
import {
  type RuntimeProviderShape,
  type ShellCommandOptions,
  type ShellRunner,
  ToolingEngine,
  type ToolingEngineResult,
  type ToolingHostStep,
  type ToolingInvocation,
} from "@lando/sdk/services";

import { makeShellRunnerService } from "./shell-runner.ts";

const HOST_SERVICE = ":host";
const HOST_POSITIONAL_PARAMETER = /\$(?:@|[1-9]|\{(?:@|[1-9]))/u;
const LANDO_TOOLING_MARKER = "lando-tooling";
/** Generated by `normalizeCommands` when the authored string has no positional refs. */
const ARGV_SENTINEL_SUFFIX = ' "$@"';

const hostShellRunner = makeShellRunnerService(() => {
  throw new ShellExecError({ message: "Interactive host tooling is unavailable.", command: "" });
});

const wrapShellAsToolingError = (tool: string, shellError: ShellExecError): ToolingExecError =>
  new ToolingExecError({
    message: `Host tooling task ${tool} failed: ${shellError.message}`,
    tool,
    ...(shellError.exitCode === undefined ? {} : { exitCode: shellError.exitCode }),
    cause: shellError,
  });

const missingHostStepsError = (tool: string): ToolingExecError =>
  new ToolingExecError({
    message: `Host tooling task ${tool} has no structural host steps to run.`,
    tool,
  });

const unsupportedPositionalError = (tool: string): ToolingCompileError =>
  new ToolingCompileError({
    message: `Host tooling task ${tool} uses shell positional references that Bun Shell cannot bind safely.`,
    tool,
    remediation: "Remove $@ and $1 through $9 references; forwarded arguments are appended structurally.",
  });

/**
 * Decode a provider-form command argv into a structural host step without spawning `sh`.
 * Only the normalized `["sh","-c",source,"lando-tooling",...argv]` shape strips the
 * generated trailing ` "$@"` sentinel; plain argv arrays become argv steps.
 */
const decodeCommandToHostStep = (command: ReadonlyArray<string>): ToolingHostStep => {
  if (command.length >= 3 && command[0] === "sh" && command[1] === "-c") {
    const rawSource = command[2] ?? "";
    const hasMarker = command[3] === LANDO_TOOLING_MARKER;
    const source =
      hasMarker && rawSource.endsWith(ARGV_SENTINEL_SUFFIX)
        ? rawSource.slice(0, -ARGV_SENTINEL_SUFFIX.length)
        : rawSource;
    return {
      kind: "shell",
      source,
      argv: hasMarker ? command.slice(4) : command.slice(3),
    };
  }
  return { kind: "argv", argv: command };
};

/** Prefer explicit hostSteps; otherwise decode legacy commands structurally. */
const resolveHostSteps = (invocation: ToolingInvocation): ReadonlyArray<ToolingHostStep> => {
  if (invocation.hostSteps !== undefined && invocation.hostSteps.length > 0) {
    return invocation.hostSteps;
  }
  return invocation.commands.map(decodeCommandToHostStep);
};

const hostStepCommand = (
  tool: string,
  step: ToolingHostStep,
): Effect.Effect<{ readonly source: string; readonly argv: ReadonlyArray<string> }, ToolingCompileError> => {
  switch (step.kind) {
    case "shell":
      return HOST_POSITIONAL_PARAMETER.test(step.source)
        ? Effect.fail(unsupportedPositionalError(tool))
        : Effect.succeed({ source: step.source, argv: step.argv });
    case "argv":
      return Effect.succeed({ source: "", argv: step.argv });
    default:
      return step satisfies never;
  }
};

const hostRun = (
  shell: Context.Tag.Service<typeof ShellRunner>,
  invocation: ToolingInvocation,
  _plan: AppPlan,
  _provider: RuntimeProviderShape,
) =>
  Effect.gen(function* () {
    const steps = resolveHostSteps(invocation);
    if (steps.length === 0) return yield* Effect.fail(missingHostStepsError(invocation.tool));
    let exitCode = 0;
    let stdout = "";
    let stderr = "";
    for (const step of steps) {
      const command = yield* hostStepCommand(invocation.tool, step);
      const options: ShellCommandOptions = {
        ...(invocation.cwd === undefined ? {} : { cwd: invocation.cwd }),
        ...(invocation.env === undefined ? {} : { env: invocation.env }),
        argv: command.argv,
      };
      const result = yield* shell.exec(command.source, options).pipe(
        Effect.catchAll((cause) =>
          cause.exitCode !== undefined
            ? Effect.succeed({
                exitCode: cause.exitCode,
                stdout: cause.stdout ?? "",
                stderr: cause.stderr ?? "",
              })
            : Effect.fail(wrapShellAsToolingError(invocation.tool, cause)),
        ),
      );
      stdout += result.stdout;
      stderr += result.stderr;
      exitCode = result.exitCode;
      if (exitCode !== 0) break;
    }
    const out: ToolingEngineResult = {
      tool: invocation.tool,
      service: invocation.service ?? HOST_SERVICE,
      exitCode,
      stdout,
      stderr,
    };
    return out;
  });

export const runHostToolingWith = (
  shell: Context.Tag.Service<typeof ShellRunner>,
  invocation: ToolingInvocation,
  plan: AppPlan,
  provider: RuntimeProviderShape,
): Effect.Effect<ToolingEngineResult, ToolingCompileError | ToolingExecError> =>
  hostRun(shell, invocation, plan, provider);

const makeHostToolingEngine = (shell: Context.Tag.Service<typeof ShellRunner>) => ({
  id: "host",
  run: (invocation: ToolingInvocation, plan: AppPlan, provider: RuntimeProviderShape) =>
    hostRun(shell, invocation, plan, provider),
});

export const HostToolingEngineLive = Layer.succeed(ToolingEngine, makeHostToolingEngine(hostShellRunner));

const normalizeRoot = async (root: string): Promise<string> => {
  const resolved = await fs.realpath(root);
  return path.resolve(resolved);
};

const isWithinRoot = (target: string, root: string): boolean => {
  if (target === root) return true;
  const prefix = root.endsWith(path.sep) ? root : `${root}${path.sep}`;
  return target.startsWith(prefix);
};

const outsideRootError = (
  scriptPath: string,
  permittedRoots: ReadonlyArray<string>,
  realpathValue?: string,
  cause?: unknown,
) =>
  new ShellScriptOutsideRootError({
    message: `Host shell script ${scriptPath} resolves outside the permitted base directories.`,
    path: scriptPath,
    ...(realpathValue === undefined ? {} : { realpath: realpathValue }),
    permittedRoots,
    remediation:
      "Move the script inside the app root (or recipe cache for recipe-bundled scripts) and ensure no symlinks escape it.",
    ...(cause === undefined ? {} : { cause }),
  });

export const resolveScriptPath = (
  scriptPath: string,
  permittedRoots: ReadonlyArray<string>,
): Effect.Effect<string, ShellScriptOutsideRootError> =>
  Effect.tryPromise({
    try: async () => {
      if (permittedRoots.length === 0) {
        throw outsideRootError(scriptPath, permittedRoots);
      }
      let resolvedScript: string;
      try {
        resolvedScript = path.resolve(await fs.realpath(scriptPath));
      } catch (cause) {
        throw outsideRootError(scriptPath, permittedRoots, undefined, cause);
      }
      const normalizedRoots: string[] = [];
      for (const root of permittedRoots) {
        try {
          normalizedRoots.push(await normalizeRoot(root));
        } catch {
          // Skip roots that cannot be resolved (e.g. missing recipe cache dir).
        }
      }
      const contained = normalizedRoots.some((root) => isWithinRoot(resolvedScript, root));
      if (!contained) {
        throw outsideRootError(scriptPath, permittedRoots, resolvedScript);
      }
      return resolvedScript;
    },
    catch: (cause) =>
      cause instanceof ShellScriptOutsideRootError
        ? cause
        : outsideRootError(scriptPath, permittedRoots, undefined, cause),
  });

export const runHostScript = (
  scriptPath: string,
  permittedRoots: ReadonlyArray<string>,
  options?: ShellCommandOptions,
) =>
  Effect.gen(function* () {
    const resolved = yield* resolveScriptPath(scriptPath, permittedRoots);
    return yield* hostShellRunner.runScript(resolved, options);
  });

export const evaluateHostVar = (
  command: string,
  options?: ShellCommandOptions,
): Effect.Effect<string, ShellExecError> =>
  hostShellRunner.exec(command, options).pipe(Effect.map((result) => result.stdout.replace(/\r?\n$/u, "")));
