export const NEXTJS_SCAFFOLD_COMMAND = [
  "set -eu",
  'fail() { echo "$1" >&2; exit 1; }',
  "app_root=/app",
  "if printenv LANDO_NEXTJS_APP_ROOT >/dev/null 2>&1; then app_root=$(printenv LANDO_NEXTJS_APP_ROOT); fi",
  'app_root=$(cd "$app_root" && pwd -P) || fail "Next.js scaffold requires an existing app root."',
  'lock_dir="$app_root/.lando-nextjs-scaffold-lock"',
  "lock_owned=0",
  "staging_root=",
  'cleanup() { if test -n "$staging_root"; then rm -rf -- "$staging_root"; fi; if test "$lock_owned" -eq 1; then rmdir -- "$lock_dir"; fi; }',
  "trap cleanup EXIT",
  "trap 'exit 1' HUP INT TERM",
  'mkdir -- "$lock_dir" 2>/dev/null || fail "Next.js scaffold cannot acquire $lock_dir; another invocation may be running. Wait for it to finish. If a previous invocation was interrupted, remove the empty lock directory yourself before retrying."',
  "lock_owned=1",
  'if test -e "$app_root/package.json" || test -L "$app_root/package.json"; then fail "Next.js scaffold refuses an existing package.json. Use lando npm install for an existing app."; fi',
  'staging_parent=$(printenv TMPDIR 2>/dev/null || true); if test -z "$staging_parent"; then staging_parent=/tmp; fi',
  "if printenv LANDO_NEXTJS_STAGING_ROOT >/dev/null 2>&1; then staging_parent=$(printenv LANDO_NEXTJS_STAGING_ROOT); fi",
  'staging_parent=$(cd "$staging_parent" && pwd -P) || fail "Next.js scaffold requires an existing temporary directory."',
  'case "$staging_parent/" in "$app_root/"*) fail "Next.js scaffold staging must be outside the app root. Set TMPDIR to a directory outside /app.";; esac',
  'staging_root=$(mktemp -d "$staging_parent/lando-nextjs.XXXXXX") || fail "Unable to create a Next.js scaffold staging directory."',
  'project="$staging_root/nextjs-app"',
  'if ! npx --yes create-next-app@16.4.0 "$project" --yes --skip-install --disable-git --use-npm --ts --eslint --no-tailwind --app --no-src-dir --import-alias "@/*" --no-react-compiler --empty; then fail "Next.js generation failed; app files were not changed. Check network access and rerun lando nextjs-scaffold."; fi',
  'test -f "$project/package.json" && test -d "$project/app" || fail "Next.js generation did not produce package.json and app/. App files were not changed."',
  "# Preflight every top-level publication target before copying anything.",
  'for source in "$project"/* "$project"/.[!.]* "$project"/..?*; do',
  '  if ! test -e "$source" && ! test -L "$source"; then continue; fi',
  '  entry=$(basename -- "$source")',
  '  case "$entry" in .git|node_modules) continue;; .lando.yml|vendor|tmp) fail "Next.js generator produced protected path $entry. App files were not changed.";; esac',
  '  target="$app_root/$entry"',
  '  if test -e "$target" || test -L "$target"; then fail "Next.js scaffold cannot publish $entry because $target already exists. Move the conflicting path yourself or use a fresh app directory, then rerun lando nextjs-scaffold. App files were not changed."; fi',
  "done",
  'for source in "$project"/* "$project"/.[!.]* "$project"/..?*; do',
  '  if ! test -e "$source" && ! test -L "$source"; then continue; fi',
  '  entry=$(basename -- "$source")',
  '  case "$entry" in .git|node_modules) continue;; esac',
  '  target="$app_root/$entry"',
  '  if test -e "$target" || test -L "$target"; then fail "Next.js scaffold stopped because $target appeared during publication. Partial sources were retained; inspect the conflicting path before retrying. Dependency installation was not started."; fi',
  '  if ! cp -R -T --no-clobber -- "$source" "$target"; then fail "Next.js scaffold copy failed at $entry; partial sources were retained. Inspect the app directory before retrying; no existing files were overwritten."; fi',
  "done",
  "# Install only in the real app root, preserving the node_modules volume.",
  'cd "$app_root"',
  'if ! npm install; then fail "Next.js sources were created, but dependency installation failed. Fix the npm error and rerun lando npm install."; fi',
  'echo "Next.js sources and dependencies are ready. Run lando next dev."',
].join("\n");
