import { ROUTER_LAST_RESORT_HTTPS_PORT, ROUTER_LAST_RESORT_HTTP_PORT } from "@lando/sdk/schema";

export const TRAEFIK_HTTP_PORT = ROUTER_LAST_RESORT_HTTP_PORT;
export const TRAEFIK_HTTPS_PORT = ROUTER_LAST_RESORT_HTTPS_PORT;
