import { Schema } from "effect";

import { FileSyncMode as FileSyncModeSchema } from "./file-sync.ts";
import { AppRef } from "./networking.ts";
import { AbsolutePath, PortablePath, ServiceName } from "./primitives.ts";

// FileSyncEngine - pluggable file-sync engine contract.

/**
 * Opaque, engine-issued handle to a created file-sync session. Stable
 * across pause/resume cycles. Engines own the encoding; the planner
 * never inspects the contents.
 */
export const FileSyncSessionRef = Schema.String.pipe(Schema.brand("FileSyncSessionRef"));
export type FileSyncSessionRef = typeof FileSyncSessionRef.Type;

/**
 * Engine capability matrix declared at registration time. Used by
 * `AppPlanner` to verify a `MountPlan`'s requested `mode` is supported
 * before a session is created.
 */
export const FileSyncEngineCapabilities = Schema.Struct({
  /** Supported sync modes; at least one MUST be declared. */
  modes: Schema.Array(FileSyncModeSchema).pipe(Schema.minItems(1)),
  /**
   * `auto`: engine deploys its in-container agent on first session start
   * via `RuntimeProvider.run`. `preinstalled`: engine assumes the agent
   * binary is already present in the target image. `none`: engine does
   * not require a per-target agent (passthrough / no-op engines).
   */
  remoteAgentDeployment: Schema.Literal("auto", "preinstalled", "none"),
  /** True iff the engine honors `FileSyncSessionSpec.excludes`. */
  exclusionPatterns: Schema.Boolean,
  /** True iff the engine emits drift / conflict events. */
  conflictReporting: Schema.Boolean,
  /** True iff the engine emits progress events for the four standard phases. */
  progressReporting: Schema.Boolean,
});
export type FileSyncEngineCapabilities = Schema.Schema.Type<typeof FileSyncEngineCapabilities>;

/**
 * Setup options for `FileSyncEngine.setup`. Mirrors the
 * `ProviderSetupOptions` shape so `lando setup` can pass through the same
 * `--force` flag.
 */
export const FileSyncSetupOptions = Schema.Struct({
  /** Re-run setup even if the engine reports `isAvailable: true`. */
  force: Schema.Boolean,
});
export type FileSyncSetupOptions = Schema.Schema.Type<typeof FileSyncSetupOptions>;

/**
 * Target the engine should sync into. `volume` is a provider-owned named
 * volume; `service` is a path inside another service container.
 */
export const FileSyncSessionTarget = Schema.Union(
  Schema.TaggedStruct("volume", {
    /** Provider-owned volume name. */
    name: Schema.String,
    /** Container-side mount path. */
    path: PortablePath,
  }),
  Schema.TaggedStruct("service", {
    /** Target service name. */
    service: ServiceName,
    /** Container-side path inside the target service. */
    path: PortablePath,
  }),
);
export type FileSyncSessionTarget = Schema.Schema.Type<typeof FileSyncSessionTarget>;

/**
 * Per-mount session creation spec. Generated by `AppPlanner` from
 * accelerated `MountPlan` entries.
 */
export const FileSyncSessionSpec = Schema.Struct({
  /** Owning app reference. */
  app: AppRef,
  /** Service whose mount this session backs. */
  service: ServiceName,
  /** Stable mount key inside the owning service. */
  mountKey: Schema.String,
  /** Host-side source root (after symlink resolution). */
  source: AbsolutePath,
  /** Where the synced bytes should appear. */
  target: FileSyncSessionTarget,
  /** Requested sync mode; engines MAY upgrade per `FileSyncDriftError.suggestedMode`. */
  mode: FileSyncModeSchema,
  /** Engine-honored exclude patterns from the service config. */
  excludes: Schema.Array(Schema.String),
  /** Optional ownership / mode overrides applied on the target side. */
  permissions: Schema.optional(
    Schema.Struct({
      owner: Schema.optional(Schema.String),
      mode: Schema.optional(Schema.String),
    }),
  ),
});
export type FileSyncSessionSpec = Schema.Schema.Type<typeof FileSyncSessionSpec>;

/** Lifecycle status surfaced by `FileSyncEngine.listSessions`. */
export const FileSyncSessionStatus = Schema.Literal("running", "paused", "draining", "errored");
export type FileSyncSessionStatus = typeof FileSyncSessionStatus.Type;

/**
 * Diagnostic snapshot of a single running session.
 */
export const FileSyncSessionInfo = Schema.Struct({
  ref: FileSyncSessionRef,
  app: AppRef,
  service: ServiceName,
  mountKey: Schema.String,
  status: FileSyncSessionStatus,
  lastUpdatedAt: Schema.DateTimeUtc,
  /** Optional structured detail (drift count, last error message, etc.). */
  detail: Schema.optional(Schema.String),
});
export type FileSyncSessionInfo = Schema.Schema.Type<typeof FileSyncSessionInfo>;

/** Filter for `FileSyncEngine.listSessions`; absent fields match everything. */
export const FileSyncSessionFilter = Schema.Struct({
  app: Schema.optional(AppRef),
  service: Schema.optional(ServiceName),
  mountKey: Schema.optional(Schema.String),
});
export type FileSyncSessionFilter = Schema.Schema.Type<typeof FileSyncSessionFilter>;

/**
 * One chunk in the `FileSyncEngine.streamEvents` stream. Engines MUST
 * emit `progress` chunks for at least the four standard phases when
 * `progressReporting: true`, and `conflict` chunks when
 * `conflictReporting: true`. `info` is a free-form diagnostic chunk for
 * the active `Logger`.
 */
export const FileSyncEventChunk = Schema.Union(
  Schema.TaggedStruct("progress", {
    sessionRef: FileSyncSessionRef,
    phase: Schema.Literal("initial-scan", "staging", "transitioning", "watching"),
    /** 0..1 inclusive when known; otherwise omit. */
    completed: Schema.optional(Schema.Number.pipe(Schema.between(0, 1))),
    message: Schema.optional(Schema.String),
  }),
  Schema.TaggedStruct("conflict", {
    sessionRef: FileSyncSessionRef,
    conflictedPaths: Schema.Array(Schema.String),
  }),
  Schema.TaggedStruct("info", {
    sessionRef: FileSyncSessionRef,
    message: Schema.String,
  }),
);
export type FileSyncEventChunk = Schema.Schema.Type<typeof FileSyncEventChunk>;
