import { Either, JSONSchema, Schema } from "effect";
import * as AST from "effect/SchemaAST";

import {
  CleanupProps,
  GuideProps,
  HiddenProps,
  InlineProps,
  InspectProps,
  MatcherSchema,
  RunProps,
  ScenarioProps,
  SkipProps,
  StepProps,
  TabProps,
  TabsProps,
  UseFixtureProps,
  VariableProps,
  VerifyProps,
} from "../docs/components/props.ts";
import { GuideFrontmatter } from "../docs/guide-frontmatter.ts";
import { PublicTranscript, Transcript } from "../docs/transcript.ts";
import {
  LandofileExpressionEvalError,
  LandofileExpressionForbiddenError,
  LandofileExpressionParseError,
} from "../errors/index.ts";
import { DownloadProgressEvent, PostDownloadEvent, PreDownloadEvent } from "../events/download.ts";
import { PostHttpCallEvent, PreHttpCallEvent } from "../events/http-call.ts";
import {
  BeforeExitEvent,
  CliCommandErrorEvent,
  CliCommandInitEvent,
  CliCommandRunEvent,
  DeprecationUsedEvent,
  LandoEvent,
  ManagedFileConflictDetectedEvent,
  ManagedFileSkippedEvent,
  MessageErrorEvent,
  MessageInfoEvent,
  MessageWarnEvent,
  PaintBannerEvent,
  PostAppStartEvent,
  PostAppStopEvent,
  PostBootstrapEvent,
  PostBuildEvent,
  PostDatasetApplyEvent,
  PostDatasetCaptureEvent,
  PostDatasetFetchEvent,
  PostDatasetSendEvent,
  PostDestroyEvent,
  PostGlobalStartEvent,
  PostGlobalStopEvent,
  PostInitEvent,
  PostManagedFileWriteEvent,
  PostProviderApplyEvent,
  PostProviderExecEvent,
  PostPullEvent,
  PostPushEvent,
  PostRebuildEvent,
  PostServiceStartEvent,
  PostServiceStopEvent,
  PostStartEvent,
  PostStopEvent,
  PostTunnelStartEvent,
  PostTunnelStopEvent,
  PreAppStartEvent,
  PreAppStopEvent,
  PreBootstrapEvent,
  PreBuildEvent,
  PreDatasetApplyEvent,
  PreDatasetCaptureEvent,
  PreDatasetFetchEvent,
  PreDatasetSendEvent,
  PreDestroyEvent,
  PreGlobalStartEvent,
  PreGlobalStopEvent,
  PreInitEvent,
  PreManagedFileWriteEvent,
  PreProviderApplyEvent,
  PreProviderExecEvent,
  PrePullEvent,
  PrePushEvent,
  PreRebuildEvent,
  PreServiceStartEvent,
  PreServiceStopEvent,
  PreStartEvent,
  PreStopEvent,
  PreTunnelStartEvent,
  PreTunnelStopEvent,
  ReadyEvent,
  TaskCompleteEvent,
  TaskDetailCollapseEvent,
  TaskDetailEvent,
  TaskDetailExpandEvent,
  TaskFailEvent,
  TaskStartEvent,
  TaskTreeCompleteEvent,
  TaskTreeStartEvent,
  TunnelReadyEvent,
  TunnelStatusEvent,
} from "../events/index.ts";
import {
  AccessExpressionNode,
  ArrayLiteralExpressionNode,
  CallExpressionNode,
  ConditionalExpressionNode,
  ExpressionNode,
  ExpressionTemplate,
  LiteralExpressionNode,
  ObjectLiteralExpressionNode,
  PathExpressionNode,
} from "../expressions/ast.ts";
import { AppPlan, FileSyncPlan, ServicePlan } from "./app-plan.ts";
import { ArtifactBuildSpec, ArtifactRef, BuildScript } from "./artifacts.ts";
import { BuildPlan, BuildStep } from "./build-plan.ts";
import { ConfigLintResult, ConfigLintViolation } from "./config-lint.ts";
import {
  GlobalConfig,
  NetworkCaConfig,
  NetworkConfig,
  NetworkProxyConfig,
  TelemetryConfig,
} from "./config.ts";
import {
  ArchiveFormat,
  DataEndpoint,
  DataTransferProgress,
  DataTransferResult,
  DataTransferSpec,
  PrunePolicy,
  ServiceCopyInSpec,
  ServiceCopyOutSpec,
  SnapshotFilter,
  SnapshotHandle,
  SnapshotInfo,
  VolumeFilter,
  VolumeInfo,
  VolumeRef,
  VolumeRestoreSpec,
  VolumeSnapshotRef,
  VolumeSnapshotSpec,
} from "./data-transfer.ts";
import {
  DeprecationNotice,
  DeprecationNoticeJsonShape,
  DeprecationUse,
  getSchemaDeprecation,
} from "./deprecation.ts";
import {
  ArtifactManifestEntry,
  DownloadRequest,
  DownloadResult,
  DownloaderCapabilities,
} from "./downloader.ts";
import {
  FileSyncEngineCapabilities,
  FileSyncEventChunk,
  FileSyncSessionInfo,
  FileSyncSessionSpec,
} from "./file-sync-engine.ts";
import {
  HttpClientCapabilities,
  HttpRequest,
  HttpResponse,
  HttpStreamResponse,
  HttpUploadRequest,
} from "./http-client.ts";
import { getJsonSchemaWithDeprecations, renderSchemaReferenceMarkdown } from "./json-schema-deprecations.ts";
import {
  EndpointInput,
  HealthcheckInput,
  IncludeEntry,
  LandofileShape,
  RouteInput,
  ServiceConfig,
  ToolingArgShape,
  ToolingFlagShape,
  ToolingTaskShape,
  ToolingVar,
} from "./landofile.ts";
import { CommandResultEnvelope, CommandResultFormat, CommandWarning, StreamFrame } from "./machine-output.ts";
import { ManagedFile, ManagedFileInfo, ManagedFilePlan, ManagedFileResult } from "./managed-file.ts";
import { McpCatalog, McpCatalogOptions, McpServeOptions, McpToolDescriptor } from "./mcp.ts";
import { AppMountPlan, DataStoreMountPlan, DataStorePlan, MountPlan, StorageScope } from "./mounts.ts";
import {
  AppRef,
  CertificatePlan,
  DependencyPlan,
  EndpointPlan,
  HealthcheckPlan,
  HostAliasPlan,
  IsolateMode,
  NetworkPlan,
  NetworkingPlan,
  PerAppBridgePlan,
  ProviderCapabilities,
  RoutePlan,
  RouteRef,
  SharedNetworkMembershipPlan,
} from "./networking.ts";
import { PluginTrustState } from "./plugin-trust.ts";
import {
  ContributionRef,
  EmbeddingPluginPolicy,
  GlobalServiceContribution,
  InteractionServiceContribution,
  PluginContribution,
  PluginManifest,
  PluginSetupContribution,
  PluginSetupFlagContribution,
} from "./plugin.ts";
import {
  AppId,
  BootstrapLevel,
  CommandSpec,
  HostArchitecture,
  HostPlatform,
  PlanMetadata,
  PluginName,
  PortablePath,
  ProviderExtensionConfig,
  ProviderId,
  ServiceName,
} from "./primitives.ts";
import { PromptSpec } from "./prompt.ts";
import {
  RecipeChoicesFrom,
  RecipeManifest,
  RecipeRegistryResolution,
  RecipeRegistryResponse,
} from "./recipe.ts";
import {
  DatasetApplyOptions,
  DatasetApplyResult,
  DatasetArtifactFormat,
  DatasetBinding,
  DatasetCapabilities,
  DatasetCaptureOptions,
  DatasetContext,
  DatasetKind,
  RemoteCapabilities,
  RemoteConfig,
  RemoteEnvId,
  RemoteEnvironment,
  RemoteFetchOptions,
  RemoteLocator,
  RemoteSendOptions,
  RemoteTestResult,
  SyncResult,
} from "./remote-sync.ts";
import { ServiceInfo } from "./service-info.ts";
import { TemplateRenderContext } from "./template.ts";
import {
  TunnelCapabilities,
  TunnelSession,
  TunnelSessionFilter,
  TunnelStartRequest,
  TunnelStatus,
  TunnelStatusRequest,
  TunnelStopRequest,
  TunnelTarget,
} from "./tunnel.ts";
import {
  UpdateChannel,
  UpdateManifestBinaries,
  UpdateManifestBinary,
  UpdateManifestChecksums,
  UpdateManifestHttpsUrl,
  UpdateManifestPlatform,
  UpdateManifestSchema,
  UpdateManifestSemver,
  UpdateManifestSha256,
} from "./update-manifest.ts";

export {
  assertJsonSchemaDeprecationsValid,
  getJsonSchemaWithDeprecations,
  renderSchemaReferenceMarkdown,
  schemaDeprecationsFromJsonSchema,
  withSchemaDeprecations,
} from "./json-schema-deprecations.ts";

type JsonObject = Record<string, unknown>;

export type PublicSchema = Schema.Schema.AnyNoContext;

export type PublicSchemaMetadata = {
  readonly id: JsonSchemaName;
  readonly title: string;
  readonly description: string;
  readonly packageExport: `@lando/sdk/schema#${JsonSchemaName}`;
  readonly jsonSchemaPath: `dist/schemas/${string}.json`;
  readonly docsPath: `docs/reference/schemas/${string}.mdx`;
  readonly deprecated: boolean;
};

export type PublicSchemaReferencePage = {
  readonly id: JsonSchemaName;
  readonly docsPath: PublicSchemaMetadata["docsPath"];
  readonly content: string;
};

const rawPublicSchemaRegistry = {
  DeprecationNotice,
  DeprecationUse,
  LandofileExpressionParseError,
  LandofileExpressionForbiddenError,
  LandofileExpressionEvalError,
  GuideFrontmatter,
  GuideProps,
  ScenarioProps,
  StepProps,
  RunProps,
  VerifyProps,
  CleanupProps,
  VariableProps,
  HiddenProps,
  InspectProps,
  TabsProps,
  TabProps,
  InlineProps,
  SkipProps,
  UseFixtureProps,
  MatcherSchema,
  Transcript,
  PublicTranscript,
  ExpressionNode,
  ExpressionTemplate,
  BootstrapLevel,
  HostArchitecture,
  AppRef,
  ArtifactRef,
  ArtifactBuildSpec,
  ArtifactManifestEntry,
  BuildScript,
  BuildPlan,
  BuildStep,
  AppPlan,
  ServicePlan,
  AppMountPlan,
  MountPlan,
  DataStorePlan,
  DataStoreMountPlan,
  StorageScope,
  EndpointPlan,
  RouteRef,
  RoutePlan,
  HealthcheckPlan,
  CertificatePlan,
  HostAliasPlan,
  DependencyPlan,
  NetworkPlan,
  PerAppBridgePlan,
  SharedNetworkMembershipPlan,
  NetworkingPlan,
  IsolateMode,
  ProviderCapabilities,
  LandofileShape,
  ServiceConfig,
  EndpointInput,
  RouteInput,
  HealthcheckInput,
  ToolingVar,
  ToolingFlagShape,
  ToolingArgShape,
  ToolingTaskShape,
  IncludeEntry,
  TelemetryConfig,
  NetworkProxyConfig,
  NetworkCaConfig,
  NetworkConfig,
  GlobalConfig,
  ConfigLintViolation,
  ConfigLintResult,
  DownloadRequest,
  DownloadResult,
  DownloaderCapabilities,
  ArchiveFormat,
  DataEndpoint,
  VolumeRef,
  VolumeInfo,
  VolumeFilter,
  VolumeSnapshotSpec,
  VolumeSnapshotRef,
  VolumeRestoreSpec,
  ServiceCopyInSpec,
  ServiceCopyOutSpec,
  DataTransferSpec,
  DataTransferResult,
  DataTransferProgress,
  SnapshotHandle,
  SnapshotInfo,
  SnapshotFilter,
  PrunePolicy,
  RemoteCapabilities,
  RemoteConfig,
  RemoteEnvironment,
  RemoteEnvId,
  RemoteLocator,
  RemoteFetchOptions,
  RemoteSendOptions,
  RemoteTestResult,
  DatasetBinding,
  DatasetKind,
  DatasetCapabilities,
  DatasetArtifactFormat,
  DatasetContext,
  DatasetCaptureOptions,
  DatasetApplyOptions,
  DatasetApplyResult,
  SyncResult,
  TunnelCapabilities,
  TunnelTarget,
  TunnelStartRequest,
  TunnelStopRequest,
  TunnelStatusRequest,
  TunnelSession,
  TunnelStatus,
  TunnelSessionFilter,
  ManagedFile,
  ManagedFileInfo,
  ManagedFilePlan,
  ManagedFileResult,
  McpToolDescriptor,
  McpCatalog,
  McpCatalogOptions,
  McpServeOptions,
  AppId,
  ServiceName,
  ProviderId,
  PluginName,
  PortablePath,
  CommandSpec,
  PlanMetadata,
  ProviderExtensionConfig,
  HostPlatform,
  ServiceInfo,
  EmbeddingPluginPolicy,
  ContributionRef,
  PluginSetupFlagContribution,
  PluginSetupContribution,
  PluginContribution,
  PluginManifest,
  PluginTrustState,
  GlobalServiceContribution,
  FileSyncEngineCapabilities,
  FileSyncSessionSpec,
  FileSyncSessionInfo,
  FileSyncEventChunk,
  FileSyncPlan,
  RecipeChoicesFrom,
  RecipeManifest,
  RecipeRegistryResolution,
  RecipeRegistryResponse,
  TemplateRenderContext,
  UpdateChannel,
  UpdateManifestPlatform,
  UpdateManifestHttpsUrl,
  UpdateManifestSemver,
  UpdateManifestSha256,
  UpdateManifestBinary,
  UpdateManifestBinaries,
  UpdateManifestChecksums,
  UpdateManifestSchema,
  LandoEvent,
  PreBootstrapEvent,
  PostBootstrapEvent,
  ReadyEvent,
  BeforeExitEvent,
  PreInitEvent,
  PostInitEvent,
  PreStartEvent,
  PostStartEvent,
  PreStopEvent,
  PostStopEvent,
  PreRebuildEvent,
  PostRebuildEvent,
  PreDestroyEvent,
  PostDestroyEvent,
  PreGlobalStartEvent,
  PostGlobalStartEvent,
  PreGlobalStopEvent,
  PostGlobalStopEvent,
  PreAppStartEvent,
  PostAppStartEvent,
  PreAppStopEvent,
  PostAppStopEvent,
  PreServiceStartEvent,
  PostServiceStartEvent,
  PreServiceStopEvent,
  PostServiceStopEvent,
  PreBuildEvent,
  PostBuildEvent,
  PreManagedFileWriteEvent,
  PostManagedFileWriteEvent,
  ManagedFileConflictDetectedEvent,
  ManagedFileSkippedEvent,
  PreDownloadEvent,
  DownloadProgressEvent,
  PostDownloadEvent,
  PrePullEvent,
  PostPullEvent,
  PrePushEvent,
  PostPushEvent,
  PreDatasetFetchEvent,
  PostDatasetFetchEvent,
  PreDatasetApplyEvent,
  PostDatasetApplyEvent,
  PreDatasetCaptureEvent,
  PostDatasetCaptureEvent,
  PreDatasetSendEvent,
  PostDatasetSendEvent,
  PreTunnelStartEvent,
  PostTunnelStartEvent,
  TunnelReadyEvent,
  PreTunnelStopEvent,
  PostTunnelStopEvent,
  TunnelStatusEvent,
  PreProviderApplyEvent,
  PostProviderApplyEvent,
  PreProviderExecEvent,
  PostProviderExecEvent,
  CliCommandInitEvent,
  CliCommandRunEvent,
  CliCommandErrorEvent,
  DeprecationUsedEvent,
  TaskTreeStartEvent,
  TaskStartEvent,
  TaskDetailEvent,
  TaskDetailExpandEvent,
  TaskDetailCollapseEvent,
  TaskCompleteEvent,
  TaskFailEvent,
  TaskTreeCompleteEvent,
  MessageInfoEvent,
  MessageWarnEvent,
  MessageErrorEvent,
  PaintBannerEvent,
  PromptSpec,
  InteractionServiceContribution,
  CommandResultFormat,
  CommandWarning,
  CommandResultEnvelope,
  StreamFrame,
  HttpClientCapabilities,
  HttpRequest,
  HttpResponse,
  HttpStreamResponse,
  HttpUploadRequest,
  PreHttpCallEvent,
  PostHttpCallEvent,
} as const;

const PUBLIC_SCHEMA_DESCRIPTIONS = {
  DeprecationNotice: "Public Lando schema contract for Deprecation Notice.",
  DeprecationUse: "Public Lando schema contract for Deprecation Use.",
  LandofileExpressionParseError: "Public Lando schema contract for Landofile Expression Parse Error.",
  LandofileExpressionForbiddenError: "Public Lando schema contract for Landofile Expression Forbidden Error.",
  LandofileExpressionEvalError: "Public Lando schema contract for Landofile Expression Eval Error.",
  GuideFrontmatter: "Public Lando schema contract for Guide Frontmatter.",
  GuideProps: "Public Lando schema contract for Guide Props.",
  ScenarioProps: "Public Lando schema contract for Scenario Props.",
  StepProps: "Public Lando schema contract for Step Props.",
  RunProps: "Public Lando schema contract for Run Props.",
  VerifyProps: "Public Lando schema contract for Verify Props.",
  CleanupProps: "Public Lando schema contract for Cleanup Props.",
  VariableProps: "Public Lando schema contract for Variable Props.",
  HiddenProps: "Public Lando schema contract for Hidden Props.",
  InspectProps: "Public Lando schema contract for Inspect Props.",
  TabsProps: "Public Lando schema contract for Tabs Props.",
  TabProps: "Public Lando schema contract for Tab Props.",
  InlineProps: "Public Lando schema contract for Inline Props.",
  SkipProps: "Public Lando schema contract for Skip Props.",
  UseFixtureProps: "Public Lando schema contract for Use Fixture Props.",
  MatcherSchema: "Public Lando schema contract for Matcher Schema.",
  Transcript: "Public Lando schema contract for Transcript.",
  PublicTranscript: "Public Lando schema contract for Public Transcript.",
  ExpressionNode: "Public Lando schema contract for Expression Node.",
  ExpressionTemplate: "Public Lando schema contract for Expression Template.",
  BootstrapLevel: "Public Lando schema contract for Bootstrap Level.",
  HostArchitecture: "Public Lando schema contract for Host Architecture.",
  AppRef: "Public Lando schema contract for App Ref.",
  ArtifactRef: "Public Lando schema contract for Artifact Ref.",
  ArtifactBuildSpec: "Public Lando schema contract for Artifact Build Spec.",
  ArtifactManifestEntry: "Public Lando schema contract for Artifact Manifest Entry.",
  BuildScript: "Public Lando schema contract for Build Script.",
  BuildPlan: "Public Lando schema contract for Build Plan.",
  BuildStep: "Public Lando schema contract for Build Step.",
  AppPlan: "Public Lando schema contract for App Plan.",
  ServicePlan: "Public Lando schema contract for Service Plan.",
  AppMountPlan: "Public Lando schema contract for App Mount Plan.",
  MountPlan: "Public Lando schema contract for Mount Plan.",
  DataStorePlan: "Public Lando schema contract for Data Store Plan.",
  DataStoreMountPlan: "Public Lando schema contract for Data Store Mount Plan.",
  StorageScope: "Public Lando schema contract for Storage Scope.",
  EndpointPlan: "Public Lando schema contract for Endpoint Plan.",
  RouteRef: "Public Lando schema contract for Route Ref.",
  RoutePlan: "Public Lando schema contract for Route Plan.",
  HealthcheckPlan: "Public Lando schema contract for Healthcheck Plan.",
  CertificatePlan: "Public Lando schema contract for Certificate Plan.",
  HostAliasPlan: "Public Lando schema contract for Host Alias Plan.",
  DependencyPlan: "Public Lando schema contract for Dependency Plan.",
  NetworkPlan: "Public Lando schema contract for Network Plan.",
  PerAppBridgePlan: "Public Lando schema contract for Per App Bridge Plan.",
  SharedNetworkMembershipPlan: "Public Lando schema contract for Shared Network Membership Plan.",
  NetworkingPlan: "Public Lando schema contract for Networking Plan.",
  IsolateMode: "Public Lando schema contract for Isolate Mode.",
  ProviderCapabilities: "Public Lando schema contract for Provider Capabilities.",
  LandofileShape: "Public Lando schema contract for Landofile Shape.",
  ServiceConfig: "Public Lando schema contract for Service Config.",
  EndpointInput: "Public Lando schema contract for Endpoint Input.",
  RouteInput: "Public Lando schema contract for Route Input.",
  HealthcheckInput: "Public Lando schema contract for Healthcheck Input.",
  ToolingVar: "Public Lando schema contract for Tooling Var.",
  ToolingFlagShape: "Public Lando schema contract for Tooling Flag Shape.",
  ToolingArgShape: "Public Lando schema contract for Tooling Arg Shape.",
  ToolingTaskShape: "Public Lando schema contract for Tooling Task Shape.",
  IncludeEntry: "Public Lando schema contract for Include Entry.",
  TelemetryConfig: "Public Lando schema contract for Telemetry Config.",
  NetworkProxyConfig: "Public Lando schema contract for Network Proxy Config.",
  NetworkCaConfig: "Public Lando schema contract for Network Ca Config.",
  NetworkConfig: "Public Lando schema contract for Network Config.",
  GlobalConfig: "Public Lando schema contract for Global Config.",
  ConfigLintViolation: "Public Lando schema contract for Config Lint Violation.",
  ConfigLintResult: "Public Lando schema contract for Config Lint Result.",
  DownloadRequest: "Public Lando schema contract for Download Request.",
  DownloadResult: "Public Lando schema contract for Download Result.",
  DownloaderCapabilities: "Public Lando schema contract for Downloader Capabilities.",
  ArchiveFormat: "Public Lando schema contract for Archive Format.",
  DataEndpoint: "Public Lando schema contract for Data Endpoint.",
  VolumeRef: "Public Lando schema contract for Volume Ref.",
  VolumeInfo: "Public Lando schema contract for Volume Info.",
  VolumeFilter: "Public Lando schema contract for Volume Filter.",
  VolumeSnapshotSpec: "Public Lando schema contract for Volume Snapshot Spec.",
  VolumeSnapshotRef: "Public Lando schema contract for Volume Snapshot Ref.",
  VolumeRestoreSpec: "Public Lando schema contract for Volume Restore Spec.",
  ServiceCopyInSpec: "Public Lando schema contract for Service Copy In Spec.",
  ServiceCopyOutSpec: "Public Lando schema contract for Service Copy Out Spec.",
  DataTransferSpec: "Public Lando schema contract for Data Transfer Spec.",
  DataTransferResult: "Public Lando schema contract for Data Transfer Result.",
  DataTransferProgress: "Public Lando schema contract for Data Transfer Progress.",
  SnapshotHandle: "Public Lando schema contract for Snapshot Handle.",
  SnapshotInfo: "Public Lando schema contract for Snapshot Info.",
  SnapshotFilter: "Public Lando schema contract for Snapshot Filter.",
  PrunePolicy: "Public Lando schema contract for Prune Policy.",
  RemoteCapabilities: "Public Lando schema contract for Remote Capabilities.",
  RemoteConfig: "Public Lando schema contract for Remote Config.",
  RemoteEnvironment: "Public Lando schema contract for Remote Environment.",
  RemoteEnvId: "Public Lando schema contract for Remote Env Id.",
  RemoteLocator: "Public Lando schema contract for Remote Locator.",
  RemoteFetchOptions: "Public Lando schema contract for Remote Fetch Options.",
  RemoteSendOptions: "Public Lando schema contract for Remote Send Options.",
  RemoteTestResult: "Public Lando schema contract for Remote Test Result.",
  DatasetBinding: "Public Lando schema contract for Dataset Binding.",
  DatasetKind: "Public Lando schema contract for Dataset Kind.",
  DatasetCapabilities: "Public Lando schema contract for Dataset Capabilities.",
  DatasetArtifactFormat: "Public Lando schema contract for Dataset Artifact Format.",
  DatasetContext: "Public Lando schema contract for Dataset Context.",
  DatasetCaptureOptions: "Public Lando schema contract for Dataset Capture Options.",
  DatasetApplyOptions: "Public Lando schema contract for Dataset Apply Options.",
  DatasetApplyResult: "Public Lando schema contract for Dataset Apply Result.",
  SyncResult: "Public Lando schema contract for Sync Result.",
  TunnelCapabilities: "Public Lando schema contract for Tunnel Capabilities.",
  TunnelTarget: "Public Lando schema contract for Tunnel Target.",
  TunnelStartRequest: "Public Lando schema contract for Tunnel Start Request.",
  TunnelStopRequest: "Public Lando schema contract for Tunnel Stop Request.",
  TunnelStatusRequest: "Public Lando schema contract for Tunnel Status Request.",
  TunnelSession: "Public Lando schema contract for Tunnel Session.",
  TunnelStatus: "Public Lando schema contract for Tunnel Status.",
  TunnelSessionFilter: "Public Lando schema contract for Tunnel Session Filter.",
  ManagedFile: "Public Lando schema contract for Managed File.",
  ManagedFileInfo: "Public Lando schema contract for Managed File Info.",
  ManagedFilePlan: "Public Lando schema contract for Managed File Plan.",
  ManagedFileResult: "Public Lando schema contract for Managed File Result.",
  McpToolDescriptor: "Public Lando schema contract for MCP Tool Descriptor.",
  McpCatalog: "Public Lando schema contract for MCP Catalog.",
  McpCatalogOptions: "Public Lando schema contract for MCP Catalog Options.",
  McpServeOptions: "Public Lando schema contract for MCP Serve Options.",
  AppId: "Public Lando schema contract for App Id.",
  ServiceName: "Public Lando schema contract for Service Name.",
  ProviderId: "Public Lando schema contract for Provider Id.",
  PluginName: "Public Lando schema contract for Plugin Name.",
  PortablePath: "Public Lando schema contract for Portable Path.",
  CommandSpec: "Public Lando schema contract for Command Spec.",
  PlanMetadata: "Public Lando schema contract for Plan Metadata.",
  ProviderExtensionConfig: "Public Lando schema contract for Provider Extension Config.",
  HostPlatform: "Public Lando schema contract for Host Platform.",
  ServiceInfo: "Public Lando schema contract for Service Info.",
  EmbeddingPluginPolicy: "Public Lando schema contract for Embedding Plugin Policy.",
  ContributionRef: "Public Lando schema contract for Contribution Ref.",
  PluginSetupFlagContribution: "Public Lando schema contract for Plugin Setup Flag Contribution.",
  PluginSetupContribution: "Public Lando schema contract for Plugin Setup Contribution.",
  PluginContribution: "Public Lando schema contract for Plugin Contribution.",
  PluginManifest: "Public Lando schema contract for Plugin Manifest.",
  PluginTrustState: "Public Lando schema contract for Plugin Trust State.",
  GlobalServiceContribution: "Public Lando schema contract for Global Service Contribution.",
  FileSyncEngineCapabilities: "Public Lando schema contract for File Sync Engine Capabilities.",
  FileSyncSessionSpec: "Public Lando schema contract for File Sync Session Spec.",
  FileSyncSessionInfo: "Public Lando schema contract for File Sync Session Info.",
  FileSyncEventChunk: "Public Lando schema contract for File Sync Event Chunk.",
  FileSyncPlan: "Public Lando schema contract for File Sync Plan.",
  RecipeChoicesFrom: "Public Lando schema contract for Recipe Choices From.",
  RecipeManifest: "Public Lando schema contract for Recipe Manifest.",
  RecipeRegistryResolution: "Public Lando schema contract for Recipe Registry Resolution.",
  RecipeRegistryResponse: "Public Lando schema contract for Recipe Registry Response.",
  TemplateRenderContext: "Public Lando schema contract for Template Render Context.",
  UpdateChannel: "Public Lando schema contract for Update Channel.",
  UpdateManifestPlatform: "Public Lando schema contract for Update Manifest Platform.",
  UpdateManifestHttpsUrl: "Public Lando schema contract for Update Manifest Https Url.",
  UpdateManifestSemver: "Public Lando schema contract for Update Manifest Semver.",
  UpdateManifestSha256: "Public Lando schema contract for Update Manifest Sha256.",
  UpdateManifestBinary: "Public Lando schema contract for Update Manifest Binary.",
  UpdateManifestBinaries: "Public Lando schema contract for Update Manifest Binaries.",
  UpdateManifestChecksums: "Public Lando schema contract for Update Manifest Checksums.",
  UpdateManifestSchema: "Public Lando schema contract for Update Manifest Schema.",
  LandoEvent: "Public Lando schema contract for Lando Event.",
  PreBootstrapEvent: "Public Lando schema contract for Pre Bootstrap Event.",
  PostBootstrapEvent: "Public Lando schema contract for Post Bootstrap Event.",
  ReadyEvent: "Public Lando schema contract for Ready Event.",
  BeforeExitEvent: "Public Lando schema contract for Before Exit Event.",
  PreInitEvent: "Public Lando schema contract for Pre Init Event.",
  PostInitEvent: "Public Lando schema contract for Post Init Event.",
  PreStartEvent: "Public Lando schema contract for Pre Start Event.",
  PostStartEvent: "Public Lando schema contract for Post Start Event.",
  PreStopEvent: "Public Lando schema contract for Pre Stop Event.",
  PostStopEvent: "Public Lando schema contract for Post Stop Event.",
  PreRebuildEvent: "Public Lando schema contract for Pre Rebuild Event.",
  PostRebuildEvent: "Public Lando schema contract for Post Rebuild Event.",
  PreDestroyEvent: "Public Lando schema contract for Pre Destroy Event.",
  PostDestroyEvent: "Public Lando schema contract for Post Destroy Event.",
  PreGlobalStartEvent: "Public Lando schema contract for Pre Global Start Event.",
  PostGlobalStartEvent: "Public Lando schema contract for Post Global Start Event.",
  PreGlobalStopEvent: "Public Lando schema contract for Pre Global Stop Event.",
  PostGlobalStopEvent: "Public Lando schema contract for Post Global Stop Event.",
  PreAppStartEvent: "Public Lando schema contract for Pre App Start Event.",
  PostAppStartEvent: "Public Lando schema contract for Post App Start Event.",
  PreAppStopEvent: "Public Lando schema contract for Pre App Stop Event.",
  PostAppStopEvent: "Public Lando schema contract for Post App Stop Event.",
  PreServiceStartEvent: "Public Lando schema contract for Pre Service Start Event.",
  PostServiceStartEvent: "Public Lando schema contract for Post Service Start Event.",
  PreServiceStopEvent: "Public Lando schema contract for Pre Service Stop Event.",
  PostServiceStopEvent: "Public Lando schema contract for Post Service Stop Event.",
  PreBuildEvent: "Public Lando schema contract for Pre Build Event.",
  PostBuildEvent: "Public Lando schema contract for Post Build Event.",
  PreManagedFileWriteEvent: "Public Lando schema contract for Pre Managed File Write Event.",
  PostManagedFileWriteEvent: "Public Lando schema contract for Post Managed File Write Event.",
  ManagedFileConflictDetectedEvent: "Public Lando schema contract for Managed File Conflict Detected Event.",
  ManagedFileSkippedEvent: "Public Lando schema contract for Managed File Skipped Event.",
  PreDownloadEvent: "Public Lando schema contract for Pre Download Event.",
  DownloadProgressEvent: "Public Lando schema contract for Download Progress Event.",
  PostDownloadEvent: "Public Lando schema contract for Post Download Event.",
  PrePullEvent: "Public Lando schema contract for Pre Pull Event.",
  PostPullEvent: "Public Lando schema contract for Post Pull Event.",
  PrePushEvent: "Public Lando schema contract for Pre Push Event.",
  PostPushEvent: "Public Lando schema contract for Post Push Event.",
  PreDatasetFetchEvent: "Public Lando schema contract for Pre Dataset Fetch Event.",
  PostDatasetFetchEvent: "Public Lando schema contract for Post Dataset Fetch Event.",
  PreDatasetApplyEvent: "Public Lando schema contract for Pre Dataset Apply Event.",
  PostDatasetApplyEvent: "Public Lando schema contract for Post Dataset Apply Event.",
  PreDatasetCaptureEvent: "Public Lando schema contract for Pre Dataset Capture Event.",
  PostDatasetCaptureEvent: "Public Lando schema contract for Post Dataset Capture Event.",
  PreDatasetSendEvent: "Public Lando schema contract for Pre Dataset Send Event.",
  PostDatasetSendEvent: "Public Lando schema contract for Post Dataset Send Event.",
  PreTunnelStartEvent: "Public Lando schema contract for Pre Tunnel Start Event.",
  PostTunnelStartEvent: "Public Lando schema contract for Post Tunnel Start Event.",
  TunnelReadyEvent: "Public Lando schema contract for Tunnel Ready Event.",
  PreTunnelStopEvent: "Public Lando schema contract for Pre Tunnel Stop Event.",
  PostTunnelStopEvent: "Public Lando schema contract for Post Tunnel Stop Event.",
  TunnelStatusEvent: "Public Lando schema contract for Tunnel Status Event.",
  PreProviderApplyEvent: "Public Lando schema contract for Pre Provider Apply Event.",
  PostProviderApplyEvent: "Public Lando schema contract for Post Provider Apply Event.",
  PreProviderExecEvent: "Public Lando schema contract for Pre Provider Exec Event.",
  PostProviderExecEvent: "Public Lando schema contract for Post Provider Exec Event.",
  CliCommandInitEvent: "Public Lando schema contract for Cli Command Init Event.",
  CliCommandRunEvent: "Public Lando schema contract for Cli Command Run Event.",
  CliCommandErrorEvent: "Public Lando schema contract for Cli Command Error Event.",
  DeprecationUsedEvent: "Public Lando schema contract for Deprecation Used Event.",
  TaskTreeStartEvent: "Public Lando schema contract for Task Tree Start Event.",
  TaskStartEvent: "Public Lando schema contract for Task Start Event.",
  TaskDetailEvent: "Public Lando schema contract for Task Detail Event.",
  TaskDetailExpandEvent: "Public Lando schema contract for Task Detail Expand Event.",
  TaskDetailCollapseEvent: "Public Lando schema contract for Task Detail Collapse Event.",
  TaskCompleteEvent: "Public Lando schema contract for Task Complete Event.",
  TaskFailEvent: "Public Lando schema contract for Task Fail Event.",
  TaskTreeCompleteEvent: "Public Lando schema contract for Task Tree Complete Event.",
  MessageInfoEvent: "Public Lando schema contract for Message Info Event.",
  MessageWarnEvent: "Public Lando schema contract for Message Warn Event.",
  MessageErrorEvent: "Public Lando schema contract for Message Error Event.",
  PaintBannerEvent: "Public Lando schema contract for Paint Banner Event.",
  PromptSpec: "Public Lando schema contract for Prompt Spec.",
  InteractionServiceContribution: "Public Lando schema contract for Interaction Service Contribution.",
  CommandResultFormat: "Public Lando schema contract for Command Result Format.",
  CommandWarning: "Public Lando schema contract for Command Warning.",
  CommandResultEnvelope: "Public Lando schema contract for Command Result Envelope.",
  StreamFrame: "Public Lando schema contract for Stream Frame.",
  HttpClientCapabilities: "Public Lando schema contract for Http Client Capabilities.",
  HttpRequest: "Public Lando schema contract for Http Request.",
  HttpResponse: "Public Lando schema contract for Http Response.",
  HttpStreamResponse: "Public Lando schema contract for Http Stream Response.",
  HttpUploadRequest: "Public Lando schema contract for Http Upload Request.",
  PreHttpCallEvent: "Public Lando schema contract for Pre Http Call Event.",
  PostHttpCallEvent: "Public Lando schema contract for Post Http Call Event.",
} as const satisfies Record<keyof typeof rawPublicSchemaRegistry, string>;

const titleFromSchemaName = (schemaName: string): string =>
  schemaName.replace(/([a-z0-9])([A-Z])/g, "$1 $2").replace(/([A-Z]+)([A-Z][a-z])/g, "$1 $2");

const annotatedPublicSchema = <Name extends keyof typeof rawPublicSchemaRegistry>(
  schemaName: Name,
  schema: (typeof rawPublicSchemaRegistry)[Name],
): (typeof rawPublicSchemaRegistry)[Name] =>
  schema.annotations({
    identifier: AST.getIdentifierAnnotation(schema.ast).pipe((option) =>
      option._tag === "Some" ? option.value : schemaName,
    ),
    title: AST.getTitleAnnotation(schema.ast).pipe((option) =>
      option._tag === "Some" ? option.value : titleFromSchemaName(schemaName),
    ),
    description: AST.getDescriptionAnnotation(schema.ast).pipe((option) =>
      option._tag === "Some" ? option.value : PUBLIC_SCHEMA_DESCRIPTIONS[schemaName],
    ),
  }) as (typeof rawPublicSchemaRegistry)[Name];

export const publicSchemaRegistry = Object.fromEntries(
  (Object.keys(rawPublicSchemaRegistry) as ReadonlyArray<keyof typeof rawPublicSchemaRegistry>).map(
    (schemaName) => [schemaName, annotatedPublicSchema(schemaName, rawPublicSchemaRegistry[schemaName])],
  ),
) as { readonly [K in keyof typeof rawPublicSchemaRegistry]: (typeof rawPublicSchemaRegistry)[K] };

export type JsonSchemaName = keyof typeof publicSchemaRegistry;
export const JSON_SCHEMA_NAMES = Object.keys(publicSchemaRegistry) as ReadonlyArray<JsonSchemaName>;

export const schemaArtifactFilename = (schemaName: JsonSchemaName): `${string}.json` =>
  `${schemaName
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/([A-Z]+)([A-Z][a-z])/g, "$1-$2")
    .toLowerCase()}.json`;

const BUILT_IN_SCHEMA_TITLES = new Set(["string", "number", "boolean", "bigint", "symbol", "object"]);

const BUILT_IN_DESCRIPTIONS = new Set([
  "a string",
  "a number",
  "a boolean",
  "a bigint",
  "a symbol",
  "an object in the TypeScript meaning, i.e. the `object` type",
]);

const schemaMetadata = (schemaName: JsonSchemaName): PublicSchemaMetadata => {
  const schema = publicSchemaRegistry[schemaName];
  const artifactFilename = schemaArtifactFilename(schemaName);
  const docsBasename = artifactFilename.replace(/\.json$/, "");
  const titleAnnotation = AST.getTitleAnnotation(schema.ast).pipe((option) =>
    option._tag === "Some" ? option.value : undefined,
  );
  const descriptionAnnotation = AST.getDescriptionAnnotation(schema.ast).pipe((option) =>
    option._tag === "Some" ? option.value : undefined,
  );
  return {
    id: schemaName,
    title:
      titleAnnotation !== undefined && !BUILT_IN_SCHEMA_TITLES.has(titleAnnotation)
        ? titleAnnotation
        : titleFromSchemaName(schemaName),
    description:
      descriptionAnnotation !== undefined && !BUILT_IN_DESCRIPTIONS.has(descriptionAnnotation)
        ? descriptionAnnotation
        : PUBLIC_SCHEMA_DESCRIPTIONS[schemaName],
    packageExport: `@lando/sdk/schema#${schemaName}`,
    jsonSchemaPath: `dist/schemas/${artifactFilename}`,
    docsPath: `docs/reference/schemas/${docsBasename}.mdx`,
    deprecated: getSchemaDeprecation(schema.ast) !== undefined,
  };
};

export const publicSchemaMetadataIndex = JSON_SCHEMA_NAMES.map(schemaMetadata);

const PUBLIC_FIELD_DESCRIPTION_EXEMPTIONS = new Set([
  "ArtifactManifestEntry.filename",
  "ArtifactManifestEntry.sha256",
  "ArtifactManifestEntry.sizeBytes",
  "ArtifactManifestEntry.url",
  "AppMountPlan.excludes",
  "AppMountPlan.includes",
  "AppMountPlan.readOnly",
  "AppMountPlan.realization",
  "AppMountPlan.source",
  "AppMountPlan.target",
  "AppPlan.extensions",
  "AppPlan.fileSync",
  "AppPlan.id",
  "AppPlan.metadata",
  "AppPlan.name",
  "AppPlan.networking",
  "AppPlan.networks",
  "AppPlan.provider",
  "AppPlan.requires",
  "AppPlan.root",
  "AppPlan.routes",
  "AppPlan.services",
  "AppPlan.slug",
  "AppPlan.stores",
  "AppRef.id",
  "AppRef.kind",
  "AppRef.root",
  "ArtifactBuildSpec.args",
  "ArtifactBuildSpec.contentHash",
  "ArtifactBuildSpec.context",
  "ArtifactBuildSpec.kind",
  "ArtifactBuildSpec.spec",
  "ArtifactBuildSpec.target",
  "ArtifactRef.digest",
  "ArtifactRef.kind",
  "ArtifactRef.ref",
  "BeforeExitEvent._tag",
  "BeforeExitEvent.exitCode",
  "BeforeExitEvent.timestamp",
  "BuildPlan.appId",
  "BuildPlan.metadata",
  "BuildPlan.steps",
  "BuildPlan.totalSteps",
  "BuildStep.artifact",
  "BuildStep.buildKey",
  "BuildStep.command",
  "BuildStep.dependsOn",
  "BuildStep.id",
  "BuildStep.kind",
  "BuildStep.phase",
  "BuildStep.service",
  "CertificatePlan.caId",
  "CertificatePlan.cn",
  "CertificatePlan.sans",
  "CliCommandErrorEvent._tag",
  "CliCommandErrorEvent.commandId",
  "CliCommandErrorEvent.message",
  "CliCommandErrorEvent.timestamp",
  "CliCommandInitEvent._tag",
  "CliCommandInitEvent.commandId",
  "CliCommandInitEvent.timestamp",
  "CliCommandRunEvent._tag",
  "CliCommandRunEvent.commandId",
  "CliCommandRunEvent.timestamp",
  "CommandResultEnvelope.apiVersion",
  "CommandResultEnvelope.command",
  "CommandResultEnvelope.deprecations",
  "CommandResultEnvelope.error",
  "CommandResultEnvelope.ok",
  "CommandResultEnvelope.result",
  "CommandResultEnvelope.warnings",
  "CommandWarning.code",
  "CommandWarning.message",
  "CommandWarning.remediation",
  "ConfigLintResult.app",
  "ConfigLintResult.file",
  "ConfigLintResult.valid",
  "ConfigLintResult.violations",
  "ConfigLintViolation.column",
  "ConfigLintViolation.line",
  "ConfigLintViolation.message",
  "ConfigLintViolation.path",
  "DownloadProgressEvent._tag",
  "DownloadProgressEvent.bytesDownloaded",
  "DownloadProgressEvent.callerId",
  "DownloadProgressEvent.eventName",
  "DownloadProgressEvent.timestamp",
  "DownloadProgressEvent.totalBytes",
  "DownloadProgressEvent.urlOrigin",
  "DownloadRequest.allowFileSource",
  "DownloadRequest.callerId",
  "DownloadRequest.destination",
  "DownloadRequest.destination.directory",
  "DownloadRequest.destination.filename",
  "DownloadRequest.destination.kind",
  "DownloadRequest.expectedSha256",
  "DownloadRequest.expectedSizeBytes",
  "DownloadRequest.offline",
  "DownloadRequest.redactionTokens",
  "DownloadRequest.url",
  "DownloadResult.fromCache",
  "DownloadResult.kind",
  "DownloadResult.path",
  "DownloadResult.sha256",
  "DownloadResult.sizeBytes",
  "DownloadResult.url",
  "DownloaderCapabilities.cacheAware",
  "DownloaderCapabilities.memoryDownload",
  "DownloaderCapabilities.mirror",
  "DownloaderCapabilities.offline",
  "DownloaderCapabilities.schemes",
  "HttpClientCapabilities.customCa",
  "HttpClientCapabilities.proxyAware",
  "HttpClientCapabilities.schemes",
  "HttpClientCapabilities.streaming",
  "HttpClientCapabilities.upload",
  "HttpRequest.allowFileSource",
  "HttpRequest.callerId",
  "HttpRequest.headers",
  "HttpRequest.method",
  "HttpRequest.offline",
  "HttpRequest.onBehalfOf",
  "HttpRequest.redactionTokens",
  "HttpRequest.redirect",
  "HttpRequest.timeoutMs",
  "HttpRequest.url",
  "HttpResponse.contentLength",
  "HttpResponse.headers",
  "HttpResponse.status",
  "HttpResponse.statusText",
  "HttpStreamResponse.headers",
  "HttpStreamResponse.status",
  "HttpStreamResponse.statusText",
  "HttpUploadRequest.callerId",
  "HttpUploadRequest.contentLength",
  "HttpUploadRequest.contentType",
  "HttpUploadRequest.headers",
  "HttpUploadRequest.method",
  "HttpUploadRequest.onBehalfOf",
  "HttpUploadRequest.redactionTokens",
  "HttpUploadRequest.source",
  "HttpUploadRequest.url",
  "PostHttpCallEvent._tag",
  "PostHttpCallEvent.callerId",
  "PostHttpCallEvent.durationMs",
  "PostHttpCallEvent.eventName",
  "PostHttpCallEvent.failureDetail",
  "PostHttpCallEvent.method",
  "PostHttpCallEvent.onBehalfOf",
  "PostHttpCallEvent.outcome",
  "PostHttpCallEvent.status",
  "PostHttpCallEvent.timestamp",
  "PostHttpCallEvent.urlOrigin",
  "PreHttpCallEvent._tag",
  "PreHttpCallEvent.callerId",
  "PreHttpCallEvent.eventName",
  "PreHttpCallEvent.method",
  "PreHttpCallEvent.onBehalfOf",
  "PreHttpCallEvent.timestamp",
  "PreHttpCallEvent.urlOrigin",
  "DataEndpoint._tag",
  "DataTransferProgress.digest",
  "DataTransferProgress.message",
  "DataTransferProgress.phase",
  "DataTransferProgress.totalBytes",
  "DataTransferProgress.transferredBytes",
  "DataTransferResult.accelerated",
  "DataTransferResult.digest",
  "DataTransferResult.sizeBytes",
  "DataTransferSpec.expectedDigest",
  "DataTransferSpec.from",
  "DataTransferSpec.overwrite",
  "DataTransferSpec.to",
  "DatasetApplyOptions.expectedDigest",
  "DatasetApplyOptions.force",
  "DatasetApplyOptions.snapshot",
  "DatasetApplyResult.changed",
  "DatasetApplyResult.localStore",
  "DatasetApplyResult.snapshot",
  "DatasetApplyResult.summary",
  "DatasetArtifactFormat.archiveFormat",
  "DatasetArtifactFormat.endpoint",
  "DatasetArtifactFormat.mediaType",
  "DatasetBinding.path",
  "DatasetBinding.service",
  "DatasetCapabilities.apply",
  "DatasetCapabilities.capture",
  "DatasetCapabilities.destructiveApply",
  "DatasetCapabilities.localStore",
  "DatasetCaptureOptions.format",
  "DatasetCaptureOptions.includeMetadata",
  "DatasetContext.app",
  "DatasetContext.binding",
  "DatasetContext.creds",
  "DatasetContext.plan",
  "DatasetContext.service",
  "DatasetKind",
  "PrunePolicy.filter",
  "PrunePolicy.keepLatest",
  "RemoteCapabilities.auth",
  "RemoteCapabilities.datasets",
  "RemoteCapabilities.environments",
  "RemoteCapabilities.protectedByDefault",
  "RemoteCapabilities.push",
  "RemoteCapabilities.tool",
  "RemoteConfig.source",
  "RemoteEnvironment.datasets",
  "RemoteEnvironment.default",
  "RemoteEnvironment.id",
  "RemoteEnvironment.label",
  "RemoteEnvironment.protected",
  "RemoteFetchOptions.expectedDigest",
  "RemoteFetchOptions.force",
  "RemoteLocator.dataset",
  "RemoteLocator.endpoint",
  "RemoteLocator.env",
  "RemoteLocator.metadata",
  "RemoteLocator.remote",
  "RemoteSendOptions.expectedDigest",
  "RemoteSendOptions.force",
  "RemoteSendOptions.protectedEnvConfirmed",
  "RemoteTestResult.env",
  "RemoteTestResult.message",
  "RemoteTestResult.ok",
  "RemoteTestResult.remediation",
  "ServiceCopyInSpec.format",
  "ServiceCopyInSpec.overwrite",
  "ServiceCopyInSpec.sourcePath",
  "ServiceCopyInSpec.targetPath",
  "ServiceCopyOutSpec.format",
  "ServiceCopyOutSpec.sourcePath",
  "SnapshotFilter.app",
  "SnapshotFilter.createdAfter",
  "SnapshotFilter.createdBefore",
  "SnapshotFilter.id",
  "SnapshotFilter.label",
  "SnapshotFilter.labels",
  "SnapshotFilter.scope",
  "SnapshotFilter.store",
  "SnapshotHandle.id",
  "SnapshotHandle.store",
  "SnapshotInfo.createdAt",
  "SnapshotInfo.digest",
  "SnapshotInfo.format",
  "SnapshotInfo.id",
  "SnapshotInfo.label",
  "SnapshotInfo.labels",
  "SnapshotInfo.native",
  "SnapshotInfo.sizeBytes",
  "SnapshotInfo.store",
  "SyncResult.artifacts",
  "SyncResult.changed",
  "SyncResult.datasets",
  "SyncResult.direction",
  "SyncResult.env",
  "SyncResult.remote",
  "SyncResult.snapshots",
  "SyncResult.summary",
  "TunnelCapabilities.basicAuth",
  "TunnelCapabilities.connectorBinary",
  "TunnelCapabilities.detached",
  "TunnelCapabilities.ephemeralUrls",
  "TunnelCapabilities.stableUrls",
  "TunnelSession.app",
  "TunnelSession.detached",
  "TunnelSession.id",
  "TunnelSession.metadata",
  "TunnelSession.provider",
  "TunnelSession.publicUrl",
  "TunnelSession.startedAt",
  "TunnelSession.status",
  "TunnelSession.target",
  "TunnelSession.updatedAt",
  "TunnelSessionFilter.app",
  "TunnelSessionFilter.detached",
  "TunnelSessionFilter.provider",
  "TunnelSessionFilter.sessionId",
  "TunnelSessionFilter.status",
  "TunnelSessionFilter.target",
  "TunnelStartRequest.app",
  "TunnelStartRequest.detached",
  "TunnelStartRequest.metadata",
  "TunnelStartRequest.plan",
  "TunnelStartRequest.provider",
  "TunnelStartRequest.target",
  "TunnelStatus",
  "TunnelStatusRequest.provider",
  "TunnelStatusRequest.sessionId",
  "TunnelStopRequest.force",
  "TunnelStopRequest.provider",
  "TunnelStopRequest.sessionId",
  "TunnelTarget._tag",
  "VolumeFilter.app",
  "VolumeFilter.labels",
  "VolumeFilter.scope",
  "VolumeFilter.store",
  "VolumeInfo.createdAt",
  "VolumeInfo.labels",
  "VolumeInfo.ref",
  "VolumeInfo.sizeBytes",
  "VolumeRef.app",
  "VolumeRef.scope",
  "VolumeRef.store",
  "VolumeRestoreSpec.overwrite",
  "VolumeRestoreSpec.snapshot",
  "VolumeRestoreSpec.target",
  "VolumeSnapshotRef.id",
  "VolumeSnapshotRef.provider",
  "VolumeSnapshotSpec.label",
  "VolumeSnapshotSpec.labels",
  "VolumeSnapshotSpec.snapshotId",
  "VolumeSnapshotSpec.volume",
  "ConfigLintViolation.suggestedFix",
  "DataStoreMountPlan.readOnly",
  "DataStoreMountPlan.store",
  "DataStoreMountPlan.target",
  "DataStorePlan.driver",
  "DataStorePlan.driverOpts",
  "DataStorePlan.key",
  "DataStorePlan.kind",
  "DataStorePlan.name",
  "DataStorePlan.scope",
  "DependencyPlan.condition",
  "DependencyPlan.service",
  "DeprecationNotice.docsUrl",
  "DeprecationNotice.note",
  "DeprecationNotice.removeIn",
  "DeprecationNotice.replacement",
  "DeprecationNotice.severity",
  "DeprecationNotice.ticket",
  "DeprecationUse.app",
  "DeprecationUse.callsite",
  "DeprecationUse.id",
  "DeprecationUse.kind",
  "DeprecationUse.plugin",
  "DeprecationUse.timestamp",
  "DeprecationUsedEvent._tag",
  "EndpointInput.name",
  "EndpointInput.port",
  "EndpointInput.protocol",
  "EndpointInput.socketPath",
  "EndpointPlan.name",
  "EndpointPlan.port",
  "EndpointPlan.protocol",
  "EndpointPlan.socketPath",
  "ExpressionNode.kind",
  "ExpressionTemplate.segments",
  "ExpressionTemplate.whole",
  "FileSyncEngineCapabilities.conflictReporting",
  "FileSyncEngineCapabilities.exclusionPatterns",
  "FileSyncEngineCapabilities.progressReporting",
  "FileSyncEngineCapabilities.remoteAgentDeployment",
  "FileSyncEventChunk._tag",
  "FileSyncEventChunk.sessionRef",
  "FileSyncPlan.engineId",
  "FileSyncPlan.session",
  "FileSyncSessionInfo.app",
  "FileSyncSessionInfo.detail",
  "FileSyncSessionInfo.lastUpdatedAt",
  "FileSyncSessionInfo.mountKey",
  "FileSyncSessionInfo.ref",
  "FileSyncSessionInfo.service",
  "FileSyncSessionInfo.status",
  "FileSyncSessionSpec.app",
  "FileSyncSessionSpec.excludes",
  "FileSyncSessionSpec.mode",
  "FileSyncSessionSpec.mountKey",
  "FileSyncSessionSpec.permissions",
  "FileSyncSessionSpec.service",
  "FileSyncSessionSpec.source",
  "FileSyncSessionSpec.target",
  "GlobalConfig.defaultProviderId",
  "GlobalConfig.network",
  "GlobalConfig.renderer",
  "GlobalConfig.systemPluginRoot",
  "GlobalConfig.telemetry",
  "GlobalConfig.userCacheRoot",
  "GlobalConfig.userConfRoot",
  "GlobalConfig.userDataRoot",
  "GlobalServiceContribution.commands",
  "GlobalServiceContribution.conflicts",
  "GlobalServiceContribution.deprecated",
  "GlobalServiceContribution.enabledByDefault",
  "GlobalServiceContribution.id",
  "GlobalServiceContribution.module",
  "GlobalServiceContribution.requires",
  "GlobalServiceContribution.summary",
  "GuideFrontmatter.axes",
  "GuideFrontmatter.defaultLayer",
  "GuideFrontmatter.deprecated",
  "GuideFrontmatter.platforms",
  "GuideFrontmatter.provider",
  "GuideFrontmatter.skip",
  "GuideFrontmatter.tabs",
  "GuideFrontmatter.tags",
  "GuideFrontmatter.variants",
  "HealthcheckInput.command",
  "HealthcheckInput.intervalSeconds",
  "HealthcheckInput.kind",
  "HealthcheckInput.port",
  "HealthcheckInput.retries",
  "HealthcheckInput.startPeriodSeconds",
  "HealthcheckInput.timeoutSeconds",
  "HealthcheckInput.url",
  "HealthcheckPlan.command",
  "HealthcheckPlan.intervalSeconds",
  "HealthcheckPlan.kind",
  "HealthcheckPlan.port",
  "HealthcheckPlan.retries",
  "HealthcheckPlan.startPeriodSeconds",
  "HealthcheckPlan.timeoutSeconds",
  "HealthcheckPlan.url",
  "HostAliasPlan.hostname",
  "HostAliasPlan.ip",
  "InlineProps.code",
  "InlineProps.lang",
  "InspectProps.events",
  "InspectProps.file",
  "InspectProps.json",
  "InspectProps.output",
  "InteractionServiceContribution.capabilities",
  "InteractionServiceContribution.deprecated",
  "InteractionServiceContribution.enabledByDefault",
  "InteractionServiceContribution.id",
  "InteractionServiceContribution.module",
  "InteractionServiceContribution.summary",
  "LandoEvent._tag",
  "LandofileExpressionEvalError._tag",
  "LandofileExpressionEvalError.cause",
  "LandofileExpressionEvalError.expression",
  "LandofileExpressionEvalError.filePath",
  "LandofileExpressionEvalError.message",
  "LandofileExpressionEvalError.remediation",
  "LandofileExpressionForbiddenError._tag",
  "LandofileExpressionForbiddenError.cause",
  "LandofileExpressionForbiddenError.filePath",
  "LandofileExpressionForbiddenError.helper",
  "LandofileExpressionForbiddenError.message",
  "LandofileExpressionForbiddenError.remediation",
  "LandofileExpressionParseError._tag",
  "LandofileExpressionParseError.cause",
  "LandofileExpressionParseError.column",
  "LandofileExpressionParseError.expression",
  "LandofileExpressionParseError.filePath",
  "LandofileExpressionParseError.line",
  "LandofileExpressionParseError.message",
  "LandofileExpressionParseError.remediation",
  "LandofileShape.configs",
  "LandofileShape.include",
  "LandofileShape.includes",
  "LandofileShape.name",
  "LandofileShape.networks",
  "LandofileShape.provider",
  "LandofileShape.providers",
  "LandofileShape.proxy",
  "LandofileShape.recipe",
  "LandofileShape.remotes",
  "LandofileShape.runtime",
  "LandofileShape.secrets",
  "LandofileShape.services",
  "LandofileShape.sshAgent",
  "LandofileShape.sync",
  "LandofileShape.tooling",
  "LandofileShape.toolingEngine",
  "LandofileShape.version",
  "LandofileShape.volumes",
  "ManagedFile.base",
  "ManagedFile.content",
  "ManagedFile.format",
  "ManagedFile.id",
  "ManagedFile.marker",
  "ManagedFile.mode",
  "ManagedFile.onConflict",
  "ManagedFile.owner",
  "ManagedFile.path",
  "ManagedFile.perms",
  "ManagedFileConflictDetectedEvent._tag",
  "ManagedFileConflictDetectedEvent.action",
  "ManagedFileConflictDetectedEvent.eventName",
  "ManagedFileConflictDetectedEvent.owner",
  "ManagedFileConflictDetectedEvent.path",
  "ManagedFileConflictDetectedEvent.summary",
  "ManagedFileConflictDetectedEvent.timestamp",
  "ManagedFileInfo.mode",
  "ManagedFileInfo.owner",
  "ManagedFileInfo.path",
  "ManagedFileInfo.state",
  "ManagedFilePlan.entries",
  "ManagedFileResult.entries",
  "ManagedFileSkippedEvent._tag",
  "ManagedFileSkippedEvent.action",
  "ManagedFileSkippedEvent.eventName",
  "ManagedFileSkippedEvent.owner",
  "ManagedFileSkippedEvent.path",
  "ManagedFileSkippedEvent.summary",
  "ManagedFileSkippedEvent.timestamp",
  "MessageErrorEvent._tag",
  "MessageErrorEvent.body",
  "MessageErrorEvent.remediation",
  "MessageErrorEvent.timestamp",
  "MessageInfoEvent._tag",
  "MessageInfoEvent.body",
  "MessageInfoEvent.timestamp",
  "MessageWarnEvent._tag",
  "MessageWarnEvent.body",
  "MessageWarnEvent.timestamp",
  "MountPlan.readOnly",
  "MountPlan.realization",
  "MountPlan.source",
  "MountPlan.target",
  "MountPlan.type",
  "NetworkCaConfig.certs",
  "NetworkCaConfig.trustHost",
  "NetworkConfig.ca",
  "NetworkConfig.proxy",
  "NetworkPlan.driver",
  "NetworkPlan.name",
  "NetworkPlan.shared",
  "NetworkProxyConfig.http",
  "NetworkProxyConfig.https",
  "NetworkProxyConfig.noProxy",
  "NetworkingPlan.perAppBridge",
  "NetworkingPlan.sharedNetworkMembership",
  "PaintBannerEvent._tag",
  "PaintBannerEvent.banner",
  "PaintBannerEvent.timestamp",
  "PerAppBridgePlan.driver",
  "PerAppBridgePlan.name",
  "PlanMetadata.resolvedAt",
  "PlanMetadata.runtime",
  "PlanMetadata.source",
  "PluginContribution.cas",
  "PluginContribution.commands",
  "PluginContribution.downloaders",
  "PluginContribution.fileSyncEngines",
  "PluginContribution.globalServices",
  "PluginContribution.httpClients",
  "PluginContribution.interactionServices",
  "PluginContribution.loggers",
  "PluginContribution.providers",
  "PluginContribution.proxies",
  "PluginContribution.datasets",
  "PluginContribution.remoteSources",
  "PluginContribution.renderers",
  "PluginContribution.appFeatures",
  "PluginContribution.serviceFeatures",
  "PluginContribution.serviceTypes",
  "PluginContribution.setup",
  "PluginContribution.templateEngines",
  "PluginManifest.api",
  "PluginManifest.bundled",
  "PluginManifest.contributes",
  "PluginManifest.deprecated",
  "PluginManifest.description",
  "PluginManifest.enabled",
  "PluginManifest.entry",
  "PluginManifest.name",
  "PluginManifest.requires",
  "PostDownloadEvent._tag",
  "PostDownloadEvent.bytesDownloaded",
  "PostDownloadEvent.callerId",
  "PostDownloadEvent.durationMs",
  "PostDownloadEvent.eventName",
  "PostDownloadEvent.failureDetail",
  "PostDownloadEvent.fromCache",
  "PostDownloadEvent.outcome",
  "PostDownloadEvent.sha256",
  "PostDownloadEvent.timestamp",
  "PostDownloadEvent.urlOrigin",
  "PostDatasetApplyEvent._tag",
  "PostDatasetApplyEvent.dataset",
  "PostDatasetApplyEvent.durationMs",
  "PostDatasetApplyEvent.env",
  "PostDatasetApplyEvent.eventName",
  "PostDatasetApplyEvent.failureDetail",
  "PostDatasetApplyEvent.outcome",
  "PostDatasetApplyEvent.remote",
  "PostDatasetApplyEvent.timestamp",
  "PostDatasetCaptureEvent._tag",
  "PostDatasetCaptureEvent.dataset",
  "PostDatasetCaptureEvent.durationMs",
  "PostDatasetCaptureEvent.env",
  "PostDatasetCaptureEvent.eventName",
  "PostDatasetCaptureEvent.failureDetail",
  "PostDatasetCaptureEvent.outcome",
  "PostDatasetCaptureEvent.remote",
  "PostDatasetCaptureEvent.timestamp",
  "PostDatasetFetchEvent._tag",
  "PostDatasetFetchEvent.dataset",
  "PostDatasetFetchEvent.durationMs",
  "PostDatasetFetchEvent.env",
  "PostDatasetFetchEvent.eventName",
  "PostDatasetFetchEvent.failureDetail",
  "PostDatasetFetchEvent.outcome",
  "PostDatasetFetchEvent.remote",
  "PostDatasetFetchEvent.timestamp",
  "PostDatasetSendEvent._tag",
  "PostDatasetSendEvent.dataset",
  "PostDatasetSendEvent.durationMs",
  "PostDatasetSendEvent.env",
  "PostDatasetSendEvent.eventName",
  "PostDatasetSendEvent.failureDetail",
  "PostDatasetSendEvent.outcome",
  "PostDatasetSendEvent.remote",
  "PostDatasetSendEvent.timestamp",
  "PostPullEvent._tag",
  "PostPullEvent.datasets",
  "PostPullEvent.durationMs",
  "PostPullEvent.env",
  "PostPullEvent.eventName",
  "PostPullEvent.failureDetail",
  "PostPullEvent.outcome",
  "PostPullEvent.remote",
  "PostPullEvent.timestamp",
  "PostPushEvent._tag",
  "PostPushEvent.datasets",
  "PostPushEvent.durationMs",
  "PostPushEvent.env",
  "PostPushEvent.eventName",
  "PostPushEvent.failureDetail",
  "PostPushEvent.outcome",
  "PostPushEvent.remote",
  "PostPushEvent.timestamp",
  "PluginManifest.version",
  "PluginSetupContribution.flags",
  "PluginSetupFlagContribution.deprecated",
  "PluginSetupFlagContribution.description",
  "PluginSetupFlagContribution.name",
  "PluginSetupFlagContribution.options",
  "PluginSetupFlagContribution.type",
  "PluginContribution.tunnelServices",
  "PluginTrustState.trustedAuthoringRoots",
  "PluginTrustState.trustedPlugins",
  "PostAppStartEvent._tag",
  "PostAppStartEvent.appRef",
  "PostAppStartEvent.eventName",
  "PostAppStartEvent.providerId",
  "PostAppStartEvent.timestamp",
  "PostAppStopEvent._tag",
  "PostAppStopEvent.appRef",
  "PostAppStopEvent.eventName",
  "PostAppStopEvent.providerId",
  "PostAppStopEvent.timestamp",
  "PostBootstrapEvent._tag",
  "PostBootstrapEvent.level",
  "PostBootstrapEvent.timestamp",
  "PostBuildEvent._tag",
  "PostBuildEvent.appRef",
  "PostBuildEvent.eventName",
  "PostBuildEvent.providerId",
  "PostBuildEvent.serviceName",
  "PostBuildEvent.timestamp",
  "PostDestroyEvent._tag",
  "PostDestroyEvent.app",
  "PostDestroyEvent.timestamp",
  "PostGlobalStartEvent._tag",
  "PostGlobalStartEvent.app",
  "PostGlobalStartEvent.cached",
  "PostGlobalStartEvent.plan",
  "PostGlobalStartEvent.scope",
  "PostGlobalStartEvent.timestamp",
  "PostGlobalStopEvent._tag",
  "PostGlobalStopEvent.app",
  "PostGlobalStopEvent.scope",
  "PostGlobalStopEvent.timestamp",
  "PostInitEvent._tag",
  "PostInitEvent.app",
  "PostInitEvent.timestamp",
  "PostManagedFileWriteEvent._tag",
  "PostManagedFileWriteEvent.action",
  "PostManagedFileWriteEvent.eventName",
  "PostManagedFileWriteEvent.owner",
  "PostManagedFileWriteEvent.path",
  "PostManagedFileWriteEvent.summary",
  "PostManagedFileWriteEvent.timestamp",
  "PostTunnelStartEvent._tag",
  "PostTunnelStartEvent.app",
  "PostTunnelStartEvent.detached",
  "PostTunnelStartEvent.durationMs",
  "PostTunnelStartEvent.eventName",
  "PostTunnelStartEvent.failureDetail",
  "PostTunnelStartEvent.outcome",
  "PostTunnelStartEvent.provider",
  "PostTunnelStartEvent.publicUrlSummary",
  "PostTunnelStartEvent.sessionId",
  "PostTunnelStartEvent.targetSummary",
  "PostTunnelStartEvent.timestamp",
  "PostTunnelStopEvent._tag",
  "PostTunnelStopEvent.app",
  "PostTunnelStopEvent.detached",
  "PostTunnelStopEvent.durationMs",
  "PostTunnelStopEvent.eventName",
  "PostTunnelStopEvent.failureDetail",
  "PostTunnelStopEvent.outcome",
  "PostTunnelStopEvent.provider",
  "PostTunnelStopEvent.publicUrlSummary",
  "PostTunnelStopEvent.sessionId",
  "PostTunnelStopEvent.targetSummary",
  "PostTunnelStopEvent.timestamp",
  "PostProviderApplyEvent._tag",
  "PostProviderApplyEvent.app",
  "PostProviderApplyEvent.providerId",
  "PostProviderApplyEvent.timestamp",
  "PostProviderExecEvent._tag",
  "PostProviderExecEvent.app",
  "PostProviderExecEvent.exitCode",
  "PostProviderExecEvent.service",
  "PostProviderExecEvent.timestamp",
  "PostRebuildEvent._tag",
  "PostRebuildEvent.app",
  "PostRebuildEvent.timestamp",
  "PostServiceStartEvent._tag",
  "PostServiceStartEvent.appRef",
  "PostServiceStartEvent.eventName",
  "PostServiceStartEvent.providerId",
  "PostServiceStartEvent.serviceName",
  "PostServiceStartEvent.timestamp",
  "PostServiceStopEvent._tag",
  "PostServiceStopEvent.appRef",
  "PostServiceStopEvent.eventName",
  "PostServiceStopEvent.providerId",
  "PostServiceStopEvent.serviceName",
  "PostServiceStopEvent.timestamp",
  "PostStartEvent._tag",
  "PostStartEvent.app",
  "PostStartEvent.plan",
  "PostStartEvent.scope",
  "PostStartEvent.timestamp",
  "PostStopEvent._tag",
  "PostStopEvent.app",
  "PostStopEvent.scope",
  "PostStopEvent.timestamp",
  "PreAppStartEvent._tag",
  "PreAppStartEvent.appRef",
  "PreAppStartEvent.eventName",
  "PreAppStartEvent.providerId",
  "PreAppStartEvent.timestamp",
  "PreAppStopEvent._tag",
  "PreAppStopEvent.appRef",
  "PreAppStopEvent.eventName",
  "PreAppStopEvent.providerId",
  "PreAppStopEvent.timestamp",
  "PreBootstrapEvent._tag",
  "PreBootstrapEvent.level",
  "PreBootstrapEvent.timestamp",
  "PreBuildEvent._tag",
  "PreBuildEvent.appRef",
  "PreBuildEvent.eventName",
  "PreBuildEvent.providerId",
  "PreBuildEvent.serviceName",
  "PreBuildEvent.timestamp",
  "PreDestroyEvent._tag",
  "PreDestroyEvent.app",
  "PreDestroyEvent.timestamp",
  "PreDownloadEvent._tag",
  "PreDownloadEvent.callerId",
  "PreDownloadEvent.eventName",
  "PreDownloadEvent.expectedSizeBytes",
  "PreDownloadEvent.timestamp",
  "PreDownloadEvent.urlOrigin",
  "PreDatasetApplyEvent._tag",
  "PreDatasetApplyEvent.dataset",
  "PreDatasetApplyEvent.env",
  "PreDatasetApplyEvent.eventName",
  "PreDatasetApplyEvent.remote",
  "PreDatasetApplyEvent.timestamp",
  "PreDatasetCaptureEvent._tag",
  "PreDatasetCaptureEvent.dataset",
  "PreDatasetCaptureEvent.env",
  "PreDatasetCaptureEvent.eventName",
  "PreDatasetCaptureEvent.remote",
  "PreDatasetCaptureEvent.timestamp",
  "PreDatasetFetchEvent._tag",
  "PreDatasetFetchEvent.dataset",
  "PreDatasetFetchEvent.env",
  "PreDatasetFetchEvent.eventName",
  "PreDatasetFetchEvent.remote",
  "PreDatasetFetchEvent.timestamp",
  "PreDatasetSendEvent._tag",
  "PreDatasetSendEvent.dataset",
  "PreDatasetSendEvent.env",
  "PreDatasetSendEvent.eventName",
  "PreDatasetSendEvent.remote",
  "PreDatasetSendEvent.timestamp",
  "PreGlobalStartEvent._tag",
  "PreGlobalStartEvent.app",
  "PreGlobalStartEvent.cached",
  "PreGlobalStartEvent.ensuringServices",
  "PreGlobalStartEvent.plan",
  "PreGlobalStartEvent.scope",
  "PreGlobalStartEvent.timestamp",
  "PreGlobalStartEvent.triggeredBy",
  "PreGlobalStopEvent._tag",
  "PreGlobalStopEvent.app",
  "PreGlobalStopEvent.scope",
  "PreGlobalStopEvent.timestamp",
  "PreGlobalStopEvent.triggeredBy",
  "PreInitEvent._tag",
  "PreInitEvent.app",
  "PreInitEvent.timestamp",
  "PreManagedFileWriteEvent._tag",
  "PreManagedFileWriteEvent.action",
  "PreManagedFileWriteEvent.eventName",
  "PreManagedFileWriteEvent.owner",
  "PreManagedFileWriteEvent.path",
  "PreManagedFileWriteEvent.summary",
  "PreManagedFileWriteEvent.timestamp",
  "PreTunnelStartEvent._tag",
  "PreTunnelStartEvent.app",
  "PreTunnelStartEvent.detached",
  "PreTunnelStartEvent.eventName",
  "PreTunnelStartEvent.provider",
  "PreTunnelStartEvent.publicUrlSummary",
  "PreTunnelStartEvent.sessionId",
  "PreTunnelStartEvent.targetSummary",
  "PreTunnelStartEvent.timestamp",
  "PreTunnelStopEvent._tag",
  "PreTunnelStopEvent.app",
  "PreTunnelStopEvent.detached",
  "PreTunnelStopEvent.eventName",
  "PreTunnelStopEvent.provider",
  "PreTunnelStopEvent.publicUrlSummary",
  "PreTunnelStopEvent.sessionId",
  "PreTunnelStopEvent.targetSummary",
  "PreTunnelStopEvent.timestamp",
  "PreProviderApplyEvent._tag",
  "PreProviderApplyEvent.app",
  "PreProviderApplyEvent.providerId",
  "PreProviderApplyEvent.timestamp",
  "PreProviderExecEvent._tag",
  "PreProviderExecEvent.app",
  "PreProviderExecEvent.service",
  "PreProviderExecEvent.timestamp",
  "PreRebuildEvent._tag",
  "PreRebuildEvent.app",
  "PreRebuildEvent.timestamp",
  "PreServiceStartEvent._tag",
  "PreServiceStartEvent.appRef",
  "PreServiceStartEvent.eventName",
  "PreServiceStartEvent.providerId",
  "PreServiceStartEvent.serviceName",
  "PreServiceStartEvent.timestamp",
  "PreServiceStopEvent._tag",
  "PreServiceStopEvent.appRef",
  "PreServiceStopEvent.eventName",
  "PreServiceStopEvent.providerId",
  "PreServiceStopEvent.serviceName",
  "PreServiceStopEvent.timestamp",
  "PreStartEvent._tag",
  "PreStartEvent.app",
  "PreStartEvent.plan",
  "PreStartEvent.scope",
  "PreStartEvent.timestamp",
  "PreStartEvent.triggeredBy",
  "PreStopEvent._tag",
  "PreStopEvent.app",
  "PreStopEvent.scope",
  "PreStopEvent.timestamp",
  "PromptSpec.choices",
  "PromptSpec.choicesFrom",
  "PromptSpec.default",
  "PromptSpec.message",
  "PromptSpec.name",
  "PromptSpec.type",
  "PromptSpec.validate",
  "PrePullEvent._tag",
  "PrePullEvent.datasets",
  "PrePullEvent.env",
  "PrePullEvent.eventName",
  "PrePullEvent.remote",
  "PrePullEvent.timestamp",
  "PrePushEvent._tag",
  "PrePushEvent.datasets",
  "PrePushEvent.env",
  "PrePushEvent.eventName",
  "PrePushEvent.remote",
  "PrePushEvent.timestamp",
  "ProviderCapabilities.artifactBuild",
  "ProviderCapabilities.artifactExport",
  "ProviderCapabilities.artifactImport",
  "ProviderCapabilities.artifactPull",
  "ProviderCapabilities.bindMountPerformance",
  "ProviderCapabilities.bindMounts",
  "ProviderCapabilities.buildSecrets",
  "ProviderCapabilities.buildSsh",
  "ProviderCapabilities.composeSpec",
  "ProviderCapabilities.copyMounts",
  "ProviderCapabilities.copyOnWriteAppRoot",
  "ProviderCapabilities.ephemeralMounts",
  "ProviderCapabilities.hostPortPublish",
  "ProviderCapabilities.hostReachability",
  "ProviderCapabilities.multiServiceApply",
  "ProviderCapabilities.persistentStorage",
  "ProviderCapabilities.privilegedServices",
  "ProviderCapabilities.providerExtensions",
  "ProviderCapabilities.rootless",
  "ProviderCapabilities.routeProvider",
  "ProviderCapabilities.serviceExec",
  "ProviderCapabilities.serviceFileCopy",
  "ProviderCapabilities.serviceHealth",
  "ProviderCapabilities.serviceLogs",
  "ProviderCapabilities.sharedCrossAppNetwork",
  "ProviderCapabilities.tlsCertificates",
  "ProviderCapabilities.volumeSnapshot",
  "PublicTranscript.frames",
  "PublicTranscript.render",
  "PublicTranscript.runtime",
  "PublicTranscript.variant",
  "ReadyEvent._tag",
  "ReadyEvent.timestamp",
  "RecipeChoicesFrom.args",
  "RecipeChoicesFrom.command",
  "RecipeChoicesFrom.parse",
  "RecipeManifest.authors",
  "RecipeManifest.deprecated",
  "RecipeManifest.description",
  "RecipeManifest.fetchAllowlist",
  "RecipeManifest.files",
  "RecipeManifest.postInit",
  "RecipeManifest.prompts",
  "RecipeManifest.requires",
  "RecipeManifest.runs",
  "RecipeManifest.tags",
  "RecipeManifest.title",
  "RecipeRegistryResolution.kind",
  "RecipeRegistryResolution.path",
  "RecipeRegistryResolution.url",
  "RecipeRegistryResponse.id",
  "RecipeRegistryResponse.resolution",
  "RouteInput.endpoint",
  "RouteInput.hostname",
  "RouteInput.pathPrefix",
  "RouteInput.scheme",
  "RoutePlan.endpoint",
  "RoutePlan.hostname",
  "RoutePlan.pathPrefix",
  "RoutePlan.scheme",
  "RoutePlan.service",
  "RouteRef.index",
  "RunProps.answers",
  "RunProps.command",
  "RunProps.expectExit",
  "RunProps.shell",
  "ScenarioProps.layer",
  "ScenarioProps.reason",
  "ScenarioProps.render",
  "ScenarioProps.tags",
  "ServiceConfig.api",
  "ServiceConfig.appMount",
  "ServiceConfig.build",
  "ServiceConfig.command",
  "ServiceConfig.composeBuild",
  "ServiceConfig.cores",
  "ServiceConfig.database",
  "ServiceConfig.dependsOn",
  "ServiceConfig.endpoints",
  "ServiceConfig.entrypoint",
  "ServiceConfig.environment",
  "ServiceConfig.framework",
  "ServiceConfig.healthcheck",
  "ServiceConfig.hostnames",
  "ServiceConfig.image",
  "ServiceConfig.mounts",
  "ServiceConfig.port",
  "ServiceConfig.ports",
  "ServiceConfig.primary",
  "ServiceConfig.providers",
  "ServiceConfig.root",
  "ServiceConfig.routes",
  "ServiceConfig.storage",
  "ServiceConfig.type",
  "ServiceConfig.user",
  "ServiceConfig.volumes",
  "ServiceConfig.workingDirectory",
  "ServiceInfo.api",
  "ServiceInfo.app",
  "ServiceInfo.endpoints",
  "ServiceInfo.primary",
  "ServiceInfo.provider",
  "ServiceInfo.routes",
  "ServiceInfo.service",
  "ServiceInfo.status",
  "ServiceInfo.type",
  "ServicePlan.appMount",
  "ServicePlan.artifact",
  "ServicePlan.certs",
  "ServicePlan.command",
  "ServicePlan.dependsOn",
  "ServicePlan.endpoints",
  "ServicePlan.entrypoint",
  "ServicePlan.environment",
  "ServicePlan.extensions",
  "ServicePlan.healthcheck",
  "ServicePlan.hostAliases",
  "ServicePlan.metadata",
  "ServicePlan.mounts",
  "ServicePlan.name",
  "ServicePlan.primary",
  "ServicePlan.provider",
  "ServicePlan.routes",
  "ServicePlan.storage",
  "ServicePlan.type",
  "ServicePlan.user",
  "ServicePlan.workingDirectory",
  "SharedNetworkMembershipPlan.aliases",
  "SharedNetworkMembershipPlan.name",
  "SkipProps.until",
  "StreamFrame._tag",
  "TabsProps.axis",
  "TaskCompleteEvent._tag",
  "TaskCompleteEvent.durationMs",
  "TaskCompleteEvent.summary",
  "TaskCompleteEvent.taskId",
  "TaskCompleteEvent.timestamp",
  "TaskDetailCollapseEvent._tag",
  "TaskDetailCollapseEvent.taskId",
  "TaskDetailCollapseEvent.timestamp",
  "TaskDetailEvent._tag",
  "TaskDetailEvent.line",
  "TaskDetailEvent.stream",
  "TaskDetailEvent.taskId",
  "TaskDetailEvent.timestamp",
  "TaskDetailExpandEvent._tag",
  "TaskDetailExpandEvent.taskId",
  "TaskDetailExpandEvent.timestamp",
  "TaskFailEvent._tag",
  "TaskFailEvent.durationMs",
  "TaskFailEvent.exitCode",
  "TaskFailEvent.remediation",
  "TaskFailEvent.summary",
  "TaskFailEvent.taskId",
  "TaskFailEvent.timestamp",
  "TaskStartEvent._tag",
  "TaskStartEvent.label",
  "TaskStartEvent.parentId",
  "TaskStartEvent.taskId",
  "TaskStartEvent.timestamp",
  "TaskTreeCompleteEvent._tag",
  "TaskTreeCompleteEvent.durationMs",
  "TaskTreeCompleteEvent.failed",
  "TaskTreeCompleteEvent.parentId",
  "TaskTreeCompleteEvent.succeeded",
  "TaskTreeCompleteEvent.summary",
  "TaskTreeCompleteEvent.timestamp",
  "TaskTreeStartEvent._tag",
  "TaskTreeStartEvent.children",
  "TaskTreeStartEvent.label",
  "TaskTreeStartEvent.mode",
  "TaskTreeStartEvent.parentId",
  "TaskTreeStartEvent.timestamp",
  "TunnelReadyEvent._tag",
  "TunnelReadyEvent.app",
  "TunnelReadyEvent.detached",
  "TunnelReadyEvent.eventName",
  "TunnelReadyEvent.provider",
  "TunnelReadyEvent.publicUrlSummary",
  "TunnelReadyEvent.sessionId",
  "TunnelReadyEvent.status",
  "TunnelReadyEvent.targetSummary",
  "TunnelReadyEvent.timestamp",
  "TunnelStatusEvent._tag",
  "TunnelStatusEvent.app",
  "TunnelStatusEvent.detached",
  "TunnelStatusEvent.eventName",
  "TunnelStatusEvent.provider",
  "TunnelStatusEvent.publicUrlSummary",
  "TunnelStatusEvent.sessionId",
  "TunnelStatusEvent.status",
  "TunnelStatusEvent.targetSummary",
  "TunnelStatusEvent.timestamp",
  "TelemetryConfig.enabled",
  "TemplateRenderContext.appRoot",
  "TemplateRenderContext.bootstrapLevel",
  "TemplateRenderContext.env",
  "TemplateRenderContext.global",
  "TemplateRenderContext.landofile",
  "TemplateRenderContext.provider",
  "TemplateRenderContext.scope",
  "ToolingArgShape.default",
  "ToolingArgShape.deprecated",
  "ToolingArgShape.description",
  "ToolingArgShape.required",
  "ToolingFlagShape.default",
  "ToolingFlagShape.deprecated",
  "ToolingFlagShape.description",
  "ToolingFlagShape.type",
  "ToolingTaskShape.args",
  "ToolingTaskShape.cmd",
  "ToolingTaskShape.cmds",
  "ToolingTaskShape.deprecated",
  "ToolingTaskShape.description",
  "ToolingTaskShape.flags",
  "ToolingTaskShape.service",
  "ToolingTaskShape.summary",
  "ToolingTaskShape.vars",
  "UpdateManifestBinaries.darwin-arm64",
  "UpdateManifestBinaries.darwin-x64",
  "UpdateManifestBinaries.linux-arm64",
  "UpdateManifestBinaries.linux-x64",
  "UpdateManifestBinaries.windows-x64",
  "UpdateManifestSchema.binaries",
  "UpdateManifestSchema.channel",
  "UpdateManifestSchema.checksums",
  "UpdateManifestSchema.released",
  "Transcript.exitStatus",
  "Transcript.frames",
  "Transcript.render",
  "UseFixtureProps.name",
  "VariableProps.display",
  "VariableProps.name",
  "VariableProps.value",
  "VerifyProps.command",
  "VerifyProps.errorTag",
  "VerifyProps.event",
  "VerifyProps.expect",
  "VerifyProps.file",
]);

export type PublicSchemaAnnotationIssue = {
  readonly schema: JsonSchemaName | string;
  readonly path: string;
  readonly message: string;
};

export type PublicSchemaAnnotationExemptions = {
  readonly topLevel?: ReadonlySet<string>;
  readonly fields?: ReadonlySet<string>;
};

const hasOwnUsefulDescription = (annotations: AST.Annotations): boolean => {
  const value = annotations[AST.DescriptionAnnotationId];
  return typeof value === "string" && value.trim().length > 0 && !BUILT_IN_DESCRIPTIONS.has(value);
};

const hasSchemaStringAnnotation = (ast: AST.AST, key: symbol): boolean => {
  const annotation = AST.getAnnotation<string>(key)(ast);
  return annotation._tag === "Some" && annotation.value.trim().length > 0;
};

const hasSchemaUsefulDescription = (ast: AST.AST): boolean => {
  const annotation = AST.getDescriptionAnnotation(ast);
  if (annotation._tag !== "Some" || annotation.value.trim().length === 0) return false;
  if (!BUILT_IN_DESCRIPTIONS.has(annotation.value)) return true;
  return AST.getIdentifierAnnotation(ast)._tag === "Some" && ast._tag !== "TypeLiteral";
};

const fieldName = (name: PropertyKey): string => (typeof name === "symbol" ? name.toString() : String(name));

const isSelfExplanatoryPublicField = (schemaName: string, name: string): boolean =>
  PUBLIC_FIELD_DESCRIPTION_EXEMPTIONS.has(`${schemaName}.${name}`) || name.startsWith("x-");

const schemaFromAst = (ast: AST.AST): Schema.Schema.AnyNoContext =>
  Schema.make(ast) as Schema.Schema.AnyNoContext;

const validateExamples = (
  schemaName: JsonSchemaName | string,
  path: string,
  schema: Schema.Schema.AnyNoContext,
): ReadonlyArray<PublicSchemaAnnotationIssue> => {
  const examples = AST.getExamplesAnnotation(schema.ast);
  if (examples._tag === "None") return [];

  return examples.value.flatMap((example, index): ReadonlyArray<PublicSchemaAnnotationIssue> => {
    const decoded = Schema.decodeUnknownEither(schema)(example);
    if (Either.isRight(decoded)) return [];
    return [
      {
        schema: schemaName,
        path: `${path}.examples[${index}]`,
        message: "Example does not decode successfully.",
      },
    ];
  });
};

export const validatePublicSchemaAnnotations = (
  registry: Record<string, PublicSchema> = publicSchemaRegistry,
  exemptions: PublicSchemaAnnotationExemptions = { fields: PUBLIC_FIELD_DESCRIPTION_EXEMPTIONS },
): ReadonlyArray<PublicSchemaAnnotationIssue> => {
  const issues: PublicSchemaAnnotationIssue[] = [];
  for (const [schemaName, schema] of Object.entries(registry)) {
    const isTopLevelExempt = exemptions.topLevel?.has(schemaName) ?? false;
    if (!isTopLevelExempt && !hasSchemaStringAnnotation(schema.ast, AST.IdentifierAnnotationId)) {
      issues.push({
        schema: schemaName,
        path: schemaName,
        message: "Missing required identifier annotation.",
      });
    }
    if (!isTopLevelExempt && !hasSchemaStringAnnotation(schema.ast, AST.TitleAnnotationId)) {
      issues.push({ schema: schemaName, path: schemaName, message: "Missing required title annotation." });
    }
    if (!isTopLevelExempt && !hasSchemaUsefulDescription(schema.ast)) {
      issues.push({
        schema: schemaName,
        path: schemaName,
        message: "Missing required description annotation.",
      });
    }

    issues.push(...validateExamples(schemaName, schemaName, schema));

    for (const property of AST.getPropertySignatures(schema.ast)) {
      const name = fieldName(property.name);
      const fieldPath = `${schemaName}.${name}`;
      issues.push(...validateExamples(schemaName, fieldPath, schemaFromAst(property.type)));
      if (
        !hasOwnUsefulDescription(property.annotations) &&
        !hasOwnUsefulDescription(property.type.annotations) &&
        !(exemptions.fields?.has(fieldPath) ?? false) &&
        !isSelfExplanatoryPublicField(schemaName, name)
      ) {
        issues.push({
          schema: schemaName,
          path: fieldPath,
          message: "Missing field description annotation or self-explanatory field exemption.",
        });
      }
    }
  }

  return issues;
};

export const assertPublicSchemaAnnotations = (
  registry: Record<string, PublicSchema> = publicSchemaRegistry,
  exemptions?: PublicSchemaAnnotationExemptions,
): void => {
  const issues = validatePublicSchemaAnnotations(registry, exemptions);
  if (issues.length === 0) return;
  const lines = issues.map((issue) => `- ${issue.path}: ${issue.message}`);
  throw new Error(`Public schema annotation gate failed:\n${lines.join("\n")}`);
};

export const renderPublicSchemaReferencePages = (): ReadonlyArray<PublicSchemaReferencePage> =>
  publicSchemaMetadataIndex.map((metadata) => ({
    id: metadata.id,
    docsPath: metadata.docsPath,
    content: renderSchemaReferenceMarkdown(metadata.id, publicSchemaRegistry[metadata.id], {
      jsonSchema: getJsonSchema(metadata.id) as JsonObject,
      jsonSchemaPath: metadata.jsonSchemaPath,
      title: metadata.title,
      description: metadata.description,
    }),
  }));

const landofileJsonSchema = (): JsonObject => {
  const schema = getJsonSchemaWithDeprecations(LandofileShape) as JsonObject;
  schema.additionalProperties = false;
  schema.patternProperties = {
    "^x-": {
      $id: "/schemas/unknown",
      title: "unknown",
    },
  };
  schema.propertyNames = undefined;
  return schema;
};

const expressionNodeDefinitions = () => {
  const placeholder = { ExpressionNode: { anyOf: [] } };
  const options = { definitions: placeholder } satisfies Parameters<typeof JSONSchema.fromAST>[1];
  return {
    ExpressionNode: {
      anyOf: [
        JSONSchema.fromAST(LiteralExpressionNode.ast, options),
        JSONSchema.fromAST(ArrayLiteralExpressionNode.ast, options),
        JSONSchema.fromAST(ObjectLiteralExpressionNode.ast, options),
        JSONSchema.fromAST(PathExpressionNode.ast, options),
        JSONSchema.fromAST(AccessExpressionNode.ast, options),
        JSONSchema.fromAST(CallExpressionNode.ast, options),
        JSONSchema.fromAST(ConditionalExpressionNode.ast, options),
      ],
    },
  } satisfies Parameters<typeof JSONSchema.fromAST>[1]["definitions"];
};

const expressionJsonSchema = (schemaName: "ExpressionNode" | "ExpressionTemplate") => {
  const schema = schemaName === "ExpressionNode" ? ExpressionNode : ExpressionTemplate;
  const definitions = expressionNodeDefinitions();
  return {
    $schema: "http://json-schema.org/draft-07/schema#",
    $defs: definitions,
    ...JSONSchema.fromAST(schema.ast, { definitions }),
  };
};

export const getJsonSchema = (schemaName: JsonSchemaName) => {
  if (schemaName === "DeprecationNotice") return getJsonSchemaWithDeprecations(DeprecationNoticeJsonShape);
  if (schemaName === "LandofileShape") return landofileJsonSchema();
  if (schemaName === "ExpressionNode" || schemaName === "ExpressionTemplate")
    return expressionJsonSchema(schemaName);
  return getJsonSchemaWithDeprecations(rawPublicSchemaRegistry[schemaName]);
};
