import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";

import { describe, expect, test } from "bun:test";

const repoRoot = resolve(import.meta.dirname, "../../..");
const packageJsonPath = resolve(repoRoot, "package.json");
const workflowPath = resolve(repoRoot, ".github/workflows/ci.yml");
const releaseWorkflowPath = resolve(repoRoot, ".github/workflows/release.yml");
const ciWorkflowGeneratorPath = resolve(repoRoot, "scripts/build-ci-workflow.ts");
const releaseWorkflowGeneratorPath = resolve(repoRoot, "scripts/build-release-workflow.ts");

const generatedHeader =
  "# Generated by scripts/codegen.ts — do not hand-edit. Edit scripts/build-ci-workflow.ts instead.";
const generatedReleaseHeader =
  "# Generated by scripts/codegen.ts — do not hand-edit. Edit scripts/build-release-workflow.ts instead.";

const runCodegen = async (): Promise<{ readonly stdout: string; readonly stderr: string }> => {
  const proc = Bun.spawn({
    cmd: [process.execPath, "run", "codegen"],
    cwd: repoRoot,
    env: {
      ...process.env,
      PATH: `${dirname(process.execPath)}:${process.env.PATH ?? ""}`,
    },
    stdout: "pipe",
    stderr: "pipe",
  });

  const [exitCode, stdout, stderr] = await Promise.all([
    proc.exited,
    new Response(proc.stdout).text(),
    new Response(proc.stderr).text(),
  ]);

  expect({ exitCode, stdout, stderr }).toMatchObject({ exitCode: 0 });
  return { stdout, stderr };
};

const changedLines = (
  before: string,
  after: string,
): ReadonlyArray<{ readonly before: string; readonly after: string }> => {
  const beforeLines = before.split("\n");
  const afterLines = after.split("\n");
  const count = Math.max(beforeLines.length, afterLines.length);
  const changes: Array<{ readonly before: string; readonly after: string }> = [];

  for (let index = 0; index < count; index += 1) {
    const beforeLine = beforeLines[index] ?? "";
    const afterLine = afterLines[index] ?? "";

    if (beforeLine !== afterLine) changes.push({ before: beforeLine, after: afterLine });
  }

  return changes;
};

describe("ci workflow codegen", () => {
  test("runs guide scenario codegen first and ignores generated guide outputs", async () => {
    const guidePath = resolve(repoRoot, "docs/guides/codegen-smoke.mdx");
    const generatedPath = resolve(repoRoot, "test/scenarios/generated/guides/codegen-smoke/runs.test.ts");

    try {
      await mkdir(dirname(guidePath), { recursive: true });
      await Bun.write(
        guidePath,
        [
          "---",
          "id: codegen-smoke",
          "provider: test",
          "---",
          "",
          "<Guide>",
          '  <Scenario id="runs">',
          '    <Step name="run">',
          '      <Run command="version" />',
          "    </Step>",
          "  </Scenario>",
          "</Guide>",
          "",
        ].join("\n"),
      );

      const { stdout } = await runCodegen();
      expect(stdout).toContain("[codegen] run build-guide-scenarios");
      expect(stdout.indexOf("[codegen] run build-guide-scenarios")).toBeLessThan(
        stdout.indexOf("[codegen] run schema-snapshot"),
      );
      expect(await Bun.file(generatedPath).exists()).toBe(true);
      expect(await readFile(resolve(repoRoot, ".gitignore"), "utf8")).toContain(
        "test/scenarios/generated/guides/**",
      );
    } finally {
      await rm(guidePath, { force: true });
      await rm(resolve(repoRoot, "test/scenarios/generated/guides"), { force: true, recursive: true });
      await runCodegen();
    }
  });

  test("regenerates ci.yml idempotently with the generated-file header", async () => {
    await runCodegen();

    const firstWorkflow = await readFile(workflowPath, "utf8");
    expect(firstWorkflow.startsWith(`${generatedHeader}\n`)).toBe(true);

    await runCodegen();

    expect(await readFile(workflowPath, "utf8")).toBe(firstWorkflow);
  });

  test("regenerates release.yml idempotently with the generated-file header", async () => {
    await runCodegen();

    const firstWorkflow = await readFile(releaseWorkflowPath, "utf8");
    expect(firstWorkflow.startsWith(`${generatedReleaseHeader}\n`)).toBe(true);

    await runCodegen();

    expect(await readFile(releaseWorkflowPath, "utf8")).toBe(firstWorkflow);
  });

  test("uses .bun-version file as the Bun version source, not package.json engines.bun", async () => {
    await runCodegen();

    const workflow = await readFile(workflowPath, "utf8");
    const releaseWorkflow = await readFile(releaseWorkflowPath, "utf8");
    const ciWorkflowGenerator = await readFile(ciWorkflowGeneratorPath, "utf8");
    const releaseWorkflowGenerator = await readFile(releaseWorkflowGeneratorPath, "utf8");

    const versionFileMatches = (workflow.match(/bun-version-file: .bun-version/g) ?? []).length;
    expect(versionFileMatches).toBe(8);
    expect(workflow).not.toContain("bun-version: ");
    expect((releaseWorkflow.match(/bun-version-file: .bun-version/g) ?? []).length).toBe(2);
    expect(releaseWorkflow).not.toContain("bun-version: ");

    for (const generatedWorkflow of [workflow, releaseWorkflow]) {
      const setupBunMatches = (generatedWorkflow.match(/uses: oven-sh\/setup-bun@v2/g) ?? []).length;
      const versionFileMatches = (generatedWorkflow.match(/bun-version-file: .bun-version/g) ?? []).length;

      expect(versionFileMatches).toBe(setupBunMatches);
      expect(generatedWorkflow).not.toContain("engines.bun");
    }

    for (const generator of [ciWorkflowGenerator, releaseWorkflowGenerator]) {
      expect(generator).not.toContain("engines.bun");
      expect(generator).not.toContain("packageJson.engines");
    }

    const originalPackageJson = await readFile(packageJsonPath, "utf8");
    const mutatedPackageJson = originalPackageJson.replace('"bun": ">=1.3.14"', '"bun": ">=9.8.7"');
    expect(mutatedPackageJson).not.toBe(originalPackageJson);

    try {
      await writeFile(packageJsonPath, mutatedPackageJson);
      await runCodegen();

      const updatedWorkflow = await readFile(workflowPath, "utf8");
      const updatedReleaseWorkflow = await readFile(releaseWorkflowPath, "utf8");
      expect(changedLines(workflow, updatedWorkflow)).toEqual([]);
      expect(changedLines(releaseWorkflow, updatedReleaseWorkflow)).toEqual([]);
    } finally {
      await writeFile(packageJsonPath, originalPackageJson);
      await runCodegen();
    }
  });

  test("generates schema-snapshot and bundled-codegen drift gates", async () => {
    await runCodegen();

    const workflow = await readFile(workflowPath, "utf8");

    expect(workflow).toContain("schema-snapshot:");
    expect(workflow).toContain("- name: Regenerate schema snapshot");
    expect(workflow).toContain("run: bun run codegen:schema-snapshot");
    expect(workflow).toContain("run: git diff --exit-code -- sdk/test/fixtures/schema-snapshot.json");

    expect(workflow).toContain("bundled-codegen:");
    expect(workflow).toContain("- name: Regenerate bundled plugins");
    expect(workflow).toContain("run: bun run codegen:bundled-plugins");
    expect(workflow).toContain("- name: Regenerate bundled recipes");
    expect(workflow).toContain("run: bun run codegen:bundled-recipes");
    expect(workflow).toContain(
      "run: git diff --exit-code -- core/src/plugins/bundled.ts core/src/recipes/bundled.ts",
    );
    expect(workflow).toContain(
      "needs: [static-checks, schema-snapshot, bundled-codegen, library-api-tests, recipe-tests]",
    );
  });

  test("generates named library API and recipe test layers", async () => {
    await runCodegen();

    const workflow = await readFile(workflowPath, "utf8");

    expect(workflow).toContain("library-api-tests:");
    expect(workflow).toContain("- name: Run library API tests");
    expect(workflow).toContain("run: bun test core/test/library sdk/test/library");

    expect(workflow).toContain("recipe-tests:");
    expect(workflow).toContain("- name: Run recipe test layer");
    expect(workflow).toContain(
      "run: bun test core/test/recipes core/test/cli/init.canonical-recipes.test.ts",
    );
    expect(workflow).toContain(
      "needs: [static-checks, schema-snapshot, bundled-codegen, library-api-tests, recipe-tests]",
    );
  });

  test("generates the guide scenario CI gate", async () => {
    await runCodegen();

    const workflow = await readFile(workflowPath, "utf8");

    expect(workflow).toContain("guide-scenarios-linux-x64:");
    expect(workflow).toContain("needs: [static-checks]");
    expect(workflow).toContain("run: bun run codegen");
    expect(workflow).toContain("run: bun run typecheck");
    expect(workflow).toContain("run: bun run lint:guides");
    expect(workflow).toContain("run: bun test test/scenarios/generated/guides/**");
    expect(workflow).toContain("name: guide-scenario-transcripts-${{ github.run_id }}.zip");
    expect(workflow).toContain("path: dist/transcripts/guides/**/*.json");
    expect(workflow).toContain("retention-days: 7");

    expect(
      workflow.indexOf("run: bun install --frozen-lockfile", workflow.indexOf("guide-scenarios-linux-x64")),
    ).toBeLessThan(workflow.indexOf("run: bun run codegen", workflow.indexOf("guide-scenarios-linux-x64")));
    expect(
      workflow.indexOf("run: bun run codegen", workflow.indexOf("guide-scenarios-linux-x64")),
    ).toBeLessThan(workflow.indexOf("run: bun run typecheck", workflow.indexOf("guide-scenarios-linux-x64")));
    expect(
      workflow.indexOf("run: bun run typecheck", workflow.indexOf("guide-scenarios-linux-x64")),
    ).toBeLessThan(
      workflow.indexOf("run: bun run lint:guides", workflow.indexOf("guide-scenarios-linux-x64")),
    );
    expect(
      workflow.indexOf("run: bun run lint:guides", workflow.indexOf("guide-scenarios-linux-x64")),
    ).toBeLessThan(
      workflow.indexOf(
        "run: bun test test/scenarios/generated/guides/**",
        workflow.indexOf("guide-scenarios-linux-x64"),
      ),
    );
  });

  test("generates a Linux x64 dev prerelease workflow", async () => {
    await runCodegen();

    const workflow = await readFile(releaseWorkflowPath, "utf8");

    expect(workflow).toContain("name: release");
    expect(workflow).toContain("workflow_run:");
    expect(workflow).toContain("workflows: [ci]");
    expect(workflow).toContain("branches: [main]");
    expect(workflow).toContain("contents: write");
    expect(workflow).toContain("actions: read");
    expect(workflow).toContain("dev-prerelease-linux-x64:");
    expect(workflow).toContain("github.event.workflow_run.conclusion == 'success'");
    expect(workflow).toContain(
      'gh run download "${{ github.event.workflow_run.id }}" --name lando-linux-x64 --dir dist',
    );
    expect(workflow).toContain("sudo apt-get install -y strace iproute2");
    expect(workflow).toContain("sudo env");
    expect(workflow).toContain("unshare --net sh -c");
    expect(workflow).toContain("strace -f -e trace=network");
    expect(workflow).toContain("first-launch.network.log");
    expect(workflow).toContain("awk '/connect\\(/ && $0 !~ /(127\\.|::1|AF_UNIX)/");
    expect(workflow).toContain("sha256sum lando > SHA256SUMS");
    expect(workflow).toContain("grep -Eq '^[0-9a-f]{64}  lando$' SHA256SUMS");
    expect(workflow).toContain("RELEASE_TAG: v4.0.0-dev.${{ github.run_number }}");
    expect(workflow).toContain('gh release create "$RELEASE_TAG" dist/lando dist/SHA256SUMS --prerelease');
    expect(workflow).toContain("--prerelease");
    expect(workflow).not.toContain("cosign");
    expect(workflow).not.toContain("gpg");
    expect(workflow).not.toContain("sbom");
    expect(workflow).not.toContain("installer");
    expect(workflow).not.toContain("update-manifest");
  });

  test("keeps broad multi-platform release targets deferred from generated workflows", async () => {
    await runCodegen();

    const ciWorkflow = await readFile(workflowPath, "utf8");
    const releaseWorkflow = await readFile(releaseWorkflowPath, "utf8");
    const generatedWorkflows = `${ciWorkflow}\n${releaseWorkflow}`;

    expect(generatedWorkflows).toContain("build-linux-x64:");
    expect(generatedWorkflows).toContain("dev-prerelease-linux-x64:");

    expect(generatedWorkflows).not.toContain("strategy:");
    expect(generatedWorkflows).not.toContain("matrix:");
    expect(generatedWorkflows).not.toContain("windows-");
    expect(generatedWorkflows).not.toContain("windows-latest");
    expect(generatedWorkflows).not.toContain("windows-2022");
    expect(generatedWorkflows).not.toContain("linux-arm64");
    expect(generatedWorkflows).not.toContain("ubuntu-latest-arm64");
    expect(generatedWorkflows).not.toContain("darwin-");

    if (generatedWorkflows.includes("runs-on: macos-")) {
      expect(generatedWorkflows).toContain("LANDO_TEST_PROVIDER_LANDO_MACOS");
    }
  });

  test("generates npm dev package publishing with dry-run coverage", async () => {
    await runCodegen();

    const workflow = await readFile(releaseWorkflowPath, "utf8");

    expect(workflow).toContain("id-token: write");
    expect(workflow).toContain("npm-dev-packages:");
    expect(workflow).toContain("needs: [dev-prerelease-linux-x64]");
    expect(workflow).toContain("Setup Node for npm trusted publishing");
    expect(workflow).toContain("registry-url: https://registry.npmjs.org");
    expect(workflow).toContain("bun run --filter='@lando/sdk' build");
    expect(workflow).toContain("bun run --filter='@lando/core' typecheck");
    expect(workflow).toContain("bun run --filter='@lando/core' build:manifest");
    expect(workflow).toContain("LANDO_NPM_VERSION: 4.0.0-alpha.${{ github.run_number }}");
    expect(workflow).toContain("run: bun run scripts/prepare-npm-dev-packages.ts");
    expect(workflow).toContain("npm publish --workspace @lando/sdk --dry-run --access public --tag dev");
    expect(workflow).toContain("npm publish --workspace @lando/core --dry-run --access public --tag dev");
    expect(workflow).toContain("npm publish --workspace @lando/sdk --access public --tag dev --provenance");
    expect(workflow).toContain("npm publish --workspace @lando/core --access public --tag dev --provenance");
    expect(workflow).toContain('test "$before_latest" = "$after_latest"');
    expect(workflow).toContain("npm view @lando/core dist-tags.dev --json");
    expect(workflow).toContain(`grep -Eq '"?4\\.0\\.0-alpha\\.[0-9]+"?'`);
    expect(workflow).not.toContain("NPM_TOKEN");
    expect(workflow).not.toContain("NODE_AUTH_TOKEN");
  });
});
