import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";

import { describe, expect, test } from "bun:test";

const repoRoot = resolve(import.meta.dirname, "../../..");
const packageJsonPath = resolve(repoRoot, "package.json");
const workflowPath = resolve(repoRoot, ".github/workflows/ci.yml");
const releaseWorkflowPath = resolve(repoRoot, ".github/workflows/release.yml");

const generatedHeader =
  "# Generated by scripts/codegen.ts — do not hand-edit. Edit scripts/build-ci-workflow.ts instead.";
const generatedReleaseHeader =
  "# Generated by scripts/codegen.ts — do not hand-edit. Edit scripts/build-release-workflow.ts instead.";

const runCodegen = async (): Promise<void> => {
  const proc = Bun.spawn({
    cmd: [process.execPath, "run", "codegen"],
    cwd: repoRoot,
    env: {
      ...process.env,
      PATH: `${dirname(process.execPath)}:${process.env.PATH ?? ""}`,
    },
    stdout: "pipe",
    stderr: "pipe",
  });

  const [exitCode, stdout, stderr] = await Promise.all([
    proc.exited,
    new Response(proc.stdout).text(),
    new Response(proc.stderr).text(),
  ]);

  expect({ exitCode, stdout, stderr }).toMatchObject({ exitCode: 0 });
};

const changedLines = (
  before: string,
  after: string,
): ReadonlyArray<{ readonly before: string; readonly after: string }> => {
  const beforeLines = before.split("\n");
  const afterLines = after.split("\n");
  const count = Math.max(beforeLines.length, afterLines.length);
  const changes: Array<{ readonly before: string; readonly after: string }> = [];

  for (let index = 0; index < count; index += 1) {
    const beforeLine = beforeLines[index] ?? "";
    const afterLine = afterLines[index] ?? "";

    if (beforeLine !== afterLine) changes.push({ before: beforeLine, after: afterLine });
  }

  return changes;
};

describe("ci workflow codegen", () => {
  test("regenerates ci.yml idempotently with the generated-file header", async () => {
    await runCodegen();

    const firstWorkflow = await readFile(workflowPath, "utf8");
    expect(firstWorkflow.startsWith(`${generatedHeader}\n`)).toBe(true);

    await runCodegen();

    expect(await readFile(workflowPath, "utf8")).toBe(firstWorkflow);
  });

  test("regenerates release.yml idempotently with the generated-file header", async () => {
    await runCodegen();

    const firstWorkflow = await readFile(releaseWorkflowPath, "utf8");
    expect(firstWorkflow.startsWith(`${generatedReleaseHeader}\n`)).toBe(true);

    await runCodegen();

    expect(await readFile(releaseWorkflowPath, "utf8")).toBe(firstWorkflow);
  });

  test("uses .bun-version file as the Bun version source, not package.json engines.bun", async () => {
    await runCodegen();

    const workflow = await readFile(workflowPath, "utf8");

    // All generated jobs must reference the .bun-version file, not a hardcoded version string
    const versionFileMatches = (workflow.match(/bun-version-file: .bun-version/g) ?? []).length;
    expect(versionFileMatches).toBe(7);
    expect(workflow).not.toContain("bun-version: ");

    // Mutating package.json engines.bun must NOT change the generated workflow
    const originalPackageJson = await readFile(packageJsonPath, "utf8");
    const mutatedPackageJson = originalPackageJson.replace('"bun": ">=1.3.14"', '"bun": ">=9.8.7"');
    expect(mutatedPackageJson).not.toBe(originalPackageJson);

    try {
      await writeFile(packageJsonPath, mutatedPackageJson);
      await runCodegen();

      const updatedWorkflow = await readFile(workflowPath, "utf8");
      expect(changedLines(workflow, updatedWorkflow)).toEqual([]);
    } finally {
      await writeFile(packageJsonPath, originalPackageJson);
      await runCodegen();
    }
  });

  test("generates schema-snapshot and bundled-codegen drift gates", async () => {
    await runCodegen();

    const workflow = await readFile(workflowPath, "utf8");

    expect(workflow).toContain("schema-snapshot:");
    expect(workflow).toContain("- name: Regenerate schema snapshot");
    expect(workflow).toContain("run: bun run codegen:schema-snapshot");
    expect(workflow).toContain("run: git diff --exit-code -- sdk/test/fixtures/schema-snapshot.json");

    expect(workflow).toContain("bundled-codegen:");
    expect(workflow).toContain("- name: Regenerate bundled plugins");
    expect(workflow).toContain("run: bun run codegen:bundled-plugins");
    expect(workflow).toContain("- name: Regenerate bundled recipes");
    expect(workflow).toContain("run: bun run codegen:bundled-recipes");
    expect(workflow).toContain(
      "run: git diff --exit-code -- core/src/plugins/bundled.ts core/src/recipes/bundled.ts",
    );
    expect(workflow).toContain(
      "needs: [static-checks, schema-snapshot, bundled-codegen, library-api-tests, recipe-tests]",
    );
  });

  test("generates named library API and recipe test layers", async () => {
    await runCodegen();

    const workflow = await readFile(workflowPath, "utf8");

    expect(workflow).toContain("library-api-tests:");
    expect(workflow).toContain("- name: Run library API tests");
    expect(workflow).toContain("run: bun test core/test/library sdk/test/library");

    expect(workflow).toContain("recipe-tests:");
    expect(workflow).toContain("- name: Run recipe test layer");
    expect(workflow).toContain(
      "run: bun test core/test/recipes core/test/cli/init.canonical-recipes.test.ts",
    );
    expect(workflow).toContain(
      "needs: [static-checks, schema-snapshot, bundled-codegen, library-api-tests, recipe-tests]",
    );
  });

  test("generates a Linux x64 dev prerelease workflow", async () => {
    await runCodegen();

    const workflow = await readFile(releaseWorkflowPath, "utf8");

    expect(workflow).toContain("name: release");
    expect(workflow).toContain("workflow_run:");
    expect(workflow).toContain("workflows: [ci]");
    expect(workflow).toContain("branches: [main]");
    expect(workflow).toContain("contents: write");
    expect(workflow).toContain("actions: read");
    expect(workflow).toContain("dev-prerelease-linux-x64:");
    expect(workflow).toContain("github.event.workflow_run.conclusion == 'success'");
    expect(workflow).toContain(
      'gh run download "${{ github.event.workflow_run.id }}" --name lando-linux-x64 --dir dist',
    );
    expect(workflow).toContain("sudo apt-get install -y strace iproute2");
    expect(workflow).toContain("sudo env");
    expect(workflow).toContain("unshare --net sh -c");
    expect(workflow).toContain("strace -f -e trace=network");
    expect(workflow).toContain("first-launch.network.log");
    expect(workflow).toContain("awk '/connect\\(/ && $0 !~ /(127\\.|::1|AF_UNIX)/");
    expect(workflow).toContain("sha256sum lando > SHA256SUMS");
    expect(workflow).toContain("grep -Eq '^[0-9a-f]{64}  lando$' SHA256SUMS");
    expect(workflow).toContain("RELEASE_TAG: v4.0.0-dev.${{ github.run_number }}");
    expect(workflow).toContain('gh release create "$RELEASE_TAG" dist/lando dist/SHA256SUMS --prerelease');
    expect(workflow).toContain("--prerelease");
    expect(workflow).not.toContain("cosign");
    expect(workflow).not.toContain("gpg");
    expect(workflow).not.toContain("sbom");
    expect(workflow).not.toContain("installer");
    expect(workflow).not.toContain("update-manifest");
  });
});
