export const renderMinimal = (): string =>
  [
    'import { Context, Layer } from "effect";',
    "",
    'import { bundledPluginModules } from "@lando/engine/composition";',
    'import * as DeprecationServiceLayer from "@lando/engine/deprecation/service";',
    'import * as DeprecationTelemetry from "@lando/engine/deprecation/telemetry";',
    'import * as AppCacheService from "@lando/engine/cache/service";',
    'import * as VerifiedDownloader from "@lando/http-client/downloader";',
    'import * as LandoHttpClient from "@lando/http-client";',
    'import * as InteractionServiceLayer from "../../../interaction/service.ts";',
    'import * as LandoLogger from "@lando/engine/logging/service";',
    'import * as ManagedFileLayer from "@lando/managed-file/service";',
    'import * as ManagedFileTransactionGuardLayer from "@lando/managed-file/transaction-guard";',
    'import * as PluginTrustStoreLayer from "@lando/engine/plugins/trust-store";',
    'import { makeHostMaintenanceRegistryLayer } from "@lando/engine/runtime/host-maintenance";',
    'import * as LandoConfigService from "@lando/engine/services/config";',
    'import * as LandoEventService from "@lando/engine/services/event-service";',
    'import * as BunFileSystem from "@lando/engine/services/file-system";',
    'import * as BunProcessRunner from "@lando/engine/services/process-runner";',
    'import * as HostPrivilegeService from "@lando/engine/services/privilege";',
    'import { RedactionService } from "@lando/redaction/service";',
    'import * as RoutedSecretStore from "@lando/engine/services/secret-store-registry";',
    'import * as StateStoreLayer from "@lando/state-store/service";',
    'import { PrivateFileAccessService } from "@lando/state-store/private-file-access";',
    'import * as TelemetryLayer from "@lando/telemetry/service";',
    'import { makeLandoPaths } from "@lando/paths";',
    'import { EventService, PathsService, Renderer } from "@lando/sdk/services";',
    'import { makeLibraryRenderer, type BootstrapLayerInputs } from "@lando/engine/runtime/bootstrap-layer-support";',
    'import { makeNoneBootstrapLayer } from "./none.ts";',
    "",
    "export const makeMinimalBootstrapLayer = (inputs: BootstrapLayerInputs) => {",
    "  const noneRuntimeLayer = makeNoneBootstrapLayer(inputs);",
    "  const telemetryLayer = TelemetryLayer.layer(inputs.telemetryEnabled);",
    "  const pathsLayer = Layer.succeed(PathsService, makeLandoPaths(inputs.rootOverrides));",
    "  const secretStoreLayer = RoutedSecretStore.layer.pipe(Layer.provide(Layer.mergeAll(",
    "    RoutedSecretStore.SecretStoreRegistry.layer(bundledPluginModules()), LandoConfigService.layer, BunProcessRunner.layer, BunFileSystem.layer, pathsLayer,",
    "  )));",
    "  const redactionLayer = RedactionService.layer.pipe(Layer.provide(secretStoreLayer));",
    "  const privateFileAccessLayer = PrivateFileAccessService.layer;",
    "  const eventServiceLayer = LandoEventService.layerRuntimeWithConfig().pipe(",
    "    Layer.provide(Layer.mergeAll(LandoConfigService.layer, redactionLayer)),",
    "    Layer.tap((context) => inputs.lifecycle.useBaseEventService(Context.get(context, EventService))),",
    "  );",
    "  const httpClientLayer = LandoHttpClient.layer.pipe(",
    "    Layer.provide(Layer.mergeAll(LandoConfigService.layer, eventServiceLayer)),",
    "  );",
    "",
    "  const minimalRuntimeLayer = Layer.mergeAll(",
    "    noneRuntimeLayer,",
    "    LandoLogger.layer({ mode: inputs.loggerMode, logLevel: inputs.logLevel, structured: inputs.structured, ...(inputs.writeDiagnosticLine === undefined ? {} : { writeLine: inputs.writeDiagnosticLine }), ...(inputs.stderrIsTTY === undefined ? {} : { stderrIsTTY: inputs.stderrIsTTY }) }),",
    "    Layer.succeed(Renderer, makeLibraryRenderer(inputs.rendererMode)),",
    "    pathsLayer,",
    "    telemetryLayer,",
    "    privateFileAccessLayer,",
    "    LandoConfigService.layer,",
    "    eventServiceLayer,",
    "    DeprecationServiceLayer.layer.pipe(Layer.provide(eventServiceLayer)),",
    "    DeprecationTelemetry.layer.pipe(Layer.provide(Layer.mergeAll(eventServiceLayer, telemetryLayer))),",
    "    PluginTrustStoreLayer.layer.pipe(Layer.provide(LandoConfigService.layer)),",
    "    makeHostMaintenanceRegistryLayer(bundledPluginModules()),",
    "    AppCacheService.layerWithPrivateFileAccess.pipe(Layer.provide(privateFileAccessLayer)),",
    "    BunFileSystem.layer,",
    "    BunProcessRunner.layer,",
    "    HostPrivilegeService.layer,",
    "    secretStoreLayer,",
    "    StateStoreLayer.layerWithPrivateFileAccess.pipe(Layer.provide(privateFileAccessLayer)),",
    "    ManagedFileTransactionGuardLayer.layerWithPrivateFileAccess.pipe(Layer.provide(privateFileAccessLayer)),",
    "    redactionLayer,",
    "    Layer.suspend(() => ManagedFileLayer.layerServicesWithPrivateFileAccess).pipe(",
    "      Layer.provide(Layer.mergeAll(eventServiceLayer, redactionLayer, privateFileAccessLayer)),",
    "    ),",
    "    Layer.suspend(() => InteractionServiceLayer.layer),",
    "    httpClientLayer,",
    "    VerifiedDownloader.layer.pipe(Layer.provide(Layer.mergeAll(httpClientLayer, eventServiceLayer))),",
    "  );",
    "  return minimalRuntimeLayer.pipe(",
    '    Layer.tap((context) => inputs.lifecycle.complete("minimal", Context.get(context, EventService))),',
    "  );",
    "};",
    "",
  ].join("\n");

export const renderCommands = (): string =>
  [
    'import { Context, Effect, Layer } from "effect";',
    "",
    'import { EventService, PathsService } from "@lando/sdk/services";',
    'import { bundledPluginModules, landofileRuntimeInputs } from "@lando/engine/composition";',
    'import * as EngineLandofileServiceLayer from "@lando/engine/services/landofile-live";',
    'import * as SubscriberRuntimeLayer from "@lando/engine/lifecycle/subscribers";',
    'import * as CommandRegistryLayer from "@lando/engine/services/command-registry";',
    'import type { BootstrapLayerInputs } from "@lando/engine/runtime/bootstrap-layer-support";',
    'import { BUILT_IN_COMMAND_IDS } from "../../../cli/generated/command-ids.ts";',
    'import { makePluginsBootstrapBaseLayer } from "./plugins.ts";',
    'import { commandAliasRegistrationError } from "../../../cli/command-alias-policy.ts";',
    "",
    "export const makeCommandsBootstrapBaseLayer = (inputs: BootstrapLayerInputs) => {",
    "  const pluginsBase = makePluginsBootstrapBaseLayer(inputs);",
    "  const landofileServiceLayer = Layer.unwrap(Effect.map(PathsService, (paths) => {",
    "    const runtimeInputs = landofileRuntimeInputs();",
    "    return EngineLandofileServiceLayer.layer({",
    "      ...runtimeInputs,",
    "      ports: {",
    "        ...runtimeInputs.ports,",
    "        resolveUserIncludesDir: () => paths.userIncludesDir,",
    "        resolveUserCacheRoot: () => paths.roots.userCacheRoot,",
    "      },",
    "    });",
    "  })).pipe(Layer.provide(pluginsBase));",
    "  const commandRegistryLayer = CommandRegistryLayer.layerWith((policy, entries) =>",
    "    commandAliasRegistrationError(policy, entries.map((entry) => entry.id), entries),",
    "  ).pipe(",
    "    Layer.provide(Layer.mergeAll(landofileServiceLayer, pluginsBase)),",
    "  );",
    "  return Layer.mergeAll(pluginsBase, landofileServiceLayer, commandRegistryLayer).pipe(",
    '    Layer.tap((context) => inputs.lifecycle.complete("commands", Context.get(context, EventService))),',
    "  );",
    "};",
    "",
    "export const makeCommandsBootstrapLayer = (inputs: BootstrapLayerInputs) => {",
    "  const commandsBase = makeCommandsBootstrapBaseLayer(inputs);",
    "  const subscriberRuntimeLayer = SubscriberRuntimeLayer.layerWithPrivateFileAccess(bundledPluginModules(), BUILT_IN_COMMAND_IDS).pipe(Layer.provide(commandsBase));",
    "  return Layer.merge(commandsBase, subscriberRuntimeLayer);",
    "};",
    "",
  ].join("\n");

export const renderProvider = (): string =>
  [
    'import { Context, Effect, Layer } from "effect";',
    "",
    'import { EventService, RuntimeProvider } from "@lando/sdk/services";',
    'import { LandoRuntimeBootstrapError } from "@lando/sdk/errors";',
    'import { bundledPluginModules } from "@lando/engine/composition";',
    'import * as BunDataMover from "@lando/data-mover/service";',
    'import * as GlobalAppServiceLayer from "@lando/engine/global-app/service";',
    'import * as GlobalAppRuntimeLayer from "@lando/engine/global-app/runtime";',
    'import * as CertificateAuthorityResolverLayer from "@lando/engine/plugins/certificate-authority-resolver";',
    'import * as SubscriberRuntimeLayer from "@lando/engine/lifecycle/subscribers";',
    'import { makeRuntimeProviderRegistryWithPrivateFileAccess } from "@lando/engine/providers/registry";',
    'import * as LogFileHelperAssetsLayer from "@lando/engine/providers/log-file-helper-payloads";',
    'import * as LandoConfigService from "@lando/engine/services/config";',
    'import * as BunFileSystem from "@lando/engine/services/file-system";',
    'import * as AppPlannerLayer from "@lando/engine/services/planner";',
    'import * as BuildOrchestratorLayer from "@lando/engine/services/build-orchestrator";',
    'import * as ProviderUrlScanner from "@lando/engine/subsystems/scanner/live";',
    'import * as AppPlanSanitizerLayer from "@lando/engine/subsystems/host-proxy/plan-sanitizer-live";',
    'import * as RouterServiceRegistryLayer from "@lando/engine/subsystems/proxy/registry";',
    'import * as SshServiceRegistryLayer from "@lando/engine/subsystems/ssh/registry";',
    'import { runtimeProviderService, type BootstrapLayerInputs } from "@lando/engine/runtime/bootstrap-layer-support";',
    'import { BUILT_IN_COMMAND_IDS } from "../../../cli/generated/command-ids.ts";',
    'import { makeCommandsBootstrapBaseLayer } from "./commands.ts";',
    "",
    "export const makeProviderBootstrapBaseLayer = (inputs: BootstrapLayerInputs) => {",
    "  // Effect 4 memoizes leaf layers, not composite traversal. Share this dependency graph too.",
    "  const pluginsRuntimeLayer = Layer.suspend(() => makeCommandsBootstrapBaseLayer(inputs));",
    "  const providerSupportLayer = Layer.mergeAll(AppPlanSanitizerLayer.layer, LogFileHelperAssetsLayer.layer);",
    "  const providerRegistryLayer = makeRuntimeProviderRegistryWithPrivateFileAccess(bundledPluginModules()).pipe(",
    "    Layer.provide(Layer.mergeAll(pluginsRuntimeLayer, providerSupportLayer)),",
    "  );",
    "",
    "  const runtimeProviderLayer = Layer.succeed(RuntimeProvider, runtimeProviderService);",
    "  const urlScannerLayer = ProviderUrlScanner.layer.pipe(",
    "    Layer.provide(Layer.mergeAll(runtimeProviderLayer, pluginsRuntimeLayer)),",
    "  );",
    "  const certificateAuthorityResolverLayer = CertificateAuthorityResolverLayer.CertificateAuthorityResolver.layer.pipe(",
    "    Layer.provide(pluginsRuntimeLayer),",
    "  );",
    "",
    "  const globalAppServiceLayer = GlobalAppServiceLayer.layer.pipe(Layer.provide(Layer.mergeAll(LandoConfigService.layer, BunFileSystem.layer)));",
    "  const baseProviderLayer = Layer.mergeAll(",
    "    pluginsRuntimeLayer,",
    "    providerSupportLayer,",
    "    runtimeProviderLayer,",
    "    certificateAuthorityResolverLayer,",
    "    urlScannerLayer,",
    "    BunDataMover.layer.pipe(Layer.provide(Layer.mergeAll(runtimeProviderLayer, pluginsRuntimeLayer))),",
    "    providerRegistryLayer,",
    "    globalAppServiceLayer,",
    "  );",
    "  const appPlannerLayer = AppPlannerLayer.layer.pipe(Layer.provide(baseProviderLayer));",
    "  const buildOrchestratorLayer = BuildOrchestratorLayer.layer.pipe(Layer.provide(baseProviderLayer));",
    "  const globalAppRuntimeLayer = GlobalAppRuntimeLayer.layer.pipe(Layer.provide(Layer.mergeAll(baseProviderLayer, appPlannerLayer, buildOrchestratorLayer)));",
    "  const routerRegistryLayer = Layer.fromBuildMemo((memoMap, scope) => Layer.buildWithMemoMap(RouterServiceRegistryLayer.RouterServiceRegistry.layerWith(bundledPluginModules()).pipe(",
    "    Layer.provide(Layer.mergeAll(baseProviderLayer, globalAppRuntimeLayer)),",
    "  ), memoMap, scope).pipe(",
    "    Effect.mapError((cause) =>",
    '      new LandoRuntimeBootstrapError({ message: cause instanceof Error ? cause.message : "RouterService bootstrap failed.", stage: "provider", cause }),',
    "    ),",
    "  ));",
    "  const routerServiceLayer = Layer.fromBuildMemo((memoMap, scope) => Layer.buildWithMemoMap(RouterServiceRegistryLayer.layerSelected.pipe(",
    "    Layer.provide(Layer.mergeAll(baseProviderLayer, globalAppRuntimeLayer, routerRegistryLayer)),",
    "  ), memoMap, scope).pipe(",
    "    Effect.mapError((cause) =>",
    '      new LandoRuntimeBootstrapError({ message: cause instanceof Error ? cause.message : "RouterService bootstrap failed.", stage: "provider", cause }),',
    "    ),",
    "  ));",
    "  const sshRegistryLayer = Layer.fromBuildMemo((memoMap, scope) => Layer.buildWithMemoMap(SshServiceRegistryLayer.SshServiceRegistry.layerWith(bundledPluginModules()).pipe(",
    "    Layer.provide(Layer.mergeAll(baseProviderLayer, globalAppRuntimeLayer)),",
    "  ), memoMap, scope).pipe(",
    "    Effect.mapError((cause) =>",
    '      new LandoRuntimeBootstrapError({ message: cause instanceof Error ? cause.message : "SshService bootstrap failed.", stage: "provider", cause }),',
    "    ),",
    "  ));",
    "  const sshServiceLayer = Layer.fromBuildMemo((memoMap, scope) => Layer.buildWithMemoMap(SshServiceRegistryLayer.layerSelected.pipe(",
    "    Layer.provide(Layer.mergeAll(baseProviderLayer, globalAppRuntimeLayer, sshRegistryLayer)),",
    "  ), memoMap, scope).pipe(",
    "    Effect.mapError((cause) =>",
    '      new LandoRuntimeBootstrapError({ message: cause instanceof Error ? cause.message : "SshService bootstrap failed.", stage: "provider", cause }),',
    "    ),",
    "  ));",
    "",
    "  return Layer.mergeAll(",
    "    baseProviderLayer,",
    "    appPlannerLayer,",
    "    buildOrchestratorLayer,",
    "    globalAppRuntimeLayer,",
    "    routerRegistryLayer,",
    "    routerServiceLayer,",
    "    sshRegistryLayer,",
    "    sshServiceLayer,",
    "  ).pipe(",
    '    Layer.tap((context) => inputs.lifecycle.complete("provider", Context.get(context, EventService))),',
    "  );",
    "};",
    "",
    "export const makeProviderBootstrapLayer = (inputs: BootstrapLayerInputs) => {",
    "  const providerBase = makeProviderBootstrapBaseLayer(inputs);",
    "  const subscriberRuntimeLayer = SubscriberRuntimeLayer.layerWithPrivateFileAccess(bundledPluginModules(), BUILT_IN_COMMAND_IDS).pipe(Layer.provide(providerBase));",
    "  return Layer.merge(providerBase, subscriberRuntimeLayer);",
    "};",
    "",
  ].join("\n");

export const renderIndex = (): string =>
  [
    'import { Effect, Layer, Option } from "effect";',
    "",
    'import type { BootstrapLevel } from "@lando/sdk/schema";',
    'import { EventService } from "@lando/sdk/services";',
    'import { withPluginLayerOverrides } from "@lando/engine/plugins/contribution-graph";',
    'import { superviseBootstrapLayer } from "@lando/engine/runtime/bootstrap-lifecycle";',
    'import type { BootstrapLayerInputs } from "@lando/engine/runtime/bootstrap-layer-support";',
    'import { makeNoneBootstrapLayer } from "./none.ts";',
    'import { makeMinimalBootstrapLayer } from "./minimal.ts";',
    'import { makePluginsBootstrapBaseLayer } from "./plugins.ts";',
    'import { makeCommandsBootstrapLayer } from "./commands.ts";',
    'import { makeToolingBootstrapLayer } from "./tooling.ts";',
    'import { makeProviderBootstrapLayer } from "./provider.ts";',
    'import { makeGlobalBootstrapLayer } from "./global.ts";',
    'import { makeScratchBootstrapLayer } from "./scratch.ts";',
    'import { makeAppBootstrapLayer } from "./app.ts";',
    "",
    "export const makeGeneratedBootstrapLayer = (bootstrap: BootstrapLevel, inputs: BootstrapLayerInputs) => {",
    "  switch (bootstrap) {",
    '    case "none":',
    "      return makeNoneBootstrapLayer(inputs);",
    '    case "minimal":',
    "      return makeMinimalBootstrapLayer(inputs);",
    '    case "plugins":',
    "      return withPluginLayerOverrides(makePluginsBootstrapBaseLayer(inputs));",
    '    case "commands":',
    "      return withPluginLayerOverrides(makeCommandsBootstrapLayer(inputs));",
    '    case "tooling":',
    "      return withPluginLayerOverrides(makeToolingBootstrapLayer(inputs));",
    '    case "provider":',
    "      return withPluginLayerOverrides(makeProviderBootstrapLayer(inputs));",
    '    case "global":',
    "      return withPluginLayerOverrides(makeGlobalBootstrapLayer(inputs));",
    '    case "scratch":',
    "      return withPluginLayerOverrides(makeScratchBootstrapLayer(inputs));",
    '    case "app":',
    "      return withPluginLayerOverrides(makeAppBootstrapLayer(inputs));",
    "  }",
    "};",
    "",
    "export const mergeRuntimeWithHostLayers = (",
    "  baseLayer: Layer.Layer<unknown, unknown, unknown>,",
    "  hostLayers: ReadonlyArray<Layer.Layer<unknown, unknown, unknown>>,",
    "  bootstrap: BootstrapLevel,",
    '  lifecycle: BootstrapLayerInputs["lifecycle"],',
    ") => {",
    "  const runtime = hostLayers.reduce((current, hostLayer) => {",
    "    const captureEventService = Layer.effectDiscard(",
    "      Effect.serviceOption(EventService).pipe(",
    "        Effect.flatMap(",
    "          Option.match({",
    "            onNone: () => Effect.void,",
    "            onSome: lifecycle.useEventService,",
    "          }),",
    "        ),",
    "      ),",
    "    );",
    "    const observedHostLayer = captureEventService.pipe(Layer.provideMerge(hostLayer));",
    "    return observedHostLayer.pipe(Layer.provideMerge(current));",
    "  }, baseLayer);",
    '  return bootstrap === "none"',
    "    ? runtime",
    "    : superviseBootstrapLayer(runtime, lifecycle);",
    "};",
    "",
  ].join("\n");
