export const renderMinimal = (): string =>
  [
    'import { Layer } from "effect";',
    "",
    'import { DeprecationServiceLive } from "../../../deprecation/service.ts";',
    'import { DeprecationTelemetryLive } from "../../../deprecation/telemetry.ts";',
    'import { CacheServiceLive } from "../../../cache/service.ts";',
    'import { DownloaderLive } from "../../../downloader/service.ts";',
    'import { HttpClientLive } from "../../../http-client/live.ts";',
    'import { InteractionServiceLive } from "../../../interaction/service.ts";',
    'import { LoggerLive } from "../../../logging/service.ts";',
    'import { ManagedFileServiceLive } from "../../../managed-file/service.ts";',
    'import { PluginTrustStoreLive } from "../../../plugins/trust-store.ts";',
    'import { ConfigServiceLive } from "../../../services/config.ts";',
    'import { EventRuntimeLive } from "../../../services/event-service.ts";',
    'import { FileSystemLive } from "../../../services/file-system.ts";',
    'import { ProcessRunnerLive } from "../../../services/process-runner.ts";',
    'import { PrivilegeServiceLive } from "../../../services/privilege.ts";',
    'import { RedactionServiceLive } from "../../../redaction/service.ts";',
    'import { SecretStoreLive } from "../../../services/secret-store.ts";',
    'import { StateStoreLive } from "../../../state/service.ts";',
    'import { makeTelemetryLayer } from "../../../telemetry/service.ts";',
    'import { makeLandoPaths } from "../../../config/paths.ts";',
    'import { PathsService, Renderer } from "@lando/sdk/services";',
    'import { makeLibraryRenderer, type BootstrapLayerInputs } from "../../bootstrap-layer-support.ts";',
    "",
    "export const makeMinimalBootstrapLayer = (inputs: BootstrapLayerInputs) => {",
    "  const telemetryLive = makeTelemetryLayer(inputs.telemetryEnabled);",
    "  const redactionLive = RedactionServiceLive.pipe(Layer.provide(SecretStoreLive));",
    "  const eventServiceLive = EventRuntimeLive.pipe(Layer.provide(redactionLive));",
    "  const httpClientLive = HttpClientLive.pipe(",
    "    Layer.provide(Layer.mergeAll(ConfigServiceLive, eventServiceLive)),",
    "  );",
    "",
    "  const minimalRuntimeLive = Layer.mergeAll(",
    "    LoggerLive({ mode: inputs.loggerMode }),",
    "    Layer.succeed(Renderer, makeLibraryRenderer(inputs.rendererMode)),",
    "    Layer.succeed(PathsService, makeLandoPaths(inputs.rootOverrides)),",
    "    telemetryLive,",
    "    ConfigServiceLive,",
    "    eventServiceLive,",
    "    DeprecationServiceLive.pipe(Layer.provide(eventServiceLive)),",
    "    DeprecationTelemetryLive.pipe(Layer.provide(Layer.mergeAll(eventServiceLive, telemetryLive))),",
    "    PluginTrustStoreLive.pipe(Layer.provide(ConfigServiceLive)),",
    "    CacheServiceLive,",
    "    FileSystemLive,",
    "    ProcessRunnerLive,",
    "    PrivilegeServiceLive,",
    "    SecretStoreLive,",
    "    StateStoreLive,",
    "    redactionLive,",
    "    Layer.suspend(() => ManagedFileServiceLive).pipe(",
    "      Layer.provide(Layer.mergeAll(eventServiceLive, redactionLive)),",
    "    ),",
    "    Layer.suspend(() => InteractionServiceLive),",
    "    httpClientLive,",
    "    DownloaderLive.pipe(Layer.provide(httpClientLive)),",
    "  );",
    "  return minimalRuntimeLive;",
    "};",
    "",
  ].join("\n");

export const renderCommands = (): string =>
  [
    'import { Layer } from "effect";',
    "",
    'import { LandofileServiceLive } from "../../../landofile/service.ts";',
    'import { makeSubscriberRuntimeLive } from "../../../lifecycle/subscribers.ts";',
    'import { CommandRegistryLive } from "../../../services/command-registry.ts";',
    'import type { BootstrapLayerInputs } from "../../bootstrap-layer-support.ts";',
    'import { makePluginsBootstrapBaseLayer } from "./plugins.ts";',
    "",
    "export const makeCommandsBootstrapBaseLayer = (inputs: BootstrapLayerInputs) => {",
    "  const pluginsBase = makePluginsBootstrapBaseLayer(inputs);",
    "  const commandRegistryLive = CommandRegistryLive.pipe(",
    "    Layer.provide(Layer.mergeAll(LandofileServiceLive, pluginsBase)),",
    "  );",
    "  return Layer.mergeAll(pluginsBase, LandofileServiceLive, commandRegistryLive);",
    "};",
    "",
    "export const makeCommandsBootstrapLayer = (inputs: BootstrapLayerInputs) => {",
    "  const commandsBase = makeCommandsBootstrapBaseLayer(inputs);",
    "  const subscriberRuntimeLive = makeSubscriberRuntimeLive().pipe(Layer.provide(commandsBase));",
    "  return Layer.merge(commandsBase, subscriberRuntimeLive);",
    "};",
    "",
  ].join("\n");

export const renderProvider = (): string =>
  [
    'import { Layer } from "effect";',
    "",
    'import { RuntimeProvider } from "@lando/sdk/services";',
    'import { DataMoverLive } from "../../../data-mover/service.ts";',
    'import { GlobalAppServiceLive } from "../../../global-app/service.ts";',
    'import { makeSubscriberRuntimeLive } from "../../../lifecycle/subscribers.ts";',
    'import { RuntimeProviderRegistryLive } from "../../../providers/registry.ts";',
    'import { ConfigServiceLive } from "../../../services/config.ts";',
    'import { FileSystemLive } from "../../../services/file-system.ts";',
    'import { UrlScannerLive } from "../../../subsystems/scanner/live.ts";',
    'import { runtimeProviderService, type BootstrapLayerInputs } from "../../bootstrap-layer-support.ts";',
    'import { makeCommandsBootstrapBaseLayer } from "./commands.ts";',
    "",
    "export const makeProviderBootstrapBaseLayer = (inputs: BootstrapLayerInputs) => {",
    "  const pluginsRuntimeLive = makeCommandsBootstrapBaseLayer(inputs);",
    "  const providerRegistryLive = RuntimeProviderRegistryLive.pipe(",
    "    Layer.provide(pluginsRuntimeLive),",
    "  );",
    "",
    "  const runtimeProviderLive = Layer.succeed(RuntimeProvider, runtimeProviderService);",
    "  const urlScannerLive = UrlScannerLive.pipe(",
    "    Layer.provide(Layer.mergeAll(runtimeProviderLive, pluginsRuntimeLive)),",
    "  );",
    "",
    "  return Layer.mergeAll(",
    "    pluginsRuntimeLive,",
    "    runtimeProviderLive,",
    "    urlScannerLive,",
    "    DataMoverLive.pipe(",
    "      Layer.provide(",
    "        Layer.mergeAll(",
    "          runtimeProviderLive,",
    "          pluginsRuntimeLive,",
    "        ),",
    "      ),",
    "    ),",
    "    providerRegistryLive,",
    "    GlobalAppServiceLive.pipe(Layer.provide(Layer.mergeAll(ConfigServiceLive, FileSystemLive))),",
    "  );",
    "};",
    "",
    "export const makeProviderBootstrapLayer = (inputs: BootstrapLayerInputs) => {",
    "  const providerBase = makeProviderBootstrapBaseLayer(inputs);",
    "  const subscriberRuntimeLive = makeSubscriberRuntimeLive().pipe(Layer.provide(providerBase));",
    "  return Layer.merge(providerBase, subscriberRuntimeLive);",
    "};",
    "",
  ].join("\n");
