export const renderMinimal = (): string =>
  [
    'import { Context, Layer } from "effect";',
    "",
    'import { bundledPluginModules } from "@lando/engine/composition";',
    'import { DeprecationServiceLive } from "@lando/engine/deprecation/service";',
    'import { DeprecationTelemetryLive } from "@lando/engine/deprecation/telemetry";',
    'import { CacheServiceLive } from "@lando/engine/cache/service";',
    'import { DownloaderLive } from "@lando/http-client/downloader";',
    'import { HttpClientLive } from "@lando/http-client/live";',
    'import { InteractionServiceLive } from "../../../interaction/service.ts";',
    'import { LoggerLive } from "@lando/engine/logging/service";',
    'import { ManagedFileServiceLive } from "@lando/managed-file/service";',
    'import { PluginTrustStoreLive } from "@lando/engine/plugins/trust-store";',
    'import { makeHostMaintenanceRegistryLayer } from "@lando/engine/runtime/host-maintenance";',
    'import { ConfigServiceLive } from "@lando/engine/services/config";',
    'import { makeEventRuntimeLive } from "@lando/engine/services/event-service";',
    'import { FileSystemLive } from "@lando/engine/services/file-system";',
    'import { ProcessRunnerLive } from "@lando/engine/services/process-runner";',
    'import { PrivilegeServiceLive } from "@lando/engine/services/privilege";',
    'import { RedactionServiceLive } from "@lando/redaction/service";',
    'import { SecretStoreLive } from "@lando/engine/services/secret-store";',
    'import { StateStoreLive } from "@lando/state-store/service";',
    'import { makeTelemetryLayer } from "@lando/engine/telemetry/service";',
    'import { makeLandoPaths } from "@lando/paths";',
    'import { EventService, PathsService, Renderer } from "@lando/sdk/services";',
    'import { makeLibraryRenderer, type BootstrapLayerInputs } from "@lando/engine/runtime/bootstrap-layer-support";',
    "",
    "export const makeMinimalBootstrapLayer = (inputs: BootstrapLayerInputs) => {",
    "  const telemetryLive = makeTelemetryLayer(inputs.telemetryEnabled);",
    "  const redactionLive = RedactionServiceLive.pipe(Layer.provide(SecretStoreLive));",
    "  const eventServiceLive = makeEventRuntimeLive().pipe(",
    "    Layer.provide(Layer.mergeAll(ConfigServiceLive, redactionLive)),",
    "    Layer.tap((context) => inputs.lifecycle.useBaseEventService(Context.get(context, EventService))),",
    "  );",
    "  const httpClientLive = HttpClientLive.pipe(",
    "    Layer.provide(Layer.mergeAll(ConfigServiceLive, eventServiceLive)),",
    "  );",
    "",
    "  const minimalRuntimeLive = Layer.mergeAll(",
    "    LoggerLive({ mode: inputs.loggerMode }),",
    "    Layer.succeed(Renderer, makeLibraryRenderer(inputs.rendererMode)),",
    "    Layer.succeed(PathsService, makeLandoPaths(inputs.rootOverrides)),",
    "    telemetryLive,",
    "    ConfigServiceLive,",
    "    eventServiceLive,",
    "    DeprecationServiceLive.pipe(Layer.provide(eventServiceLive)),",
    "    DeprecationTelemetryLive.pipe(Layer.provide(Layer.mergeAll(eventServiceLive, telemetryLive))),",
    "    PluginTrustStoreLive.pipe(Layer.provide(ConfigServiceLive)),",
    "    makeHostMaintenanceRegistryLayer(bundledPluginModules()),",
    "    CacheServiceLive,",
    "    FileSystemLive,",
    "    ProcessRunnerLive,",
    "    PrivilegeServiceLive,",
    "    SecretStoreLive,",
    "    StateStoreLive,",
    "    redactionLive,",
    "    Layer.suspend(() => ManagedFileServiceLive).pipe(",
    "      Layer.provide(Layer.mergeAll(eventServiceLive, redactionLive)),",
    "    ),",
    "    Layer.suspend(() => InteractionServiceLive),",
    "    httpClientLive,",
    "    DownloaderLive.pipe(Layer.provide(httpClientLive)),",
    "  );",
    "  return minimalRuntimeLive.pipe(",
    '    Layer.tap((context) => inputs.lifecycle.complete("minimal", Context.get(context, EventService))),',
    "  );",
    "};",
    "",
  ].join("\n");

export const renderCommands = (): string =>
  [
    'import { Context, Layer } from "effect";',
    "",
    'import { EventService } from "@lando/sdk/services";',
    'import { bundledPluginModules, landofileRuntimeInputs } from "@lando/engine/composition";',
    'import { makeEngineLandofileServiceLive } from "@lando/engine/services/landofile-live";',
    'import { makeSubscriberRuntimeLive } from "@lando/engine/lifecycle/subscribers";',
    'import { CommandRegistryLive } from "@lando/engine/services/command-registry";',
    'import type { BootstrapLayerInputs } from "@lando/engine/runtime/bootstrap-layer-support";',
    'import { BUILT_IN_COMMAND_IDS } from "../../../cli/generated/command-ids.ts";',
    'import { makePluginsBootstrapBaseLayer } from "./plugins.ts";',
    "",
    "export const makeCommandsBootstrapBaseLayer = (inputs: BootstrapLayerInputs) => {",
    "  const pluginsBase = makePluginsBootstrapBaseLayer(inputs);",
    "  const landofileServiceLive = makeEngineLandofileServiceLive(landofileRuntimeInputs());",
    "  const commandRegistryLive = CommandRegistryLive.pipe(",
    "    Layer.provide(Layer.mergeAll(landofileServiceLive, pluginsBase)),",
    "  );",
    "  return Layer.mergeAll(pluginsBase, landofileServiceLive, commandRegistryLive).pipe(",
    '    Layer.tap((context) => inputs.lifecycle.complete("commands", Context.get(context, EventService))),',
    "  );",
    "};",
    "",
    "export const makeCommandsBootstrapLayer = (inputs: BootstrapLayerInputs) => {",
    "  const commandsBase = makeCommandsBootstrapBaseLayer(inputs);",
    "  const subscriberRuntimeLive = makeSubscriberRuntimeLive(bundledPluginModules(), BUILT_IN_COMMAND_IDS).pipe(Layer.provide(commandsBase));",
    "  return Layer.merge(commandsBase, subscriberRuntimeLive);",
    "};",
    "",
  ].join("\n");

export const renderProvider = (): string =>
  [
    'import { Context, Layer } from "effect";',
    "",
    'import { EventService, RuntimeProvider } from "@lando/sdk/services";',
    'import { LandoRuntimeBootstrapError } from "@lando/sdk/errors";',
    'import { bundledPluginModules } from "@lando/engine/composition";',
    'import { DataMoverLive } from "@lando/engine/data-mover/service";',
    'import { GlobalAppServiceLive } from "@lando/engine/global-app/service";',
    'import { GlobalAppRuntimeLive } from "@lando/engine/global-app/runtime";',
    'import { CertificateAuthorityResolverLive } from "@lando/engine/plugins/certificate-authority-resolver";',
    'import { makeSubscriberRuntimeLive } from "@lando/engine/lifecycle/subscribers";',
    'import { makeRuntimeProviderRegistry } from "@lando/engine/providers/registry";',
    'import { LogFileHelperAssetsLive } from "@lando/engine/providers/log-file-helper-payloads";',
    'import { ConfigServiceLive } from "@lando/engine/services/config";',
    'import { FileSystemLive } from "@lando/engine/services/file-system";',
    'import { AppPlannerLive } from "@lando/engine/services/planner";',
    'import { BuildOrchestratorLive } from "@lando/engine/services/build-orchestrator";',
    'import { UrlScannerLive } from "@lando/engine/subsystems/scanner/live";',
    'import { AppPlanSanitizerLive } from "@lando/engine/subsystems/host-proxy/plan-sanitizer-live";',
    'import { makeProxyServiceRegistryLive, SelectedProxyServiceLive } from "@lando/engine/subsystems/proxy/registry";',
    'import { makeSshServiceRegistryLive, SelectedSshServiceLive } from "@lando/engine/subsystems/ssh/registry";',
    'import { runtimeProviderService, type BootstrapLayerInputs } from "@lando/engine/runtime/bootstrap-layer-support";',
    'import { BUILT_IN_COMMAND_IDS } from "../../../cli/generated/command-ids.ts";',
    'import { makeCommandsBootstrapBaseLayer } from "./commands.ts";',
    "",
    "export const makeProviderBootstrapBaseLayer = (inputs: BootstrapLayerInputs) => {",
    "  const pluginsRuntimeLive = makeCommandsBootstrapBaseLayer(inputs);",
    "  const providerSupportLive = Layer.mergeAll(AppPlanSanitizerLive, LogFileHelperAssetsLive);",
    "  const providerRegistryLive = makeRuntimeProviderRegistry(bundledPluginModules()).pipe(",
    "    Layer.provide(Layer.mergeAll(pluginsRuntimeLive, providerSupportLive)),",
    "  );",
    "",
    "  const runtimeProviderLive = Layer.succeed(RuntimeProvider, runtimeProviderService);",
    "  const urlScannerLive = UrlScannerLive.pipe(",
    "    Layer.provide(Layer.mergeAll(runtimeProviderLive, pluginsRuntimeLive)),",
    "  );",
    "  const certificateAuthorityResolverLive = CertificateAuthorityResolverLive.pipe(",
    "    Layer.provide(pluginsRuntimeLive),",
    "  );",
    "",
    "  const globalAppServiceLive = GlobalAppServiceLive.pipe(Layer.provide(Layer.mergeAll(ConfigServiceLive, FileSystemLive)));",
    "  const baseProviderLayer = Layer.mergeAll(",
    "    pluginsRuntimeLive,",
    "    providerSupportLive,",
    "    runtimeProviderLive,",
    "    certificateAuthorityResolverLive,",
    "    urlScannerLive,",
    "    DataMoverLive.pipe(Layer.provide(Layer.mergeAll(runtimeProviderLive, pluginsRuntimeLive))),",
    "    providerRegistryLive,",
    "    globalAppServiceLive,",
    "  );",
    "  const appPlannerLive = AppPlannerLive.pipe(Layer.provide(baseProviderLayer));",
    "  const buildOrchestratorLive = BuildOrchestratorLive.pipe(Layer.provide(baseProviderLayer));",
    "  const globalAppRuntimeLive = GlobalAppRuntimeLive.pipe(Layer.provide(Layer.mergeAll(baseProviderLayer, appPlannerLive, buildOrchestratorLive)));",
    "  const proxyRegistryLive = makeProxyServiceRegistryLive(bundledPluginModules()).pipe(",
    "    Layer.provide(Layer.mergeAll(baseProviderLayer, globalAppRuntimeLive)),",
    "    Layer.mapError((cause) =>",
    '      new LandoRuntimeBootstrapError({ message: cause instanceof Error ? cause.message : "ProxyService bootstrap failed.", stage: "provider", cause }),',
    "    ),",
    "  );",
    "  const proxyServiceLive = SelectedProxyServiceLive.pipe(",
    "    Layer.provide(Layer.mergeAll(baseProviderLayer, globalAppRuntimeLive, proxyRegistryLive)),",
    "    Layer.mapError((cause) =>",
    '      new LandoRuntimeBootstrapError({ message: cause instanceof Error ? cause.message : "ProxyService bootstrap failed.", stage: "provider", cause }),',
    "    ),",
    "  );",
    "  const sshRegistryLive = makeSshServiceRegistryLive(bundledPluginModules()).pipe(",
    "    Layer.provide(Layer.mergeAll(baseProviderLayer, globalAppRuntimeLive)),",
    "    Layer.mapError((cause) =>",
    '      new LandoRuntimeBootstrapError({ message: cause instanceof Error ? cause.message : "SshService bootstrap failed.", stage: "provider", cause }),',
    "    ),",
    "  );",
    "  const sshServiceLive = SelectedSshServiceLive.pipe(",
    "    Layer.provide(Layer.mergeAll(baseProviderLayer, globalAppRuntimeLive, sshRegistryLive)),",
    "    Layer.mapError((cause) =>",
    '      new LandoRuntimeBootstrapError({ message: cause instanceof Error ? cause.message : "SshService bootstrap failed.", stage: "provider", cause }),',
    "    ),",
    "  );",
    "",
    "  return Layer.mergeAll(",
    "    baseProviderLayer,",
    "    appPlannerLive,",
    "    buildOrchestratorLive,",
    "    globalAppRuntimeLive,",
    "    proxyRegistryLive,",
    "    proxyServiceLive,",
    "    sshRegistryLive,",
    "    sshServiceLive,",
    "  ).pipe(",
    '    Layer.tap((context) => inputs.lifecycle.complete("provider", Context.get(context, EventService))),',
    "  );",
    "};",
    "",
    "export const makeProviderBootstrapLayer = (inputs: BootstrapLayerInputs) => {",
    "  const providerBase = makeProviderBootstrapBaseLayer(inputs);",
    "  const subscriberRuntimeLive = makeSubscriberRuntimeLive(bundledPluginModules(), BUILT_IN_COMMAND_IDS).pipe(Layer.provide(providerBase));",
    "  return Layer.merge(providerBase, subscriberRuntimeLive);",
    "};",
    "",
  ].join("\n");

export const renderIndex = (): string =>
  [
    'import { Effect, Layer, Option } from "effect";',
    "",
    'import type { BootstrapLevel } from "@lando/sdk/schema";',
    'import { EventService } from "@lando/sdk/services";',
    'import { withPluginLayerOverrides } from "@lando/engine/plugins/contribution-graph";',
    'import { superviseBootstrapLayer } from "@lando/engine/runtime/bootstrap-lifecycle";',
    'import type { BootstrapLayerInputs } from "@lando/engine/runtime/bootstrap-layer-support";',
    'import { noneBootstrapLayer } from "./none.ts";',
    'import { makeMinimalBootstrapLayer } from "./minimal.ts";',
    'import { makePluginsBootstrapBaseLayer } from "./plugins.ts";',
    'import { makeCommandsBootstrapLayer } from "./commands.ts";',
    'import { makeToolingBootstrapLayer } from "./tooling.ts";',
    'import { makeProviderBootstrapLayer } from "./provider.ts";',
    'import { makeGlobalBootstrapLayer } from "./global.ts";',
    'import { makeScratchBootstrapLayer } from "./scratch.ts";',
    'import { makeAppBootstrapLayer } from "./app.ts";',
    "",
    "export const makeGeneratedBootstrapLayer = (bootstrap: BootstrapLevel, inputs: BootstrapLayerInputs) => {",
    "  switch (bootstrap) {",
    '    case "none":',
    "      return noneBootstrapLayer;",
    '    case "minimal":',
    "      return makeMinimalBootstrapLayer(inputs);",
    '    case "plugins":',
    "      return withPluginLayerOverrides(makePluginsBootstrapBaseLayer(inputs));",
    '    case "commands":',
    "      return withPluginLayerOverrides(makeCommandsBootstrapLayer(inputs));",
    '    case "tooling":',
    "      return withPluginLayerOverrides(makeToolingBootstrapLayer(inputs));",
    '    case "provider":',
    "      return withPluginLayerOverrides(makeProviderBootstrapLayer(inputs));",
    '    case "global":',
    "      return withPluginLayerOverrides(makeGlobalBootstrapLayer(inputs));",
    '    case "scratch":',
    "      return withPluginLayerOverrides(makeScratchBootstrapLayer(inputs));",
    '    case "app":',
    "      return withPluginLayerOverrides(makeAppBootstrapLayer(inputs));",
    "  }",
    "};",
    "",
    "export const mergeRuntimeWithHostLayers = (",
    "  baseLayer: Layer.Layer<unknown, unknown, unknown>,",
    "  hostLayers: ReadonlyArray<Layer.Layer<unknown, unknown, unknown>>,",
    "  bootstrap: BootstrapLevel,",
    '  lifecycle: BootstrapLayerInputs["lifecycle"],',
    ") => {",
    "  const runtime = hostLayers.reduce((current, hostLayer) => {",
    "    const captureEventService = Layer.effectDiscard(",
    "      Effect.serviceOption(EventService).pipe(",
    "        Effect.flatMap(",
    "          Option.match({",
    "            onNone: () => Effect.void,",
    "            onSome: lifecycle.useEventService,",
    "          }),",
    "        ),",
    "      ),",
    "    );",
    "    const observedHostLayer = captureEventService.pipe(Layer.provideMerge(hostLayer));",
    "    return observedHostLayer.pipe(Layer.provideMerge(current));",
    "  }, baseLayer);",
    '  return bootstrap === "none"',
    "    ? runtime",
    "    : superviseBootstrapLayer(runtime, lifecycle);",
    "};",
    "",
  ].join("\n");
