#!/usr/bin/env bun
import { resolve } from "node:path";

import { createJourneyWorkflowBuilder, runtimeHelperBuilds } from "./_journey-workflow.ts";
import { PLATFORM_READINESS_CELLS, type PlatformReadinessCell } from "./ci-platforms.ts";

const REPO_ROOT = resolve(import.meta.dirname, "..");
const OUTPUT = resolve(REPO_ROOT, ".github/workflows/drupal-journey.yml");
const GENERATED_HEADER =
  "# Generated by scripts/codegen.ts — do not hand-edit. Edit scripts/build-drupal-journey-workflow.ts instead.";
const {
  ciPlatformFor,
  renderRunsOn,
  renderCadenceIf,
  isolateRootsStep,
  setupBunSteps,
  derivedSourcesSteps,
  renderCompileStep,
  renderBundleSteps,
  renderLinuxLandoPrereqs,
  renderSetupStep,
} = createJourneyWorkflowBuilder("drupal-journey", runtimeHelperBuilds);

const renderJob = (cell: PlatformReadinessCell): string => {
  const platform = ciPlatformFor(cell.id);
  const binary = `dist/${platform.binaryName}`;
  return `  drupal-journey-${cell.id}:
${renderCadenceIf(cell.cadence)}    runs-on: ${renderRunsOn(cell.runsOn)}
    timeout-minutes: 90
    env:
      COMPOSER_PROCESS_TIMEOUT: "2000"
    steps:
      - uses: actions/checkout@v5

${isolateRootsStep}

${setupBunSteps}

${derivedSourcesSteps}

${renderCompileStep(platform)}
${renderBundleSteps(cell)}${renderLinuxLandoPrereqs(cell)}
${renderSetupStep(cell, binary)}

      - name: Run Drupal journey
        run: bun run scripts/drupal-journey.ts --binary ${binary} --app-dir \${{ runner.temp }}/drupal-app --report \${{ runner.temp }}/drupal-journey.json

      - name: Teardown
        if: always()
        run: |
          BINARY="\$GITHUB_WORKSPACE/${binary}"
          (cd "\${{ runner.temp }}/drupal-app/drupal-journey" && "\$BINARY" destroy -y) || true
          "\$BINARY" poweroff || true

      - name: Upload evidence
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: drupal-journey-${cell.id}
          path: \${{ runner.temp }}/drupal-journey.json
          if-no-files-found: ignore
          retention-days: 14
`;
};

export const renderDrupalJourneyWorkflow = (): string => `${GENERATED_HEADER}
name: drupal-journey

on:
  pull_request:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
${PLATFORM_READINESS_CELLS.map(renderJob).join("\n")}
`;

const main = async (): Promise<void> => {
  await Bun.write(OUTPUT, renderDrupalJourneyWorkflow());
  console.log(`[build-drupal-journey-workflow] wrote ${OUTPUT}`);
};

if (import.meta.main) await main();
