#!/usr/bin/env bun
import { resolve } from "node:path";

import { landoRootlessPrereqSteps } from "./build-ci-workflow.ts";
import { CI_PLATFORMS, type CiPlatform, type PlatformReadinessCell } from "./ci-platforms.ts";
import * as supplyChain from "./runtime-bundle-supply-chain.ts";
import { WORKFLOW_PERFORMANCE_CELLS } from "./workflow-performance-plan.ts";

const REPO_ROOT = resolve(import.meta.dirname, "..");
const OUTPUT = resolve(REPO_ROOT, ".github/workflows/workflow-performance.yml");
const GENERATED_HEADER =
  "# Generated by scripts/codegen.ts — do not hand-edit. Edit scripts/build-workflow-performance-workflow.ts instead.";

const ciPlatformFor = (id: string): CiPlatform => {
  const platform = CI_PLATFORMS.find((candidate) => candidate.id === id);
  if (platform === undefined) throw new Error(`CI_PLATFORMS is missing ${id}`);
  return platform;
};

const renderSourceBuildPrerequisites = (): string => `      - name: Setup Go for Linux Podman source build
        uses: ${supplyChain.RUNTIME_BUNDLE_ACTION_PINS.setupGo} # v5.5.0
        with:
          go-version: 1.25.6

      - name: Setup Rust for Linux helper source builds
        uses: ${supplyChain.RUNTIME_BUNDLE_ACTION_PINS.rustToolchain} # 1.88.0

      - name: Install Linux Podman source-build prerequisites
        run: |
          ${supplyChain.RUNTIME_BUNDLE_UBUNTU_PREREQUISITE_SCRIPT}`;

const renderJob = (cell: PlatformReadinessCell): string => {
  const platform = ciPlatformFor(cell.id);
  const binary = `dist/${platform.binaryName}`;
  return `  workflow-performance-${cell.id}:
    runs-on: ${cell.runsOn}
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v5

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: .bun-version

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Regenerate derived sources
        run: bun run codegen

      - name: Build command registry manifest
        run: bun run --filter='@lando/core' build:manifest

      - name: Build ${cell.id} binary
        run: |
          mkdir -p dist
          bun run --filter='@lando/core' build:host-proxy-shim
          bun run --filter='@lando/core' build:log-file-helper
          bun -e "const fs = await import('node:fs/promises'); await fs.cp('core/dist/host-proxy', 'dist/host-proxy', { recursive: true }); await fs.cp('core/dist/log-file-access', 'dist/log-file-access', { recursive: true });"
          VERSION=$(git describe --tags --always --dirty 2>/dev/null || echo "0.0.0-dev")
          bun run scripts/build-compiled-binary.ts --target ${platform.bunTarget} --outfile ./${binary} --version "$VERSION" --minify --sourcemap=external

${renderSourceBuildPrerequisites()}

      - name: Assemble current-commit ${cell.bundleKey} runtime bundle
        run: bun run scripts/assemble-runtime-bundle.ts --platform ${cell.bundleKey}

      - name: Build local runtime bundle manifest
        run: |
          RUNTIME_VERSION="$(bun -e 'import { readRuntimeBundleSources } from "./scripts/runtime-bundle-sources.ts"; process.stdout.write((await readRuntimeBundleSources()).runtimeVersion)')"
          MANIFEST="$(bun run scripts/build-runtime-bundle.ts --local --platform ${cell.bundleKey} --runtime-version "$RUNTIME_VERSION")"
          echo "LANDO_RUNTIME_BUNDLE_MANIFEST=$MANIFEST" >> "$GITHUB_ENV"
          echo "WORKFLOW_PERF_RUNTIME_VERSION=$RUNTIME_VERSION" >> "$GITHUB_ENV"

${landoRootlessPrereqSteps}

      - name: Run workflow performance samples
        id: performance
        env:
          START_SAMPLES: \${{ inputs.start_samples || '5' }}
          HEAVY_SAMPLES: \${{ inputs.heavy_samples || '3' }}
          FAILING_FIXTURE_LANE: \${{ inputs.failing_fixture_lane || '' }}
        run: |
          set +e
          ROOT="$RUNNER_TEMP/workflow-performance-${cell.id}"
          mkdir -p "$ROOT"
          BINARY_VERSION="$(${binary} --version)"
          PROVIDER_VERSION="$(bun -e 'const value = await Bun.file("plugins/provider-lando/package.json").json(); process.stdout.write(String(value.version))')"
          bun run scripts/workflow-performance.ts \\
            --binary "$GITHUB_WORKSPACE/${binary}" \\
            --report "$ROOT/report.json" \\
            --root-dir "$ROOT/work" \\
            --run-id "\${{ github.run_id }}.${cell.id}" \\
            --run-attempt "\${{ github.run_attempt }}" \\
            --commit "\${{ github.sha }}" \\
            --platform "${cell.id}" \\
            --architecture "${cell.id.split("-").at(-1) ?? "unknown"}" \\
            --runner "${cell.runsOn}" \\
            --binary-version "$BINARY_VERSION" \\
            --runtime-version "$WORKFLOW_PERF_RUNTIME_VERSION" \\
            --provider-version "$PROVIDER_VERSION" \\
            --fixture-seed "workflow-performance-v1" \\
            --start-samples "$START_SAMPLES" \\
            --heavy-samples "$HEAVY_SAMPLES" \\
            --failing-fixture-lane "$FAILING_FIXTURE_LANE"
          echo "$?" > "$ROOT/exit-code"
          exit 0

      - name: Download compatible performance history candidates
        env:
          GH_TOKEN: \${{ github.token }}
        run: |
          ROOT="$RUNNER_TEMP/workflow-performance-${cell.id}"
          mkdir -p "$ROOT/history"
          gh api "/repos/\${{ github.repository }}/actions/workflows/workflow-performance.yml/runs?status=completed&per_page=30" \\
            --jq '.workflow_runs[] | [.id, .created_at, .conclusion] | @tsv' > "$ROOT/history-index.tsv"
          while IFS=$'\t' read -r run_id _created _conclusion; do
            test -n "$run_id" || continue
            mkdir -p "$ROOT/history/$run_id"
            gh run download "$run_id" --name "workflow-performance-${cell.id}" --dir "$ROOT/history/$run_id" || true
          done < "$ROOT/history-index.tsv"

      - name: Render last-30-run trend
        if: always()
        run: |
          ROOT="$RUNNER_TEMP/workflow-performance-${cell.id}"
          bun run scripts/workflow-performance-history-cli.ts \\
            --current "$ROOT/report.json" \\
            --index "$ROOT/history-index.tsv" \\
            --artifact-root "$ROOT/history" \\
            --summary "$ROOT/history-summary.json" \\
            --markdown "$ROOT/history-summary.md"

      - name: Upload workflow performance report and trend
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: workflow-performance-${cell.id}
          path: |
            \${{ runner.temp }}/workflow-performance-${cell.id}/report.json
            \${{ runner.temp }}/workflow-performance-${cell.id}/history-summary.json
            \${{ runner.temp }}/workflow-performance-${cell.id}/history-summary.md
          if-no-files-found: error
          retention-days: 90

      - name: Enforce workflow correctness
        if: always()
        run: |
          ROOT="$RUNNER_TEMP/workflow-performance-${cell.id}"
          test -f "$ROOT/exit-code"
          exit "$(cat "$ROOT/exit-code")"

      - name: Ownership-scoped cleanup
        if: always()
        run: rm -rf "$RUNNER_TEMP/workflow-performance-${cell.id}"
`;
};

export const renderWorkflowPerformanceWorkflow = (): string => `${GENERATED_HEADER}
name: workflow-performance

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:
    inputs:
      start_samples:
        description: Start-class samples per lane
        default: '5'
        type: string
      heavy_samples:
        description: Heavy samples per lane
        default: '3'
        type: string
      failing_fixture_lane:
        description: Controlled failure proof (empty, mysql-import, or postgres-import)
        default: ''
        type: string

defaults:
  run:
    shell: bash

permissions:
  actions: read
  contents: read

jobs:
${WORKFLOW_PERFORMANCE_CELLS.map(renderJob).join("\n")}`;

const main = async (): Promise<void> => {
  await Bun.write(OUTPUT, renderWorkflowPerformanceWorkflow());
  console.log(`[build-workflow-performance-workflow] wrote ${OUTPUT}`);
};

if (import.meta.main) await main();
