import { resolve } from "node:path";

import { CI_PLATFORMS, type CiPlatform } from "./ci-platforms.ts";
import { renderAssertPodman6Step, renderInstallPodman6Step } from "./ci-podman-install.ts";

const REPO_ROOT = resolve(import.meta.dirname, "..");
const OUTPUT = resolve(REPO_ROOT, ".github/workflows/ci.yml");
const GENERATED_HEADER =
  "# Generated by scripts/codegen.ts — do not hand-edit. Edit scripts/build-ci-workflow.ts instead.";

const platformList = CI_PLATFORMS.map((platform) => platform.id).join(", ");
const buildNeeds = "[static-checks, schema-snapshot, bundled-codegen, library-api-tests, recipe-tests]";

const timingStartStep = `      - name: Mark job start
        run: echo "CI_JOB_STARTED_AT=$(date +%s)" >> "$GITHUB_ENV"`;

const timingNoticeStep = (label: string, timeoutMinutes: number): string => `      - name: Report job timing
        if: always()
        run: |
          echo "::notice title=ci-timing::${label} completed in $(($(date +%s)-CI_JOB_STARTED_AT))s (timeout cap: ${timeoutMinutes}m)"`;

const setupBunSteps = `      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: .bun-version

      - name: Install dependencies
        run: bun install --frozen-lockfile`;

const renderStaticChecks = (): string => `  static-checks-platform:
    strategy:
      fail-fast: false
      matrix:
        platform: [${platformList}]
        include:
${CI_PLATFORMS.map((platform) => `          - platform: ${platform.id}\n            runs-on: ${platform.runsOn}`).join("\n")}
    runs-on: \${{ matrix.runs-on }}
    timeout-minutes: 35
    steps:
      - uses: actions/checkout@v4

${timingStartStep}

${setupBunSteps}

      - name: Typecheck
        run: bun run typecheck

      - name: Lint
        run: bun run lint

      - name: Renderer boundary lint
        run: bun run check:renderer-boundary

      - name: Managed-file boundary lint
        run: bun run check:managed-file-boundary

      - name: Telemetry inventory lint
        run: bun run check:telemetry-inventory

      - name: Redaction boundary lint
        run: bun run check:redaction-boundary

      - name: Env helper boundary lint
        run: bun run check:env-helper-boundary

      - name: Paths boundary lint
        run: bun run check:paths-boundary

      - name: State-store boundary lint
        run: bun run check:state-store-boundary

      - name: Probe boundary lint
        run: bun run check:probe-boundary

      - name: Network boundary lint
        run: bun run check:network-boundary

      - name: Libpod API prefix lint
        run: bun run check:libpod-prefix

      - name: Machine output boundary lint
        run: bun run check:machine-output

      - name: Runtime-bundle manifest invariant
        run: bun run check:runtime-bundle-manifest

      - name: Static scope notice for portable static matrix
        run: |
          echo "::notice title=static-checks-scope::\${{ matrix.platform }} runs fork-safe portable static gates only; linux-x64 unit tests run as unit-tests-linux-x64. Full cross-platform static test portability remains a follow-up portability effort."

${timingNoticeStep("static-checks/${{ matrix.platform }}", 35)}

  static-checks:
    needs: [static-checks-platform]
    if: always()
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - name: Confirm static-checks platform matrix
        run: |
          if [[ "\${{ needs.static-checks-platform.result }}" != "success" ]]; then
            echo "static-checks platform matrix result: \${{ needs.static-checks-platform.result }}"
            exit 1
          fi
          echo "static-checks platform matrix passed"
`;

const renderUnitTests = (): string => `  unit-tests-linux-x64:
    needs: [static-checks]
    runs-on: ubuntu-24.04
    timeout-minutes: 35
    steps:
      - uses: actions/checkout@v4

${timingStartStep}

${setupBunSteps}

      - name: Unit test layer
        run: bun run test:unit

${timingNoticeStep("unit-tests-linux-x64", 35)}
`;

const renderSmokeCommands = (platform: CiPlatform): string =>
  platform.id === "windows-x64"
    ? `          bun run scripts/smoke-windows-binary.ts ./dist/${platform.binaryName}`
    : `          test -f dist/${platform.binaryName}
          ./dist/${platform.binaryName} --version
          ./dist/${platform.binaryName} --help
          ./dist/${platform.binaryName} shellenv`;

const renderBuildNeeds = (platform: CiPlatform): string =>
  platform.id === "windows-x64"
    ? "[static-checks, schema-snapshot, bundled-codegen, library-api-tests, recipe-tests, build-linux-x64]"
    : buildNeeds;

const renderHostProxyShimBuildCommands = (platform: CiPlatform): string =>
  platform.id === "windows-x64"
    ? `          bun -e "const fs = await import('node:fs/promises'); await fs.cp('linux-sidecars/host-proxy', 'dist/host-proxy', { recursive: true }); await fs.cp('linux-sidecars/log-file-access', 'dist/log-file-access', { recursive: true });"`
    : `          bun run --filter='@lando/core' build:host-proxy-shim
          bun run --filter='@lando/core' build:log-file-helper
          bun -e "const fs = await import('node:fs/promises'); await fs.cp('core/dist/host-proxy', 'dist/host-proxy', { recursive: true }); await fs.cp('core/dist/log-file-access', 'dist/log-file-access', { recursive: true });"`;

const renderHostProxyShimDownloadStep = (platform: CiPlatform): string =>
  platform.id === "windows-x64"
    ? `

      - name: Download Linux sidecars from Linux artifact
        uses: actions/download-artifact@v4
        with:
          name: lando-linux-x64
          path: linux-sidecars`
    : "";

const renderBuildJob = (platform: CiPlatform): string => `  build-${platform.id}:
    needs: ${renderBuildNeeds(platform)}
    runs-on: ${platform.runsOn}
    timeout-minutes: ${platform.timeoutMinutes}
    steps:
      - uses: actions/checkout@v4

${timingStartStep}

${setupBunSteps}${renderHostProxyShimDownloadStep(platform)}

      - name: Build OCLIF manifest
        run: bun run --filter='@lando/core' build:manifest

      - name: Build ${platform.id} binary
        run: |
          mkdir -p dist
${renderHostProxyShimBuildCommands(platform)}
          bun build ./core/bin/lando.ts --compile --bytecode --target=${platform.bunTarget} --outfile ./dist/${platform.binaryName} --sourcemap=external
          bun run scripts/sanitize-compiled-binary.ts ./dist/${platform.binaryName}

      - name: Smoke test binary
        run: |
${renderSmokeCommands(platform)}

      - name: Upload ${platform.id} binary
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lando-${platform.id}
          path: |
            dist/${platform.binaryName}
            dist/host-proxy/**
            dist/log-file-access/**
          if-no-files-found: ignore
          retention-days: 14

${timingNoticeStep(`build-${platform.id}`, platform.timeoutMinutes)}
`;

const renderPerfBudgetJob = (): string => `  perf-budget-linux-x64:
    needs: [build-linux-x64]
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

${timingStartStep}

${setupBunSteps}

      - name: Download Linux x64 binary artifact
        uses: actions/download-artifact@v4
        with:
          name: lando-linux-x64
          path: dist

      - name: Restore binary executable bit
        run: chmod +x dist/lando

      - name: Run tooling hot-path benchmark
        run: bun run bench:tooling-hot-path -- --binary dist/lando

${timingNoticeStep("perf-budget-linux-x64", 10)}
`;

export const landoManagedPodmanTeardownCommands = `          LANDO_PODMAN="$HOME/.local/share/lando/runtime/bin/podman"
          LANDO_PODMAN_ARGS=(--root "$HOME/.local/share/lando/runtime/storage" --runroot "$HOME/.local/share/lando/runtime/run" --config "$HOME/.local/share/lando/runtime/config")
          "$LANDO_PODMAN" "\${LANDO_PODMAN_ARGS[@]}" ps -aq --filter "name=lando-" | xargs -r "$LANDO_PODMAN" "\${LANDO_PODMAN_ARGS[@]}" rm -f || true
          "$LANDO_PODMAN" "\${LANDO_PODMAN_ARGS[@]}" network ls --format '{{.Name}}' | grep '^lando-' | xargs -r "$LANDO_PODMAN" "\${LANDO_PODMAN_ARGS[@]}" network rm || true`;

const contractProviderTestSteps = `      - name: Run provider contract tests
        run: |
          bun test sdk/test/contract/provider.test.ts sdk/test/contract/service.test.ts
          bun test plugins/provider-lando/test/contract.integration.test.ts
          bun test plugins/provider-docker/test/contract.integration.test.ts
          bun test plugins/provider-podman/test/contract.integration.test.ts
          bun test plugins/provider-podman/test/capabilities.test.ts`;

export const landoRuntimeSocketPath = '"$HOME/.local/share/lando/runtime/run/podman.sock"';

export const landoRootlessPrereqSteps = `      - name: Provision rootless runtime prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y uidmap fuse-overlayfs
          if ! grep -q "^$(id -un):" /etc/subuid; then
            echo "$(id -un):100000:65536" | sudo tee -a /etc/subuid
          fi
          if ! grep -q "^$(id -un):" /etc/subgid; then
            echo "$(id -un):100000:65536" | sudo tee -a /etc/subgid
          fi
          sudo sysctl net.ipv4.ip_unprivileged_port_start=0
          if test -e /proc/sys/kernel/apparmor_restrict_unprivileged_userns; then
            sudo sysctl kernel.apparmor_restrict_unprivileged_userns=0
          fi
          if ! grep -q "systemd.unified_cgroup_hierarchy" /proc/cmdline; then
            echo "::notice title=ci-runtime::cgroups v2 unified hierarchy assumed via ubuntu-24.04 default (systemd.unified_cgroup_hierarchy)"
          fi
          sudo mkdir -p /sys/fs/cgroup/user.slice/user-$(id -u).slice
          sudo chown -R "$(id -un)" "/sys/fs/cgroup/user.slice/user-$(id -u).slice" || true`;

const landoRuntimeBundleSetupSteps = `${renderInstallPodman6Step()}

${renderAssertPodman6Step()}

      - name: Stage current-commit runtime bundle
        run: |
          mkdir -p dist/cache/runtime-bundle
          STAGE="$(mktemp -d)"
          cp "$(command -v podman)" "$STAGE/podman"
          for helper in newuidmap newgidmap pasta passt rootlessport catatonit slirp4netns fuse-overlayfs crun runc conmon netavark aardvark-dns gvproxy; do
            src=""
            IFS=":"
            for dir in \${LANDO_CI_PODMAN_TOOLCHAIN_DIRS:-}; do
              if test -x "$dir/$helper"; then src="$dir/$helper"; break; fi
            done
            unset IFS
            if test -z "$src"; then src="$(command -v "$helper" 2>/dev/null || true)"; fi
            if test -z "$src" && test -x "/usr/lib/podman/$helper"; then src="/usr/lib/podman/$helper"; fi
            if test -n "$src"; then cp "$src" "$STAGE/$helper"; fi
          done
          tar -czf dist/cache/runtime-bundle/lando-runtime-linux-x64.tar.gz -C "$STAGE" .
          rm -rf "$STAGE"

      - name: Build local runtime bundle manifest
        run: |
          MANIFEST="$(bun run scripts/build-runtime-bundle.ts --local --platform linux-x64)"
          echo "LANDO_RUNTIME_BUNDLE_MANIFEST=$MANIFEST" >> "$GITHUB_ENV"

      - name: Configure rootless overlay storage
        run: |
          cat > dist/cache/runtime-bundle/storage.conf <<EOF
          [storage]
          driver = "overlay"

          [storage.options.overlay]
          mount_program = "$HOME/.local/share/lando/runtime/bin/fuse-overlayfs"
          EOF
          echo "CONTAINERS_STORAGE_CONF=$GITHUB_WORKSPACE/dist/cache/runtime-bundle/storage.conf" >> "$GITHUB_ENV"

      - name: Prepare provider via lando setup
        run: |
          export XDG_RUNTIME_DIR="\${XDG_RUNTIME_DIR:-/run/user/\$(id -u)}"
          mkdir -p "\$XDG_RUNTIME_DIR"
          dist/lando setup --yes --provider=lando --skip-install-ca --skip-shell-integration --skip-file-sync
          echo "LANDO_CONFIG__default_provider_id=lando" >> "\$GITHUB_ENV"

      - name: Verify managed runtime socket
        run: |
          for _ in {1..30}; do
            test -S ${landoRuntimeSocketPath} && break
            sleep 1
          done
          test -S ${landoRuntimeSocketPath}

      - name: Configure Docker socket
        run: |
          test -S /var/run/docker.sock
          echo "LANDO_TEST_DOCKER_SOCKET=/var/run/docker.sock" >> "$GITHUB_ENV"

      - name: Pre-pull container images
        run: |
          LANDO_PODMAN="$HOME/.local/share/lando/runtime/bin/podman"
          LANDO_PODMAN_ARGS=(--root "$HOME/.local/share/lando/runtime/storage" --runroot "$HOME/.local/share/lando/runtime/run" --config "$HOME/.local/share/lando/runtime/config")
          pull_image() {
            local image="$1"
            for attempt in 1 2 3; do
              "$LANDO_PODMAN" "\${LANDO_PODMAN_ARGS[@]}" pull "$image" && return 0
              if test "$attempt" -eq 3; then return 1; fi
              sleep $((attempt * 5))
            done
          }
          docker_pull_image() {
            local image="$1"
            for attempt in 1 2 3; do
              docker pull "$image" && return 0
              if test "$attempt" -eq 3; then return 1; fi
              sleep $((attempt * 5))
            done
          }
          pull_image docker.io/library/alpine:3.21
          pull_image docker.io/library/node:lts
          pull_image docker.io/library/node:22-alpine
          pull_image docker.io/library/node:22
          pull_image docker.io/library/postgres:16
          pull_image docker.io/library/postgres:16-alpine
          pull_image docker.io/library/golang:1.22
          pull_image docker.elastic.co/elasticsearch/elasticsearch:8.17.0
          pull_image docker.io/getmeili/meilisearch:v1.11
          pull_image docker.io/axllent/mailpit:v1.30.1
          pull_image docker.io/library/memcached:1.6
          pull_image docker.io/library/nginx:1.27
          pull_image docker.io/opensearchproject/opensearch:2
          pull_image docker.io/library/solr:9
          pull_image docker.io/library/traefik:v3.3
          pull_image docker.io/valkey/valkey:8
          docker_pull_image docker.io/library/node:22-alpine
          docker_pull_image docker.io/library/node:22`;

const landoRuntimeLiveTestSteps = (
  platform: CiPlatform,
): string => `      - name: Run provider integration tests
        run: |
          mkdir -p /tmp/lando-provider-test-logs
          set -o pipefail
          LANDO_MVP_BINARY_PATH="$GITHUB_WORKSPACE/dist/${platform.binaryName}" bun test core/test/scenario | tee /tmp/lando-provider-test-logs/core-scenario.log
          bun test plugins/provider-lando/test/*.integration.test.ts | tee /tmp/lando-provider-test-logs/provider-lando-integration.log
          bun test plugins/provider-docker/test/*.integration.test.ts | tee /tmp/lando-provider-test-logs/provider-docker-integration.log
          bun test plugins/service-lando/test/*.integration.test.ts | tee /tmp/lando-provider-test-logs/service-lando-integration.log

      - name: Teardown Lando runtime
        if: always()
        run: |
          dist/lando poweroff || true
${landoManagedPodmanTeardownCommands}

      - name: Collect provider diagnostics
        if: failure()
        run: |
          mkdir -p provider-diagnostics/test-logs
          dist/lando doctor --format json > provider-diagnostics/doctor.json 2>&1 || true
          journalctl --no-pager --since "-30 minutes" > provider-diagnostics/journalctl.log 2>&1 || true
          for log in /tmp/lando-provider-test-logs/*.log; do
            test -f "$log" || continue
            tail -n 100 "$log" > "provider-diagnostics/test-logs/$(basename "$log")"
          done
          LANDO_RT="$HOME/.local/share/lando/runtime"
          ls -la "$LANDO_RT/bin" > provider-diagnostics/runtime-bin.txt 2>&1 || true
          ls -la "$LANDO_RT/run" >> provider-diagnostics/runtime-bin.txt 2>&1 || true
          ps auxww | grep -i podman > provider-diagnostics/podman-processes.txt 2>&1 || true
          cp -r "$HOME/.cache/lando/logs" provider-diagnostics/lando-logs 2>/dev/null || true
          LP="$LANDO_RT/bin/podman"
          if test -x "$LP"; then
            ldd "$LP" > provider-diagnostics/managed-podman-ldd.txt 2>&1 || true
            timeout 20 "$LP" --root "$LANDO_RT/storage" --runroot "$LANDO_RT/run" --log-level=debug info \
              > provider-diagnostics/managed-podman-info.log 2>&1 || true
            timeout 25 "$LP" --root "$LANDO_RT/storage" --runroot "$LANDO_RT/run" --log-level=debug \
              system service --time=10 "unix:///tmp/diag-podman.sock" \
              > provider-diagnostics/managed-podman-service.log 2>&1 || true
          fi`;

const landoProviderIntegrationSteps = (platform: CiPlatform): string =>
  `${landoRootlessPrereqSteps}\n\n${landoRuntimeBundleSetupSteps}\n\n${contractProviderTestSteps}\n\n${landoRuntimeLiveTestSteps(platform)}`;

const windowsRuntimeBundleJob = `  runtime-bundle-win32-x64:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

${timingStartStep}

${setupBunSteps}

      - name: Assemble current-commit Windows runtime bundle
        run: bun run scripts/assemble-runtime-bundle.ts --platform win32-x64

      - name: Upload current-commit Windows runtime bundle
        uses: actions/upload-artifact@v4
        with:
          name: runtime-bundle-win32-x64-current
          path: dist/cache/runtime-bundle/lando-runtime-win32-x64.zip
          if-no-files-found: error
          retention-days: 1

${timingNoticeStep("runtime-bundle-win32-x64", 15)}
`;

const windowsManagedSetupSteps = `      - name: Download current-commit Windows runtime bundle
        uses: actions/download-artifact@v4
        with:
          name: runtime-bundle-win32-x64-current
          path: dist/cache/runtime-bundle

      - name: Build local Windows runtime manifest
        run: |
          RUNTIME_VERSION="$(bun -e 'import { readRuntimeBundleSources } from "./scripts/runtime-bundle-sources.ts"; process.stdout.write((await readRuntimeBundleSources()).runtimeVersion)')"
          bun run scripts/build-runtime-bundle.ts --local --platform win32-x64 --runtime-version "$RUNTIME_VERSION"

      - name: Verify compiled Windows managed setup and API reachability
        env:
          LANDO_USER_DATA_ROOT: \${{ runner.temp }}/lando-data
          LANDO_USER_CACHE_ROOT: \${{ runner.temp }}/lando-cache
          LANDO_USER_CONF_ROOT: \${{ runner.temp }}/lando-config
          LANDO_RUNTIME_BUNDLE_MANIFEST: \${{ github.workspace }}/dist/cache/runtime-bundle/runtime-bundle-versions.json
        run: |
          bun run scripts/windows-managed-setup-acceptance.ts --binary dist/lando-windows-x64.exe --report provider-diagnostics/windows-managed-setup.json

      - name: Teardown Windows managed machine
        if: always()
        env:
          LANDO_USER_DATA_ROOT: \${{ runner.temp }}/lando-data
          LANDO_USER_CACHE_ROOT: \${{ runner.temp }}/lando-cache
          LANDO_USER_CONF_ROOT: \${{ runner.temp }}/lando-config
        run: |
          powershell.exe -NoProfile -Command '$podman = Join-Path $env:LANDO_USER_DATA_ROOT "runtime\\bin\\podman.exe"; if (Test-Path $podman) { $env:CONTAINERS_CONF = Join-Path $env:LANDO_USER_DATA_ROOT "runtime\\config\\containers.conf"; & $podman machine rm --force lando; if ($LASTEXITCODE -ne 0) { Write-Warning "managed machine teardown exited $LASTEXITCODE" } }; Remove-Item -Recurse -Force -ErrorAction SilentlyContinue $env:LANDO_USER_DATA_ROOT, $env:LANDO_USER_CACHE_ROOT, $env:LANDO_USER_CONF_ROOT; exit 0'`;

const providerIntegrationSteps = (platform: CiPlatform): string => {
  if (platform.liveProviderIntegration) return landoProviderIntegrationSteps(platform);
  if (platform.id === "windows-x64") {
    return `${windowsManagedSetupSteps}\n\n${contractProviderTestSteps}`;
  }
  return contractProviderTestSteps;
};

const renderProviderIntegrationJob = (platform: CiPlatform): string => `  provider-integration-${platform.id}:
    needs: ${platform.id === "windows-x64" ? "[build-windows-x64, runtime-bundle-win32-x64]" : `[build-${platform.id}]`}
    runs-on: ${platform.runsOn}
    timeout-minutes: ${platform.providerTimeoutMinutes}
    steps:
      - uses: actions/checkout@v4

${timingStartStep}

${setupBunSteps}

      - name: Download ${platform.id} binary artifact
        uses: actions/download-artifact@v4
        with:
          name: lando-${platform.id}
          path: dist

      - name: Restore binary executable bit
        run: chmod +x dist/${platform.binaryName}

${providerIntegrationSteps(platform)}

      - name: Upload provider integration diagnostics
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: provider-integration-diagnostics-${platform.id}
          path: provider-diagnostics
          if-no-files-found: ignore
          retention-days: 7

${timingNoticeStep(`provider-integration-${platform.id}`, platform.providerTimeoutMinutes)}
`;

const guideScenarioRunCommand =
  "bun run scripts/test-reporters/run-guide-scenarios.ts test/scenarios/generated/guides/**";

const linuxGuideE2eProviderSetupSteps = `${landoRootlessPrereqSteps}

${landoRuntimeBundleSetupSteps}`;

const linuxGuideScenarioE2eSteps = `      - name: Download Linux x64 binary artifact
        uses: actions/download-artifact@v4
        with:
          name: lando-linux-x64
          path: dist

      - name: Restore binary executable bit
        run: chmod +x dist/lando

${linuxGuideE2eProviderSetupSteps}

      - name: Run e2e smoke guide scenarios
        env:
          LANDO_GUIDE_E2E: "1"
        run: LANDO_MVP_BINARY_PATH="$GITHUB_WORKSPACE/dist/lando" LANDO_SCENARIO_E2E_BINARY="$GITHUB_WORKSPACE/dist/lando" ${guideScenarioRunCommand} --max-concurrency=1 --test-name-pattern="@smoke.*\\[e2e\\]"

      - name: Teardown guide e2e provider
        if: always()
        run: |
          dist/lando poweroff || true
${landoManagedPodmanTeardownCommands}

      - name: Collect guide e2e provider diagnostics
        if: failure()
        run: |
          mkdir -p guide-e2e-provider-diagnostics
          dist/lando doctor --format json > guide-e2e-provider-diagnostics/doctor.json 2>&1 || true
          journalctl --no-pager --since "-30 minutes" > guide-e2e-provider-diagnostics/journalctl.log 2>&1 || true

      - name: Upload guide scenario transcripts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: guide-scenario-transcripts-\${{ github.run_id }}.zip
          path: dist/transcripts/guides/**/*.json
          if-no-files-found: ignore
          retention-days: 7

      - name: Upload guide e2e provider diagnostics
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: guide-e2e-provider-diagnostics-\${{ github.run_id }}.zip
          path: guide-e2e-provider-diagnostics
          if-no-files-found: ignore
          retention-days: 7`;

const renderGuideScenariosJob = (platform: CiPlatform): string => {
  const isLinuxX64 = platform.id === "linux-x64";

  return `  guide-scenarios-${platform.id}:
    needs: ${isLinuxX64 ? "[static-checks, build-linux-x64]" : "[static-checks]"}
    runs-on: ${platform.runsOn}
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

${timingStartStep}

${setupBunSteps}

      - name: Regenerate guide scenarios
        run: bun run codegen

      - name: Typecheck
        run: bun run typecheck

      - name: Lint guides
        run: bun run lint:guides

      - name: Check guide coverage
        run: bun run check:guide-coverage

      - name: Check public transcripts
        run: bun run check:public-transcripts

      - name: Check guide drift
        if: \${{ github.event_name == 'pull_request' }}
        env:
          GUIDE_DRIFT_BASE_SHA: \${{ github.event.pull_request.base.sha }}
          GUIDE_DRIFT_HEAD_SHA: \${{ github.event.pull_request.head.sha }}
          GH_TOKEN: \${{ github.token }}
        run: |
          GUIDE_DRIFT_PR_BODY="$(gh pr view \${{ github.event.pull_request.number }} --json body --jq .body)" bun run check:guide-drift

      - name: Run generated guide scenarios
        run: ${guideScenarioRunCommand}${
          isLinuxX64
            ? `

${linuxGuideScenarioE2eSteps}`
            : ""
        }

${timingNoticeStep(`guide-scenarios-${platform.id}`, 30)}
`;
};

export const renderCiWorkflow = (): string => {
  const buildJobs = CI_PLATFORMS.map(renderBuildJob).join("\n");
  const perfBudgetJob = renderPerfBudgetJob();
  const providerIntegrationJobs = CI_PLATFORMS.map(renderProviderIntegrationJob).join("\n");
  const guideScenarioJobs = CI_PLATFORMS.map(renderGuideScenariosJob).join("\n");

  return `${GENERATED_HEADER}
name: ci

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

defaults:
  run:
    shell: bash

permissions:
  contents: read
  pull-requests: read

jobs:
${renderStaticChecks()}
${renderUnitTests()}
  schema-snapshot:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

${timingStartStep}

${setupBunSteps}

      - name: Regenerate schema snapshot
        run: bun run codegen:schema-snapshot

      - name: Verify schema snapshot is current
        run: git diff --exit-code -- sdk/test/fixtures/schema-snapshot.json dist/schemas docs/reference/schemas

      - name: Regenerate command reference
        run: |
          bun run codegen:oclif-manifest
          bun run codegen:command-reference

      - name: Verify command reference is current
        run: git diff --exit-code -- docs/reference/commands.mdx

${timingNoticeStep("schema-snapshot", 15)}

  bundled-codegen:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

${timingStartStep}

${setupBunSteps}

      - name: Regenerate bundled plugins
        run: bun run codegen:bundled-plugins

      - name: Regenerate bundled recipes
        run: bun run codegen:bundled-recipes

      - name: Regenerate bootstrap layers
        run: bun run codegen:bootstrap-layers

      - name: Regenerate Mutagen versions manifest
        run: bun run codegen:mutagen-versions

      - name: Regenerate provider images manifest
        run: bun run codegen:provider-images

      - name: Verify bundled codegen is current
        run: git diff --exit-code -- core/src/plugins/bundled.ts core/src/recipes/bundled.ts core/src/runtime/generated/layers plugins/file-sync-mutagen/mutagen-versions.json core/src/data-mover/generated/provider-images.ts

${timingNoticeStep("bundled-codegen", 15)}

  library-api-tests:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

${timingStartStep}

${setupBunSteps}

      - name: Run library API tests
        run: bun test core/test/library sdk/test/library

${timingNoticeStep("library-api-tests", 15)}

  recipe-tests:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

${timingStartStep}

${setupBunSteps}

      - name: Run recipe test layer
        run: bun test core/test/recipes core/test/cli/init.canonical-recipes.test.ts

${timingNoticeStep("recipe-tests", 15)}

${guideScenarioJobs}
${buildJobs}
${windowsRuntimeBundleJob}
${perfBudgetJob}
${providerIntegrationJobs}`;
};

const main = async (): Promise<void> => {
  const workflow = renderCiWorkflow();

  await Bun.write(OUTPUT, workflow);
  console.log(`[build-ci-workflow] wrote ${OUTPUT}`);
};

if (import.meta.main) await main();
