#!/usr/bin/env bun
import { resolve } from "node:path";

const REPO_ROOT = resolve(import.meta.dirname, "..");
const OUTPUT = resolve(REPO_ROOT, ".github/workflows/php-base-images.yml");
const GENERATED_HEADER =
  "# Generated by scripts/codegen.ts — do not hand-edit. Edit scripts/build-php-base-workflow.ts instead.";

const CHECKOUT_ACTION = "actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955";
const LOGIN_ACTION = "docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567";
const BUILD_PUSH_ACTION = "docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83";

export const renderPhpBaseWorkflow = (): string => `${GENERATED_HEADER}
name: php-base-images

on:
  push:
    branches: [main]
    paths:
      - images/php/**
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        php: [8.1, 8.2, 8.3, 8.4]
    steps:
      - uses: ${CHECKOUT_ACTION} # v4.3.0
        with:
          persist-credentials: false

      - name: Log in to GHCR
        uses: ${LOGIN_ACTION} # v3.4.0
        with:
          registry: ghcr.io
          username: \${{ github.actor }}
          password: \${{ secrets.GITHUB_TOKEN }}

      - name: Build and publish PHP \${{ matrix.php }} base
        uses: ${BUILD_PUSH_ACTION} # v6.18.0
        with:
          context: images/php/\${{ matrix.php }}
          push: true
          tags: |
            ghcr.io/\${{ github.repository_owner }}/php:\${{ matrix.php }}-apache
            ghcr.io/\${{ github.repository_owner }}/php:\${{ matrix.php }}-apache-\${{ github.sha }}
`;

const main = async (): Promise<void> => {
  await Bun.write(OUTPUT, renderPhpBaseWorkflow());
};

if (import.meta.main) await main();
