#!/usr/bin/env bun
import { resolve } from "node:path";

import { createJourneyWorkflowBuilder } from "./_journey-workflow.ts";
import { PLATFORM_READINESS_CELLS, type PlatformReadinessCell } from "./ci-platforms.ts";

const REPO_ROOT = resolve(import.meta.dirname, "..");
const OUTPUT = resolve(REPO_ROOT, ".github/workflows/platform-readiness.yml");
const GENERATED_HEADER =
  "# Generated by scripts/codegen.ts — do not hand-edit. Edit scripts/build-platform-readiness-workflow.ts instead.";
const {
  ciPlatformFor,
  renderRunsOn,
  renderCadenceIf,
  isolateRootsStep,
  setupBunSteps,
  derivedSourcesSteps,
  renderCompileStep,
  renderBundleSteps,
  renderLinuxLandoPrereqs,
  renderSetupStep,
} = createJourneyWorkflowBuilder("platform-readiness", "");

const renderJob = (cell: PlatformReadinessCell): string => {
  const platform = ciPlatformFor(cell.id);
  const binary = `dist/${platform.binaryName}`;
  return `  platform-readiness-${cell.id}:
${renderCadenceIf(cell.cadence)}    runs-on: ${renderRunsOn(cell.runsOn)}
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v5

${isolateRootsStep}

${setupBunSteps}

${derivedSourcesSteps}

${renderCompileStep(platform)}
${renderBundleSteps(cell)}${renderLinuxLandoPrereqs(cell)}
${renderSetupStep(cell, binary)}

      - name: Run platform-readiness doctor
        run: bun run scripts/platform-readiness-doctor.ts --binary ${binary} --report \${{ runner.temp }}/platform-readiness-doctor.json

      - name: Teardown
        if: always()
        run: ${binary} poweroff || true

      - name: Upload platform-readiness evidence
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: platform-readiness-${cell.id}
          path: \${{ runner.temp }}/platform-readiness-doctor.json
          if-no-files-found: ignore
          retention-days: 14
`;
};

export const renderPlatformReadinessWorkflow = (): string => `${GENERATED_HEADER}
name: platform-readiness

on:
  pull_request:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
${PLATFORM_READINESS_CELLS.map(renderJob).join("\n")}
`;

const main = async (): Promise<void> => {
  await Bun.write(OUTPUT, renderPlatformReadinessWorkflow());
  console.log(`[build-platform-readiness-workflow] wrote ${OUTPUT}`);
};

if (import.meta.main) await main();
