#!/usr/bin/env bun
import { resolve } from "node:path";

import { RUNTIME_BUNDLE_ACTION_PINS } from "./runtime-bundle-supply-chain.ts";

const REPO_ROOT = resolve(import.meta.dirname, "..");
const OUTPUT = resolve(REPO_ROOT, ".github/workflows/compose-vendor-bump.yml");
const GENERATED_HEADER =
  "# Generated by scripts/codegen.ts — do not hand-edit. Edit scripts/build-compose-vendor-bump-workflow.ts instead.";

const selectNewerTagScript = [
  'const { selectNewerComposeGoTag, readComposeVendorPin } = await import("./scripts/compose-vendor.ts");',
  'const pin = await readComposeVendorPin("vendor/compose/pin.json");',
  'const candidates = (await new Response(Bun.stdin.stream()).text()).split("\\n").map((line) => line.trim()).filter(Boolean);',
  "const newer = selectNewerComposeGoTag(pin.tag, candidates);",
  "if (newer !== undefined) process.stdout.write(newer);",
].join(" ");
const readPinnedTagScript = [
  'const { readComposeVendorPin } = await import("./scripts/compose-vendor.ts");',
  'const pin = await readComposeVendorPin("vendor/compose/pin.json");',
  "process.stdout.write(pin.tag);",
].join(" ");

export const renderComposeVendorBumpWorkflow = (): string => `${GENERATED_HEADER}
#
# Daily checks the latest tagged compose-spec/compose-go release against the
# committed pin. When a newer tag exists it re-vendors the pinned schema and
# opens or updates a single rolling PR whose body lists added and removed
# service and top-level key paths. Unclassified new keys fail
# check:compose-coverage on the PR (the merge blocker); this workflow never
# classifies keys.
name: compose-vendor-bump

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

concurrency:
  group: compose-vendor-bump
  cancel-in-progress: false

permissions:
  actions: write
  contents: write
  issues: write
  pull-requests: write

jobs:
  bump:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - uses: ${RUNTIME_BUNDLE_ACTION_PINS.checkout}
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Bun
        uses: ${RUNTIME_BUNDLE_ACTION_PINS.setupBun}
        with:
          bun-version-file: .bun-version

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Bump compose-go vendored schema and open rolling PR
        env:
          GH_TOKEN: \${{ github.token }}
        run: |
          set -euo pipefail
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          gh auth setup-git
          git fetch origin main:refs/remotes/origin/main
          BRANCH_EXISTS=false
          if git ls-remote --exit-code --heads origin automation/compose-go-bump >/dev/null 2>&1; then
            BRANCH_EXISTS=true
            git fetch origin automation/compose-go-bump:refs/remotes/origin/automation/compose-go-bump
            git checkout -B automation/compose-go-bump origin/automation/compose-go-bump
            git merge --no-edit origin/main
          else
            git checkout -b automation/compose-go-bump
          fi

          TARGET_TAG="$(gh api --paginate repos/compose-spec/compose-go/tags --jq '.[].name' | bun -e '${selectNewerTagScript}')"
          if [ -z "$TARGET_TAG" ]; then
            if [ "$BRANCH_EXISTS" = false ] || git diff --quiet origin/main...HEAD -- vendor/compose/pin.json vendor/compose/compose-spec.json; then
              echo "::notice title=compose-vendor-bump::compose-go pin is already current; nothing to bump."
              exit 0
            fi
            TARGET_TAG="$(bun -e '${readPinnedTagScript}')"
            echo "::notice title=compose-vendor-bump::reconciling the existing $TARGET_TAG bump branch."
          else
            echo "::notice title=compose-vendor-bump::bumping compose-go pin to $TARGET_TAG"
          fi

          git show origin/main:vendor/compose/compose-spec.json > "$RUNNER_TEMP/old-compose-spec.json"
          bun run codegen:compose-vendor --tag "$TARGET_TAG"
          bun run scripts/report-compose-schema-diff.ts "$RUNNER_TEMP/old-compose-spec.json" vendor/compose/compose-spec.json > "$RUNNER_TEMP/pr-body.md"

          if ! git diff --quiet -- vendor/compose/pin.json vendor/compose/compose-spec.json; then
            git add vendor/compose/pin.json vendor/compose/compose-spec.json
            git commit -m "bump compose-go vendored schema to $TARGET_TAG"
          fi
          git push origin HEAD:automation/compose-go-bump

          TITLE="bump compose-go vendored schema to $TARGET_TAG"
          if [ -z "$(gh pr list --state open --head automation/compose-go-bump --json number --jq '.[].number')" ]; then
            gh pr create --base main --head automation/compose-go-bump --title "$TITLE" --body-file "$RUNNER_TEMP/pr-body.md"
          else
            gh pr edit automation/compose-go-bump --title "$TITLE" --body-file "$RUNNER_TEMP/pr-body.md"
          fi

          gh workflow run ci.yml --ref automation/compose-go-bump

  report-failure:
    needs: [bump]
    if: \${{ failure() }}
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    env:
      GH_TOKEN: \${{ github.token }}
      RUN_URL: \${{ github.server_url }}/\${{ github.repository }}/actions/runs/\${{ github.run_id }}
    steps:
      - name: Open or update rolling failure issue
        run: |
          set -euo pipefail
          TITLE='compose-vendor-bump automation failure'
          printf -v BODY 'Workflow run failed: %s' "$RUN_URL"
          ISSUE_NUMBER="$(gh issue list --state open --limit 100 --json number,title --jq '[.[] | select(.title == "compose-vendor-bump automation failure")] | .[0].number // ""')"
          if [[ -n "$ISSUE_NUMBER" ]]; then
            gh issue comment "$ISSUE_NUMBER" --body "$BODY"
          else
            gh issue create --title "$TITLE" --body "$BODY"
          fi
`;

const main = async (): Promise<void> => {
  await Bun.write(OUTPUT, renderComposeVendorBumpWorkflow());
  console.log(`[build-compose-vendor-bump-workflow] wrote ${OUTPUT}`);
};

if (import.meta.main) await main();
