#!/usr/bin/env bun
import { resolve } from "node:path";

const REPO_ROOT = resolve(import.meta.dirname, "..");
const OUTPUT = resolve(REPO_ROOT, ".github/workflows/nightly.yml");
const GENERATED_HEADER =
  "# Generated by scripts/codegen.ts — do not hand-edit. Edit scripts/build-nightly-workflow.ts instead.";

const bunSetupStep = `
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: .bun-version

      - name: Install dependencies
        run: bun install --frozen-lockfile`;

const contractTestStep = (platform: string): string => `
      - name: Run file-sync contract matrix (${platform})
        run: bun test plugins/file-sync-mutagen/test/contract.test.ts
        env:
          LANDO_TEST_FILE_SYNC_LIVE: "1"`;

const providerLandoE2eJob = `
  provider-lando-e2e-linux-x64:
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
${bunSetupStep}

      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman
          sudo sysctl net.ipv4.ip_unprivileged_port_start=0

      - name: Start Podman socket
        run: |
          podman system service --time=0 unix:///tmp/podman.sock > /tmp/podman-service.log 2>&1 &
          echo "$!" > /tmp/podman-service.pid
          for i in {1..30}; do test -S /tmp/podman.sock && exit 0; sleep 1; done
          cat /tmp/podman-service.log
          exit 1

      - name: Build Linux x64 binary
        run: |
          bun run --filter='@lando/core' build:manifest
          bun build ./core/bin/lando.ts --compile --target=bun-linux-x64 --outfile ./core/dist/lando --sourcemap=external
          bun run scripts/sanitize-compiled-binary.ts ./core/dist/lando
          ./core/dist/lando --version

      - name: Run smoke e2e scenarios
        run: |
          LANDO_MVP_BINARY_PATH="$GITHUB_WORKSPACE/core/dist/lando" LANDO_SCENARIO_E2E_BINARY="$GITHUB_WORKSPACE/core/dist/lando" bun test core/test/scenario --test-name-pattern="@smoke"
        env:
          LANDO_TEST_PODMAN_SOCKET: /tmp/podman.sock
          LANDO_CONFIG__default_provider_id: lando

      - name: Run non-smoke e2e scenarios
        run: |
          LANDO_MVP_BINARY_PATH="$GITHUB_WORKSPACE/core/dist/lando" LANDO_SCENARIO_E2E_BINARY="$GITHUB_WORKSPACE/core/dist/lando" bun test core/test/scenario --test-name-pattern="^(?!.*@smoke).*$"
        env:
          LANDO_TEST_PODMAN_SOCKET: /tmp/podman.sock
          LANDO_CONFIG__default_provider_id: lando

      - name: Teardown Podman
        if: always()
        run: |
          podman ps -aq --filter "name=lando-" | xargs -r podman rm -f || true
          podman network ls --format '{{.Name}}' | grep '^lando-' | xargs -r podman network rm || true
          if test -f /tmp/podman-service.pid; then kill "$(cat /tmp/podman-service.pid)" || true; fi
          rm -f /tmp/podman.sock /tmp/podman-service.pid

      - name: Collect provider-lando e2e diagnostics
        if: failure()
        run: |
          mkdir -p provider-lando-e2e-diagnostics
          cp /tmp/podman-service.log provider-lando-e2e-diagnostics/podman-service.log || true
          journalctl --no-pager --since "-30 minutes" > provider-lando-e2e-diagnostics/journalctl.log 2>&1 || true

      - name: Upload provider-lando e2e diagnostics
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: provider-lando-e2e-diagnostics-linux-x64
          path: provider-lando-e2e-diagnostics
          if-no-files-found: ignore
          retention-days: 7`;

const distributionRehearsalJob = `
  distribution-rehearsal-linux-x64:
    runs-on: ubuntu-24.04
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
${bunSetupStep}

      - name: Build OCLIF manifest
        run: bun run --filter='@lando/core' build:manifest

      - name: Compile all platform binaries
        run: |
          mkdir -p dist/bundle
          bun build ./core/bin/lando.ts --compile --target=bun-linux-x64 --outfile ./dist/bundle/lando-linux-x64 --sourcemap=external
          bun build ./core/bin/lando.ts --compile --target=bun-linux-arm64 --outfile ./dist/bundle/lando-linux-arm64 --sourcemap=external
          bun build ./core/bin/lando.ts --compile --target=bun-darwin-x64 --outfile ./dist/bundle/lando-darwin-x64 --sourcemap=external
          bun build ./core/bin/lando.ts --compile --target=bun-darwin-arm64 --outfile ./dist/bundle/lando-darwin-arm64 --sourcemap=external
          bun build ./core/bin/lando.ts --compile --target=bun-windows-x64 --outfile ./dist/bundle/lando-windows-x64.exe --sourcemap=external
          bun run scripts/sanitize-compiled-binary.ts ./dist/bundle/lando-linux-x64
          bun run scripts/sanitize-compiled-binary.ts ./dist/bundle/lando-linux-arm64
          bun run scripts/sanitize-compiled-binary.ts ./dist/bundle/lando-darwin-x64
          bun run scripts/sanitize-compiled-binary.ts ./dist/bundle/lando-darwin-arm64
          bun run scripts/sanitize-compiled-binary.ts ./dist/bundle/lando-windows-x64.exe
          ./dist/bundle/lando-linux-x64 --version

      - name: Package distribution bundle
        run: bun run scripts/dist-bundle.ts dist/bundle

      - name: Verify SHA256SUMS match the binaries
        run: bun run scripts/dist-bundle.ts --verify dist/bundle

      - name: Upload distribution rehearsal bundle
        uses: actions/upload-artifact@v4
        with:
          name: lando-dist-rehearsal-v4.0.0-nightly.\${{ github.run_number }}
          path: dist/bundle
          if-no-files-found: error
          retention-days: 14`;

interface NightlyJob {
  readonly id: string;
  readonly runsOn: string;
  readonly platform: string;
}

const JOBS: ReadonlyArray<NightlyJob> = [
  { id: "file-sync-contract-linux-x64", runsOn: "ubuntu-24.04", platform: "linux-x64" },
  { id: "file-sync-contract-darwin-arm64", runsOn: "macos-15", platform: "darwin-arm64" },
  { id: "file-sync-contract-darwin-x64", runsOn: "macos-15-intel", platform: "darwin-x64" },
  { id: "file-sync-contract-windows-x64", runsOn: "windows-2022", platform: "windows-x64" },
];

const renderJob = (job: NightlyJob): string => `
  ${job.id}:
    runs-on: ${job.runsOn}
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
${bunSetupStep}
${contractTestStep(job.platform)}`;

export const renderNightlyWorkflow = (): string => {
  const jobsYaml = [...JOBS.map(renderJob), providerLandoE2eJob, distributionRehearsalJob].join("\n");

  return `${GENERATED_HEADER}
name: nightly

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
${jobsYaml}
`;
};

const main = async (): Promise<void> => {
  const workflow = renderNightlyWorkflow();
  await Bun.write(OUTPUT, workflow);
  console.log(`[build-nightly-workflow] wrote ${OUTPUT}`);
};

if (import.meta.main) await main();
