#!/usr/bin/env bun
import { resolve } from "node:path";

const REPO_ROOT = resolve(import.meta.dirname, "..");
const OUTPUT = resolve(REPO_ROOT, ".github/workflows/nightly.yml");
const GENERATED_HEADER =
  "# Generated by scripts/codegen.ts — do not hand-edit. Edit scripts/build-nightly-workflow.ts instead.";

const bunSetupStep = `
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: .bun-version

      - name: Install dependencies
        run: bun install --frozen-lockfile`;

const contractTestStep = (platform: string): string => `
      - name: Run file-sync contract matrix (${platform})
        run: bun test plugins/file-sync-mutagen/test/contract.test.ts
        env:
          LANDO_TEST_FILE_SYNC_LIVE: "1"`;

interface NightlyJob {
  readonly id: string;
  readonly runsOn: string;
  readonly platform: string;
}

const JOBS: ReadonlyArray<NightlyJob> = [
  { id: "file-sync-contract-linux-x64", runsOn: "ubuntu-24.04", platform: "linux-x64" },
  { id: "file-sync-contract-darwin-arm64", runsOn: "macos-15", platform: "darwin-arm64" },
  { id: "file-sync-contract-darwin-x64", runsOn: "macos-15-intel", platform: "darwin-x64" },
  { id: "file-sync-contract-win32-x64", runsOn: "windows-latest", platform: "win32-x64" },
];

const renderJob = (job: NightlyJob): string => `
  ${job.id}:
    runs-on: ${job.runsOn}
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
${bunSetupStep}
${contractTestStep(job.platform)}`;

export const renderNightlyWorkflow = (): string => {
  const jobsYaml = JOBS.map(renderJob).join("\n");

  return `${GENERATED_HEADER}
name: nightly-file-sync

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
${jobsYaml}
`;
};

const main = async (): Promise<void> => {
  const workflow = renderNightlyWorkflow();
  await Bun.write(OUTPUT, workflow);
  console.log(`[build-nightly-workflow] wrote ${OUTPUT}`);
};

if (import.meta.main) await main();
