#!/usr/bin/env bun
import { resolve } from "node:path";

import { RUNTIME_BUNDLE_TARGETS } from "./build-runtime-bundle.ts";

const REPO_ROOT = resolve(import.meta.dirname, "..");
const OUTPUT = resolve(REPO_ROOT, ".github/workflows/runtime-bundle.yml");
const GENERATED_HEADER =
  "# Generated by scripts/codegen.ts — do not hand-edit. Edit scripts/build-runtime-bundle-workflow.ts instead.";

// Podman 6 drops Intel Mac support, so darwin-x64 is neither a runtime-bundle
// target nor a published asset; these are the four runtime host keys that ship
// as release assets, matching RUNTIME_BUNDLE_TARGETS exactly.
export const RUNTIME_BUNDLE_PUBLISH_TARGET_KEYS = [
  "linux-x64",
  "linux-arm64",
  "darwin-arm64",
  "win32-x64",
] as const;

const publishTargets = RUNTIME_BUNDLE_PUBLISH_TARGET_KEYS.map((key) => {
  const target = RUNTIME_BUNDLE_TARGETS.find((candidate) => candidate.key === key);
  if (target === undefined) {
    throw new Error(`build-runtime-bundle-workflow: RUNTIME_BUNDLE_TARGETS is missing host key ${key}`);
  }
  return target;
});

const runnerFor = (hostKey: string): string =>
  hostKey === "linux-arm64" ? "ubuntu-24.04-arm" : "ubuntu-24.04";

const matrixInclude = publishTargets
  .map(
    (target) =>
      `          - hostKey: ${target.key}\n            filename: ${target.filename}\n            runsOn: ${runnerFor(target.key)}`,
  )
  .join("\n");

const assetArgs = publishTargets.map((target) => `dist/cache/runtime-bundle/${target.filename}`).join(" ");

export const renderRuntimeBundleWorkflow = (): string => `${GENERATED_HEADER}
#
# Publishes per-platform runtime bundles as immutable assets on a
# runtime-v<version> GitHub Release when plugins/provider-lando/runtime-bundle-version
# is bumped. Bundles are assembled from pinned upstream sources
# (plugins/provider-lando/runtime-bundle-sources.json), never from whatever the
# runner's package manager installed. The publish job fails rather than
# re-uploads if the tag or release already exists (release-asset immutability).
name: runtime-bundle

on:
  push:
    branches: [main]
    paths:
      - plugins/provider-lando/runtime-bundle-version
      - plugins/provider-lando/runtime-bundle-sources.json
  workflow_dispatch:

permissions:
  contents: read

jobs:
  assemble:
    if: github.ref == 'refs/heads/main'
    runs-on: \${{ matrix.runsOn }}
    strategy:
      fail-fast: true
      matrix:
        include:
${matrixInclude}
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: .bun-version

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Setup Go for Linux Podman source build
        if: startsWith(matrix.hostKey, 'linux-')
        uses: actions/setup-go@v5
        with:
          go-version: 1.25.6

      - name: Install Linux Podman source-build prerequisites
        if: startsWith(matrix.hostKey, 'linux-')
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \\
            build-essential \\
            libassuan-dev \\
            libbtrfs-dev \\
            libdevmapper-dev \\
            libglib2.0-dev \\
            libgpg-error-dev \\
            libgpgme-dev \\
            libseccomp-dev \\
            libsubid-dev \\
            libsystemd-dev \\
            pkg-config \\
            uidmap

      - name: Assemble \${{ matrix.hostKey }} runtime bundle from pinned sources
        run: bun run scripts/assemble-runtime-bundle.ts --platform \${{ matrix.hostKey }}

      - name: Upload assembled bundle
        uses: actions/upload-artifact@v4
        with:
          name: runtime-bundle-\${{ matrix.hostKey }}
          path: dist/cache/runtime-bundle/\${{ matrix.filename }}
          if-no-files-found: error
          retention-days: 7

  publish:
    needs: [assemble]
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: .bun-version

      - name: Download assembled bundles
        uses: actions/download-artifact@v4
        with:
          pattern: runtime-bundle-*
          merge-multiple: true
          path: dist/cache/runtime-bundle

      - name: Resolve runtime bundle tag
        run: |
          VERSION="$(tr -d '[:space:]' < plugins/provider-lando/runtime-bundle-version)"
          test -n "$VERSION"
          echo "RUNTIME_BUNDLE_VERSION=$VERSION" >> "$GITHUB_ENV"
          echo "RUNTIME_BUNDLE_TAG=runtime-v$VERSION" >> "$GITHUB_ENV"

      - name: Enforce release-asset immutability
        env:
          GH_TOKEN: \${{ github.token }}
        run: |
          set -euo pipefail
          if git ls-remote --tags origin "refs/tags/$RUNTIME_BUNDLE_TAG" | grep -q "$RUNTIME_BUNDLE_TAG"; then
            echo "::error title=runtime-bundle-immutable::tag $RUNTIME_BUNDLE_TAG already exists; runtime bundles are immutable — bump runtime-bundle-version instead of overwriting."
            exit 1
          fi
          if gh release view "$RUNTIME_BUNDLE_TAG" >/dev/null 2>&1; then
            echo "::error title=runtime-bundle-immutable::release $RUNTIME_BUNDLE_TAG already exists; refusing to re-upload assets."
            exit 1
          fi

      - name: Prepare manifest pin branch for landing
        env:
          GH_TOKEN: \${{ github.token }}
        run: |
          set -euo pipefail
          bun run scripts/build-runtime-bundle.ts --staging dist/cache/runtime-bundle
          if git diff --quiet -- plugins/provider-lando/runtime-bundle-versions.json; then
            echo "::notice title=runtime-bundle-manifest::manifest already pins $RUNTIME_BUNDLE_TAG assets; nothing to land."
            echo "RUNTIME_BUNDLE_MANIFEST_BRANCH=" >> "$GITHUB_ENV"
            exit 0
          fi
          BRANCH="runtime-bundle-manifest-$RUNTIME_BUNDLE_VERSION"
          echo "RUNTIME_BUNDLE_MANIFEST_BRANCH=$BRANCH" >> "$GITHUB_ENV"
          MANIFEST_PIN="$(mktemp)"
          cp plugins/provider-lando/runtime-bundle-versions.json "$MANIFEST_PIN"
          git restore -- plugins/provider-lando/runtime-bundle-versions.json
          if git ls-remote --heads origin "$BRANCH" | grep -q "$BRANCH"; then
            git fetch origin "$BRANCH:$BRANCH"
            git switch "$BRANCH"
          else
            git switch -c "$BRANCH"
          fi
          cp "$MANIFEST_PIN" plugins/provider-lando/runtime-bundle-versions.json
          if git diff --quiet -- plugins/provider-lando/runtime-bundle-versions.json; then
            echo "::notice title=runtime-bundle-manifest::manifest pin branch $BRANCH already matches regenerated assets."
            exit 0
          fi
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add plugins/provider-lando/runtime-bundle-versions.json
          git commit -m "pin runtime bundle manifest $RUNTIME_BUNDLE_VERSION"
          git push -u origin "$BRANCH"

      - name: Publish runtime-v release assets
        env:
          GH_TOKEN: \${{ github.token }}
        run: |
          set -euo pipefail
          gh release create "$RUNTIME_BUNDLE_TAG" ${assetArgs} \\
            --target "\${{ github.sha }}" \\
            --title "Lando runtime bundle $RUNTIME_BUNDLE_VERSION" \\
            --notes "Immutable per-platform runtime bundles assembled from pinned upstream sources for runtime version $RUNTIME_BUNDLE_VERSION."

      - name: Surface manifest pin PR
        env:
          GH_TOKEN: \${{ github.token }}
        run: |
          set -euo pipefail
          if [ -z "\${RUNTIME_BUNDLE_MANIFEST_BRANCH:-}" ]; then
            echo "::notice title=runtime-bundle-manifest::manifest already pins $RUNTIME_BUNDLE_TAG assets; no PR needed."
            exit 0
          fi
          if gh pr view "$RUNTIME_BUNDLE_MANIFEST_BRANCH" >/dev/null 2>&1; then
            echo "::notice title=runtime-bundle-manifest::manifest pin PR for $RUNTIME_BUNDLE_MANIFEST_BRANCH already exists."
            exit 0
          fi
          gh pr create --base main --head "$RUNTIME_BUNDLE_MANIFEST_BRANCH" \\
            --title "Pin runtime bundle manifest $RUNTIME_BUNDLE_VERSION" \\
            --body "Regenerated runtime-bundle-versions.json against the published $RUNTIME_BUNDLE_TAG release assets."
`;

const main = async (): Promise<void> => {
  await Bun.write(OUTPUT, renderRuntimeBundleWorkflow());
  console.log(`[build-runtime-bundle-workflow] wrote ${OUTPUT}`);
};

if (import.meta.main) await main();
