#!/usr/bin/env bun
import { mkdir } from "node:fs/promises";
import { dirname, resolve } from "node:path";

import type { BuiltInCommandEntry } from "../core/src/cli/built-in-command-registry.ts";
import { COMMAND_TOPICS } from "../core/src/cli/command-topics.ts";
import { universalFormatFlagDefs } from "../core/src/cli/format-flags.ts";
import { resolveTopLevelAliases } from "../core/src/cli/spec/command-spec.ts";
import { writeFormattedOutput } from "./_codegen-output.ts";

type JsonValue =
  | string
  | number
  | boolean
  | null
  | readonly JsonValue[]
  | { readonly [key: string]: JsonValue };

const REPOSITORY_ROOT = resolve(import.meta.dirname, "..");
const CORE_ROOT = resolve(REPOSITORY_ROOT, "core");
const OUTPUT = resolve(CORE_ROOT, "src/cli/generated/command-registry-manifest.ts");
const COMMAND_IDS_OUTPUT = resolve(CORE_ROOT, "src/cli/generated/command-ids.ts");
const RECIPE_POST_INIT_OUTPUT = resolve(CORE_ROOT, "src/cli/allowlists/recipe-post-init.ts");
const RECIPE_POST_INIT_DOCS = resolve(REPOSITORY_ROOT, "docs/reference/recipe-post-init.mdx");
const BOOTSTRAP_SOURCE =
  'export const COMMAND_REGISTRY_MANIFEST = { commands: {}, source: "built-in-command-registry", topics: {}, version: "0.0.0" } as const;\n';
const COMMAND_IDS_BOOTSTRAP_SOURCE = "export const BUILT_IN_COMMAND_IDS: ReadonlyArray<string> = [];\n";

const toJsonValue = (value: unknown): JsonValue | undefined => {
  if (value === null || typeof value === "string" || typeof value === "boolean") return value;
  if (typeof value === "number") return Number.isFinite(value) ? value : undefined;
  if (Array.isArray(value)) {
    return value.flatMap((item) => {
      const serialized = toJsonValue(item);
      return serialized === undefined ? [] : [serialized];
    });
  }
  if (typeof value !== "object") return undefined;

  const entries = Object.entries(value).flatMap(([key, item]) => {
    const serialized = toJsonValue(item);
    return serialized === undefined ? [] : [[key, serialized] as const];
  });
  return Object.fromEntries(entries);
};

const projectSpec = (entry: BuiltInCommandEntry): JsonValue => {
  const spec = entry.spec;
  return (
    toJsonValue({
      id: spec.id,
      summary: spec.summary,
      description: spec.summary,
      namespace: spec.namespace,
      deprecated: spec.deprecated,
      mcpAllowed: spec.mcpAllowed,
      hostProxyAllowed: spec.hostProxyAllowed,
      recipePostInitAllowed: spec.recipePostInitAllowed,
      topLevelAlias: spec.topLevelAlias,
      aliases: spec.aliases,
      examples: spec.examples,
      hidden: spec.hidden,
      deferred: spec.deferred,
      bootstrap: spec.bootstrap,
      helpGroup: spec.helpGroup,
      flags: spec.flags,
      args: spec.args,
      streamingMode: spec.streamingMode,
    }) ?? {}
  );
};

const projectCommand = (entry: BuiltInCommandEntry): JsonValue => {
  const spec = entry.spec;
  return (
    toJsonValue({
      aliases: resolveTopLevelAliases(spec),
      args: spec.args,
      description: spec.description,
      flags: { ...universalFormatFlagDefs, ...(spec.flags ?? {}) },
      hidden: spec.hidden === true,
      spec: projectSpec(entry),
      strict: spec.strict,
      summary: spec.summary,
    }) ?? {}
  );
};

const readCoreVersion = async (): Promise<string> => {
  const packageJson: unknown = await Bun.file(resolve(CORE_ROOT, "package.json")).json();
  if (
    typeof packageJson !== "object" ||
    packageJson === null ||
    !("version" in packageJson) ||
    typeof packageJson.version !== "string"
  ) {
    throw new TypeError("core/package.json is missing a string version");
  }
  return packageJson.version;
};

const renderManifestModule = (entries: readonly BuiltInCommandEntry[], version: string): string => {
  const commands = Object.fromEntries(entries.map((entry) => [entry.spec.id, projectCommand(entry)]));
  const manifest = { commands, source: "built-in-command-registry", topics: COMMAND_TOPICS, version };
  return `/**
 * **GENERATED FILE** — do not edit by hand.
 *
 * Regenerate via \`bun run scripts/build-command-registry-manifest.ts\`.
 * Source of truth: \`builtInCommandEntries\` and \`COMMAND_TOPICS\`.
 */
export const COMMAND_REGISTRY_MANIFEST = ${JSON.stringify(manifest, null, 2)} as const;
`;
};

const renderCommandIdsModule = (commandIds: readonly string[]): string => `/**
 * **GENERATED FILE** — do not edit by hand.
 *
 * Regenerate via \`bun run scripts/build-command-registry-manifest.ts\`.
 */
export const BUILT_IN_COMMAND_IDS = ${JSON.stringify(commandIds, null, 2)} as const;
`;

export const renderRecipePostInitAllowlist = (
  entries: readonly Pick<BuiltInCommandEntry, "spec">[],
): string => {
  const ids = entries
    .filter(({ spec }) => spec.recipePostInitAllowed === true)
    .map(({ spec }) => spec.id)
    .sort();
  return `// Generated by scripts/build-command-registry-manifest.ts. Do not edit.\nexport const RECIPE_POST_INIT_COMMAND_IDS = ${JSON.stringify(ids)} as const;\n`;
};

const main = async (): Promise<void> => {
  await Promise.all(
    [
      { content: BOOTSTRAP_SOURCE, path: OUTPUT },
      { content: COMMAND_IDS_BOOTSTRAP_SOURCE, path: COMMAND_IDS_OUTPUT },
      {
        content: "export const RECIPE_POST_INIT_COMMAND_IDS: readonly string[] = [];\n",
        path: RECIPE_POST_INIT_OUTPUT,
      },
    ].map(async ({ content, path }) => {
      if (await Bun.file(path).exists()) return;
      await mkdir(dirname(path), { recursive: true });
      await Bun.write(path, content);
    }),
  );
  const { builtInCommandEntries } = await import("../core/src/cli/built-in-command-registry.ts");
  const version = await readCoreVersion();
  const commandIds = builtInCommandEntries.map((entry) => entry.spec.id);
  await writeFormattedOutput(OUTPUT, renderManifestModule(builtInCommandEntries, version));
  await writeFormattedOutput(COMMAND_IDS_OUTPUT, renderCommandIdsModule(commandIds));
  await writeFormattedOutput(RECIPE_POST_INIT_OUTPUT, renderRecipePostInitAllowlist(builtInCommandEntries));
  await Bun.write(
    RECIPE_POST_INIT_DOCS,
    [
      "---",
      "title: Recipe post-init commands",
      "description: Canonical commands authorized after recipe scaffolding.",
      "---",
      "",
      "# Choose an authorized post-init command",
      "",
      "Recipe command actions accept only the canonical ids below. Aliases and host executable names are rejected during manifest validation and again at execution. Recipe-authored `runs` entries cannot extend this list.",
      "",
      "| Canonical command | Additional requirement |",
      "| --- | --- |",
      ...builtInCommandEntries
        .filter(({ spec }) => spec.recipePostInitAllowed === true)
        .map(
          ({ spec }) =>
            `| \`${spec.id}\` | ${spec.id === "app:start" ? "Explicit affirmative answer; never starts by default." : "Successful scaffold commit."} |`,
        ),
      "",
      "## Start opt-in",
      "",
      'For `app:start`, use a direct answer guard such as `when: "{{ options.start }}"`. A matching recipe prompt must be `confirm` with a false or omitted default. An explicit answer such as `--answer start=true` can only satisfy that declared matching prompt. Only boolean `true` or the CLI answer string `true` opts in; missing and negative answers skip the action.',
      "",
      "```yaml",
      "prompts:",
      "  - name: start",
      "    type: confirm",
      "    message: Start the app now?",
      "    default: false",
      "postInit:",
      "  - type: command",
      "    cmd: app:start",
      '    when: "{{ options.start }}"',
      "```",
      "",
      "## Conditions and execution",
      "",
      "Other actions may use bounded pure boolean expressions over `options`. Conditions cannot read host, environment, filesystem, or secret scopes. Invalid conditions fail closed. Canonical commands run through Lando from the scaffold destination, not through the host-tool `runs` policy. Public `lando start` flags are unchanged.",
      "",
      "Post-init executes after commit. A later action failure does not roll back committed files or earlier external effects. `gitInit` remains unsupported; run `git init` separately when needed.",
      "",
    ].join("\n"),
  );
  console.log(
    `[build-command-registry-manifest] wrote ${OUTPUT} + ${COMMAND_IDS_OUTPUT} (${commandIds.length} commands)`,
  );
};

if (import.meta.main) await main();
