#!/usr/bin/env bun
import { resolve } from "node:path";

const REPO_ROOT = resolve(import.meta.dirname, "..");
const OUTPUT = resolve(REPO_ROOT, ".github/workflows/release.yml");
const GENERATED_HEADER =
  "# Generated by scripts/codegen.ts — do not hand-edit. Edit scripts/build-release-workflow.ts instead.";

export const renderReleaseWorkflow = (): string => `${GENERATED_HEADER}
name: release

on:
  workflow_run:
    workflows: [ci]
    branches: [main]
    types: [completed]

permissions:
  contents: write
  actions: read

jobs:
  dev-prerelease-linux-x64:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: .bun-version

      - name: Download Linux x64 binary artifact
        env:
          GH_TOKEN: \${{ github.token }}
        run: gh run download "\${{ github.event.workflow_run.id }}" --name lando-linux-x64 --dir dist

      - name: Restore binary executable bit
        run: chmod +x dist/lando

      - name: Install first-launch sandbox tools
        run: |
          sudo apt-get update
          sudo apt-get install -y strace iproute2

      - name: Sandboxed first launch has no non-loopback network calls
        run: |
          set -euo pipefail
          mkdir -p "$RUNNER_TEMP/lando-conf" "$RUNNER_TEMP/lando-data" "$RUNNER_TEMP/lando-cache"
          sudo env LANDO_USER_CONF_ROOT="$RUNNER_TEMP/lando-conf" LANDO_USER_DATA_ROOT="$RUNNER_TEMP/lando-data" LANDO_USER_CACHE_ROOT="$RUNNER_TEMP/lando-cache" unshare --net sh -c '
            set -euo pipefail
            ip link set lo up
            strace -f -e trace=network -o dist/first-launch.network.log ./dist/lando --version
          '
          awk '/connect\\(/ && $0 !~ /(127\\.|::1|AF_UNIX)/ { bad = 1 } END { exit bad }' dist/first-launch.network.log

      - name: Write SHA256SUMS
        run: |
          cd dist
          sha256sum lando > SHA256SUMS
          grep -Eq '^[0-9a-f]{64}  lando$' SHA256SUMS

      - name: Publish dev prerelease
        env:
          GH_TOKEN: \${{ github.token }}
          RELEASE_TAG: v4.0.0-dev.\${{ github.run_number }}
        run: |
          gh release delete "$RELEASE_TAG" --yes --cleanup-tag 2>/dev/null || true
          gh release create "$RELEASE_TAG" dist/lando dist/SHA256SUMS --prerelease --target "\${{ github.event.workflow_run.head_sha }}" --title "Lando v4 dev \${{ github.run_number }}" --notes "Generated Linux x64 dev prerelease from successful ci workflow run \${{ github.event.workflow_run.id }}."
`;

const main = async (): Promise<void> => {
  await Bun.write(OUTPUT, renderReleaseWorkflow());
  console.log(`[build-release-workflow] wrote ${OUTPUT}`);
};

if (import.meta.main) await main();
