#!/usr/bin/env bun
import { mkdir } from "node:fs/promises";
import { resolve } from "node:path";

import {
  PHP_COMMON_EXTENSIONS,
  PHP_COMPOSER,
  PHP_COMPOSER_COMMAND,
  PHP_PREREQUISITES_COMMAND,
} from "../plugins/service-lando/src/services/php-prerequisites.ts";
import {
  SUPPORTED_PHP_VERSIONS,
  type SupportedPhpVersion,
} from "../plugins/service-lando/src/services/php.ts";

const REPO_ROOT = resolve(import.meta.dirname, "..");
const GENERATED_HEADER =
  "# Generated by scripts/codegen.ts — do not hand-edit. Edit plugins/service-lando/src/services/php-prerequisites.ts instead.";

export const renderPhpBaseDockerfile = (version: SupportedPhpVersion): string => `${GENERATED_HEADER}
FROM php:${version}-apache-bookworm

LABEL org.lando.php.extensions="${PHP_COMMON_EXTENSIONS.join(",")}" \\
      org.lando.composer.version="${PHP_COMPOSER.version}" \\
      org.lando.composer.sha256="${PHP_COMPOSER.sha256}"

RUN ${PHP_PREREQUISITES_COMMAND}
RUN ${PHP_COMPOSER_COMMAND}
`;

const main = async (): Promise<void> => {
  for (const version of SUPPORTED_PHP_VERSIONS) {
    const directory = resolve(REPO_ROOT, "images/php", version);
    await mkdir(directory, { recursive: true });
    await Bun.write(resolve(directory, "Dockerfile"), renderPhpBaseDockerfile(version));
  }
};

if (import.meta.main) await main();
