import { resolve } from "node:path";

import { renderAssertPodman6Step, renderInstallPodman6Step } from "./ci-podman-install.ts";

const REPO_ROOT = resolve(import.meta.dirname, "..");
const OUTPUT = resolve(REPO_ROOT, ".github/workflows/provider-matrix.yml");
const GENERATED_HEADER =
  "# Generated by scripts/codegen.ts — do not hand-edit. Edit scripts/build-provider-matrix-workflow.ts instead.";

interface ProviderMatrixCell {
  readonly id: string;
  readonly engine: string;
  readonly runsOn: string;
  readonly provider: "docker" | "podman" | "lando";
  readonly installable: boolean;
  readonly notice?: string;
}

const CELLS: ReadonlyArray<ProviderMatrixCell> = [
  {
    id: "docker-desktop-macos",
    engine: "Docker Desktop",
    runsOn: "macos-15",
    provider: "docker",
    installable: false,
    notice:
      "Docker Desktop requires a licensed desktop app and is not installed on GitHub-hosted macOS runners.",
  },
  {
    id: "docker-engine-linux",
    engine: "Docker Engine",
    runsOn: "ubuntu-24.04",
    provider: "docker",
    installable: true,
  },
  {
    id: "podman-desktop-macos",
    engine: "Podman Desktop",
    runsOn: "macos-15",
    provider: "podman",
    installable: false,
    notice:
      "Podman Desktop is not installable in GitHub-hosted CI; run this cell on a prepared self-hosted runner.",
  },
  {
    id: "podman-linux",
    engine: "Podman",
    runsOn: "ubuntu-24.04",
    provider: "lando",
    installable: true,
  },
  {
    id: "lima-macos",
    engine: "Lima",
    runsOn: "macos-15",
    provider: "docker",
    installable: false,
    notice:
      "Lima provider coverage needs a prepared macOS runtime; GitHub-hosted runners do not ship a reusable Lima daemon.",
  },
  {
    id: "orbstack-macos",
    engine: "OrbStack",
    runsOn: "macos-15",
    provider: "docker",
    installable: false,
    notice: "OrbStack is a macOS desktop runtime and is not installable in GitHub-hosted CI.",
  },
];

const setupBunSteps = `      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: .bun-version

      - name: Install dependencies
        run: bun install --frozen-lockfile`;

const matrixInclude = CELLS.map(
  (cell) => `          - cell: ${cell.id}
            engine: ${cell.engine}
            runs-on: ${cell.runsOn}
            provider: ${cell.provider}
            installable: ${cell.installable ? "true" : "false"}
            notice: ${cell.notice ?? "GitHub-hosted CI runtime is available."}`,
).join("\n");

export const renderProviderMatrixWorkflow = (): string => `${GENERATED_HEADER}
name: provider-matrix

on:
  schedule:
    - cron: '0 8 * * 1'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  provider-contracts:
    strategy:
      fail-fast: false
      matrix:
        include:
${matrixInclude}
    runs-on: \${{ matrix.runs-on }}
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4

${setupBunSteps}

      - name: Notice unsupported hosted runner cell
        if: \${{ matrix.installable == false }}
        run: |
          echo "::notice title=provider-matrix::\${{ matrix.engine }} skipped: \${{ matrix.notice }}"

${renderInstallPodman6Step({ condition: "matrix.cell == 'podman-linux'" })}

${renderAssertPodman6Step({ condition: "matrix.cell == 'podman-linux'" })}

      - name: Start Podman socket
        if: \${{ matrix.cell == 'podman-linux' }}
        run: |
          sudo sysctl net.ipv4.ip_unprivileged_port_start=0
          podman system service --time=0 unix:///tmp/podman.sock > /tmp/podman-service.log 2>&1 &
          echo "$!" > /tmp/podman-service.pid
          for _ in {1..30}; do
            test -S /tmp/podman.sock && break
            sleep 1
          done
          test -S /tmp/podman.sock
          echo "LANDO_TEST_PODMAN_SOCKET=/tmp/podman.sock" >> "$GITHUB_ENV"
          echo "LANDO_CONFIG__default_provider_id=\${{ matrix.provider }}" >> "$GITHUB_ENV"

      - name: Configure Docker socket
        if: \${{ matrix.cell == 'docker-engine-linux' }}
        run: |
          test -S /var/run/docker.sock
          echo "LANDO_TEST_DOCKER_SOCKET=/var/run/docker.sock" >> "$GITHUB_ENV"
          echo "LANDO_CONFIG__default_provider_id=\${{ matrix.provider }}" >> "$GITHUB_ENV"

      - name: Run provider contract tests
        if: \${{ matrix.installable == true }}
        run: |
          bun test sdk/test/contract/provider.test.ts sdk/test/contract/service.test.ts
          bun test plugins/provider-lando/test/contract.integration.test.ts
          bun test plugins/provider-docker/test/contract.integration.test.ts
          bun test plugins/provider-podman/test/contract.integration.test.ts
          bun test plugins/provider-podman/test/capabilities.test.ts

      - name: Teardown Podman
        if: \${{ always() && matrix.cell == 'podman-linux' }}
        run: |
          podman ps -aq --filter "name=lando-" | xargs -r podman rm -f || true
          podman network ls --format '{{.Name}}' | grep '^lando-' | xargs -r podman network rm || true
          if test -f /tmp/podman-service.pid; then kill "$(cat /tmp/podman-service.pid)" || true; fi
          rm -f /tmp/podman.sock /tmp/podman-service.pid

      - name: Collect provider matrix diagnostics
        if: failure()
        run: |
          mkdir -p provider-matrix-diagnostics
          cp /tmp/podman-service.log provider-matrix-diagnostics/podman-service.log || true
          journalctl --no-pager --since "-30 minutes" > provider-matrix-diagnostics/journalctl.log 2>&1 || true

      - name: Upload provider matrix diagnostics
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: provider-matrix-diagnostics-\${{ matrix.cell }}
          path: provider-matrix-diagnostics
          if-no-files-found: ignore
          retention-days: 7
`;

const main = async (): Promise<void> => {
  await Bun.write(OUTPUT, renderProviderMatrixWorkflow());
  console.log(`[build-provider-matrix-workflow] wrote ${OUTPUT}`);
};

if (import.meta.main) await main();
