import { resolve } from "node:path";

import { landoRootlessPrereqSteps } from "./build-ci-workflow.ts";
import { renderAssertPodman6Step, renderInstallPodman6Step } from "./ci-podman-install.ts";
import { PROVIDER_ACCEPTANCE_CELLS, type ProviderAcceptanceCellPlan } from "./provider-matrix-plan.ts";

const REPO_ROOT = resolve(import.meta.dirname, "..");
const OUTPUT = resolve(REPO_ROOT, ".github/workflows/provider-matrix.yml");
const GENERATED_HEADER =
  "# Generated by scripts/codegen.ts — do not hand-edit. Edit scripts/build-provider-matrix-workflow.ts instead.";

const yamlString = (value: string): string => JSON.stringify(value);
const cells: readonly ProviderAcceptanceCellPlan[] = PROVIDER_ACCEPTANCE_CELLS;

const setupBunSteps = `      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: .bun-version

      - name: Install dependencies
        run: bun install --frozen-lockfile`;

const matrixInclude = cells
  .map(
    (cell) => `          - cell: ${cell.id}
            engine: ${cell.engine}
            runs-on: ${cell.runsOn}
            provider: ${cell.provider}
            release-blocking: ${cell.releaseBlocking ? "true" : "false"}
            install-podman6: ${cell.installPodman6 ? "true" : "false"}
            setup: ${cell.setup}
            advisory-skip: ${cell.advisorySkipReason === undefined ? "false" : "true"}
            notice: ${yamlString(cell.advisorySkipReason ?? "GitHub-hosted CI runtime is available.")}`,
  )
  .join("\n");

const landoRootlessPrereqStep = landoRootlessPrereqSteps.replace(
  "      - name: Provision rootless runtime prerequisites",
  "      - name: Provision Linux rootless runtime prerequisites\n        if: ${{ matrix.cell == 'lando-podman6-linux' || matrix.cell == 'podman-podman6-linux' }}",
);

const managedLandoSteps = `${landoRootlessPrereqStep}

      - name: Build Linux x64 binary for managed Lando provider
        if: \${{ matrix.cell == 'lando-podman6-linux' }}
        run: |
          mkdir -p dist
          bun run --filter='@lando/core' build:manifest
          bun run --filter='@lando/core' build:log-file-helper
          bun -e "const fs = await import('node:fs/promises'); await fs.cp('core/dist/log-file-access', 'dist/log-file-access', { recursive: true });"
          bun run scripts/build-compiled-binary.ts --target bun-linux-x64 --outfile ./dist/lando --minify --sourcemap=external
          bun run scripts/sanitize-compiled-binary.ts ./dist/lando
          ./dist/lando --version

      - name: Prepare managed Lando provider from committed manifest
        if: \${{ matrix.cell == 'lando-podman6-linux' }}
        run: |
          test -z "\${LANDO_RUNTIME_BUNDLE_MANIFEST:-}"
          test -z "\${LANDO_RUNTIME_BUNDLE_URL:-}"
          test -z "\${LANDO_RUNTIME_BUNDLE_SHA256:-}"
          export LANDO_USER_CONF_ROOT="$RUNNER_TEMP/lando-conf"
          export LANDO_USER_DATA_ROOT="$RUNNER_TEMP/lando-data"
          export LANDO_USER_CACHE_ROOT="$RUNNER_TEMP/lando-cache"
          echo "LANDO_USER_CONF_ROOT=$LANDO_USER_CONF_ROOT" >> "$GITHUB_ENV"
          echo "LANDO_USER_DATA_ROOT=$LANDO_USER_DATA_ROOT" >> "$GITHUB_ENV"
          echo "LANDO_USER_CACHE_ROOT=$LANDO_USER_CACHE_ROOT" >> "$GITHUB_ENV"
          export XDG_RUNTIME_DIR="\${XDG_RUNTIME_DIR:-/run/user/$(id -u)}"
          mkdir -p "$XDG_RUNTIME_DIR"
          cat > "$RUNNER_TEMP/lando-storage.conf" <<EOF
          [storage]
          driver = "overlay"

          [storage.options.overlay]
          mount_program = "$LANDO_USER_DATA_ROOT/runtime/bin/fuse-overlayfs"
          EOF
          export CONTAINERS_STORAGE_CONF="$RUNNER_TEMP/lando-storage.conf"
          echo "CONTAINERS_STORAGE_CONF=$CONTAINERS_STORAGE_CONF" >> "$GITHUB_ENV"
          dist/lando setup --yes --provider=lando --skip-install-ca --skip-shell-integration --skip-file-sync

      - name: Verify managed Lando socket
        if: \${{ matrix.cell == 'lando-podman6-linux' }}
        run: |
          for _ in {1..30}; do
            test -S "$RUNNER_TEMP/lando-data/runtime/run/podman.sock" && break
            sleep 1
          done
          test -S "$RUNNER_TEMP/lando-data/runtime/run/podman.sock"
          "$RUNNER_TEMP/lando-data/runtime/bin/podman" --version
          dist/lando doctor --format json > /tmp/lando-managed-provider-doctor.json
          echo "LANDO_TEST_PODMAN_SOCKET=$RUNNER_TEMP/lando-data/runtime/run/podman.sock" >> "$GITHUB_ENV"
          echo "LANDO_CONFIG__default_provider_id=lando" >> "$GITHUB_ENV"`;

const managedLandoTeardown = `      - name: Teardown managed Lando runtime
        if: \${{ always() && matrix.cell == 'lando-podman6-linux' }}
        run: |
          dist/lando poweroff || true
          LANDO_PODMAN="$RUNNER_TEMP/lando-data/runtime/bin/podman"
          LANDO_PODMAN_ARGS=(--root "$RUNNER_TEMP/lando-data/runtime/storage" --runroot "$RUNNER_TEMP/lando-data/runtime/run" --config "$RUNNER_TEMP/lando-data/runtime/config")
          if test -x "$LANDO_PODMAN"; then
            "$LANDO_PODMAN" "\${LANDO_PODMAN_ARGS[@]}" ps -aq --filter "name=lando-" | xargs -r "$LANDO_PODMAN" "\${LANDO_PODMAN_ARGS[@]}" rm -f || true
            "$LANDO_PODMAN" "\${LANDO_PODMAN_ARGS[@]}" network ls --format '{{.Name}}' | grep '^lando-' | xargs -r "$LANDO_PODMAN" "\${LANDO_PODMAN_ARGS[@]}" network rm || true
          fi`;

export const renderProviderMatrixWorkflow = (): string => `${GENERATED_HEADER}
name: provider-matrix

on:
  schedule:
    - cron: '0 8 * * 1'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  provider-contracts:
    env:
      LANDO_TEST_PROVIDER_LANDO_MACHINE_LIFECYCLE: \${{ vars.LANDO_TEST_PROVIDER_LANDO_MACHINE_LIFECYCLE }}
      LANDO_TEST_PROVIDER_PODMAN_MACHINE_LIFECYCLE: \${{ vars.LANDO_TEST_PROVIDER_PODMAN_MACHINE_LIFECYCLE }}
      LANDO_TEST_PODMAN_COMMAND: \${{ vars.LANDO_TEST_PODMAN_COMMAND }}
    strategy:
      fail-fast: false
      matrix:
        include:
${matrixInclude}
    runs-on: \${{ matrix.runs-on }}
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4

${setupBunSteps}

      - name: Notice unsupported hosted runner cell
        if: \${{ matrix['advisory-skip'] == true }}
        run: |
          echo "::notice title=provider-matrix::\${{ matrix.engine }} skipped: \${{ matrix.notice }}"

${managedLandoSteps}

${renderInstallPodman6Step({ condition: "matrix.cell == 'podman-podman6-linux'" })}

${renderAssertPodman6Step({ condition: "matrix.cell == 'podman-podman6-linux'" })}

      - name: Start Podman socket
        if: \${{ matrix.cell == 'podman-podman6-linux' }}
        run: |
          sudo sysctl net.ipv4.ip_unprivileged_port_start=0
          podman system service --time=0 unix:///tmp/podman.sock > /tmp/podman-service.log 2>&1 &
          echo "$!" > /tmp/podman-service.pid
          for _ in {1..30}; do
            test -S /tmp/podman.sock && break
            sleep 1
          done
          if test -S /tmp/podman.sock; then
            echo "LANDO_TEST_PODMAN_SOCKET=/tmp/podman.sock" >> "$GITHUB_ENV"
          else
            echo "::warning title=provider-matrix::Podman socket was not ready; acceptance runner will emit a structured skip."
          fi
          echo "LANDO_CONFIG__default_provider_id=\${{ matrix.provider }}" >> "$GITHUB_ENV"

      - name: Configure Docker socket
        if: \${{ matrix.cell == 'docker-engine-linux' }}
        run: |
          test -S /var/run/docker.sock
          echo "LANDO_TEST_DOCKER_SOCKET=/var/run/docker.sock" >> "$GITHUB_ENV"
          echo "LANDO_CONFIG__default_provider_id=\${{ matrix.provider }}" >> "$GITHUB_ENV"

      - name: Pull live acceptance fixture images
        if: \${{ matrix['release-blocking'] == true }}
        run: |
          for image in node:22-alpine postgres:16-alpine alpine:3.20; do
            case "\${{ matrix.cell }}" in
              lando-podman6-linux)
                CONTAINERS_REGISTRIES_CONF="$RUNNER_TEMP/lando-data/runtime/config/registries.conf" "$RUNNER_TEMP/lando-data/runtime/bin/podman" --url "unix://$LANDO_TEST_PODMAN_SOCKET" pull "$image"
                ;;
              podman-podman6-linux)
                podman --url "unix://$LANDO_TEST_PODMAN_SOCKET" pull "$image"
                ;;
              docker-engine-linux)
                docker pull "$image"
                ;;
            esac
          done

      - name: Run structured provider acceptance cell
        if: always()
        run: |
          bun run scripts/provider-matrix-acceptance.ts --cell '\${{ matrix.cell }}' --report-dir provider-matrix-reports

      - name: Upload provider matrix cell report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: provider-matrix-report-\${{ matrix.cell }}
          path: provider-matrix-reports/\${{ matrix.cell }}.json
          if-no-files-found: error
          retention-days: 14

      - name: Teardown Podman
        if: \${{ always() && matrix.cell == 'podman-podman6-linux' }}
        run: |
          podman ps -aq --filter "name=lando-" | xargs -r podman rm -f || true
          podman network ls --format '{{.Name}}' | grep '^lando-' | xargs -r podman network rm || true
          if test -f /tmp/podman-service.pid; then kill "$(cat /tmp/podman-service.pid)" || true; fi
          rm -f /tmp/podman.sock /tmp/podman-service.pid

${managedLandoTeardown}

      - name: Collect provider matrix diagnostics
        if: failure()
        run: |
          mkdir -p provider-matrix-diagnostics
          cp /tmp/podman-service.log provider-matrix-diagnostics/podman-service.log || true
          if test -f "\${LANDO_USER_DATA_ROOT:-}/runtime/run/service.log"; then
            cp "$LANDO_USER_DATA_ROOT/runtime/run/service.log" provider-matrix-diagnostics/lando-managed-service.log || true
          fi
          if test -d "\${LANDO_USER_CACHE_ROOT:-}/logs"; then
            cp -r "$LANDO_USER_CACHE_ROOT/logs" provider-matrix-diagnostics/lando-logs || true
          fi
          journalctl --no-pager --since "-30 minutes" > provider-matrix-diagnostics/journalctl.log 2>&1 || true

      - name: Upload provider matrix diagnostics
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: provider-matrix-diagnostics-\${{ matrix.cell }}
          path: provider-matrix-diagnostics
          if-no-files-found: ignore
          retention-days: 7
`;

const main = async (): Promise<void> => {
  await Bun.write(OUTPUT, renderProviderMatrixWorkflow());
  console.log(`[build-provider-matrix-workflow] wrote ${OUTPUT}`);
};

if (import.meta.main) await main();
