#!/usr/bin/env bun
import { readdir, rm } from "node:fs/promises";
import { resolve } from "node:path";

import { CI_PLATFORMS } from "./ci-platforms.ts";

const REPO_ROOT = resolve(import.meta.dirname, "..");
const OPENTUI_ROOT = resolve(REPO_ROOT, "node_modules/@opentui/core");
const RENDERER_PACKAGE = resolve(REPO_ROOT, "plugins/renderer-lando/package.json");
const LOCKFILE = resolve(REPO_ROOT, "bun.lock");
const OUTPUT_ROOT = resolve(REPO_ROOT, "scripts/generated/opentui-native");
const STUBS_ROOT = resolve(OUTPUT_ROOT, "stubs");
const CATALOG_PATH = resolve(OUTPUT_ROOT, "catalog.generated.ts");
const PINNED_VERSION = "0.4.3";
const PINNED_RENDERER_RANGE = "^0.4.3";

const NATIVE_ROOTS = [
  "@opentui/core-darwin-arm64",
  "@opentui/core-darwin-x64",
  "@opentui/core-linux-arm64",
  "@opentui/core-linux-arm64-musl",
  "@opentui/core-linux-x64",
  "@opentui/core-linux-x64-musl",
  "@opentui/core-win32-arm64",
  "@opentui/core-win32-x64",
] as const;

const TARGET_TO_NATIVE_ROOT = {
  "darwin-arm64": "@opentui/core-darwin-arm64",
  "darwin-x64": "@opentui/core-darwin-x64",
  "linux-arm64": "@opentui/core-linux-arm64",
  "linux-x64": "@opentui/core-linux-x64",
  "windows-x64": "@opentui/core-win32-x64",
} as const;

export interface PinnedInputs {
  readonly installedVersion: string;
  readonly literalBranchRoots: readonly string[];
  readonly rendererDependencyRange: string;
  readonly lockResolution: string;
}

const sameStrings = (left: readonly string[], right: readonly string[]): boolean =>
  left.length === right.length && left.every((value, index) => value === right[index]);

export const validatePinnedInputs = (inputs: PinnedInputs): void => {
  if (inputs.installedVersion !== PINNED_VERSION) {
    throw new Error(
      `Unexpected installed @opentui/core version ${inputs.installedVersion}; expected ${PINNED_VERSION}.`,
    );
  }
  if (!sameStrings([...inputs.literalBranchRoots].sort(), NATIVE_ROOTS)) {
    throw new Error("Installed @opentui/core literal branch roots diverged from the pinned catalog.");
  }
  if (inputs.rendererDependencyRange !== PINNED_RENDERER_RANGE) {
    throw new Error(
      `Unexpected renderer dependency range ${inputs.rendererDependencyRange}; expected ${PINNED_RENDERER_RANGE}.`,
    );
  }
  if (inputs.lockResolution !== PINNED_VERSION) {
    throw new Error(`Unexpected bun.lock resolution ${inputs.lockResolution}; expected ${PINNED_VERSION}.`);
  }
};

const requiredCapture = (source: string, pattern: RegExp, description: string): string => {
  const value = pattern.exec(source)?.[1];
  if (value === undefined) {
    throw new Error(`Could not read ${description}.`);
  }
  return value;
};

const readPinnedInputs = async (): Promise<PinnedInputs> => {
  const packageJson = await Bun.file(resolve(OPENTUI_ROOT, "package.json")).text();
  const rendererPackage = await Bun.file(RENDERER_PACKAGE).text();
  const lockfile = await Bun.file(LOCKFILE).text();
  const literalBranchRoots = new Set<string>();
  const lockResolutions = new Map<string, string>();

  for (const entry of await readdir(OPENTUI_ROOT, { withFileTypes: true })) {
    if (!entry.isFile() || !entry.name.endsWith(".js")) continue;
    const source = await Bun.file(resolve(OPENTUI_ROOT, entry.name)).text();
    for (const match of source.matchAll(/import\("(@opentui\/core-[^"]+)"\)/gu)) {
      const root = match[1];
      if (root !== undefined) literalBranchRoots.add(root);
    }
  }
  for (const match of lockfile.matchAll(
    /"(@opentui\/core(?:-[^"]+)?)"\s*:\s*\["@opentui\/core(?:-[^@"]+)?@([^"]+)"/gu,
  )) {
    const packageName = match[1];
    const version = match[2];
    if (packageName !== undefined && version !== undefined) lockResolutions.set(packageName, version);
  }
  const expectedLockedPackages = ["@opentui/core", ...NATIVE_ROOTS].sort();
  if (!sameStrings([...lockResolutions.keys()].sort(), expectedLockedPackages)) {
    throw new Error("bun.lock resolution package set diverged from the pinned OpenTUI catalog.");
  }

  return {
    installedVersion: requiredCapture(packageJson, /"version"\s*:\s*"([^"]+)"/u, "installed version"),
    literalBranchRoots: [...literalBranchRoots].sort(),
    rendererDependencyRange: requiredCapture(
      rendererPackage,
      /"@opentui\/core"\s*:\s*"([^"]+)"/u,
      "renderer dependency range",
    ),
    lockResolution: [...new Set(lockResolutions.values())].sort().join(","),
  };
};

const stubFilename = (root: string): string => `${root.replace("@opentui/", "")}.generated.ts`;

const renderCatalog =
  (): string => `// Generated by scripts/build-opentui-native-stubs.ts. Do not edit by hand.
import { resolve } from "node:path";

const allNativeRoots = ${JSON.stringify(NATIVE_ROOTS, null, 2)} as const;
const targetToNativeRoot = ${JSON.stringify(TARGET_TO_NATIVE_ROOT, null, 2)} as const;
const knownNativeRoots = new Set<string>(allNativeRoots);
const knownTargets = new Set<string>(Object.keys(targetToNativeRoot));

const stubPathFor = (target: string, root: string): string => {
  if (!knownTargets.has(target)) throw new Error(\`Unknown Lando release target: \${target}.\`);
  if (!knownNativeRoots.has(root)) throw new Error(\`Cannot stub unknown OpenTUI native root: \${root}.\`);
  const targetNativeRoot = Object.entries(targetToNativeRoot).find(([candidate]) => candidate === target)?.[1];
  if (root === targetNativeRoot) throw new Error(\`Cannot stub target native root \${root} for \${target}.\`);
  return resolve(import.meta.dirname, "stubs", target, \`\${root.replace("@opentui/", "")}.generated.ts\`);
};

export const opentuiNativeCatalog = {
  allNativeRoots,
  targetToNativeRoot,
  rootImportFilter: /^(?:${NATIVE_ROOTS.map((root) => root.replaceAll("/", "\\/")).join("|")})$/,
  stubPathFor,
} as const;
`;

const main = async (): Promise<void> => {
  validatePinnedInputs(await readPinnedInputs());
  const releaseTargets = CI_PLATFORMS.map((platform) => platform.id).sort();
  if (!sameStrings(releaseTargets, Object.keys(TARGET_TO_NATIVE_ROOT).sort())) {
    throw new Error("CI release targets diverged from the pinned OpenTUI native target mapping.");
  }

  await rm(STUBS_ROOT, { recursive: true, force: true });
  await Bun.write(CATALOG_PATH, renderCatalog());
  const generatedPaths = [CATALOG_PATH];

  for (const target of releaseTargets) {
    const nativeRoot = Object.entries(TARGET_TO_NATIVE_ROOT).find(([candidate]) => candidate === target)?.[1];
    for (const root of NATIVE_ROOTS) {
      if (root === nativeRoot) continue;
      const path = resolve(STUBS_ROOT, target, stubFilename(root));
      await Bun.write(
        path,
        `throw new Error(\n  ${JSON.stringify(`OpenTUI native package ${root} is unreachable for release target ${target}.`)},\n);\n`,
      );
      generatedPaths.push(path);
    }
  }

  const formatter = Bun.spawn(["bun", "run", "biome", "check", "--write", ...generatedPaths], {
    cwd: REPO_ROOT,
    stdout: "ignore",
    stderr: "inherit",
  });
  const formatterExitCode = await formatter.exited;
  if (formatterExitCode !== 0) {
    throw new Error(`Biome failed with exit code ${formatterExitCode}.`);
  }
  console.log(`[build-opentui-native-stubs] wrote 1 catalog and ${generatedPaths.length - 1} stubs`);
};

if (import.meta.main) await main();
