#!/usr/bin/env bun
import { resolve } from "node:path";

import { landoRootlessPrereqSteps } from "./build-ci-workflow.ts";
import {
  CI_PLATFORMS,
  type CiPlatform,
  PLATFORM_READINESS_CELLS,
  type PlatformReadinessCell,
  isWindowsCiPlatform,
} from "./ci-platforms.ts";
import * as supplyChain from "./runtime-bundle-supply-chain.ts";

const REPO_ROOT = resolve(import.meta.dirname, "..");
const OUTPUT = resolve(REPO_ROOT, ".github/workflows/rails-journey.yml");
const GENERATED_HEADER =
  "# Generated by scripts/codegen.ts — do not hand-edit. Edit scripts/build-rails-journey-workflow.ts instead.";
const SCHEDULE_IF = "github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'";

const assertNever = (value: never): never => {
  throw new Error(`Unexpected rails-journey value: ${String(value)}`);
};

const ciPlatformFor = (id: string): CiPlatform => {
  const platform = CI_PLATFORMS.find((candidate) => candidate.id === id);
  if (platform === undefined) {
    throw new Error(`CI_PLATFORMS is missing ${id}`);
  }
  return platform;
};

const renderRunsOn = (runsOn: PlatformReadinessCell["runsOn"]): string =>
  typeof runsOn === "string" ? runsOn : `[${runsOn.join(", ")}]`;

const renderCadenceIf = (cadence: PlatformReadinessCell["cadence"]): string => {
  switch (cadence) {
    case "pr+evidence":
      return "";
    case "evidence":
      return `    if: ${SCHEDULE_IF}\n`;
    default:
      return assertNever(cadence);
  }
};

const isLinuxLando = (cell: PlatformReadinessCell): boolean =>
  cell.id.startsWith("linux-") && cell.provider === "lando";
const isLinuxCurrentCommit = (cell: PlatformReadinessCell): boolean =>
  cell.bundleMode === "current-commit" && cell.bundleKey.startsWith("linux-");

const setupFlags = (cell: PlatformReadinessCell): string => {
  const flags = `--yes --provider=${cell.provider} --skip-install-ca --skip-shell-integration --skip-file-sync`;
  return isWindowsCiPlatform(cell) ? `${flags} --no-interactive` : flags;
};

// GitHub does not expose the `runner` context to job-level `env:`, so these
// roots are exported from the first step instead. Declaring them at job level
// makes GitHub reject the entire workflow file.
const isolateRootsStep = `      - name: Isolate Lando roots
        run: |
          echo "LANDO_USER_CONF_ROOT=$RUNNER_TEMP/lando-conf" >> "$GITHUB_ENV"
          echo "LANDO_USER_DATA_ROOT=$RUNNER_TEMP/lando-data" >> "$GITHUB_ENV"
          echo "LANDO_USER_CACHE_ROOT=$RUNNER_TEMP/lando-cache" >> "$GITHUB_ENV"`;

const setupBunSteps = `      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: .bun-version

      - name: Install dependencies
        run: bun install --frozen-lockfile`;

const derivedSourcesSteps = `      - name: Regenerate derived sources
        run: bun run codegen

      - name: Build command registry manifest
        run: bun run --filter='@lando/core' build:manifest`;

const renderCompileStep = (platform: CiPlatform): string => `      - name: Build ${platform.id} binary
        run: |
          mkdir -p dist
          VERSION=$(git describe --tags --always --dirty 2>/dev/null || echo "0.0.0-dev")
          bun run scripts/build-compiled-binary.ts --target ${platform.bunTarget} --outfile ./dist/${platform.binaryName} --version "$VERSION" --minify --sourcemap=external`;

const renderLinuxSourceBuildPrereqs = (): string => `
      - name: Setup Go for Linux Podman source build
        uses: ${supplyChain.RUNTIME_BUNDLE_ACTION_PINS.setupGo} # v5.5.0
        with:
          go-version: 1.25.6

      - name: Setup Rust for Linux helper source builds
        uses: ${supplyChain.RUNTIME_BUNDLE_ACTION_PINS.rustToolchain} # 1.88.0

      - name: Install Linux Podman source-build prerequisites
        run: |
          ${supplyChain.RUNTIME_BUNDLE_UBUNTU_PREREQUISITE_SCRIPT}
`;

const renderBundleSteps = (cell: PlatformReadinessCell): string => {
  switch (cell.bundleMode) {
    case "current-commit":
      return `${isLinuxCurrentCommit(cell) ? renderLinuxSourceBuildPrereqs() : ""}
      - name: Assemble current-commit ${cell.bundleKey} runtime bundle
        run: bun run scripts/assemble-runtime-bundle.ts --platform ${cell.bundleKey}

      - name: Build local runtime bundle manifest
        run: |
          RUNTIME_VERSION="$(bun -e 'import { readRuntimeBundleSources } from "./scripts/runtime-bundle-sources.ts"; process.stdout.write((await readRuntimeBundleSources()).runtimeVersion)')"
          MANIFEST="$(bun run scripts/build-runtime-bundle.ts --local --platform ${cell.bundleKey} --runtime-version "$RUNTIME_VERSION")"
          echo "LANDO_RUNTIME_BUNDLE_MANIFEST=$MANIFEST" >> "$GITHUB_ENV"
`;
    case "published":
    case "none":
      return "";
    default:
      return assertNever(cell.bundleMode);
  }
};

const renderLinuxLandoPrereqs = (cell: PlatformReadinessCell): string => {
  if (!isLinuxLando(cell)) return "";
  return `
${landoRootlessPrereqSteps}

      - name: Configure rootless overlay storage
        run: |
          cat > "\${{ runner.temp }}/lando-storage.conf" <<EOF
          [storage]
          driver = "overlay"

          [storage.options.overlay]
          mount_program = "\${{ runner.temp }}/lando-data/runtime/bin/fuse-overlayfs"
          EOF
          echo "CONTAINERS_STORAGE_CONF=\${{ runner.temp }}/lando-storage.conf" >> "$GITHUB_ENV"
`;
};

const renderSetupStep = (cell: PlatformReadinessCell, binary: string): string => {
  const command = `${binary} setup ${setupFlags(cell)}`;
  if (!isLinuxLando(cell)) {
    return `      - name: Setup provider
        run: ${command}`;
  }
  return `      - name: Setup provider
        run: |
          export XDG_RUNTIME_DIR="\${XDG_RUNTIME_DIR:-/run/user/\$(id -u)}"
          mkdir -p "$XDG_RUNTIME_DIR"
          ${command}`;
};

const renderJob = (cell: PlatformReadinessCell): string => {
  const platform = ciPlatformFor(cell.id);
  const binary = `dist/${platform.binaryName}`;
  return `  rails-journey-${cell.id}:
${renderCadenceIf(cell.cadence)}    runs-on: ${renderRunsOn(cell.runsOn)}
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v5

${isolateRootsStep}

${setupBunSteps}

${derivedSourcesSteps}

${renderCompileStep(platform)}
${renderBundleSteps(cell)}${renderLinuxLandoPrereqs(cell)}
${renderSetupStep(cell, binary)}

      - name: Run Rails journey
        run: bun run scripts/rails-journey.ts --binary ${binary} --app-dir \${{ runner.temp }}/rails-app --report \${{ runner.temp }}/rails-journey.json

      - name: Teardown
        if: always()
        run: |
          BINARY="\$GITHUB_WORKSPACE/${binary}"
          (cd "\${{ runner.temp }}/rails-app/rails-journey" && "\$BINARY" destroy -y) || true
          "\$BINARY" poweroff || true

      - name: Upload evidence
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: rails-journey-${cell.id}
          path: \${{ runner.temp }}/rails-journey.json
          if-no-files-found: ignore
          retention-days: 14
`;
};

export const renderRailsJourneyWorkflow = (): string => `${GENERATED_HEADER}
name: rails-journey

on:
  pull_request:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
${PLATFORM_READINESS_CELLS.map(renderJob).join("\n")}
`;

const main = async (): Promise<void> => {
  await Bun.write(OUTPUT, renderRailsJourneyWorkflow());
  console.log(`[build-rails-journey-workflow] wrote ${OUTPUT}`);
};

if (import.meta.main) await main();
