#!/usr/bin/env bun
import { resolve } from "node:path";

import { releasePackageNames } from "./prepare-npm-dev-packages.ts";

const REPO_ROOT = resolve(import.meta.dirname, "..");
const OUTPUT = resolve(REPO_ROOT, ".github/workflows/release.yml");
const GENERATED_HEADER =
  "# Generated by scripts/codegen.ts — do not hand-edit. Edit scripts/build-release-workflow.ts instead.";

const packageBuildLines = releasePackageNames
  .filter((packageName) => packageName !== "@lando/core")
  .map((packageName) => `          bun run --filter='${packageName}' build`)
  .join("\n");

const dryRunPublishLines = releasePackageNames
  .map(
    (packageName) => `          npm publish --workspace ${packageName} --dry-run --access public --tag dev`,
  )
  .join("\n");

const publishLines = releasePackageNames
  .map(
    (packageName) =>
      `          npm publish --workspace ${packageName} --access public --tag dev --provenance`,
  )
  .join("\n");

const SCOPE_COMMENT = `#
# Scope: dev prerelease only. This workflow does not produce a signed release; it republishes the
# ci-built linux-x64 binary as a v4.0.0-dev.N GitHub prerelease and publishes npm dev-tag packages.
# The full signed release pipeline (scripts/release.ts) is invoked manually, not by this workflow.
# Runbook: docs/release-runbook.md.`;

export const renderReleaseWorkflow = (): string => `${GENERATED_HEADER}
${SCOPE_COMMENT}
name: release

on:
  workflow_run:
    workflows: [ci]
    branches: [main]
    types: [completed]

permissions:
  contents: write
  actions: read
  id-token: write

jobs:
  dev-prerelease-linux-x64:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: .bun-version

      - name: Verify committed runtime-bundle manifest resolves live
        run: bun run check:runtime-bundle-manifest --live

      - name: Download Linux x64 binary artifact
        env:
          GH_TOKEN: \${{ github.token }}
        run: gh run download "\${{ github.event.workflow_run.id }}" --name lando-linux-x64 --dir dist

      - name: Restore binary executable bit
        run: chmod +x dist/lando

      - name: Install first-launch sandbox tools
        run: |
          sudo apt-get update
          sudo apt-get install -y strace iproute2

      - name: Sandboxed first launch has no non-loopback network calls
        run: |
          set -euo pipefail
          mkdir -p "$RUNNER_TEMP/lando-conf" "$RUNNER_TEMP/lando-data" "$RUNNER_TEMP/lando-cache"
          sudo env LANDO_USER_CONF_ROOT="$RUNNER_TEMP/lando-conf" LANDO_USER_DATA_ROOT="$RUNNER_TEMP/lando-data" LANDO_USER_CACHE_ROOT="$RUNNER_TEMP/lando-cache" unshare --net sh -c '
            set -euo pipefail
            ip link set lo up
            strace -f -e trace=network -o dist/first-launch.network.log ./dist/lando --version
          '
          awk '/connect\\(/ && $0 !~ /(127\\.|::1|AF_UNIX)/ { bad = 1 } END { exit bad }' dist/first-launch.network.log

      - name: Write SHA256SUMS
        run: |
          cd dist
          sha256sum lando > SHA256SUMS
          grep -Eq '^[0-9a-f]{64}  lando$' SHA256SUMS

      - name: Publish dev prerelease
        env:
          GH_TOKEN: \${{ github.token }}
          RELEASE_TAG: v4.0.0-dev.\${{ github.run_number }}
        run: |
          gh release delete "$RELEASE_TAG" --yes --cleanup-tag 2>/dev/null || true
          gh release create "$RELEASE_TAG" dist/lando dist/SHA256SUMS --prerelease --target "\${{ github.event.workflow_run.head_sha }}" --title "Lando v4 dev \${{ github.run_number }}" --notes "Generated Linux x64 dev prerelease from successful ci workflow run \${{ github.event.workflow_run.id }}."

  npm-alpha-packages:
    if: github.event.workflow_run.conclusion == 'success'
    needs: [dev-prerelease-linux-x64]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: .bun-version

      - name: Setup Node for npm trusted publishing
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build package artifacts
        run: |
${packageBuildLines}
          bun run --filter='@lando/core' typecheck
          bun run --filter='@lando/core' build:manifest

      - name: Prepare alpha package metadata
        env:
          LANDO_NPM_VERSION: 4.0.0-alpha.\${{ github.run_number }}
          LANDO_NPM_DIST_TAG: dev
        run: bun run scripts/prepare-npm-dev-packages.ts

      - name: Dry-run npm dev publishes
        run: |
${dryRunPublishLines}

      - name: Publish npm dev packages
        run: |
          before_latest="$(npm view @lando/core dist-tags.latest --json 2>/dev/null || true)"
${publishLines}
          after_latest="$(npm view @lando/core dist-tags.latest --json 2>/dev/null || true)"
          test "$before_latest" = "$after_latest"
          npm view @lando/core dist-tags.dev --json | grep -Eq '"?4\\.0\\.0-alpha\\.[0-9]+"?'
`;

const main = async (): Promise<void> => {
  await Bun.write(OUTPUT, renderReleaseWorkflow());
  console.log(`[build-release-workflow] wrote ${OUTPUT}`);
};

if (import.meta.main) await main();
