#!/usr/bin/env bun
import { resolve } from "node:path";

import { CI_PLATFORMS, isWindowsCiPlatform, releaseBinaryFileName } from "./ci-platforms.ts";
import { RUNTIME_BUNDLE_ACTION_PINS } from "./runtime-bundle-supply-chain.ts";

const REPO_ROOT = resolve(import.meta.dirname, "..");
const OUTPUT = resolve(REPO_ROOT, ".github/workflows/release.yml");
const GENERATED_HEADER =
  "# Generated by scripts/codegen.ts — do not hand-edit. Edit scripts/build-release-workflow.ts instead.";

const SCOPE_COMMENT = `#
# Scope: dev prerelease only. This workflow does not produce a signed release; it republishes
# six unsigned binaries for every CI platform as a v4.0.0-dev.N GitHub prerelease.
# The full signed release pipeline (scripts/release.ts) is invoked manually, not by this workflow.
# Runbook: docs/contributing/release.md.`;

const YAML_RUN_INDENT = "          ";

const stageBinaryBlock = (): string =>
  CI_PLATFORMS.map((platform) => {
    const artifactDir = `dist/artifacts/${platform.id}`;
    const source = `${artifactDir}/${platform.binaryName}`;
    const staged = `dist/${releaseBinaryFileName(platform)}`;
    const lines = [
      `gh run download "\${{ github.event.workflow_run.id }}" --name lando-${platform.id} --dir ${artifactDir}`,
      `test -f ${source}`,
      `mv ${source} ${staged}`,
      ...(isWindowsCiPlatform(platform) ? [] : [`chmod +x ${staged}`]),
      `test -f ${staged}`,
    ];
    return lines.join(`\n${YAML_RUN_INDENT}`);
  }).join(`\n${YAML_RUN_INDENT}`);

const sha256sumBlock = (): string =>
  CI_PLATFORMS.map((platform) => {
    const name = releaseBinaryFileName(platform);
    return [`sha256sum ${name} >> SHA256SUMS`, `grep -Eq '^[0-9a-f]{64}  ${name}$' SHA256SUMS`].join(
      `\n${YAML_RUN_INDENT}`,
    );
  }).join(`\n${YAML_RUN_INDENT}`);

const releaseAssetArgs = (): string =>
  [...CI_PLATFORMS.map((platform) => `dist/${releaseBinaryFileName(platform)}`), "dist/SHA256SUMS"].join(" ");

export const renderReleaseWorkflow = (): string => `${GENERATED_HEADER}
${SCOPE_COMMENT}
name: release

on:
  workflow_run:
    workflows: [ci]
    branches: [main]
    types: [completed]

permissions:
  contents: write
  actions: read

jobs:
  dev-prerelease:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-24.04
    steps:
      - uses: ${RUNTIME_BUNDLE_ACTION_PINS.checkout} # v5.0.0

      - name: Setup Bun
        uses: ${RUNTIME_BUNDLE_ACTION_PINS.setupBun} # v2.0.2
        with:
          bun-version-file: .bun-version

      - name: Verify committed runtime-bundle manifest resolves live
        run: bun run check:runtime-bundle-manifest --live

      - name: Download and stage binaries
        env:
          GH_TOKEN: \${{ github.token }}
        run: |
          set -euo pipefail
          ${stageBinaryBlock()}

      - name: Install first-launch sandbox tools
        run: |
          sudo apt-get update
          sudo apt-get install -y strace iproute2

      - name: Sandboxed first launch has no non-loopback network calls
        run: |
          set -euo pipefail
          mkdir -p "$RUNNER_TEMP/lando-conf" "$RUNNER_TEMP/lando-data" "$RUNNER_TEMP/lando-cache"
          sudo env LANDO_USER_CONF_ROOT="$RUNNER_TEMP/lando-conf" LANDO_USER_DATA_ROOT="$RUNNER_TEMP/lando-data" LANDO_USER_CACHE_ROOT="$RUNNER_TEMP/lando-cache" unshare --net bash -c '
            set -euo pipefail
            ip link set lo up
            strace -f -e trace=network -o dist/first-launch.network.log ./dist/lando-linux-x64 --version
          '
          awk '/connect\\(/ && $0 !~ /(127\\.|::1|AF_UNIX)/ { bad = 1 } END { exit bad }' dist/first-launch.network.log

      - name: Write SHA256SUMS
        run: |
          set -euo pipefail
          cd dist
          : > SHA256SUMS
          ${sha256sumBlock()}

      - name: Publish dev prerelease
        env:
          GH_TOKEN: \${{ github.token }}
          RELEASE_TAG: v4.0.0-dev.\${{ github.run_number }}
        run: |
          gh release delete "$RELEASE_TAG" --yes --cleanup-tag 2>/dev/null || true
          gh release create "$RELEASE_TAG" ${releaseAssetArgs()} --prerelease --target "\${{ github.event.workflow_run.head_sha }}" --title "Lando v4 dev \${{ github.run_number }}" --notes "Unsigned six-target dev prerelease from successful ci run \${{ github.event.workflow_run.id }}."
`;

const main = async (): Promise<void> => {
  await Bun.write(OUTPUT, renderReleaseWorkflow());
  console.log(`[build-release-workflow] wrote ${OUTPUT}`);
};

if (import.meta.main) await main();
