#!/usr/bin/env bun
import { resolve } from "node:path";

const REPO_ROOT = resolve(import.meta.dirname, "..");
const OUTPUT = resolve(REPO_ROOT, ".github/workflows/compose-vendor-bump.yml");
const GENERATED_HEADER =
  "# Generated by scripts/codegen.ts — do not hand-edit. Edit scripts/build-compose-vendor-bump-workflow.ts instead.";

const selectNewerTagScript = [
  'const { selectNewerComposeGoTag, readComposeVendorPin } = await import("./scripts/compose-vendor.ts");',
  'const pin = await readComposeVendorPin("spec/compose/vendor/pin.json");',
  'const candidates = (await new Response(Bun.stdin.stream()).text()).split("\\n").map((line) => line.trim()).filter(Boolean);',
  "const newer = selectNewerComposeGoTag(pin.tag, candidates);",
  "if (newer !== undefined) process.stdout.write(newer);",
].join(" ");

export const renderComposeVendorBumpWorkflow = (): string => `${GENERATED_HEADER}
#
# Weekly checks the latest tagged compose-spec/compose-go release against the
# committed pin. When a newer tag exists it re-vendors the pinned schema and
# opens or updates a single rolling PR whose body lists the added and removed
# service key paths. Unclassified new keys fail check:compose-coverage on the
# PR, which is the intended merge blocker; this workflow never classifies keys.
name: compose-vendor-bump

on:
  schedule:
    - cron: '0 12 * * 1'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  bump:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: .bun-version

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Bump compose-go vendored schema and open rolling PR
        env:
          GH_TOKEN: \${{ github.token }}
        run: |
          set -euo pipefail
          NEW_TAG="$(gh api --paginate repos/compose-spec/compose-go/tags --jq '.[].name' | bun -e '${selectNewerTagScript}')"
          if [ -z "$NEW_TAG" ]; then
            echo "::notice title=compose-vendor-bump::compose-go pin is already current; nothing to bump."
            exit 0
          fi
          echo "::notice title=compose-vendor-bump::bumping compose-go pin to $NEW_TAG"

          git show HEAD:spec/compose/vendor/compose-spec.json > "$RUNNER_TEMP/old-compose-spec.json"
          bun run codegen:compose-vendor --tag "$NEW_TAG"
          bun run scripts/report-compose-schema-diff.ts "$RUNNER_TEMP/old-compose-spec.json" spec/compose/vendor/compose-spec.json > "$RUNNER_TEMP/pr-body.md"

          if git diff --quiet -- spec/compose/vendor/pin.json spec/compose/vendor/compose-spec.json; then
            echo "::notice title=compose-vendor-bump::pin already matches $NEW_TAG; nothing to commit."
            exit 0
          fi

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -B automation/compose-go-bump
          git add spec/compose/vendor/pin.json spec/compose/vendor/compose-spec.json
          git commit -m "bump compose-go vendored schema to $NEW_TAG"
          gh auth setup-git
          git push --force origin HEAD:automation/compose-go-bump

          TITLE="bump compose-go vendored schema to $NEW_TAG"
          if [ -z "$(gh pr list --state open --head automation/compose-go-bump --json number --jq '.[].number')" ]; then
            gh pr create --base main --head automation/compose-go-bump --title "$TITLE" --body-file "$RUNNER_TEMP/pr-body.md"
          else
            gh pr edit automation/compose-go-bump --title "$TITLE" --body-file "$RUNNER_TEMP/pr-body.md"
          fi
`;

const main = async (): Promise<void> => {
  await Bun.write(OUTPUT, renderComposeVendorBumpWorkflow());
  console.log(`[build-compose-vendor-bump-workflow] wrote ${OUTPUT}`);
};

if (import.meta.main) await main();
