import { Schema } from "effect";

import type { ServiceConfig } from "@lando/sdk/schema";

import pinsData from "./php-msmtp-pins.json" with { type: "json" };
import { hasCustomPhpImage } from "./php-via.ts";

/**
 * Base image families msmtp can be acquired for. Each family is pinned to its
 * own Debian snapshot and package version and is repinned independently, so
 * adding or moving one family never re-pins another.
 */
export const MSMTP_SUPPORTED_FAMILIES = ["debian-bookworm", "debian-bullseye"] as const;
export type MsmtpBaseFamily = (typeof MSMTP_SUPPORTED_FAMILIES)[number];

const MsmtpArtifact = Schema.Struct({
  file: Schema.String,
  sha256: Schema.String.pipe(Schema.pattern(/^[0-9a-f]{64}$/u)),
  sizeBytes: Schema.Number,
  url: Schema.String,
});

const MsmtpFamilyPinSchema = Schema.Struct({
  suite: Schema.String,
  snapshot: Schema.String,
  package: Schema.String,
  version: Schema.String,
  artifacts: Schema.Record({ key: Schema.String, value: MsmtpArtifact }),
});

export const MsmtpPinManifest = Schema.Struct({
  schemaVersion: Schema.Literal(1),
  families: Schema.Struct({
    "debian-bookworm": MsmtpFamilyPinSchema,
    "debian-bullseye": MsmtpFamilyPinSchema,
  }),
});
export type MsmtpPinManifest = typeof MsmtpPinManifest.Type;

/** One family's pin record, carrying the family key it was selected by. */
export type MsmtpFamilyPin = typeof MsmtpFamilyPinSchema.Type & { readonly family: MsmtpBaseFamily };

/** The committed pin table, regenerated by `bun run codegen:php-msmtp-pins`. */
export const MSMTP_PINS: MsmtpPinManifest = Schema.decodeUnknownSync(MsmtpPinManifest)(pinsData);

// Canonical upstream PHP tags state their Debian suite in the tag. Anything
// else — a private registry, a floating `-alpine` tag, an unlisted suite — is
// not provable from the reference alone and is never guessed.
const CANONICAL_PHP_TAG = /^(?:docker\.io\/library\/)?php:[A-Za-z0-9][A-Za-z0-9._-]*-(bookworm|bullseye)$/u;

/**
 * The base image family a PHP service's image belongs to, or `undefined` when
 * the image proves no family. Stock Lando PHP images are Debian bookworm for
 * every serving mode.
 */
export const resolveMsmtpBaseFamily = (service: ServiceConfig): MsmtpBaseFamily | undefined => {
  if (!hasCustomPhpImage(service)) return "debian-bookworm";
  const image = service.image;
  if (image === undefined) return undefined;
  const suite = CANONICAL_PHP_TAG.exec(image)?.[1];
  if (suite === undefined) return undefined;
  return suite === "bullseye" ? "debian-bullseye" : "debian-bookworm";
};

export const msmtpPinFor = (
  family: MsmtpBaseFamily,
  manifest: MsmtpPinManifest = MSMTP_PINS,
): MsmtpFamilyPin => ({ family, ...manifest.families[family] });

/**
 * The immutable identity of the selected pin. Only the selected family travels
 * into the image build key, so repinning one family leaves every other
 * family's images up to date.
 */
export const msmtpBuildKeyInput = (pin: MsmtpFamilyPin): Readonly<Record<string, unknown>> => ({
  family: pin.family,
  suite: pin.suite,
  snapshot: pin.snapshot,
  package: pin.package,
  version: pin.version,
  artifacts: pin.artifacts,
});

const SENDMAIL_INI_PATH = "/usr/local/etc/php/conf.d/zz-lando-mailpit.ini";

/**
 * Installs the pinned msmtp for one family. apt reads only the snapshot source
 * for this invocation — the image's own sources stay untouched and ineligible —
 * so the resolved package and its dependency closure are fixed by the snapshot
 * timestamp rather than by whatever the live archive holds at build time.
 */
export const msmtpBuildStepCommand = (
  pin: MsmtpFamilyPin,
  mail: { readonly host: string; readonly port: number },
): string => {
  const source = `deb [check-valid-until=no] https://snapshot.debian.org/archive/debian/${pin.snapshot}/ ${pin.suite} main`;
  const apt =
    'apt-get -o Dir::Etc::SourceList="$LANDO_MSMTP_LIST" -o Dir::Etc::SourceParts=- -o Acquire::Check-Valid-Until=false';
  const sendmailPath = `sendmail_path = "/usr/bin/msmtp --host=${mail.host} --port=${String(mail.port)} --from=lando@localhost -t"`;
  return [
    "set -eu",
    'LANDO_MSMTP_LIST="$(mktemp)"',
    `printf '%s\\n' '${source}' > "$LANDO_MSMTP_LIST"`,
    `${apt} update`,
    `DEBIAN_FRONTEND=noninteractive ${apt} install -y --no-install-recommends ${pin.package}=${pin.version}`,
    'rm -f "$LANDO_MSMTP_LIST"',
    "rm -rf /var/lib/apt/lists/*",
    `printf '%s\\n' '${sendmailPath}' > ${SENDMAIL_INI_PATH}`,
  ].join(" && ");
};
